var annotated_dup =
[
    [ "ble_provisioning_config_t", "structble__provisioning__config__t.html", "structble__provisioning__config__t" ],
    [ "ble_provisioning_private_data_t", "structble__provisioning__private__data__t.html", null ],
    [ "event_data_wrapper_t", "structevent__data__wrapper__t.html", "structevent__data__wrapper__t" ],
    [ "event_message_t", "structevent__message__t.html", "structevent__message__t" ],
    [ "event_subscriber_t", "structevent__subscriber__t.html", null ],
    [ "event_subscription_list_t", "structevent__subscription__list__t.html", "structevent__subscription__list__t" ],
    [ "event_subscription_node_t", "structevent__subscription__node__t.html", "structevent__subscription__node__t" ],
    [ "event_to_command_map_t", "structevent__to__command__map__t.html", null ],
    [ "fmw_config_updated_payload_t", "structfmw__config__updated__payload__t.html", "structfmw__config__updated__payload__t" ],
    [ "fmw_health_pong_payload_t", "structfmw__health__pong__payload__t.html", "structfmw__health__pong__payload__t" ],
    [ "fmw_module_control_payload_t", "structfmw__module__control__payload__t.html", "structfmw__module__control__payload__t" ],
    [ "fmw_telemetry_payload_t", "structfmw__telemetry__payload__t.html", "structfmw__telemetry__payload__t" ],
    [ "led_blinker_config_t", "structled__blinker__config__t.html", "structled__blinker__config__t" ],
    [ "led_blinker_module_t", "structled__blinker__module__t.html", "structled__blinker__module__t" ],
    [ "led_command_t", "structled__command__t.html", null ],
    [ "logger_private_data_t", "structlogger__private__data__t.html", null ],
    [ "module_factory_map_t", "structmodule__factory__map__t.html", null ],
    [ "module_t", "structmodule__t.html", "structmodule__t" ],
    [ "oled_display_config_t", "structoled__display__config__t.html", "structoled__display__config__t" ],
    [ "oled_display_private_data_t", "structoled__display__private__data__t.html", "structoled__display__private__data__t" ],
    [ "resource_pool_t", "structresource__pool__t.html", "structresource__pool__t" ],
    [ "rgb_led_api_t", "structrgb__led__api__t.html", null ],
    [ "rgb_led_private_data_t", "structrgb__led__private__data__t.html", null ],
    [ "service_entry_t", "structservice__entry__t.html", "structservice__entry__t" ],
    [ "test_module_config_t", "structtest__module__config__t.html", "structtest__module__config__t" ],
    [ "test_module_module_t", "structtest__module__module__t.html", "structtest__module__module__t" ],
    [ "wifi_manager_config_t", "structwifi__manager__config__t.html", "structwifi__manager__config__t" ],
    [ "wifi_manager_private_data_t", "structwifi__manager__private__data__t.html", null ]
];