var searchData=
[
  ['💡_20ახალი_20ტესტის_20დამატების_20მაგალითი_0',['6. 💡 ახალი ტესტის დამატების მაგალითი',['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md36',1,'']]],
  ['💡_20გამოყენება_20და_20უსაფრთხოების_20ჩართვა_1',['6. 💡 გამოყენება და უსაფრთხოების ჩართვა',['../md_components_2modules_2security_2security__status__reporter_2README.html#autotoc_md69',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_2',['💡 გამოყენების მაგალითი',['../md_docs_2api__reference_2storage__api.html#autotoc_md612',1,'💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2system__timer_2README.html#autotoc_md213',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2i2c__bus_2README.html#autotoc_md51',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md88',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2testing_2sensor__simulator_2README.html#autotoc_md156',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md61',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2command__router_2README.html#autotoc_md169',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md149',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md133',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md141',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md206',1,'8. 💡 გამოყენების მაგალითი']]],
  ['💡_20გამოყენების_20მაგალითი_20და_20ტესტირება_3',['5. 💡 გამოყენების მაგალითი და ტესტირება',['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md79',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_20მოთხოვნა_20პასუხი_4',['💡 გამოყენების მაგალითი მოთხოვნა პასუხი',['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md28',1,'7. 💡 გამოყენების მაგალითი (მოთხოვნა-პასუხი)'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md124',1,'8. 💡 გამოყენების მაგალითი (მოთხოვნა-პასუხი)']]],
  ['💡_20გამოყენების_20მაგალითი_20tt_20selftest_5fmanager_20tt_20ში_5',['6. 💡 გამოყენების მაგალითი (&lt;tt&gt;selftest_manager&lt;/tt&gt;-ში)',['../md_components_2modules_2displays_2ssd1306__oled__display_2README.html#autotoc_md44',1,'']]],
  ['💡_20გამოყენების_20პატერნი_3a_20კონფლიქტისგან_20დაცული_20რეგისტრაცია_6',['💡 გამოყენების პატერნი: კონფლიქტისგან დაცული რეგისტრაცია',['../md_docs_2api__reference_2command__router__api.html#autotoc_md259',1,'']]],
  ['💡_20გამოყენების_20სცენარები_7',['6. 💡 გამოყენების სცენარები',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md98',1,'']]],
  ['💡_20მოდული_20tt_20rgb_5fled_5findicator_20tt_8',['💡 მოდული &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['💡_20პრაქტიკული_20მაგალითი_3a_20tt_20wifi_5fmanager_20tt_20და_20tt_20command_5frouter_20tt_9',['💡 პრაქტიკული მაგალითი: &lt;tt&gt;wifi_manager&lt;/tt&gt; და &lt;tt&gt;command_router&lt;/tt&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md993',1,'']]],
  ['💡_20mqtt_20api_20ს_20გამოყენების_20მაგალითი_10',['💡 MQTT API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md269',1,'']]],
  ['💡_20strong_20დონე_204_3a_20აპლიკაციის_20ლოგიკა_20და_20პერიფერია_2060_2079_20strong_11',['💡 &lt;strong&gt;დონე 4: აპლიკაციის ლოგიკა და პერიფერია (60-79)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1002',1,'']]],
  ['💡_20wifi_20api_20ს_20გამოყენების_20მაგალითი_12',['💡 WiFi API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md265',1,'']]]
];
