var searchData=
[
  ['⚙️_20კონფიგურაცია_0',['⚙️ კონფიგურაცია',['../md_components_2modules_2testing_2timer__test__module_2README.html#autotoc_md205',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md130',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md121',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md154',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2security_2security__status__reporter_2README.html#autotoc_md95',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2time__sync_2README.html#autotoc_md185',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md191',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2testing_2sensor__simulator_2README.html#autotoc_md199',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utillities_2system__timer_2README.html#autotoc_md254',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2displays_2ssd1306__driver_2README.html#autotoc_md39',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md31',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md22',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2communications_2mqtt__manager_2README.html#autotoc_md12',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utillities_2ui__manager_2README.html#autotoc_md261',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md167',1,'4. ⚙️ კონფიგურაცია']]],
  ['⚙️_20კონფიგურაცია_20tt_20config_20json_20tt_1',['⚙️ კონფიგურაცია tt config json tt',['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md3',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2utillities_2rgb__led__indicator_2README.html#autotoc_md246',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2sensors_2time__of__flight__sensor_2README.html#autotoc_md113',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2spi__bus_2README.html#autotoc_md88',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2sn74hc595n__writer_2README.html#autotoc_md81',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2rotary__encoder__input_2README.html#autotoc_md71',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2mcp23017__io__expander_2README.html#autotoc_md61',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2i2c__bus_2README.html#autotoc_md54',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2button__input_2README.html#autotoc_md45',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)']]],
  ['⚙️_20კონფიგურაცია_20tt_20system_5fconfig_20json_20tt_2',['⚙️ კონფიგურაცია tt system_config json tt',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md140',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;system_config.json&lt;/tt&gt;)'],['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md103',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;system_config.json&lt;/tt&gt;)']]],
  ['⚙️_20მოდული_3a_20command_20router_20system_20shell_3',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utillities_2command__router_2README.html',1,'']]],
  ['⚙️_20როგორ_20მუშაობს_4',['⚙️ როგორ მუშაობს?',['../md_docs_2convention_2initialization__levels.html#autotoc_md1252',1,'']]],
  ['⚙️_20როგორ_20მუშაობს_20იმპლემენტაცია_5',['4. ⚙️ როგორ მუშაობს იმპლემენტაცია?',['../md_docs_2convention_2promise__pattern.html#autotoc_md1318',1,'']]],
  ['⚙️_20ტექნიკური_20იმპლემენტაცია_6',['2. ⚙️ ტექნიკური იმპლემენტაცია',['../md_docs_2convention_2logging__colors.html#autotoc_md1270',1,'']]],
  ['⚙️_20ძირითადი_20api_20ფუნქციები_7',['⚙️ ძირითადი API ფუნქციები',['../md_docs_2api__reference_2configuration__api.html#autotoc_md330',1,'']]],
  ['⚙️_20api_20სტრუქტურა_20tt_20cmd_5frouter_5fapi_5ft_20tt_8',['⚙️ API სტრუქტურა (&lt;tt&gt;cmd_router_api_t&lt;/tt&gt;)',['../md_docs_2api__reference_2command__router__api.html#autotoc_md297',1,'']]],
  ['⚙️_20api_20ს_20სტრუქტურა_20tt_20storage_5fapi_5ft_20tt_9',['⚙️ API-ს სტრუქტურა (&lt;tt&gt;storage_api_t&lt;/tt&gt;)',['../md_docs_2api__reference_2storage__api.html#autotoc_md669',1,'']]]
];
