var searchData=
[
  ['uint32_5ft_20timeout_5fms_0',['esp_err_t watchdog_module_set_timeout(uint32_t timeout_ms);',['../md_docs_2api__reference_2system__api.html#autotoc_md434',1,'']]],
  ['uint8_5ft_20device_5faddress_20const_20uint8_5ft_20data_20size_5ft_20data_5flength_1',['esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md201',1,'']]],
  ['uint8_5ft_20device_5faddress_20uint8_5ft_20data_20size_5ft_20data_5flength_2',['esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md200',1,'']]],
  ['uint8_5ft_20line_3',['uint8_t line',['../md_docs_2api__reference_2display__api.html#autotoc_md179',1,'esp_err_t ssd1306_api_write_text(const char *text, uint8_t line);'],['../md_docs_2api__reference_2module__api.html#autotoc_md286',1,'esp_err_t {module_name}_api_write_text(const char *text, uint8_t line);']]],
  ['uint8_5ft_20peer_5fmac_20const_20uint8_5ft_20data_20size_5ft_20data_5flength_4',['esp_err_t espnow_module_send(const uint8_t *peer_mac, const uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2communication__api.html#autotoc_md90',1,'']]],
  ['uint8_5ft_20resource_5fid_20const_20char_20owner_20tt_5',['uint8_t resource_id const char owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md367',1,'&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md369',1,'&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['uint8_5ft_20resource_5fid_20tt_6',['uint8_t resource_id tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md371',1,'&lt;tt&gt;bool fmw_resource_is_locked(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md373',1,'&lt;tt&gt;const char *fmw_resource_get_owner(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;']]],
  ['uint8_5ft_20tx_5fdata_20uint8_5ft_20rx_5fdata_20size_5ft_20data_5flength_7',['esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md207',1,'']]],
  ['unregister_5fcustom_5fcheck_8',['unregister_custom_check',['../structhealth__api__t.html#a091a9e71908d5abc456eeef50a30182d',1,'health_api_t']]],
  ['updated_5fkey_9',['updated_key',['../structfmw__config__updated__payload__t.html#a81fedf3181c56afb2a889f0ff2e8b2d5',1,'fmw_config_updated_payload_t']]],
  ['uri_20http_5fmethod_5ft_20method_20local_5fctrl_5fhandler_5ft_20handler_10',['esp_err_t local_ctrl_module_register_endpoint(const char *uri, http_method_t method, local_ctrl_handler_t handler);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md265',1,'']]],
  ['url_11',['url',['../md_docs_2api__reference_2ota__api.html#autotoc_md304',1,'esp_err_t ota_module_start_update(const char *url);'],['../md_docs_2api__reference_2system__api.html#autotoc_md424',1,'esp_err_t ota_module_start_update(const char *url);']]],
  ['usage_12',['usage',['../md_docs_2convention_2logging__standards.html#autotoc_md825',1,'2. Memory Usage'],['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1503',1,'5. Heap და Memory Usage'],['../md_docs_2convention_2communication__patterns.html#autotoc_md714',1,'Event Bus Usage'],['../md_docs_2convention_2communication__patterns.html#autotoc_md711',1,'Service Locator Usage']]],
  ['usage_20გაფართოებული_20გამოყენება_13',['Advanced Usage (გაფართოებული გამოყენება)',['../md_docs_2tutorials_2advanced__usage.html',1,'']]],
  ['usage_20მონიტორინგი_14',['4. Task და Stack Usage მონიტორინგი',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1502',1,'']]],
  ['usage_20guide_15',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['usage_20mqtt_20module_16',['2. Service Usage (MQTT Module)',['../md_docs_2convention_2communication__patterns.html#autotoc_md713',1,'']]],
  ['using_20config_20manager_17',['Using Config Manager',['../md_docs_2convention_2configuration__management.html#autotoc_md745',1,'']]],
  ['utility_20module_20api_20reference_18',['Synapse Utility Module API Reference',['../md_docs_2api__reference_2utility__api.html',1,'']]]
];
