var searchData=
[
  ['კატეგორია_20მოდულებისთვის_0',['8. როგორ დავამატო ახალი კატეგორია მოდულებისთვის?',['../md_docs_2structure_2faq.html#autotoc_md1392',1,'']]],
  ['კატეგორიები_1',['კატეგორიები',['../md_docs_2convention_2module__structure.html#autotoc_md791',1,'']]],
  ['კითხვა_2',['სენსორის კითხვა',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1147',1,'']]],
  ['კითხვა_20ამ_20faq_20ში_3',['9. როგორ დავამატო ახალი კითხვა ამ FAQ-ში?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1484',1,'']]],
  ['კითხვების_20ან_20პრობლემების_20შემთხვევაში_4',['10. ვის მივმართო დამატებითი კითხვების ან პრობლემების შემთხვევაში?',['../md_docs_2contributing_2faq.html#autotoc_md572',1,'']]],
  ['კითხვები_20faq_5',['კითხვები faq',['../md_docs_2contributing_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)'],['../md_docs_2structure_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)']]],
  ['კითხვები_20troubleshooting_20faq_6',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['კლონირება_7',['პროექტის კლონირება',['../md_docs_2contributing_2local__setup.html#autotoc_md602',1,'']]],
  ['კოდები_8',['შეცდომების კოდები',['../md_docs_2structure_2error__handling__and__logging.html#autotoc_md1371',1,'']]],
  ['კოდექსი_9',['კოდექსი',['../contributing_docs.html#contrib_coc_sec',1,'ქცევის კოდექსი'],['../md_docs_2contributing_2faq.html#autotoc_md571',1,'9. როგორ დავიცვა ქცევის კოდექსი?']]],
  ['კოდექსი_20code_20of_20conduct_10',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['კოდის_20ოპტიმიზაცია_11',['კოდის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1192',1,'']]],
  ['კოდის_20სტანდარტები_12',['2. კოდის სტანდარტები',['../md_docs_2contributing_2contributing__guide.html#autotoc_md539',1,'']]],
  ['კოდის_20ტერმინები_20glossary_20—_20api_20code_13',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['კოდის_20ხარისხი_3a_14',['კოდის ხარისხი:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md867',1,'3. კოდის ხარისხი:'],['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1263',1,'3. კოდის ხარისხი:']]],
  ['კოდი_20არ_20იკითხება_15',['პრობლემა: შეცდომის კოდი არ იკითხება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1455',1,'']]],
  ['კომენტარების_20სტანდარტი_16',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['კომენტარების_20სტანდარტი_20v1_200_17',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['კომენტარები_18',['4. სტრუქტურების და ტიპების კომენტარები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md652',1,'']]],
  ['კომენტარი_19',['კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md646',1,'2. ფაილის სათაურის (Header) კომენტარი'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md649',1,'3. ფუნქციის კომენტარი']]],
  ['კომპილაცია_20smart_20system_20_3a_20',['კომპილაცია smart system :',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1238',1,'1. 🧠 კონდიციური კომპილაცია (SMART SYSTEM):'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md842',1,'1. 🧠 კონდიციური კომპილაცია (SMART SYSTEM):']]],
  ['კომპონენტები_21',['კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md873',1,'არქიტექტურული ფენები და ძირითადი კომპონენტები'],['../md_docs_2structure_2core__components.html#autotoc_md1351',1,'ძირითადი კომპონენტები'],['../index.html#autotoc_md1423',1,'ძირითადი კომპონენტები'],['../md_docs_2design__decisions_2core__components.html#autotoc_md904',1,'ძირითადი კომპონენტები']]],
  ['კომპონენტები_20core_20components_22',['კომპონენტები core components',['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['კომპრომისები_20performance_20trade_20offs_23',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['კომუნიკაცია_24',['3. როგორ ხდება მოდულებს შორის კომუნიკაცია?',['../md_docs_2structure_2faq.html#autotoc_md1387',1,'']]],
  ['კომუნიკაციის_20არქიტექტურული_20არჩევანი_20communication_20choices_25',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['კომუნიკაციის_20გაფართოება_26',['5. კომუნიკაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1531',1,'']]],
  ['კომუნიკაციის_20პატერნების_20წესები_27',['კომუნიკაციის პატერნების წესები',['../md_docs_2convention_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პატერნები_28',['კომუნიკაციის პატერნები',['../structure_docs.html#struct_comm_patterns_sec',1,'კომუნიკაციის პატერნები'],['../conventions_docs.html#conv_comm_sec',1,'კომუნიკაციის პატერნები'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md874',1,'მოდულებს შორის კომუნიკაციის პატერნები']]],
  ['კომუნიკაციის_20პატერნები_20communication_20patterns_29',['კომუნიკაციის პატერნები (Communication Patterns)',['../md_docs_2structure_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პატერნი_30',['ორი კომუნიკაციის პატერნი',['../md_docs_2convention_2communication__patterns.html#autotoc_md657',1,'']]],
  ['კომუნიკაციის_20პრობლემები_31',['3. კომუნიკაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1449',1,'']]],
  ['კომუნიკაციის_20ტიპები_32',['კომუნიკაციის ტიპები',['../md_docs_2convention_2communication__patterns.html#autotoc_md660',1,'']]],
  ['კონდიციური_20კომპილაცია_20smart_20system_20_3a_33',['კონდიციური კომპილაცია smart system :',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1238',1,'1. 🧠 კონდიციური კომპილაცია (SMART SYSTEM):'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md842',1,'1. 🧠 კონდიციური კომპილაცია (SMART SYSTEM):']]],
  ['კონვენცია_3a_34',['კონვენცია:',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1261',1,'1. სახელების კონვენცია:'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md865',1,'1. სახელების კონვენცია:']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_35',['კონვენციების ავტომატური შემმოწმებელი',['../contributing_docs.html#contrib_linter_guide_sec',1,'']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_20tt_20check_5fconventions_20py_20tt_36',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['კონვენციების_20გამოყენება_37',['4. Naming და Structure კონვენციების გამოყენება',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1501',1,'']]],
  ['კონვენციები_38',['კონვენციები',['../md_docs_2convention_2function__naming.html#autotoc_md753',1,'სპეციალური კონვენციები'],['../md_docs_2convention_2variable__naming.html#autotoc_md813',1,'4. კონვენციები']]],
  ['კონვენციები_20და_20სტანდარტები_39',['კონვენციები და სტანდარტები',['../conventions_docs.html',1,'']]],
  ['კონვენციებს_20უნდა_20დავიცვა_40',['2. რა სტანდარტებს და კონვენციებს უნდა დავიცვა?',['../md_docs_2contributing_2faq.html#autotoc_md564',1,'']]],
  ['კონტექსტი_41',['კონტექსტი',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md976',1,'კონტექსტი'],['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md997',1,'კონტექსტი'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1018',1,'კონტექსტი'],['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md956',1,'კონტექსტი'],['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1039',1,'კონტექსტი'],['../md_docs_2design__decisions_2error__handling__decisions.html#autotoc_md936',1,'კონტექსტი'],['../md_docs_2design__decisions_2decision__record__template.html#autotoc_md921',1,'კონტექსტი'],['../md_docs_2design__decisions_2communication__choices.html#autotoc_md884',1,'კონტექსტი']]],
  ['კონტრიბუცია_20synapse_20framework_20ში_42',['1. როგორ დავიწყო კონტრიბუცია Synapse Framework-ში?',['../md_docs_2contributing_2faq.html#autotoc_md563',1,'']]],
  ['კონტრიბუციის_20გზამკვლევი_43',['კონტრიბუციის გზამკვლევი',['../contributing_docs.html',1,'']]],
  ['კონტრიბუციის_20პროცესი_44',['კონტრიბუციის პროცესი',['../contributing_docs.html#contrib_guide_sec',1,'კონტრიბუციის პროცესი'],['../md_docs_2contributing_2contributing__guide.html#autotoc_md538',1,'1. კონტრიბუციის პროცესი']]],
  ['კონტრიბუციის_20სახელმძღვანელო_20contributing_20guide_45',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['კონტროლი_46',['კონტროლი',['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1029',1,'ლოგირების კონტროლი'],['../md_docs_2security_2security__best__practices.html#autotoc_md1275',1,'ლოგირების კონტროლი']]],
  ['კონფიგურაცია_47',['კონფიგურაცია',['../md_docs_2convention_2configuration__management.html#autotoc_md683',1,'მაგალითი სრული კონფიგურაცია'],['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1488',1,'1. მრავალმოდულიანი კონფიგურაცია'],['../md_docs_2tutorials_2integration__example.html#autotoc_md1518',1,'2. საჭირო მოდულების ჩართვა და კონფიგურაცია'],['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1467',1,'2. Debug Build-ის კონფიგურაცია'],['../md_docs_2structure_2faq.html#autotoc_md1388',1,'4. როგორ მივიღო ან შევცვალო მოდულის კონფიგურაცია?'],['../md_docs_2contributing_2local__setup.html#autotoc_md604',1,'sdkconfig ფაილის კონფიგურაცია']]],
  ['კონფიგურაცია_20მუშაობს_3a_48',['კონფიგურაცია მუშაობს:',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1257',1,'3. რომ დარწმუნდეთ კონფიგურაცია მუშაობს:'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md861',1,'3. რომ დარწმუნდეთ კონფიგურაცია მუშაობს:']]],
  ['კონფიგურაცია_20system_20configuration_49',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['კონფიგურაცია_3a_50',['კონფიგურაცია:',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1244',1,'3. კონფიგურაცია:'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md848',1,'3. კონფიგურაცია:']]],
  ['კონფიგურაციისა_20და_20შენახვის_20ტერმინები_20glossary_20—_20configuration_20storage_51',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['კონფიგურაციის_20გაფართოება_52',['4. კონფიგურაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1530',1,'']]],
  ['კონფიგურაციის_20გაფართოება_3a_53',['კონფიგურაციის გაფართოება:',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1248',1,'1. კონფიგურაციის გაფართოება:'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md852',1,'1. კონფიგურაციის გაფართოება:']]],
  ['კონფიგურაციის_20დამუშავების_20ეტაპები_54',['კონფიგურაციის დამუშავების ეტაპები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1343',1,'']]],
  ['კონფიგურაციის_20ვალიდაცია_20და_20შეცდომების_20თავიდან_20აცილება_55',['5. კონფიგურაციის ვალიდაცია და შეცდომების თავიდან აცილება',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1543',1,'']]],
  ['კონფიგურაციის_20მართვა_56',['კონფიგურაციის მართვა',['../conventions_docs.html#conv_config_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_57',['კონფიგურაციის მართვის პროცესი',['../structure_docs.html#struct_config_flow_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_20configuration_20flow_58',['კონფიგურაციის მართვის პროცესი (Configuration Flow)',['../md_docs_2structure_2configuration__flow.html',1,'']]],
  ['კონფიგურაციის_20მართვის_20წესები_59',['კონფიგურაციის მართვის წესები',['../md_docs_2convention_2configuration__management.html',1,'']]],
  ['კონფიგურაციის_20ოპტიმიზაცია_60',['კონფიგურაციის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1194',1,'']]],
  ['კონფიგურაციის_20პარამეტრები_61',['კონფიგურაციის პარამეტრები',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md850',1,'🎛️ კონფიგურაციის პარამეტრები'],['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1246',1,'🎛️ კონფიგურაციის პარამეტრები']]],
  ['კონფიგურაციის_20პრობლემები_62',['2. კონფიგურაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1445',1,'']]],
  ['კონფიგურაციის_20სტრუქტურა_63',['კონფიგურაციის სტრუქტურა',['../md_docs_2structure_2configuration__flow.html#autotoc_md1342',1,'']]],
  ['კონფიგურაციის_20ტიპები_64',['კონფიგურაციის ტიპები',['../md_docs_2convention_2configuration__management.html#autotoc_md684',1,'']]],
  ['კონფიგურაციის_20შეცდომა_65',['8. როგორ დავადგინო კონფიგურაციის შეცდომა?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1483',1,'']]],
  ['კონფიგურაციის_20წვდომის_20მაგალითები_66',['კონფიგურაციის წვდომის მაგალითები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1344',1,'']]],
  ['კონფიგურაციის_20წყაროები_67',['კონფიგურაციის წყაროები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1341',1,'']]],
  ['კონფიგურაციის_20parsing_68',['კონფიგურაციის Parsing',['../md_docs_2convention_2configuration__management.html#autotoc_md691',1,'']]],
  ['კრიტერიუმები_69',['მიმოხილვის კრიტერიუმები',['../md_docs_2contributing_2review__guidelines.html#autotoc_md636',1,'']]]
];
