var searchData=
[
  ['ფაილების_20სტრუქტურა_0',['ფაილების სტრუქტურა',['../structure_docs.html#struct_dir_sec',1,'საქაღალდეებისა და ფაილების სტრუქტურა'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md895',1,'საქაღალდეებისა და ფაილების სტრუქტურა']]],
  ['ფაილების_20სტრუქტურა_20directory_20structure_1',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['ფაილების_20შაბლონები_2',['3. Header და Source ფაილების შაბლონები',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1519',1,'']]],
  ['ფაილების_20შექმნა_3',['2. საქაღალდის და ფაილების შექმნა',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1518',1,'']]],
  ['ფაილები_4',['დამატებული და განახლებული ფაილები',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md473',1,'']]],
  ['ფაილები_205_20ფაილი_20_3a_5',['ფაილები 5 ფაილი :',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1245',1,'✅ შექმნილი ფაილები (5 ფაილი):'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md849',1,'✅ შექმნილი ფაილები (5 ფაილი):']]],
  ['ფაილის_20კონფიგურაცია_6',['sdkconfig ფაილის კონფიგურაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md623',1,'']]],
  ['ფაილის_20სათაურის_20header_20კომენტარი_7',['2. ფაილის სათაურის (Header) კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md665',1,'']]],
  ['ფაილის_20სტრუქტურა_8',['ფაილის სტრუქტურა',['../md_docs_2convention_2module__structure.html#autotoc_md811',1,'']]],
  ['ფაილი_20_3a_9',['ფაილი :',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md849',1,'✅ შექმნილი ფაილები (5 ფაილი):'],['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1245',1,'✅ შექმნილი ფაილები (5 ფაილი):']]],
  ['ფაილი_20tt_20include_20module_5fname_20h_20tt_10',['1. Header ფაილი (&lt;tt&gt;include/{module_name}.h&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md812',1,'']]],
  ['ფაილი_20tt_20module_5fname_20c_20tt_11',['2. Source ფაილი (&lt;tt&gt;{module_name}.c&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md813',1,'']]],
  ['ფაქტობრივი_20შედეგი_12',['ფაქტობრივი შედეგი',['../md_docs_2contributing_2issue__template.html#autotoc_md605',1,'']]],
  ['ფენები_20და_20ძირითადი_20კომპონენტები_13',['არქიტექტურული ფენები და ძირითადი კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md892',1,'']]],
  ['ფლეში_14',['4. ბილდი და ფლეში',['../md_docs_2tutorials_2getting__started.html#autotoc_md1530',1,'']]],
  ['ფორმატი_15',['ფორმატი',['../md_docs_2convention_2logging__standards.html#autotoc_md781',1,'სტანდარტული ფორმატი'],['../md_docs_2convention_2configuration__management.html#autotoc_md701',1,'სტანდარტული ფორმატი']]],
  ['ფორმატი_20dot_20notation_16',['🔑 გასაღების ფორმატი (Dot-Notation)',['../md_docs_2api__reference_2configuration__api.html#autotoc_md92',1,'']]],
  ['ფრეიმვორქის_20გაფართოება_17',['ფრეიმვორქის გაფართოება',['../structure_docs.html#struct_extending_sec',1,'']]],
  ['ფრეიმვორქის_20გაფართოება_20და_20best_20practices_20extending_20the_20framework_18',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['ფუნქციების_20დასახელება_19',['ფუნქციების დასახელება',['../conventions_docs.html#conv_func_name_sec',1,'']]],
  ['ფუნქციების_20დასახელების_20წესები_20',['ფუნქციების დასახელების წესები',['../md_docs_2convention_2function__naming.html',1,'']]],
  ['ფუნქციები_21',['ფუნქციები',['../md_docs_2api__reference_2configuration__api.html#autotoc_md94',1,'⚙️ ძირითადი API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md773',1,'1. Module Lifecycle ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md774',1,'2. Runtime Management ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md775',1,'3. Event Handler ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md776',1,'4. Task ფუნქციები'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md340',1,'API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md765',1,'Framework API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md763',1,'Public API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md764',1,'Static/Private ფუნქციები']]],
  ['ფუნქციის_20დამატება_22',['3. ახალი API ან ფუნქციის დამატება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1548',1,'']]],
  ['ფუნქციის_20კომენტარი_23',['3. ფუნქციის კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md668',1,'']]],
  ['ფუნქციონალის_20დამატება_20module_20extension_20feature_20addition_24',['მოდულის გაფართოება ან ფუნქციონალის დამატება (Module Extension &amp; Feature Addition)',['../md_docs_2tutorials_2module__extension.html',1,'']]]
];
