var searchData=
[
  ['tag_20definition_0',['Component Tag Definition',['../md_docs_2convention_2logging__standards.html#autotoc_md821',1,'']]],
  ['task_20და_20stack_20usage_20მონიტორინგი_1',['4. Task და Stack Usage მონიტორინგი',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1519',1,'']]],
  ['task_20ფუნქციები_2',['4. Task ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md817',1,'']]],
  ['task_20state_20changes_3',['2. Task State Changes',['../md_docs_2convention_2logging__standards.html#autotoc_md839',1,'']]],
  ['task_20watchdog_4',['1. Stack Overflow და Task Watchdog',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1480',1,'']]],
  ['telemetry_5fevents_20h_5',['[interfaces/include/telemetry_events.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md528',1,'']]],
  ['telemetry_5fevents_2ec_6',['telemetry_events.c',['../telemetry__events_8c.html',1,'']]],
  ['temperature_20float_20humidity_7',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md408',1,'']]],
  ['template_8',['template',['../md_docs_2design__decisions_2decision__record__template.html',1,'არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)'],['../md_docs_2contributing_2issue__template.html',1,'Synapse Issue Template'],['../md_docs_2contributing_2pull__request__template.html',1,'Synapse Pull Request Template']]],
  ['test_5fmodule_2ec_9',['test_module.c',['../test__module_8c.html',1,'']]],
  ['test_5fmodule_2eh_10',['test_module.h',['../test__module_8h.html',1,'']]],
  ['test_5fmodule_5fconfig_5ft_11',['test_module_config_t',['../structtest__module__config__t.html',1,'']]],
  ['test_5fmodule_5fcreate_12',['test_module_create',['../test__module_8c.html#ab57d0c0bbfc2bd7c2772984652a91059',1,'test_module_create(const cJSON *config):&#160;test_module.c'],['../test__module_8h.html#ab57d0c0bbfc2bd7c2772984652a91059',1,'test_module_create(const cJSON *config):&#160;test_module.c']]],
  ['test_5fmodule_5fmodule_5ft_13',['test_module_module_t',['../structtest__module__module__t.html',1,'']]],
  ['testability_14',['7. Testability',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1202',1,'']]],
  ['testing_15',['Testing',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md541',1,'']]],
  ['text_20uint8_5ft_20line_16',['text uint8_t line',['../md_docs_2api__reference_2display__api.html#autotoc_md196',1,'esp_err_t ssd1306_api_write_text(const char *text, uint8_t line);'],['../md_docs_2api__reference_2module__api.html#autotoc_md303',1,'esp_err_t {module_name}_api_write_text(const char *text, uint8_t line);']]],
  ['the_20air_20module_20api_20reference_17',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['the_20framework_18',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['time_20sync_20module_20api_19',['Time Sync Module API',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md465',1,'']]],
  ['time_20sync_20module_20api_20reference_20',['Synapse Time Sync Module API Reference',['../md_docs_2api__reference_2time__sync__api.html',1,'']]],
  ['time_5fstr_20size_5ft_20size_21',['esp_err_t version_module_get_build_time(char *time_str, size_t size);',['../md_docs_2api__reference_2version__api.html#autotoc_md499',1,'']]],
  ['time_5fsync_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_22',['static void time_sync_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md473',1,'']]],
  ['time_5fsync_5fmodule_5fcreate_20const_20cjson_20config_23',['module_t *time_sync_module_create(const cJSON *config);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md466',1,'']]],
  ['time_5fsync_5fmodule_5fget_5ftime_20time_5ft_20current_5ftime_24',['esp_err_t time_sync_module_get_time(time_t *current_time);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md470',1,'']]],
  ['time_5fsync_5fmodule_5fset_5fserver_20module_5ft_20module_20const_20char_20server_5furl_25',['esp_err_t time_sync_module_set_server(module_t *module, const char *server_url);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md469',1,'']]],
  ['time_5fsync_5fmodule_5fstart_20module_5ft_20module_26',['esp_err_t time_sync_module_start(module_t *module);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md467',1,'']]],
  ['time_5fsync_5fmodule_5fstop_20module_5ft_20module_27',['esp_err_t time_sync_module_stop(module_t *module);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md468',1,'']]],
  ['time_5ft_20current_5ftime_28',['esp_err_t time_sync_module_get_time(time_t *current_time);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md470',1,'']]],
  ['timeout_5fms_29',['esp_err_t watchdog_module_set_timeout(uint32_t timeout_ms);',['../md_docs_2api__reference_2system__api.html#autotoc_md451',1,'']]],
  ['timing_30',['1. Operation Timing',['../md_docs_2convention_2logging__standards.html#autotoc_md841',1,'']]],
  ['timing_20parameters_31',['2. Timing Parameters',['../md_docs_2convention_2configuration__management.html#autotoc_md766',1,'']]],
  ['tls_20ssl_32',['TLS/SSL',['../md_docs_2security_2security__guidelines.html#autotoc_md1346',1,'']]],
  ['tls_20ssl_20ჩართვა_20mqtt_20ში_33',['tls ssl ჩართვა mqtt ში',['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1090',1,'TLS/SSL ჩართვა MQTT-ში'],['../md_docs_2security_2security__best__practices.html#autotoc_md1323',1,'TLS/SSL ჩართვა MQTT-ში']]],
  ['topic_20const_20char_20message_34',['esp_err_t mqtt_module_publish(const char *topic, const char *message);',['../md_docs_2api__reference_2communication__api.html#autotoc_md96',1,'']]],
  ['topic_20mqtt_5fmessage_5fhandler_5ft_20handler_35',['esp_err_t mqtt_module_subscribe(const char *topic, mqtt_message_handler_t handler);',['../md_docs_2api__reference_2communication__api.html#autotoc_md97',1,'']]],
  ['trade_20offs_36',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['troubleshooting_37',['7. Troubleshooting',['../md_docs_2tutorials_2integration__example.html#autotoc_md1573',1,'']]],
  ['troubleshooting_20faq_38',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['tt_20bool_20fmw_5fresource_5fis_5flocked_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20tt_39',['&lt;tt&gt;bool fmw_resource_is_locked(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md388',1,'']]],
  ['tt_20check_5fconventions_20py_20tt_40',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['tt_20const_20char_20fmw_5fresource_5fget_5fowner_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20tt_41',['&lt;tt&gt;const char *fmw_resource_get_owner(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md390',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fevent_5fbus_5finit_20void_20tt_42',['&lt;tt&gt;esp_err_t fmw_event_bus_init(void)&lt;/tt&gt;',['../md_docs_2api__reference_2event__api.html#autotoc_md234',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fevent_5fbus_5fpost_20core_5fframework_5fevent_5fid_5ft_20event_5fid_20event_5fdata_5fwrapper_5ft_20data_5fwrapper_20tt_43',['&lt;tt&gt;esp_err_t fmw_event_bus_post(core_framework_event_id_t event_id, event_data_wrapper_t *data_wrapper)&lt;/tt&gt;',['../md_docs_2api__reference_2event__api.html#autotoc_md235',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fevent_5fbus_5fsubscribe_20core_5fframework_5fevent_5fid_5ft_20event_5fid_20struct_20module_5ft_20module_20tt_44',['&lt;tt&gt;esp_err_t fmw_event_bus_subscribe(core_framework_event_id_t event_id, struct module_t *module)&lt;/tt&gt;',['../md_docs_2api__reference_2event__api.html#autotoc_md236',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fevent_5fbus_5funsubscribe_20core_5fframework_5fevent_5fid_5ft_20event_5fid_20struct_20module_5ft_20module_20tt_45',['&lt;tt&gt;esp_err_t fmw_event_bus_unsubscribe(core_framework_event_id_t event_id, struct module_t *module)&lt;/tt&gt;',['../md_docs_2api__reference_2event__api.html#autotoc_md237',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fresource_5flock_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20const_20char_20owner_20tt_46',['&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md384',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fresource_5fmanager_5finit_20void_20tt_47',['&lt;tt&gt;esp_err_t fmw_resource_manager_init(void)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md382',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fresource_5frelease_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20const_20char_20owner_20tt_48',['&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md386',1,'']]],
  ['tt_20event_5fbus_5fpost_20tt_49',['&lt;tt&gt;event_bus_post&lt;/tt&gt;',['../md_docs_2api__reference_2core__api.html#autotoc_md145',1,'']]],
  ['tt_20event_5fbus_5fsubscribe_20tt_50',['&lt;tt&gt;event_bus_subscribe&lt;/tt&gt;',['../md_docs_2api__reference_2core__api.html#autotoc_md146',1,'']]],
  ['tt_20event_5fbus_5funsubscribe_20tt_51',['&lt;tt&gt;event_bus_unsubscribe&lt;/tt&gt;',['../md_docs_2api__reference_2core__api.html#autotoc_md147',1,'']]],
  ['tt_20health_5fapi_5ft_20tt_52',['5. Service API (&lt;tt&gt;health_api_t&lt;/tt&gt;)',['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md5',1,'']]],
  ['tt_20i2c_5fbus_5fmodule_20h_20tt_53',['2.2. მაგალითი (&lt;tt&gt;i2c_bus_module.h&lt;/tt&gt;)',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md708',1,'']]],
  ['tt_20include_20module_5fname_20h_20tt_54',['1. Header ფაილი (&lt;tt&gt;include/{module_name}.h&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md853',1,'']]],
  ['tt_20logger_5fmodule_5fcreate_20const_20cjson_20config_20tt_55',['&lt;tt&gt;logger_module_create(const cJSON *config)&lt;/tt&gt;',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md48',1,'']]],
  ['tt_20menuconfig_20tt_56',['tt menuconfig tt',['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md10',1,'2. წინაპირობები და &lt;tt&gt;menuconfig&lt;/tt&gt;'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md2',1,'2. წინაპირობები და &lt;tt&gt;menuconfig&lt;/tt&gt;'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md19',1,'2. წინაპირობები და &lt;tt&gt;menuconfig&lt;/tt&gt;']]],
  ['tt_20module_5fname_20c_20tt_57',['2. Source ფაილი (&lt;tt&gt;{module_name}.c&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md854',1,'']]],
  ['tt_20ota_5fapi_5ft_20tt_58',['5. Service API (&lt;tt&gt;ota_api_t&lt;/tt&gt;)',['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md13',1,'']]],
  ['tt_20rgb_5fled_5fapi_5ft_20tt_59',['4. Service API (&lt;tt&gt;rgb_led_api_t&lt;/tt&gt;)',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md56',1,'']]],
  ['tt_20rgb_5fled_5findicator_20tt_60',['მოდული &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['tt_20service_5flocator_20h_20tt_61',['3.2. მაგალითი (&lt;tt&gt;service_locator.h&lt;/tt&gt;)',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md711',1,'']]],
  ['tt_20system_5fconfig_20json_20tt_20ის_20როლი_62',['1. &lt;tt&gt;system_config.json&lt;/tt&gt;-ის როლი',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1590',1,'']]],
  ['tt_20watchdog_5fapi_5ft_20tt_63',['5. Service API (&lt;tt&gt;watchdog_api_t&lt;/tt&gt;)',['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md22',1,'']]],
  ['turn_5foff_64',['turn_off',['../structrgb__led__api__t.html#a1e7bd763888a4afbe12354d27250ecd3',1,'rgb_led_api_t']]],
  ['tx_5fdata_20uint8_5ft_20rx_5fdata_20size_5ft_20data_5flength_65',['esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md224',1,'']]],
  ['txt_66',['[core/CMakeLists.txt]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md515',1,'']]],
  ['txt_20სტრუქტურა_67',['CMakeLists.txt სტრუქტურა',['../md_docs_2convention_2module__structure.html#autotoc_md859',1,'']]],
  ['type_68',['type',['../structservice__entry__t.html#a2ffb19a8df6aa8318e4fca7de82b22a3',1,'service_entry_t']]],
  ['type_20uint8_5ft_20resource_5fid_20const_20char_20owner_20tt_69',['type uint8_t resource_id const char owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md384',1,'&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md386',1,'&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['type_20uint8_5ft_20resource_5fid_20tt_70',['type uint8_t resource_id tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md388',1,'&lt;tt&gt;bool fmw_resource_is_locked(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md390',1,'&lt;tt&gt;const char *fmw_resource_get_owner(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;']]]
];
