var searchData=
[
  ['ობიექტის_20პარამეტრები_0',['ობიექტის პარამეტრები',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md89',1,'3.2. &lt;tt&gt;layers&lt;/tt&gt; ობიექტის პარამეტრები'],['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md60',1,'3.2. &lt;tt&gt;sensors_to_aggregate&lt;/tt&gt; ობიექტის პარამეტრები'],['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md90',1,'3.3. &lt;tt&gt;actions&lt;/tt&gt; ობიექტის პარამეტრები']]],
  ['ობიექტი_1',['ობიექტი',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md78',1,'3.1. განგაშის წესის პარამეტრები (&lt;tt&gt;alarms&lt;/tt&gt; ობიექტი)'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md79',1,'3.2. მოქმედებების პარამეტრები (&lt;tt&gt;actions&lt;/tt&gt; ობიექტი)']]],
  ['ოპერაციები_2',['ოპერაციები',['../md_docs_2api__reference_2storage__api.html#autotoc_md594',1,'🔑 Key-Value ოპერაციები'],['../md_docs_2api__reference_2storage__api.html#autotoc_md596',1,'🗂️ ფაილური ოპერაციები'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md70',1,'Key-Value ოპერაციები']]],
  ['ოპერაციები_20მხარდაჭერილია_20spiffs_20და_20sd_20card_20backend_20ებზე_3',['ფაილური ოპერაციები (მხარდაჭერილია SPIFFS და SD Card backend-ებზე)',['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md71',1,'']]],
  ['ოპტიმიზაცია_4',['ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1449',1,'კოდის ოპტიმიზაცია'],['../md_docs_2performance_2performance__optimization.html#autotoc_md1451',1,'კონფიგურაციის ოპტიმიზაცია'],['../md_docs_2performance_2performance__optimization.html#autotoc_md1453',1,'მოდულების ოპტიმიზაცია'],['../md_docs_2performance_2performance__display.html#autotoc_md1430',1,'Refresh interval-ის ოპტიმიზაცია']]],
  ['ოპტიმიზაცია_20და_20რესურსების_20მართვა_5',['6. ოპტიმიზაცია და რესურსების მართვა',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1737',1,'']]],
  ['ოპტიმიზაცია_20performance_20—_20display_20modules_6',['ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)',['../md_docs_2performance_2performance__display.html',1,'']]],
  ['ოპტიმიზაციის_20რეკომენდაციები_7',['ოპტიმიზაციის რეკომენდაციები',['../md_docs_2performance_2performance__display.html#autotoc_md1427',1,'']]],
  ['ოპტიმიზაციის_20სახელმძღვანელოები_20performance_20optimization_20guide_8',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['ორი_20კომუნიკაციის_20პატერნი_9',['ორი კომუნიკაციის პატერნი',['../md_docs_2convention_2communication__patterns.html#autotoc_md891',1,'']]],
  ['ოქროს_20წესი_10',['📜 ოქროს წესი',['../md_docs_2convention_2initialization__levels.html#autotoc_md999',1,'']]]
];
