var searchData=
[
  ['data_20pointer_20naming_0',['Private Data Pointer Naming',['../md_docs_2convention_2variable__naming.html#autotoc_md1043',1,'']]],
  ['data_20size_5ft_20data_5flength_1',['data size_t data_length',['../md_docs_2api__reference_2drivers__api.html#autotoc_md349',1,'esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md350',1,'esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);']]],
  ['data_20structure_2',['Private Data Structure',['../md_docs_2convention_2configuration__management.html#autotoc_md894',1,'']]],
  ['data_5flength_3',['data_length',['../md_docs_2api__reference_2drivers__api.html#autotoc_md349',1,'esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md350',1,'esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md356',1,'esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);']]],
  ['data_5fwrapper_4',['data_wrapper',['../structevent__message__t.html#a6d545c17b49bd18413b4cd6d14c026c3',1,'event_message_t']]],
  ['data_5fwrapper_20tt_5',['&lt;tt&gt;esp_err_t fmw_event_bus_post(core_framework_event_id_t event_id, event_data_wrapper_t *data_wrapper)&lt;/tt&gt;',['../md_docs_2api__reference_2event__api.html#autotoc_md367',1,'']]],
  ['date_5fstr_20size_5ft_20size_6',['esp_err_t version_module_get_build_date(char *date_str, size_t size);',['../md_docs_2api__reference_2version__api.html#autotoc_md630',1,'']]],
  ['debug_20build_20ის_20კონფიგურაცია_7',['2. Debug Build-ის კონფიგურაცია',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1677',1,'']]],
  ['debug_20level_8',['4. ESP_LOGD - Debug Level',['../md_docs_2convention_2logging__standards.html#autotoc_md988',1,'']]],
  ['debugging_9',['6. Event და Service Debugging',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1681',1,'']]],
  ['debugging_20guide_20დიბაგინგის_20სახელმძღვანელო_10',['Debugging Guide (დიბაგინგის სახელმძღვანელო)',['../md_docs_2troubleshooting_2debugging__guide.html',1,'']]],
  ['decision_20record_20template_11',['არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)',['../md_docs_2design__decisions_2decision__record__template.html',1,'']]],
  ['decisions_12',['decisions',['../md_docs_2design__decisions_2error__handling__decisions.html',1,'შეცდომების დამუშავების არქიტექტურული გადაწყვეტილებები (Error Handling Decisions)'],['../md_docs_2design__decisions_2design__decisions__index.html',1,'Synapse Design Decisions']]],
  ['default_20მნიშვნელობები_13',['ვალიდაცია და Default მნიშვნელობები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1555',1,'']]],
  ['default_20მნიშვნელობები_20არ_20მუშაობს_14',['პრობლემა: default მნიშვნელობები არ მუშაობს',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1657',1,'']]],
  ['default_20values_15',['Default Values',['../md_docs_2convention_2configuration__management.html#autotoc_md896',1,'']]],
  ['define_5fcomponent_5ftag_16',['define_component_tag',['../logger__module_8c.html#ae7c63dd9d16170942bd5413a956ef9be',1,'DEFINE_COMPONENT_TAG(&quot;LOGGER_MODULE&quot;):&#160;logger_module.c'],['../logging_8h.html#a7ece332eb67f0652fb4b9af20392c0f9',1,'DEFINE_COMPONENT_TAG:&#160;logging.h'],['../md_docs_2api__reference_2core__api.html#autotoc_md283',1,'DEFINE_COMPONENT_TAG']]],
  ['definition_17',['definition',['../md_docs_2convention_2logging__standards.html#autotoc_md981',1,'Component Tag Definition'],['../md_docs_2convention_2configuration__management.html#autotoc_md897',1,'Constants Definition']]],
  ['degradation_18',['2. Graceful Degradation',['../md_docs_2convention_2error__handling.html#autotoc_md940',1,'']]],
  ['deinit_19',['deinit',['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1613',1,'4. Deinit'],['../structmodule__t.html#a87b58a95264772d03f62ec21793d140b',1,'module_t::deinit']]],
  ['delete_5ffile_20',['delete_file',['../structstorage__api__t.html#ab3fd3106abdc33a7ea91b1fd7dd3c935',1,'storage_api_t']]],
  ['dependencies_21',['❌ პირდაპირი Dependencies',['../md_docs_2convention_2communication__patterns.html#autotoc_md866',1,'']]],
  ['dependencies_20მიხედვით_22',['Dependencies მიხედვით',['../md_docs_2convention_2module__structure.html#autotoc_md1020',1,'']]],
  ['deprecated_20api_20ის_20მონიშვნა_23',['Deprecated API-ის მონიშვნა',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md1209',1,'']]],
  ['deprecated_20list_24',['Deprecated List',['../deprecated.html',1,'']]],
  ['description_25',['description',['../structtest__report__line__t.html#a1456ded2bee7e2b01fe41f4f472154c9',1,'test_report_line_t']]],
  ['design_20checklist_26',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['design_20decisions_27',['Synapse Design Decisions',['../md_docs_2design__decisions_2design__decisions__index.html',1,'']]],
  ['detailed_20file_20changes_28',['Detailed File Changes',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md681',1,'']]],
  ['details_29',['details',['../structtest__report__line__t.html#a2b19e8c7c0bb250db357b84d32380d14',1,'test_report_line_t::details'],['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md156',1,'Implementation Details']]],
  ['development_20notes_30',['Development Notes',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md160',1,'']]],
  ['device_20identity_20service_20api_31',['Device Identity Service API',['../md_docs_2api__reference_2device__identity__api.html#autotoc_md306',1,'']]],
  ['device_20identity_20service_20api_20reference_32',['Synapse Device Identity Service API Reference',['../md_docs_2api__reference_2device__identity__api.html',1,'']]],
  ['device_5faddress_20const_20uint8_5ft_20data_20size_5ft_20data_5flength_33',['esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md350',1,'']]],
  ['device_5faddress_20uint8_5ft_20data_20size_5ft_20data_5flength_34',['esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md349',1,'']]],
  ['device_5fid_35',['device_id',['../structdevice__identity__private__data__t.html#a694bded633d18d5d97cf36922b0d1cbc',1,'device_identity_private_data_t']]],
  ['device_5fidentity_5fapi_5ft_36',['device_identity_api_t',['../structdevice__identity__api__t.html',1,'']]],
  ['device_5fidentity_5fapi_5ft_20tt_37',['4. 🔌 Service API (&lt;tt&gt;device_identity_api_t&lt;/tt&gt;)',['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md87',1,'']]],
  ['device_5fidentity_5finterface_2eh_38',['device_identity_interface.h',['../device__identity__interface_8h.html',1,'']]],
  ['device_5fidentity_5fprivate_5fdata_5ft_39',['device_identity_private_data_t',['../structdevice__identity__private__data__t.html',1,'']]],
  ['device_5fidentity_5fservice_20tt_40',['🆔 მოდული: &lt;tt&gt;device_identity_service&lt;/tt&gt;',['../md_components_2modules_2system_2device__identity__service_2README.html',1,'']]],
  ['device_5fidentity_5fservice_2ec_41',['device_identity_service.c',['../device__identity__service_8c.html',1,'']]],
  ['device_5fidentity_5fservice_2eh_42',['device_identity_service.h',['../device__identity__service_8h.html',1,'']]],
  ['device_5fidentity_5fservice_5fcreate_43',['device_identity_service_create',['../device__identity__service_8c.html#a9687f2ed1bc8ee6d3697dd399376d97f',1,'device_identity_service_create(const cJSON *config):&#160;device_identity_service.c'],['../device__identity__service_8h.html#a9687f2ed1bc8ee6d3697dd399376d97f',1,'device_identity_service_create(const cJSON *config):&#160;device_identity_service.c']]],
  ['device_5fname_44',['device_name',['../structble__provisioning__private__data__t.html#ad37d705cb2eb4ea70d0c43973c8e19cf',1,'ble_provisioning_private_data_t']]],
  ['dht22_45',['1. Event-Driven Module (მაგ., DHT22)',['../md_docs_2convention_2module__structure.html#autotoc_md1016',1,'']]],
  ['dht22_5fdata_46',['static esp_err_t parse_dht22_config(const cJSON *config, dht22_private_data_t *dht22_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md549',1,'']]],
  ['dht22_5fdata_20float_20temperature_20float_20humidity_47',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md546',1,'']]],
  ['dht22_5fdeinit_20module_5ft_20module_48',['static esp_err_t dht22_deinit(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md542',1,'']]],
  ['dht22_5fdisable_20module_5ft_20module_49',['static esp_err_t dht22_disable(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md541',1,'']]],
  ['dht22_5fenable_20module_5ft_20module_50',['static esp_err_t dht22_enable(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md540',1,'']]],
  ['dht22_5fget_5fstatus_20module_5ft_20module_51',['static module_status_t dht22_get_status(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md552',1,'']]],
  ['dht22_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_52',['static void dht22_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md545',1,'']]],
  ['dht22_5finit_20module_5ft_20module_53',['static esp_err_t dht22_init(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md539',1,'']]],
  ['dht22_5fmodule_5fcreate_20const_20cjson_20config_54',['module_t &lt;em&gt;dht22_module_create(const cJSON *config);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md538',1,'']]],
  ['dht22_5fprivate_5fdata_5ft_20dht22_5fdata_55',['static esp_err_t parse_dht22_config(const cJSON *config, dht22_private_data_t *dht22_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md549',1,'']]],
  ['dht22_5fprivate_5fdata_5ft_20dht22_5fdata_20float_20temperature_20float_20humidity_56',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md546',1,'']]],
  ['diagnostics_57',['diagnostics',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1644',1,'5. Peripheral Diagnostics'],['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1645',1,'6. Network Diagnostics']]],
  ['diagnostics_20გაფართოებული_20დიაგნოსტიკა_58',['Advanced Diagnostics (გაფართოებული დიაგნოსტიკა)',['../md_docs_2troubleshooting_2advanced__diagnostics.html',1,'']]],
  ['diagnostics_20module_20api_59',['Diagnostics Module API',['../md_docs_2api__reference_2system__api.html#autotoc_md585',1,'']]],
  ['diagnostics_5fmodule_5fcreate_20const_20cjson_20config_60',['module_t *diagnostics_module_create(const cJSON *config);',['../md_docs_2api__reference_2system__api.html#autotoc_md586',1,'']]],
  ['diagnostics_5fmodule_5fget_5freport_20char_20report_5fbuffer_20size_5ft_20buffer_5fsize_61',['esp_err_t diagnostics_module_get_report(char *report_buffer, size_t buffer_size);',['../md_docs_2api__reference_2system__api.html#autotoc_md588',1,'']]],
  ['diagnostics_5fmodule_5frun_5ftests_20void_62',['esp_err_t diagnostics_module_run_tests(void);',['../md_docs_2api__reference_2system__api.html#autotoc_md587',1,'']]],
  ['diagram_63',['Architecture Diagram',['../md_docs_2convention_2communication__patterns.html#autotoc_md879',1,'']]],
  ['direct_20api_20communication_20service_20locator_64',['Direct API Communication (Service Locator)',['../md_docs_2convention_2communication__patterns.html#autotoc_md863',1,'']]],
  ['directory_20structure_65',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['disable_66',['disable',['../md_docs_2convention_2logging__standards.html#autotoc_md998',1,'1. Module Enable/Disable'],['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1612',1,'3. Enable/Disable'],['../structmodule__t.html#ae00c883b7a5e858edad93c7cdbd5239b',1,'module_t::disable']]],
  ['disable_20ზე_67',['პრობლემა: მოდული არ რეაგირებს enable/disable-ზე',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1668',1,'']]],
  ['disable_20logger_68',['Disable Logger',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md153',1,'']]],
  ['disable_20logger_20module_69',['Disable Logger Module',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md149',1,'']]],
  ['disclosure_20policy_20უსაფრთხოების_20ხარვეზების_20აღმოჩენისა_20და_20შეტყობინების_20პროცედურა_70',['Vulnerability Disclosure Policy (უსაფრთხოების ხარვეზების აღმოჩენისა და შეტყობინების პროცედურა)',['../md_docs_2security_2security__vulnerability__disclosure.html',1,'']]],
  ['display_20configuration_71',['3. LCD Display Configuration',['../md_docs_2convention_2configuration__management.html#autotoc_md889',1,'']]],
  ['display_20configuration_20ssd1306_72',['2. Display Configuration (SSD1306)',['../md_docs_2convention_2configuration__management.html#autotoc_md888',1,'']]],
  ['display_20module_73',['1. Service Registration (Display Module)',['../md_docs_2convention_2communication__patterns.html#autotoc_md871',1,'']]],
  ['display_20module_20api_20reference_74',['Synapse Display Module API Reference',['../md_docs_2api__reference_2display__api.html',1,'']]],
  ['display_20modules_75',['display modules',['../md_docs_2performance_2performance__display.html',1,'ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)'],['../md_docs_2convention_2function__naming.html#autotoc_md952',1,'3. Display Modules'],['../md_docs_2convention_2variable__naming.html#autotoc_md1032',1,'Display Modules']]],
  ['display_20parameters_76',['3. Display Parameters',['../md_docs_2convention_2configuration__management.html#autotoc_md909',1,'']]],
  ['do_20tt_20მოქმედებები_77',['3.4. მხარდაჭერილი &lt;tt&gt;type&lt;/tt&gt;-ები და &lt;tt&gt;do&lt;/tt&gt; მოქმედებები',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md76',1,'']]],
  ['documentation_78',['documentation',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1360',1,'5. Documentation'],['../md_docs_2convention_2convention__index.html#autotoc_md915',1,'Coding &amp; Documentation']]],
  ['documentation_20module_20design_20checklist_79',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['dot_20notation_80',['dot notation',['../md_docs_2api__reference_2configuration__api.html#autotoc_md246',1,'🔑 გასაღების ფორმატი (Dot-Notation)'],['../md_docs_2tutorials_2system__configuration.html#autotoc_md1756',1,'4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)']]],
  ['doxygen_20კომენტარების_20სტანდარტი_81',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['doxygen_20კომენტარების_20სტანდარტი_20v1_200_82',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['doxygen_20ტეგების_20გამოყენების_20წესები_83',['5. Doxygen ტეგების გამოყენების წესები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md856',1,'']]],
  ['doxygen_5fmain_5fpages_84',['doxygen_main_pages',['../md_docs_2doxygen__main__pages.html',1,'']]],
  ['driven_20module_20მაგ_20dht22_85',['1. Event-Driven Module (მაგ., DHT22)',['../md_docs_2convention_2module__structure.html#autotoc_md1016',1,'']]],
  ['driven_20module_20მაგ_20ssd1306_86',['2. Service-Driven Module (მაგ., SSD1306)',['../md_docs_2convention_2module__structure.html#autotoc_md1017',1,'']]],
  ['driver_20api_87',['driver api',['../md_docs_2api__reference_2drivers__api.html#autotoc_md346',1,'I2C Bus Driver API'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md353',1,'SPI Bus Driver API']]],
  ['driver_20module_20მაგ_20i2c_20bus_88',['3. Driver Module (მაგ., I2C Bus)',['../md_docs_2convention_2module__structure.html#autotoc_md1018',1,'']]],
  ['drivers_20module_20api_20reference_89',['Synapse Drivers Module API Reference',['../md_docs_2api__reference_2drivers__api.html',1,'']]],
  ['dumps_20და_20crash_20reporting_90',['3. Core Dumps და Crash Reporting',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1642',1,'']]]
];
