var searchData=
[
  ['კატეგორია_20მოდულებისთვის_0',['8. როგორ დავამატო ახალი კატეგორია მოდულებისთვის?',['../md_docs_2structure_2faq.html#autotoc_md1250',1,'']]],
  ['კატეგორიები_1',['კატეგორიები',['../md_docs_2convention_2module__structure.html#autotoc_md735',1,'']]],
  ['კითხვა_2',['სენსორის კითხვა',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1048',1,'']]],
  ['კითხვა_20ამ_20faq_20ში_3',['9. როგორ დავამატო ახალი კითხვა ამ FAQ-ში?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1342',1,'']]],
  ['კითხვების_20ან_20პრობლემების_20შემთხვევაში_4',['10. ვის მივმართო დამატებითი კითხვების ან პრობლემების შემთხვევაში?',['../md_docs_2contributing_2faq.html#autotoc_md516',1,'']]],
  ['კითხვები_20faq_5',['კითხვები faq',['../md_docs_2structure_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)'],['../md_docs_2contributing_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)']]],
  ['კითხვები_20troubleshooting_20faq_6',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['კლონირება_7',['პროექტის კლონირება',['../md_docs_2contributing_2local__setup.html#autotoc_md546',1,'']]],
  ['კოდები_8',['შეცდომების კოდები',['../md_docs_2structure_2error__handling__and__logging.html#autotoc_md1229',1,'']]],
  ['კოდექსი_9',['კოდექსი',['../contributing_docs.html#contrib_coc_sec',1,'ქცევის კოდექსი'],['../md_docs_2contributing_2faq.html#autotoc_md515',1,'9. როგორ დავიცვა ქცევის კოდექსი?']]],
  ['კოდექსი_20code_20of_20conduct_10',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['კოდის_20ოპტიმიზაცია_11',['კოდის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1093',1,'']]],
  ['კოდის_20სტანდარტები_12',['2. კოდის სტანდარტები',['../md_docs_2contributing_2contributing__guide.html#autotoc_md483',1,'']]],
  ['კოდის_20ტერმინები_20glossary_20—_20api_20code_13',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['კოდი_20არ_20იკითხება_14',['პრობლემა: შეცდომის კოდი არ იკითხება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1313',1,'']]],
  ['კომენტარების_20სტანდარტი_15',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['კომენტარების_20სტანდარტი_20v1_200_16',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['კომენტარები_17',['4. სტრუქტურების და ტიპების კომენტარები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md596',1,'']]],
  ['კომენტარი_18',['კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md590',1,'2. ფაილის სათაურის (Header) კომენტარი'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md593',1,'3. ფუნქციის კომენტარი']]],
  ['კომპონენტების_20tag_20ები_19',['კომპონენტების TAG-ები',['../group__ComponentTags.html',1,'']]],
  ['კომპონენტები_20',['კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md774',1,'არქიტექტურული ფენები და ძირითადი კომპონენტები'],['../md_docs_2structure_2core__components.html#autotoc_md1209',1,'ძირითადი კომპონენტები'],['../md_docs_2design__decisions_2core__components.html#autotoc_md805',1,'ძირითადი კომპონენტები'],['../index.html#autotoc_md1281',1,'ძირითადი კომპონენტები']]],
  ['კომპონენტები_20core_20components_21',['კომპონენტები core components',['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['კომპრომისები_20performance_20trade_20offs_22',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['კომუნიკაცია_23',['3. როგორ ხდება მოდულებს შორის კომუნიკაცია?',['../md_docs_2structure_2faq.html#autotoc_md1245',1,'']]],
  ['კომუნიკაციის_20არქიტექტურული_20არჩევანი_20communication_20choices_24',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['კომუნიკაციის_20გაფართოება_25',['5. კომუნიკაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1389',1,'']]],
  ['კომუნიკაციის_20პატერნების_20წესები_26',['კომუნიკაციის პატერნების წესები',['../md_docs_2convention_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პატერნები_27',['კომუნიკაციის პატერნები',['../structure_docs.html#struct_comm_patterns_sec',1,'კომუნიკაციის პატერნები'],['../conventions_docs.html#conv_comm_sec',1,'კომუნიკაციის პატერნები'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md775',1,'მოდულებს შორის კომუნიკაციის პატერნები']]],
  ['კომუნიკაციის_20პატერნები_20communication_20patterns_28',['კომუნიკაციის პატერნები (Communication Patterns)',['../md_docs_2structure_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პატერნი_29',['ორი კომუნიკაციის პატერნი',['../md_docs_2convention_2communication__patterns.html#autotoc_md601',1,'']]],
  ['კომუნიკაციის_20პრობლემები_30',['3. კომუნიკაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1307',1,'']]],
  ['კომუნიკაციის_20ტიპები_31',['კომუნიკაციის ტიპები',['../md_docs_2convention_2communication__patterns.html#autotoc_md604',1,'']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_32',['კონვენციების ავტომატური შემმოწმებელი',['../contributing_docs.html#contrib_linter_guide_sec',1,'']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_20tt_20check_5fconventions_20py_20tt_33',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['კონვენციების_20გამოყენება_34',['4. Naming და Structure კონვენციების გამოყენება',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1359',1,'']]],
  ['კონვენციები_35',['კონვენციები',['../md_docs_2convention_2function__naming.html#autotoc_md697',1,'სპეციალური კონვენციები'],['../md_docs_2convention_2variable__naming.html#autotoc_md757',1,'4. კონვენციები']]],
  ['კონვენციები_20და_20სტანდარტები_36',['კონვენციები და სტანდარტები',['../conventions_docs.html',1,'']]],
  ['კონვენციებს_20უნდა_20დავიცვა_37',['2. რა სტანდარტებს და კონვენციებს უნდა დავიცვა?',['../md_docs_2contributing_2faq.html#autotoc_md508',1,'']]],
  ['კონტექსტი_38',['კონტექსტი',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md940',1,'კონტექსტი'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md919',1,'კონტექსტი'],['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md898',1,'კონტექსტი'],['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md877',1,'კონტექსტი'],['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md857',1,'კონტექსტი'],['../md_docs_2design__decisions_2communication__choices.html#autotoc_md785',1,'კონტექსტი'],['../md_docs_2design__decisions_2error__handling__decisions.html#autotoc_md837',1,'კონტექსტი'],['../md_docs_2design__decisions_2decision__record__template.html#autotoc_md822',1,'კონტექსტი']]],
  ['კონტრიბუცია_20synapse_20framework_20ში_39',['1. როგორ დავიწყო კონტრიბუცია Synapse Framework-ში?',['../md_docs_2contributing_2faq.html#autotoc_md507',1,'']]],
  ['კონტრიბუციის_20გზამკვლევი_40',['კონტრიბუციის გზამკვლევი',['../contributing_docs.html',1,'']]],
  ['კონტრიბუციის_20პროცესი_41',['კონტრიბუციის პროცესი',['../contributing_docs.html#contrib_guide_sec',1,'კონტრიბუციის პროცესი'],['../md_docs_2contributing_2contributing__guide.html#autotoc_md482',1,'1. კონტრიბუციის პროცესი']]],
  ['კონტრიბუციის_20სახელმძღვანელო_20contributing_20guide_42',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['კონტროლი_43',['კონტროლი',['../md_docs_2security_2security__best__practices.html#autotoc_md1133',1,'ლოგირების კონტროლი'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md930',1,'ლოგირების კონტროლი']]],
  ['კონფიგურაცია_44',['კონფიგურაცია',['../md_docs_2convention_2configuration__management.html#autotoc_md627',1,'მაგალითი სრული კონფიგურაცია'],['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1346',1,'1. მრავალმოდულიანი კონფიგურაცია'],['../md_docs_2tutorials_2integration__example.html#autotoc_md1376',1,'2. საჭირო მოდულების ჩართვა და კონფიგურაცია'],['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1325',1,'2. Debug Build-ის კონფიგურაცია'],['../md_docs_2structure_2faq.html#autotoc_md1246',1,'4. როგორ მივიღო ან შევცვალო მოდულის კონფიგურაცია?'],['../group__EventBusConfig.html',1,'Event Bus კონფიგურაცია'],['../group__MemoryConfig.html',1,'Memory კონფიგურაცია'],['../group__ModuleConfig.html',1,'Module კონფიგურაცია'],['../group__ModuleRegistryConfig.html',1,'Module Registry კონფიგურაცია'],['../group__PerformanceMonitoringConfig.html',1,'Performance Monitoring კონფიგურაცია'],['../group__ResourceManagerConfig.html',1,'Resource Manager კონფიგურაცია'],['../group__RuntimeOptimizationConfig.html',1,'Runtime Module Optimization კონფიგურაცია'],['../md_docs_2contributing_2local__setup.html#autotoc_md548',1,'sdkconfig ფაილის კონფიგურაცია'],['../group__SecurityConfig.html',1,'Security კონფიგურაცია'],['../group__ServiceLocatorConfig.html',1,'Service Locator კონფიგურაცია'],['../group__TaskConfig.html',1,'Task კონფიგურაცია'],['../group__TimeoutConfig.html',1,'Timeout კონფიგურაცია']]],
  ['კონფიგურაცია_20system_20configuration_45',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['კონფიგურაციისა_20და_20შენახვის_20ტერმინები_20glossary_20—_20configuration_20storage_46',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['კონფიგურაციის_20გაფართოება_47',['4. კონფიგურაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1388',1,'']]],
  ['კონფიგურაციის_20დამუშავების_20ეტაპები_48',['კონფიგურაციის დამუშავების ეტაპები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1201',1,'']]],
  ['კონფიგურაციის_20ვალიდაცია_20და_20შეცდომების_20თავიდან_20აცილება_49',['5. კონფიგურაციის ვალიდაცია და შეცდომების თავიდან აცილება',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1401',1,'']]],
  ['კონფიგურაციის_20მართვა_50',['კონფიგურაციის მართვა',['../conventions_docs.html#conv_config_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_51',['კონფიგურაციის მართვის პროცესი',['../structure_docs.html#struct_config_flow_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_20configuration_20flow_52',['კონფიგურაციის მართვის პროცესი (Configuration Flow)',['../md_docs_2structure_2configuration__flow.html',1,'']]],
  ['კონფიგურაციის_20მართვის_20წესები_53',['კონფიგურაციის მართვის წესები',['../md_docs_2convention_2configuration__management.html',1,'']]],
  ['კონფიგურაციის_20ოპტიმიზაცია_54',['კონფიგურაციის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1095',1,'']]],
  ['კონფიგურაციის_20პრობლემები_55',['2. კონფიგურაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1303',1,'']]],
  ['კონფიგურაციის_20სტრუქტურა_56',['კონფიგურაციის სტრუქტურა',['../md_docs_2structure_2configuration__flow.html#autotoc_md1200',1,'']]],
  ['კონფიგურაციის_20ტიპები_57',['კონფიგურაციის ტიპები',['../md_docs_2convention_2configuration__management.html#autotoc_md628',1,'']]],
  ['კონფიგურაციის_20შეცდომა_58',['8. როგორ დავადგინო კონფიგურაციის შეცდომა?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1341',1,'']]],
  ['კონფიგურაციის_20წვდომის_20მაგალითები_59',['კონფიგურაციის წვდომის მაგალითები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1202',1,'']]],
  ['კონფიგურაციის_20წყაროები_60',['კონფიგურაციის წყაროები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1199',1,'']]],
  ['კონფიგურაციის_20parsing_61',['კონფიგურაციის Parsing',['../md_docs_2convention_2configuration__management.html#autotoc_md635',1,'']]],
  ['კრიტერიუმები_62',['მიმოხილვის კრიტერიუმები',['../md_docs_2contributing_2review__guidelines.html#autotoc_md580',1,'']]]
];
