var searchData=
[
  ['✨_20არქიტექტურული_20გაუმჯობესებები_20და_20dx_20architectural_20developer_20experience_20improvements_0',['✨ არქიტექტურული გაუმჯობესებები და DX (Architectural &amp; Developer Experience Improvements)',['../md_docs_2changelog_2v9.html#autotoc_md775',1,'']]],
  ['✨_20არქიტექტურული_20გაუმჯობესებები_20architectural_20improvements_1',['✨ არქიტექტურული გაუმჯობესებები architectural improvements',['../md_docs_2changelog_2v9.html#autotoc_md800',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md791',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md788',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v8.html#autotoc_md770',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v8.html#autotoc_md764',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v7.html#autotoc_md748',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)']]],
  ['✨_20ახალი_20ფუნქციები_20features_2',['✨ ახალი ფუნქციები features',['../md_docs_2changelog_2v5.html#autotoc_md657',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md690',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md705',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md662',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md666',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md701',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md671',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md696',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md676',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md693',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md681',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md685',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md653',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md649',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md644',1,'✨ ახალი ფუნქციები (Features)']]],
  ['✨_20ახალი_20ფუნქციონალი_3',['✨ ახალი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md713',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md715',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md719',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md722',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md726',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md729',1,'✨ ახალი ფუნქციონალი']]],
  ['✨_20გაუმჯობესებები_20improvements_4',['✨ გაუმჯობესებები improvements',['../md_docs_2changelog_2v7.html#autotoc_md754',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md780',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md796',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md677',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md687',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md672',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md667',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md658',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md654',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md650',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md645',1,'✨ გაუმჯობესებები (Improvements)']]],
  ['✨_20დამატებულია_5',['✨ დამატებულია',['../md_docs_2changelog_2v5.html#autotoc_md709',1,'']]],
  ['✨_20დამატებულია_20added_6',['✨ დამატებულია (Added)',['../md_docs_2changelog_2v5.html#autotoc_md640',1,'']]],
  ['✨_20დამატებული_7',['✨ დამატებული',['../md_docs_2changelog_2v6.html#autotoc_md743',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md734',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md738',1,'✨ დამატებული']]],
  ['✨_20დამატებული_20ფუნქციონალი_20და_20dx_20added_20features_20developer_20experience_8',['✨ დამატებული ფუნქციონალი და dx added features developer experience',['../md_docs_2changelog_2v10.html#autotoc_md579',1,'✨ დამატებული ფუნქციონალი და DX (Added Features &amp; Developer Experience)'],['../md_docs_2changelog_2v10.html#autotoc_md584',1,'✨ დამატებული ფუნქციონალი და DX (Added Features &amp; Developer Experience)'],['../md_docs_2changelog_2v10.html#autotoc_md574',1,'✨ დამატებული ფუნქციონალი და DX (Added Features &amp; Developer Experience)']]],
  ['✨_20დამატებული_20ფუნქციონალი_20added_9',['✨ დამატებული ფუნქციონალი added',['../md_docs_2changelog_2v5.html#autotoc_md612',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md607',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md601',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md595',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v10.html#autotoc_md589',1,'✨ დამატებული ფუნქციონალი (Added)']]],
  ['✨_20added_20დამატებული_20ფუნქციონალი_10',['✨ added დამატებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md631',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md626',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md621',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md616',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md636',1,'✨ Added (დამატებული ფუნქციონალი)']]]
];
