var searchData=
[
  ['warning_20level_0',['2. ESP_LOGW - Warning Level',['../md_docs_2convention_2logging__standards.html#autotoc_md801',1,'']]],
  ['watchdog_1',['1. Stack Overflow და Task Watchdog',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1455',1,'']]],
  ['watchdog_20module_20api_2',['Watchdog Module API',['../md_docs_2api__reference_2system__api.html#autotoc_md423',1,'']]],
  ['watchdog_5fmodule_5fcreate_20const_20cjson_20config_3',['module_t *watchdog_module_create(const cJSON *config);',['../md_docs_2api__reference_2system__api.html#autotoc_md424',1,'']]],
  ['watchdog_5fmodule_5ffeed_20void_4',['esp_err_t watchdog_module_feed(void);',['../md_docs_2api__reference_2system__api.html#autotoc_md425',1,'']]],
  ['watchdog_5fmodule_5fset_5ftimeout_20uint32_5ft_20timeout_5fms_5',['esp_err_t watchdog_module_set_timeout(uint32_t timeout_ms);',['../md_docs_2api__reference_2system__api.html#autotoc_md426',1,'']]],
  ['websocket_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20websocket_6',['WebSocket ინტეგრაციის სახელმძღვანელო (Integration — WebSocket)',['../md_docs_2integration_2integration__websocket.html',1,'']]],
  ['websocket_20integration_7',['5. WebSocket Integration',['../md_docs_2tutorials_2integration__example.html#autotoc_md1546',1,'']]],
  ['why_20how_8',['Why/How',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md515',1,'']]],
  ['wifi_20მოდული_9',['📡 WiFi მოდული',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1269',1,'']]],
  ['wifi_20მოდული_3a_10',['📡 WiFi მოდული:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md870',1,'']]],
  ['wifi_20esp_20now_11',['3. Communication Integration (MQTT/WiFi/ESP-NOW)',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1173',1,'']]],
  ['wifi_20module_20api_12',['WiFi Module API',['../md_docs_2api__reference_2communication__api.html#autotoc_md74',1,'']]],
  ['wifi_5fdata_13',['static esp_err_t parse_wifi_config(const cJSON *config, wifi_private_data_t *wifi_data);',['../md_docs_2api__reference_2communication__api.html#autotoc_md91',1,'']]],
  ['wifi_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_14',['static void wifi_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2communication__api.html#autotoc_md87',1,'']]],
  ['wifi_5fmanager_2ec_15',['wifi_manager.c',['../wifi__manager_8c.html',1,'']]],
  ['wifi_5fmanager_2eh_16',['wifi_manager.h',['../wifi__manager_8h.html',1,'']]],
  ['wifi_5fmanager_5fconfig_5ft_17',['wifi_manager_config_t',['../structwifi__manager__config__t.html',1,'']]],
  ['wifi_5fmanager_5fcreate_18',['wifi_manager_create',['../wifi__manager_8h.html#a5100b2f029e2c1e6e8212bd03703667e',1,'wifi_manager_create(const cJSON *config):&#160;wifi_manager.c'],['../wifi__manager_8c.html#a5100b2f029e2c1e6e8212bd03703667e',1,'wifi_manager_create(const cJSON *config):&#160;wifi_manager.c']]],
  ['wifi_5fmanager_5fprivate_5fdata_5ft_19',['wifi_manager_private_data_t',['../structwifi__manager__private__data__t.html',1,'']]],
  ['wifi_5fmodule_5fconnect_20const_20char_20ssid_20const_20char_20password_20',['esp_err_t wifi_module_connect(const char *ssid, const char *password);',['../md_docs_2api__reference_2communication__api.html#autotoc_md76',1,'']]],
  ['wifi_5fmodule_5fcreate_20const_20cjson_20config_21',['module_t *wifi_module_create(const cJSON *config);',['../md_docs_2api__reference_2communication__api.html#autotoc_md75',1,'']]],
  ['wifi_5fmodule_5fdisconnect_20void_22',['esp_err_t wifi_module_disconnect(void);',['../md_docs_2api__reference_2communication__api.html#autotoc_md77',1,'']]],
  ['wifi_5fprivate_5fdata_5ft_20wifi_5fdata_23',['static esp_err_t parse_wifi_config(const cJSON *config, wifi_private_data_t *wifi_data);',['../md_docs_2api__reference_2communication__api.html#autotoc_md91',1,'']]],
  ['workflow_24',['🔄 სრული Workflow',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md880',1,'']]],
  ['workflow_20განახლებული_25',['🔄 სრული Workflow (განახლებული)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1279',1,'']]],
  ['workflow_3a_26',['2. განვითარების workflow:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md901',1,'']]]
];
