var searchData=
[
  ['data_20pointer_20naming_0',['Private Data Pointer Naming',['../md_docs_2convention_2variable__naming.html#autotoc_md831',1,'']]],
  ['data_20size_5ft_20data_5flength_1',['data size_t data_length',['../md_docs_2api__reference_2communication__api.html#autotoc_md74',1,'esp_err_t espnow_module_send(const uint8_t *peer_mac, const uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md184',1,'esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md185',1,'esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);']]],
  ['data_20structure_2',['Private Data Structure',['../md_docs_2convention_2configuration__management.html#autotoc_md700',1,'']]],
  ['data_5flength_3',['data_length',['../md_docs_2api__reference_2communication__api.html#autotoc_md74',1,'esp_err_t espnow_module_send(const uint8_t *peer_mac, const uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md184',1,'esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md185',1,'esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md191',1,'esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);']]],
  ['data_5fwrapper_4',['data_wrapper',['../structevent__message__t.html#a6d545c17b49bd18413b4cd6d14c026c3',1,'event_message_t']]],
  ['date_5fstr_20size_5ft_20size_5',['esp_err_t version_module_get_build_date(char *date_str, size_t size);',['../md_docs_2api__reference_2version__api.html#autotoc_md455',1,'']]],
  ['debug_20build_20ის_20კონფიგურაცია_6',['2. Debug Build-ის კონფიგურაცია',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1475',1,'']]],
  ['debug_20level_7',['4. ESP_LOGD - Debug Level',['../md_docs_2convention_2logging__standards.html#autotoc_md776',1,'']]],
  ['debugging_8',['6. Event და Service Debugging',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1479',1,'']]],
  ['debugging_20guide_20დიბაგინგის_20სახელმძღვანელო_9',['Debugging Guide (დიბაგინგის სახელმძღვანელო)',['../md_docs_2troubleshooting_2debugging__guide.html',1,'']]],
  ['decision_20record_20template_10',['არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)',['../md_docs_2design__decisions_2decision__record__template.html',1,'']]],
  ['decisions_11',['decisions',['../md_docs_2design__decisions_2error__handling__decisions.html',1,'შეცდომების დამუშავების არქიტექტურული გადაწყვეტილებები (Error Handling Decisions)'],['../md_docs_2design__decisions_2design__decisions__index.html',1,'Synapse Design Decisions']]],
  ['default_20მნიშვნელობები_12',['ვალიდაცია და Default მნიშვნელობები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1353',1,'']]],
  ['default_20მნიშვნელობები_20არ_20მუშაობს_13',['პრობლემა: default მნიშვნელობები არ მუშაობს',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1455',1,'']]],
  ['default_20values_14',['Default Values',['../md_docs_2convention_2configuration__management.html#autotoc_md702',1,'']]],
  ['define_5fcomponent_5ftag_15',['define_component_tag',['../logging_8h.html#a7ece332eb67f0652fb4b9af20392c0f9',1,'DEFINE_COMPONENT_TAG:&#160;logging.h'],['../logger__module_8c.html#ae7c63dd9d16170942bd5413a956ef9be',1,'DEFINE_COMPONENT_TAG(&quot;LOGGER_MODULE&quot;):&#160;logger_module.c'],['../md_docs_2api__reference_2core__api.html#autotoc_md129',1,'DEFINE_COMPONENT_TAG']]],
  ['definition_16',['definition',['../md_docs_2convention_2logging__standards.html#autotoc_md769',1,'Component Tag Definition'],['../md_docs_2convention_2configuration__management.html#autotoc_md703',1,'Constants Definition']]],
  ['degradation_17',['2. Graceful Degradation',['../md_docs_2convention_2error__handling.html#autotoc_md746',1,'']]],
  ['deinit_18',['4. Deinit',['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1411',1,'']]],
  ['dependencies_19',['❌ პირდაპირი Dependencies',['../md_docs_2convention_2communication__patterns.html#autotoc_md672',1,'']]],
  ['dependencies_20მიხედვით_20',['Dependencies მიხედვით',['../md_docs_2convention_2module__structure.html#autotoc_md808',1,'']]],
  ['deprecated_20api_20ის_20მონიშვნა_21',['Deprecated API-ის მონიშვნა',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md994',1,'']]],
  ['deprecated_20list_22',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20checklist_23',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['design_20decisions_24',['Synapse Design Decisions',['../md_docs_2design__decisions_2design__decisions__index.html',1,'']]],
  ['detailed_20file_20changes_25',['Detailed File Changes',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md496',1,'']]],
  ['details_26',['Implementation Details',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md16',1,'']]],
  ['development_20notes_27',['Development Notes',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md20',1,'']]],
  ['device_5faddress_20const_20uint8_5ft_20data_20size_5ft_20data_5flength_28',['esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md185',1,'']]],
  ['device_5faddress_20uint8_5ft_20data_20size_5ft_20data_5flength_29',['esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md184',1,'']]],
  ['dht22_30',['1. Event-Driven Module (მაგ., DHT22)',['../md_docs_2convention_2module__structure.html#autotoc_md804',1,'']]],
  ['dht22_5fdata_31',['static esp_err_t parse_dht22_config(const cJSON *config, dht22_private_data_t *dht22_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md368',1,'']]],
  ['dht22_5fdata_20float_20temperature_20float_20humidity_32',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md365',1,'']]],
  ['dht22_5fdeinit_20module_5ft_20module_33',['static esp_err_t dht22_deinit(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md361',1,'']]],
  ['dht22_5fdisable_20module_5ft_20module_34',['static esp_err_t dht22_disable(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md360',1,'']]],
  ['dht22_5fenable_20module_5ft_20module_35',['static esp_err_t dht22_enable(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md359',1,'']]],
  ['dht22_5fget_5fstatus_20module_5ft_20module_36',['static module_status_t dht22_get_status(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md371',1,'']]],
  ['dht22_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_37',['static void dht22_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md364',1,'']]],
  ['dht22_5finit_20module_5ft_20module_38',['static esp_err_t dht22_init(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md358',1,'']]],
  ['dht22_5fmodule_5fcreate_20const_20cjson_20config_39',['module_t &lt;em&gt;dht22_module_create(const cJSON *config);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md357',1,'']]],
  ['dht22_5fprivate_5fdata_5ft_20dht22_5fdata_40',['static esp_err_t parse_dht22_config(const cJSON *config, dht22_private_data_t *dht22_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md368',1,'']]],
  ['dht22_5fprivate_5fdata_5ft_20dht22_5fdata_20float_20temperature_20float_20humidity_41',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md365',1,'']]],
  ['diagnostics_42',['diagnostics',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1442',1,'5. Peripheral Diagnostics'],['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1443',1,'6. Network Diagnostics']]],
  ['diagnostics_20გაფართოებული_20დიაგნოსტიკა_43',['Advanced Diagnostics (გაფართოებული დიაგნოსტიკა)',['../md_docs_2troubleshooting_2advanced__diagnostics.html',1,'']]],
  ['diagnostics_20module_20api_44',['Diagnostics Module API',['../md_docs_2api__reference_2system__api.html#autotoc_md410',1,'']]],
  ['diagnostics_5fmodule_5fcreate_20const_20cjson_20config_45',['module_t *diagnostics_module_create(const cJSON *config);',['../md_docs_2api__reference_2system__api.html#autotoc_md411',1,'']]],
  ['diagnostics_5fmodule_5fget_5freport_20char_20report_5fbuffer_20size_5ft_20buffer_5fsize_46',['esp_err_t diagnostics_module_get_report(char *report_buffer, size_t buffer_size);',['../md_docs_2api__reference_2system__api.html#autotoc_md413',1,'']]],
  ['diagnostics_5fmodule_5frun_5ftests_20void_47',['esp_err_t diagnostics_module_run_tests(void);',['../md_docs_2api__reference_2system__api.html#autotoc_md412',1,'']]],
  ['diagram_48',['Architecture Diagram',['../md_docs_2convention_2communication__patterns.html#autotoc_md685',1,'']]],
  ['direct_20api_20communication_20service_20locator_49',['Direct API Communication (Service Locator)',['../md_docs_2convention_2communication__patterns.html#autotoc_md669',1,'']]],
  ['directory_20structure_50',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['disable_51',['disable',['../md_docs_2convention_2logging__standards.html#autotoc_md786',1,'1. Module Enable/Disable'],['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1410',1,'3. Enable/Disable'],['../structmodule__t.html#ae00c883b7a5e858edad93c7cdbd5239b',1,'module_t::disable']]],
  ['disable_20ზე_52',['პრობლემა: მოდული არ რეაგირებს enable/disable-ზე',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1466',1,'']]],
  ['disable_20logger_53',['Disable Logger',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md13',1,'']]],
  ['disable_20logger_20module_54',['Disable Logger Module',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md9',1,'']]],
  ['disclosure_20policy_20უსაფრთხოების_20ხარვეზების_20აღმოჩენისა_20და_20შეტყობინების_20პროცედურა_55',['Vulnerability Disclosure Policy (უსაფრთხოების ხარვეზების აღმოჩენისა და შეტყობინების პროცედურა)',['../md_docs_2security_2security__vulnerability__disclosure.html',1,'']]],
  ['display_20configuration_56',['3. LCD Display Configuration',['../md_docs_2convention_2configuration__management.html#autotoc_md695',1,'']]],
  ['display_20configuration_20ssd1306_57',['2. Display Configuration (SSD1306)',['../md_docs_2convention_2configuration__management.html#autotoc_md694',1,'']]],
  ['display_20module_58',['1. Service Registration (Display Module)',['../md_docs_2convention_2communication__patterns.html#autotoc_md677',1,'']]],
  ['display_20module_20api_20reference_59',['Synapse Display Module API Reference',['../md_docs_2api__reference_2display__api.html',1,'']]],
  ['display_20modules_60',['display modules',['../md_docs_2performance_2performance__display.html',1,'ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)'],['../md_docs_2convention_2function__naming.html#autotoc_md758',1,'3. Display Modules'],['../md_docs_2convention_2variable__naming.html#autotoc_md820',1,'Display Modules']]],
  ['display_20parameters_61',['3. Display Parameters',['../md_docs_2convention_2configuration__management.html#autotoc_md715',1,'']]],
  ['documentation_62',['documentation',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1145',1,'5. Documentation'],['../md_docs_2convention_2convention__index.html#autotoc_md721',1,'Coding &amp; Documentation']]],
  ['documentation_20module_20design_20checklist_63',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['doxygen_20კომენტარების_20სტანდარტი_64',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['doxygen_20კომენტარების_20სტანდარტი_20v1_200_65',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['doxygen_20ტეგების_20გამოყენების_20წესები_66',['5. Doxygen ტეგების გამოყენების წესები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md662',1,'']]],
  ['doxygen_5fmain_5fpages_67',['doxygen_main_pages',['../md_docs_2doxygen__main__pages.html',1,'']]],
  ['driven_20module_20მაგ_20dht22_68',['1. Event-Driven Module (მაგ., DHT22)',['../md_docs_2convention_2module__structure.html#autotoc_md804',1,'']]],
  ['driven_20module_20მაგ_20ssd1306_69',['2. Service-Driven Module (მაგ., SSD1306)',['../md_docs_2convention_2module__structure.html#autotoc_md805',1,'']]],
  ['driver_20api_70',['driver api',['../md_docs_2api__reference_2drivers__api.html#autotoc_md181',1,'I2C Bus Driver API'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md188',1,'SPI Bus Driver API']]],
  ['driver_20module_20მაგ_20i2c_20bus_71',['3. Driver Module (მაგ., I2C Bus)',['../md_docs_2convention_2module__structure.html#autotoc_md806',1,'']]],
  ['drivers_20module_20api_20reference_72',['Synapse Drivers Module API Reference',['../md_docs_2api__reference_2drivers__api.html',1,'']]],
  ['dumps_20და_20crash_20reporting_73',['3. Core Dumps და Crash Reporting',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1440',1,'']]]
];
