var searchData=
[
  ['tag_20definition_0',['Component Tag Definition',['../md_docs_2convention_2logging__standards.html#autotoc_md761',1,'']]],
  ['task_20და_20stack_20usage_20მონიტორინგი_1',['4. Task და Stack Usage მონიტორინგი',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1469',1,'']]],
  ['task_20ფუნქციები_2',['4. Task ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md757',1,'']]],
  ['task_20state_20changes_3',['2. Task State Changes',['../md_docs_2convention_2logging__standards.html#autotoc_md779',1,'']]],
  ['task_20watchdog_4',['1. Stack Overflow და Task Watchdog',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1430',1,'']]],
  ['telemetry_5fevents_20h_5',['[interfaces/include/telemetry_events.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md477',1,'']]],
  ['temperature_20float_20humidity_6',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md365',1,'']]],
  ['template_7',['template',['../md_docs_2design__decisions_2decision__record__template.html',1,'არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)'],['../md_docs_2contributing_2issue__template.html',1,'Synapse Issue Template'],['../md_docs_2contributing_2pull__request__template.html',1,'Synapse Pull Request Template']]],
  ['test_5fmodule_2ec_8',['test_module.c',['../test__module_8c.html',1,'']]],
  ['test_5fmodule_2eh_9',['test_module.h',['../test__module_8h.html',1,'']]],
  ['test_5fmodule_5fconfig_5ft_10',['test_module_config_t',['../structtest__module__config__t.html',1,'']]],
  ['test_5fmodule_5fcreate_11',['test_module_create',['../test__module_8h.html#ab57d0c0bbfc2bd7c2772984652a91059',1,'test_module_create(const cJSON *config):&#160;test_module.c'],['../test__module_8c.html#ab57d0c0bbfc2bd7c2772984652a91059',1,'test_module_create(const cJSON *config):&#160;test_module.c']]],
  ['test_5fmodule_5fmodule_5ft_12',['test_module_module_t',['../structtest__module__module__t.html',1,'']]],
  ['testability_13',['7. Testability',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1139',1,'']]],
  ['testing_14',['Testing',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md490',1,'']]],
  ['text_20uint8_5ft_20line_15',['text uint8_t line',['../md_docs_2api__reference_2display__api.html#autotoc_md163',1,'esp_err_t ssd1306_api_write_text(const char *text, uint8_t line);'],['../md_docs_2api__reference_2module__api.html#autotoc_md260',1,'esp_err_t {module_name}_api_write_text(const char *text, uint8_t line);']]],
  ['the_20air_20module_20api_20reference_16',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['the_20framework_17',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['time_20sync_20module_20api_18',['Time Sync Module API',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md422',1,'']]],
  ['time_20sync_20module_20api_20reference_19',['Synapse Time Sync Module API Reference',['../md_docs_2api__reference_2time__sync__api.html',1,'']]],
  ['time_5fstr_20size_5ft_20size_20',['esp_err_t version_module_get_build_time(char *time_str, size_t size);',['../md_docs_2api__reference_2version__api.html#autotoc_md456',1,'']]],
  ['time_5fsync_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_21',['static void time_sync_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md430',1,'']]],
  ['time_5fsync_5fmodule_5fcreate_20const_20cjson_20config_22',['module_t *time_sync_module_create(const cJSON *config);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md423',1,'']]],
  ['time_5fsync_5fmodule_5fget_5ftime_20time_5ft_20current_5ftime_23',['esp_err_t time_sync_module_get_time(time_t *current_time);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md427',1,'']]],
  ['time_5fsync_5fmodule_5fset_5fserver_20module_5ft_20module_20const_20char_20server_5furl_24',['esp_err_t time_sync_module_set_server(module_t *module, const char *server_url);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md426',1,'']]],
  ['time_5fsync_5fmodule_5fstart_20module_5ft_20module_25',['esp_err_t time_sync_module_start(module_t *module);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md424',1,'']]],
  ['time_5fsync_5fmodule_5fstop_20module_5ft_20module_26',['esp_err_t time_sync_module_stop(module_t *module);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md425',1,'']]],
  ['time_5ft_20current_5ftime_27',['esp_err_t time_sync_module_get_time(time_t *current_time);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md427',1,'']]],
  ['timeout_5fms_28',['esp_err_t watchdog_module_set_timeout(uint32_t timeout_ms);',['../md_docs_2api__reference_2system__api.html#autotoc_md408',1,'']]],
  ['timing_29',['1. Operation Timing',['../md_docs_2convention_2logging__standards.html#autotoc_md781',1,'']]],
  ['timing_20parameters_30',['2. Timing Parameters',['../md_docs_2convention_2configuration__management.html#autotoc_md706',1,'']]],
  ['tls_20ssl_31',['TLS/SSL',['../md_docs_2security_2security__guidelines.html#autotoc_md1296',1,'']]],
  ['tls_20ssl_20ჩართვა_20mqtt_20ში_32',['tls ssl ჩართვა mqtt ში',['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1027',1,'TLS/SSL ჩართვა MQTT-ში'],['../md_docs_2security_2security__best__practices.html#autotoc_md1273',1,'TLS/SSL ჩართვა MQTT-ში']]],
  ['topic_20const_20char_20message_33',['esp_err_t mqtt_module_publish(const char *topic, const char *message);',['../md_docs_2api__reference_2communication__api.html#autotoc_md63',1,'']]],
  ['topic_20mqtt_5fmessage_5fhandler_5ft_20handler_34',['esp_err_t mqtt_module_subscribe(const char *topic, mqtt_message_handler_t handler);',['../md_docs_2api__reference_2communication__api.html#autotoc_md64',1,'']]],
  ['trade_20offs_35',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['troubleshooting_36',['7. Troubleshooting',['../md_docs_2tutorials_2integration__example.html#autotoc_md1523',1,'']]],
  ['troubleshooting_20faq_37',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['tt_20bool_20fmw_5fresource_5fis_5flocked_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20tt_38',['&lt;tt&gt;bool fmw_resource_is_locked(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md345',1,'']]],
  ['tt_20check_5fconventions_20py_20tt_39',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['tt_20const_20char_20fmw_5fresource_5fget_5fowner_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20tt_40',['&lt;tt&gt;const char *fmw_resource_get_owner(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md347',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fresource_5flock_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20const_20char_20owner_20tt_41',['&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md341',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fresource_5fmanager_5finit_20void_20tt_42',['&lt;tt&gt;esp_err_t fmw_resource_manager_init(void)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md339',1,'']]],
  ['tt_20esp_5ferr_5ft_20fmw_5fresource_5frelease_20fmw_5fresource_5ftype_5ft_20type_20uint8_5ft_20resource_5fid_20const_20char_20owner_20tt_43',['&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md343',1,'']]],
  ['tt_20i2c_5fbus_5fmodule_20h_20tt_44',['2.2. მაგალითი (&lt;tt&gt;i2c_bus_module.h&lt;/tt&gt;)',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md648',1,'']]],
  ['tt_20include_20module_5fname_20h_20tt_45',['1. Header ფაილი (&lt;tt&gt;include/{module_name}.h&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md793',1,'']]],
  ['tt_20logger_5fmodule_5fcreate_20const_20cjson_20config_20tt_46',['&lt;tt&gt;logger_module_create(const cJSON *config)&lt;/tt&gt;',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md23',1,'']]],
  ['tt_20module_5fname_20c_20tt_47',['2. Source ფაილი (&lt;tt&gt;{module_name}.c&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md794',1,'']]],
  ['tt_20service_5flocator_20h_20tt_48',['3.2. მაგალითი (&lt;tt&gt;service_locator.h&lt;/tt&gt;)',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md651',1,'']]],
  ['tx_5fdata_20uint8_5ft_20rx_5fdata_20size_5ft_20data_5flength_49',['esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md191',1,'']]],
  ['txt_50',['[core/CMakeLists.txt]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md464',1,'']]],
  ['txt_20სტრუქტურა_51',['CMakeLists.txt სტრუქტურა',['../md_docs_2convention_2module__structure.html#autotoc_md799',1,'']]],
  ['type_52',['type',['../structservice__entry__t.html#a2ffb19a8df6aa8318e4fca7de82b22a3',1,'service_entry_t']]],
  ['type_20uint8_5ft_20resource_5fid_20const_20char_20owner_20tt_53',['type uint8_t resource_id const char owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md341',1,'&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md343',1,'&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['type_20uint8_5ft_20resource_5fid_20tt_54',['type uint8_t resource_id tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md345',1,'&lt;tt&gt;bool fmw_resource_is_locked(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md347',1,'&lt;tt&gt;const char *fmw_resource_get_owner(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;']]]
];
