var searchData=
[
  ['სად_20ვიპოვო_20დოკუმენტაციის_20სტრუქტურის_20და_20სტანდარტების_20შესახებ_20ინფორმაცია_0',['7. სად ვიპოვო დოკუმენტაციის სტრუქტურის და სტანდარტების შესახებ ინფორმაცია?',['../md_docs_2contributing_2faq.html#autotoc_md513',1,'']]],
  ['სათაურის_20წერის_20წესები_1',['სათაურის წერის წესები',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md469',1,'']]],
  ['სათაურის_20header_20კომენტარი_2',['2. ფაილის სათაურის (Header) კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md590',1,'']]],
  ['საკონტაქტო_20ინფორმაცია_3',['საკონტაქტო ინფორმაცია',['../md_docs_2security_2security__vulnerability__disclosure.html#autotoc_md1182',1,'']]],
  ['საკუთარი_20მოდულის_20შექმნა_20create_20your_20first_20module_4',['პირველი საკუთარი მოდულის შექმნა (Create Your First Module)',['../md_docs_2tutorials_2create__first__module.html',1,'']]],
  ['სამუშაო_20პროცესი_5',['სამუშაო პროცესი',['../md_docs_2contributing_2branching__strategy.html#autotoc_md443',1,'']]],
  ['საუკეთესო_20პრაქტიკები_6',['საუკეთესო პრაქტიკები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md445',1,'საუკეთესო პრაქტიკები'],['../md_docs_2contributing_2review__guidelines.html#autotoc_md582',1,'საუკეთესო პრაქტიკები']]],
  ['საუკეთესო_20პრაქტიკები_20წარმადობისთვის_20performance_20best_20practices_7',['საუკეთესო პრაქტიკები წარმადობისთვის (Performance Best Practices)',['../md_docs_2performance_2performance__best__practices.html',1,'']]],
  ['საუკეთესო_20პრაქტიკები_20security_20best_20practices_8',['უსაფრთხოების საუკეთესო პრაქტიკები (Security Best Practices)',['../md_docs_2security_2security__best__practices.html',1,'']]],
  ['საქაღალდეებისა_20და_20ფაილების_20სტრუქტურა_9',['საქაღალდეებისა და ფაილების სტრუქტურა',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md777',1,'საქაღალდეებისა და ფაილების სტრუქტურა'],['../structure_docs.html#struct_dir_sec',1,'საქაღალდეებისა და ფაილების სტრუქტურა']]],
  ['საქაღალდეებისა_20და_20ფაილების_20სტრუქტურა_20directory_20structure_10',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['საქაღალდეების_20აღწერა_11',['ძირითადი საქაღალდეების აღწერა',['../md_docs_2structure_2directory__structure.html#autotoc_md1221',1,'']]],
  ['საქაღალდის_20და_20ფაილების_20შექმნა_12',['2. საქაღალდის და ფაილების შექმნა',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1357',1,'']]],
  ['საქაღალდის_20სტრუქტურა_13',['საქაღალდის სტრუქტურა',['../md_docs_2convention_2module__structure.html#autotoc_md733',1,'საქაღალდის სტრუქტურა'],['../md_docs_2structure_2directory__structure.html#autotoc_md1222',1,'modules საქაღალდის სტრუქტურა']]],
  ['საჭიროების_20განსაზღვრა_14',['საჭიროების განსაზღვრა',['../md_docs_2tutorials_2integration__example.html#autotoc_md1375',1,'1. ინტეგრაციის საჭიროების განსაზღვრა'],['../md_docs_2tutorials_2module__extension.html#autotoc_md1385',1,'1. საჭიროების განსაზღვრა'],['../md_docs_2tutorials_2create__first__module.html#autotoc_md1356',1,'1. საჭიროების განსაზღვრა']]],
  ['საჭირო_20მოდულების_20ჩართვა_20და_20კონფიგურაცია_15',['2. საჭირო მოდულების ჩართვა და კონფიგურაცია',['../md_docs_2tutorials_2integration__example.html#autotoc_md1376',1,'']]],
  ['სახელდების_20წესები_16',['ბრენჩის სახელდების წესები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md441',1,'']]],
  ['სახელები_17',['1. დესკრიპტიული სახელები',['../md_docs_2convention_2variable__naming.html#autotoc_md750',1,'']]],
  ['სახელმძღვანელოების_20ინდექსი_18',['სახელმძღვანელოების ინდექსი',['../md_docs_2integration_2integration__index.html',1,'Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)'],['../md_docs_2security_2security__index.html',1,'Security Index (უსაფრთხოების სახელმძღვანელოების ინდექსი)']]],
  ['სახელმძღვანელოები_19',['სახელმძღვანელოები',['../md_docs_2integration_2integration__index.html#autotoc_md999',1,'თემატური ინტეგრაციის სახელმძღვანელოები'],['../md_docs_2security_2security__index.html#autotoc_md1169',1,'თემატური უსაფრთხოების სახელმძღვანელოები'],['../md_docs_2performance_2performance__index.html#autotoc_md1085',1,'თემატური performance სახელმძღვანელოები'],['../md_docs_2contributing_2contributing__index.html#autotoc_md491',1,'ძირითადი სახელმძღვანელოები']]],
  ['სახელმძღვანელოები_20და_20მაგალითები_20',['სახელმძღვანელოები და მაგალითები',['../tutorials_docs.html',1,'']]],
  ['სახელმძღვანელოები_20performance_20optimization_20guide_21',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['სახელმძღვანელოები_20security_20guidelines_22',['უსაფრთხოების სახელმძღვანელოები (Security Guidelines)',['../md_docs_2security_2security__guidelines.html',1,'']]],
  ['სახელმძღვანელო_23',['სახელმძღვანელო',['../md_docs_2troubleshooting_2debugging__guide.html',1,'Debugging Guide (დიბაგინგის სახელმძღვანელო)'],['../md_docs_2performance_2performance__index.html',1,'Performance (წარმადობის სახელმძღვანელო)']]],
  ['სახელმძღვანელო_20contributing_20guide_24',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20cloud_25',['Cloud ინტეგრაციის სახელმძღვანელო (Integration — Cloud)',['../md_docs_2integration_2integration__cloud.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20mqtt_26',['MQTT ინტეგრაციის სახელმძღვანელო (Integration — MQTT)',['../md_docs_2integration_2integration__mqtt.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20rest_20api_27',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20websocket_28',['WebSocket ინტეგრაციის სახელმძღვანელო (Integration — WebSocket)',['../md_docs_2integration_2integration__websocket.html',1,'']]],
  ['სახელმძღვანელო_20performance_20benchmarks_20guide_29',['ბენჩმარკების ჩატარების სახელმძღვანელო (Performance Benchmarks Guide)',['../md_docs_2performance_2performance__benchmarks.html',1,'']]],
  ['სახელმძღვანელო_20performance_20resource_20usage_20guide_30',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['სა_20და_20კოდის_20ტერმინები_20glossary_20—_20api_20code_31',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['სენსორის_20კითხვა_32',['სენსორის კითხვა',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1048',1,'']]],
  ['სერვისს_33',['3. რატომ ვერ პოულობს Service Locator-ი ჩემს სერვისს?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1336',1,'']]],
  ['სია_20security_20checklist_34',['უსაფრთხოების შემოწმების სია (Security Checklist)',['../md_docs_2security_2security__checklist.html',1,'']]],
  ['სიგნირება_35',['სიგნირება',['../md_docs_2security_2security__best__practices.html#autotoc_md1132',1,'OTA განახლების სიგნირება'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md929',1,'OTA განახლების სიგნირება']]],
  ['სისტემის_20კონფიგურაცია_20system_20configuration_36',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['სისტემური_20მოთხოვნები_37',['სისტემური მოთხოვნები',['../md_docs_2contributing_2local__setup.html#autotoc_md542',1,'']]],
  ['სიცოცხლის_20ციკლის_20დიაგრამა_38',['სიცოცხლის ციკლის დიაგრამა',['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1262',1,'']]],
  ['სიცოცხლის_20ციკლის_20ეტაპები_39',['სიცოცხლის ციკლის ეტაპები',['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1256',1,'']]],
  ['სიცოცხლის_20ციკლის_20მართვის_40',['მაგალითი მოდულის სიცოცხლის ციკლის მართვის',['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1263',1,'']]],
  ['სიცოცხლის_20ციკლი_41',['სიცოცხლის ციკლი',['../structure_docs.html#struct_lifecycle_sec',1,'მოდულის სიცოცხლის ციკლი'],['../md_docs_2api__reference_2display__api.html#autotoc_md125',1,'მოდულის შექმნა და სიცოცხლის ციკლი'],['../md_docs_2api__reference_2sensor__api.html#autotoc_md308',1,'მოდულის შექმნა და სიცოცხლის ციკლი'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md776',1,'სიცოცხლის ციკლი']]],
  ['სიცოცხლის_20ციკლი_20და_20ინიციალიზაცია_20lifecycle_20initialization_42',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['სიცოცხლის_20ციკლი_20lifecycle_43',['მოდულის სიცოცხლის ციკლი (Lifecycle)',['../md_docs_2structure_2module__architecture.html#autotoc_md1270',1,'']]],
  ['სკრიპტის_20გამოყენება_44',['მიგრაციის სკრიპტის გამოყენება',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md888',1,'']]],
  ['სკრიპტი_45',['2. რას ამოწმებს სკრიპტი?',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md496',1,'']]],
  ['სპეციალური_20კონვენციები_46',['სპეციალური კონვენციები',['../md_docs_2convention_2function__naming.html#autotoc_md697',1,'']]],
  ['სრული_20კონფიგურაცია_47',['მაგალითი სრული კონფიგურაცია',['../md_docs_2convention_2configuration__management.html#autotoc_md627',1,'']]],
  ['სრული_20მოდული_48',['მაგალითი სრული მოდული',['../md_docs_2convention_2function__naming.html#autotoc_md703',1,'']]],
  ['სრული_20მოდული_20სტრუქტურა_49',['მაგალითი სრული მოდული სტრუქტურა',['../md_docs_2convention_2module__structure.html#autotoc_md747',1,'']]],
  ['სტანდარტებზე_20დაყრდნობით_50',['სტანდარტებზე დაყრდნობით',['../index.html#autotoc_md1283',1,'']]],
  ['სტანდარტების_20შესახებ_20ინფორმაცია_51',['7. სად ვიპოვო დოკუმენტაციის სტრუქტურის და სტანდარტების შესახებ ინფორმაცია?',['../md_docs_2contributing_2faq.html#autotoc_md513',1,'']]],
  ['სტანდარტები_52',['სტანდარტები',['../conventions_docs.html',1,'კონვენციები და სტანდარტები'],['../conventions_docs.html#conv_logging_sec',1,'ლოგირების სტანდარტები'],['../md_docs_2structure_2error__handling__and__logging.html#autotoc_md1231',1,'ლოგირების სტანდარტები'],['../md_docs_2contributing_2contributing__guide.html#autotoc_md483',1,'2. კოდის სტანდარტები'],['../md_docs_2structure_2faq.html#autotoc_md1248',1,'6. როგორ დავიცვა naming და structure სტანდარტები?'],['../md_docs_2convention_2logging__standards.html',1,'Logging-ის სტანდარტები']]],
  ['სტანდარტები_20და_20დოკუმენტაცია_53',['სტანდარტები და დოკუმენტაცია',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md779',1,'']]],
  ['სტანდარტები_20error_20handling_20logging_54',['შეცდომების დამუშავება და ლოგირების სტანდარტები (Error Handling &amp; Logging)',['../md_docs_2structure_2error__handling__and__logging.html',1,'']]],
  ['სტანდარტებს_20და_20კონვენციებს_20უნდა_20დავიცვა_55',['2. რა სტანდარტებს და კონვენციებს უნდა დავიცვა?',['../md_docs_2contributing_2faq.html#autotoc_md508',1,'']]],
  ['სტანდარტი_56',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['სტანდარტი_20v1_200_57',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['სტანდარტი_3a_20strong_58',['✅ &lt;strong&gt;ლოგირების სტანდარტი:&lt;/strong&gt;',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md498',1,'']]],
  ['სტანდარტული_20მოდულის_20layout_59',['სტანდარტული მოდულის layout',['../md_docs_2convention_2module__structure.html#autotoc_md734',1,'']]],
  ['სტანდარტული_20ფორმატი_60',['სტანდარტული ფორმატი',['../md_docs_2convention_2configuration__management.html#autotoc_md626',1,'სტანდარტული ფორმატი'],['../md_docs_2convention_2logging__standards.html#autotoc_md706',1,'სტანდარტული ფორმატი']]],
  ['სტარტი_61',['სწრაფი სტარტი',['../tutorials_docs.html#tut_getting_started_sec',1,'']]],
  ['სტარტი_20getting_20started_62',['სწრაფი სტარტი (Getting Started)',['../md_docs_2tutorials_2getting__started.html',1,'']]],
  ['სტატუსის_20მონიტორინგი_63',['5. მოდულის სტატუსის მონიტორინგი',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1350',1,'']]],
  ['სტატუსი_64',['სტატუსი',['../md_docs_2design__decisions_2decision__record__template.html#autotoc_md821',1,'']]],
  ['სტრატეგია_65',['ბრენჩინგის სტრატეგია',['../contributing_docs.html#contrib_branching_sec',1,'']]],
  ['სტრატეგიები_66',['სტრატეგიები',['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md859',1,'არჩეული სტრატეგიები'],['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md879',1,'არჩეული სტრატეგიები'],['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md900',1,'არჩეული სტრატეგიები']]],
  ['სტრიქონის_20შენახვა_67',['NVS-ში სტრიქონის შენახვა',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md949',1,'']]],
  ['სტრიქონის_20წაკითხვა_68',['NVS-დან სტრიქონის წაკითხვა',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md950',1,'']]],
  ['სტრუქტურა_69',['სტრუქტურა',['../structure_docs.html',1,'არქიტექტურა და სტრუქტურა'],['../md_docs_2structure_2directory__structure.html#autotoc_md1223',1,'თითოეული მოდულის სტრუქტურა'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1200',1,'კონფიგურაციის სტრუქტურა'],['../md_docs_2convention_2module__structure.html#autotoc_md747',1,'მაგალითი სრული მოდული სტრუქტურა'],['../conventions_docs.html#conv_module_struct_sec',1,'მოდულის სტრუქტურა'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md777',1,'საქაღალდეებისა და ფაილების სტრუქტურა'],['../structure_docs.html#struct_dir_sec',1,'საქაღალდეებისა და ფაილების სტრუქტურა'],['../md_docs_2convention_2module__structure.html#autotoc_md733',1,'საქაღალდის სტრუქტურა'],['../md_docs_2convention_2module__structure.html#autotoc_md736',1,'ფაილის სტრუქტურა'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md467',1,'ძირითადი სტრუქტურა'],['../md_docs_2structure_2directory__structure.html#autotoc_md1220',1,'ძირითადი სტრუქტურა'],['../md_docs_2convention_2function__naming.html#autotoc_md686',1,'1. სტრუქტურა'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md591',1,'2.1. სტრუქტურა'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md594',1,'3.1. სტრუქტურა'],['../md_docs_2convention_2module__structure.html#autotoc_md743',1,'CMakeLists.txt სტრუქტურა'],['../md_docs_2api__reference_2custom__api.html#autotoc_md115',1,'Custom Event-ის მონაცემების სტრუქტურა'],['../md_docs_2convention_2module__structure.html#autotoc_md745',1,'module.json სტრუქტურა'],['../md_docs_2structure_2directory__structure.html#autotoc_md1222',1,'modules საქაღალდის სტრუქტურა'],['../md_docs_2convention_2configuration__management.html#autotoc_md625',1,'system_config.json სტრუქტურა']]],
  ['სტრუქტურა_20და_20მაგალითი_70',['2. სტრუქტურა და მაგალითი',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1398',1,'']]],
  ['სტრუქტურა_20directory_20structure_71',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['სტრუქტურების_20და_20ტიპების_20კომენტარები_72',['4. სტრუქტურების და ტიპების კომენტარები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md596',1,'']]],
  ['სტრუქტურის_20გაცნობა_73',['2. პროექტის სტრუქტურის გაცნობა',['../md_docs_2tutorials_2getting__started.html#autotoc_md1367',1,'']]],
  ['სტრუქტურის_20დაცვა_74',['2. სტრუქტურის დაცვა',['../md_docs_2tutorials_2module__extension.html#autotoc_md1386',1,'']]],
  ['სტრუქტურის_20და_20სტანდარტების_20შესახებ_20ინფორმაცია_75',['7. სად ვიპოვო დოკუმენტაციის სტრუქტურის და სტანდარტების შესახებ ინფორმაცია?',['../md_docs_2contributing_2faq.html#autotoc_md513',1,'']]],
  ['სტრუქტურის_20მაგალითი_76',['სტრუქტურის მაგალითი',['../md_docs_2structure_2module__architecture.html#autotoc_md1271',1,'მოდულის სტრუქტურის მაგალითი'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md597',1,'4.1. სტრუქტურის მაგალითი']]],
  ['სტრუქტურის_20წესები_77',['მოდულის სტრუქტურის წესები',['../md_docs_2convention_2module__structure.html',1,'']]],
  ['სტრუქტურული_20მთლიანობა_3a_20strong_78',['✅ &lt;strong&gt;სტრუქტურული მთლიანობა:&lt;/strong&gt;',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md497',1,'']]],
  ['სქემის_20ვერსიონირება_79',['სქემის ვერსიონირება',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md886',1,'']]],
  ['სწორი_80',['✅ სწორი',['../md_docs_2convention_2variable__naming.html#autotoc_md769',1,'']]],
  ['სწორი_20გამოყენების_20წესები_81',['სწორი გამოყენების წესები',['../md_docs_2structure_2communication__patterns.html#autotoc_md1191',1,'']]],
  ['სწორი_20იმპლემენტაცია_82',['სწორი იმპლემენტაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md611',1,'']]],
  ['სწორი_20მიდგომა_83',['3. სწორი მიდგომა',['../md_docs_2convention_2variable__naming.html#autotoc_md752',1,'']]],
  ['სწრაფი_20სტარტი_84',['სწრაფი სტარტი',['../tutorials_docs.html#tut_getting_started_sec',1,'']]],
  ['სწრაფი_20სტარტი_20getting_20started_85',['სწრაფი სტარტი (Getting Started)',['../md_docs_2tutorials_2getting__started.html',1,'']]]
];
