var searchData=
[
  ['ram_0',['RAM',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1279',1,'']]],
  ['ram_20ის_20გამოყენება_1',['RAM-ის გამოყენება',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1273',1,'']]],
  ['readme_20md_2',['[README.md]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md529',1,'']]],
  ['reconfiguration_3',['reconfiguration',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1540',1,'3. Runtime Reconfiguration'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1396',1,'Runtime Reconfiguration']]],
  ['reconfiguration_20support_4',['Reconfiguration Support',['../md_docs_2convention_2configuration__management.html#autotoc_md758',1,'']]],
  ['reconfigure_5',['reconfigure',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1306',1,'2. სისტემის reconfigure'],['../structmodule__t.html#a68e5d4c7041e43135876d4f0b4e39ea7',1,'module_t::reconfigure']]],
  ['reconfigure_3a_6',['2. სისტემის reconfigure:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md907',1,'']]],
  ['record_20template_7',['არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)',['../md_docs_2design__decisions_2decision__record__template.html',1,'']]],
  ['recovery_20strategies_8',['Error Recovery Strategies',['../md_docs_2convention_2error__handling.html#autotoc_md796',1,'']]],
  ['redraw_9',['Conditional redraw',['../md_docs_2performance_2performance__display.html#autotoc_md1237',1,'']]],
  ['ref_5fcount_10',['ref_count',['../structevent__data__wrapper__t.html#a1d75bdc3d17e5c455be5bdc2ad22574b',1,'event_data_wrapper_t']]],
  ['refactor_11',['[Major] Module System Automation &amp; Refactor',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md535',1,'']]],
  ['reference_12',['reference',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md46',1,'API Reference'],['../md_docs_2api__reference_2actuators__api.html',1,'Synapse Actuators Module API Reference'],['../md_docs_2api__reference_2communication__api.html',1,'Synapse Communication Module API Reference'],['../md_docs_2api__reference_2configuration__api.html',1,'Synapse Configuration Manager API Reference'],['../md_docs_2api__reference_2core__api.html',1,'Synapse Core API Reference'],['../md_docs_2api__reference_2custom__api.html',1,'Synapse Custom API Reference'],['../md_docs_2api__reference_2display__api.html',1,'Synapse Display Module API Reference'],['../md_docs_2api__reference_2drivers__api.html',1,'Synapse Drivers Module API Reference'],['../md_docs_2api__reference_2event__api.html',1,'Synapse Event Bus API Reference'],['../md_docs_2api__reference_2health__monitor__api.html',1,'Synapse Health Monitor Module API Reference'],['../md_docs_2api__reference_2local__ctrl__api.html',1,'Synapse Local Control Module API Reference'],['../md_docs_2api__reference_2module__api.html',1,'Synapse Module API Reference'],['../md_docs_2api__reference_2ota__api.html',1,'Synapse OTA (Over-the-Air) Module API Reference'],['../md_docs_2api__reference_2provisioning__api.html',1,'Synapse Provisioning Module API Reference'],['../md_docs_2api__reference_2resource__manager__api.html',1,'Synapse Resource Manager API Reference'],['../md_docs_2api__reference_2sensor__api.html',1,'Synapse Sensor Module API Reference'],['../md_docs_2api__reference_2storage__api.html',1,'Synapse Storage Module API Reference'],['../md_docs_2api__reference_2system__api.html',1,'Synapse System Module API Reference'],['../md_docs_2api__reference_2time__sync__api.html',1,'Synapse Time Sync Module API Reference'],['../md_docs_2api__reference_2utility__api.html',1,'Synapse Utility Module API Reference'],['../md_docs_2api__reference_2version__api.html',1,'Synapse Version Module API Reference']]],
  ['reference_20counting_13',['ივენთის მონაცემების მართვა (Reference Counting)',['../md_docs_2api__reference_2event__api.html#autotoc_md239',1,'']]],
  ['reference_20index_14',['reference index',['../md_docs_2api__reference_2api__index.html',1,'Synapse API Reference Index'],['../md_docs_2contributing_2contributing__index.html',1,'Synapse Contributing Reference Index'],['../md_docs_2convention_2convention__index.html',1,'Synapse Convention Reference Index']]],
  ['refresh_20interval_20ის_20ოპტიმიზაცია_15',['Refresh interval-ის ოპტიმიზაცია',['../md_docs_2performance_2performance__display.html#autotoc_md1236',1,'']]],
  ['register_16',['register',['../md_docs_2structure_2core__components.html#autotoc_md1404',1,'3. Module Register'],['../md_docs_2design__decisions_2core__components.html#autotoc_md970',1,'3. Module Register']]],
  ['register_20api_17',['Module Register API',['../md_docs_2api__reference_2core__api.html#autotoc_md149',1,'']]],
  ['register_5fcustom_5fcheck_18',['register_custom_check',['../structhealth__api__t.html#a2c81e551b68935b03450b76d0d09870c',1,'health_api_t']]],
  ['register_5fheartbeat_19',['register_heartbeat',['../structwatchdog__api__t.html#ac16b85ae36dedce6596731ba9d56f28c',1,'watchdog_api_t']]],
  ['registration_20display_20module_20',['1. Service Registration (Display Module)',['../md_docs_2convention_2communication__patterns.html#autotoc_md729',1,'']]],
  ['registration_20logging_21',['2. Service Registration Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md832',1,'']]],
  ['registry_22',['Module Registry',['../md_docs_2convention_2variable__naming.html#autotoc_md871',1,'']]],
  ['relay_20configuration_23',['6. Relay Configuration',['../md_docs_2convention_2configuration__management.html#autotoc_md750',1,'']]],
  ['relay_20module_20api_24',['Relay Module API',['../md_docs_2api__reference_2actuators__api.html#autotoc_md63',1,'']]],
  ['relay_5fdata_25',['static esp_err_t parse_relay_config(const cJSON *config, relay_private_data_t *relay_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md75',1,'']]],
  ['relay_5fget_5fstatus_20module_5ft_20module_26',['static module_status_t relay_get_status(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md78',1,'']]],
  ['relay_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_27',['static void relay_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md72',1,'']]],
  ['relay_5fmodule_5fcreate_20const_20cjson_20config_28',['module_t &lt;em&gt;relay_module_create(const cJSON *config);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md64',1,'']]],
  ['relay_5fmodule_5fdisable_20module_5ft_20module_29',['esp_err_t relay_module_disable(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md66',1,'']]],
  ['relay_5fmodule_5fenable_20module_5ft_20module_30',['esp_err_t relay_module_enable(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md65',1,'']]],
  ['relay_5fmodule_5fget_5fstate_20module_5ft_20module_31',['bool relay_module_get_state(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md69',1,'']]],
  ['relay_5fmodule_5fset_5fstate_20module_5ft_20module_20bool_20state_32',['esp_err_t relay_module_set_state(module_t *module, bool state);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md68',1,'']]],
  ['relay_5fmodule_5ftoggle_20module_5ft_20module_33',['esp_err_t relay_module_toggle(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md67',1,'']]],
  ['relay_5fprivate_5fdata_5ft_20relay_5fdata_34',['static esp_err_t parse_relay_config(const cJSON *config, relay_private_data_t *relay_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md75',1,'']]],
  ['release_20checklist_35',['Release Checklist',['../md_docs_2security_2security__checklist.html#autotoc_md1335',1,'']]],
  ['release_5fcontrol_36',['release_control',['../structrgb__led__api__t.html#a51197765d41c0532713fa702fe463f88',1,'rgb_led_api_t']]],
  ['report_5fbuffer_20size_5ft_20buffer_5fsize_37',['esp_err_t diagnostics_module_get_report(char *report_buffer, size_t buffer_size);',['../md_docs_2api__reference_2system__api.html#autotoc_md456',1,'']]],
  ['reporting_38',['3. Core Dumps და Crash Reporting',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1482',1,'']]],
  ['request_39',['3. როგორ შევქმნა Pull Request?',['../md_docs_2contributing_2faq.html#autotoc_md625',1,'']]],
  ['request_20ის_20მიმოხილვა_40',['4. Pull Request-ის მიმოხილვა',['../md_docs_2contributing_2contributing__guide.html#autotoc_md601',1,'']]],
  ['request_20template_41',['Synapse Pull Request Template',['../md_docs_2contributing_2pull__request__template.html',1,'']]],
  ['resource_20allocation_20checking_42',['2. Resource Allocation Checking',['../md_docs_2convention_2error__handling.html#autotoc_md786',1,'']]],
  ['resource_20cleanup_20functions_43',['2. Resource Cleanup Functions',['../md_docs_2convention_2error__handling.html#autotoc_md792',1,'']]],
  ['resource_20management_44',['Cleanup and Resource Management',['../md_docs_2convention_2error__handling.html#autotoc_md790',1,'']]],
  ['resource_20manager_20api_20reference_45',['Synapse Resource Manager API Reference',['../md_docs_2api__reference_2resource__manager__api.html',1,'']]],
  ['resource_20usage_20guide_46',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['resource_5fid_20const_20char_20owner_20tt_47',['resource_id const char owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md384',1,'&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md386',1,'&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['resource_5fid_20tt_48',['resource_id tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md388',1,'&lt;tt&gt;bool fmw_resource_is_locked(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md390',1,'&lt;tt&gt;const char *fmw_resource_get_owner(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;']]],
  ['resource_5fmanager_20h_49',['[core/include/resource_manager.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md524',1,'']]],
  ['resource_5fmanager_2ec_50',['resource_manager.c',['../resource__manager_8c.html',1,'']]],
  ['resource_5fmanager_2eh_51',['resource_manager.h',['../resource__manager_8h.html',1,'']]],
  ['resource_5fpool_5ft_52',['resource_pool_t',['../structresource__pool__t.html',1,'']]],
  ['rest_20api_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20rest_20api_53',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['rest_20api_20integration_54',['4. REST API Integration',['../md_docs_2tutorials_2integration__example.html#autotoc_md1570',1,'']]],
  ['retry_20logic_55',['1. Retry Logic',['../md_docs_2convention_2error__handling.html#autotoc_md797',1,'']]],
  ['review_20checklist_56',['Code Review Checklist',['../md_docs_2security_2security__checklist.html#autotoc_md1336',1,'']]],
  ['review_20guidelines_57',['Synapse Review Guidelines',['../md_docs_2contributing_2review__guidelines.html',1,'']]],
  ['rgb_5fled_5fapi_5ft_58',['rgb_led_api_t',['../structrgb__led__api__t.html',1,'']]],
  ['rgb_5fled_5fapi_5ft_20tt_59',['4. Service API (&lt;tt&gt;rgb_led_api_t&lt;/tt&gt;)',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md56',1,'']]],
  ['rgb_5fled_5findicator_20tt_60',['მოდული &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['rgb_5fled_5findicator_2ec_61',['rgb_led_indicator.c',['../rgb__led__indicator_8c.html',1,'']]],
  ['rgb_5fled_5findicator_2eh_62',['rgb_led_indicator.h',['../rgb__led__indicator_8h.html',1,'']]],
  ['rgb_5fled_5findicator_5fcreate_63',['rgb_led_indicator_create',['../rgb__led__indicator_8c.html#af7ab099c2a16ab7a894d97a3a01f3d31',1,'rgb_led_indicator_create(const cJSON *config):&#160;rgb_led_indicator.c'],['../rgb__led__indicator_8h.html#af7ab099c2a16ab7a894d97a3a01f3d31',1,'rgb_led_indicator_create(const cJSON *config):&#160;rgb_led_indicator.c']]],
  ['rgb_5fled_5finterface_2eh_64',['rgb_led_interface.h',['../rgb__led__interface_8h.html',1,'']]],
  ['rgb_5fled_5fprivate_5fdata_5ft_65',['rgb_led_private_data_t',['../structrgb__led__private__data__t.html',1,'']]],
  ['rollback_66',['8. განახლების ვალიდაცია და Rollback',['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md16',1,'']]],
  ['runtime_20პრობლემები_67',['5. Runtime პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1507',1,'']]],
  ['runtime_20configuration_68',['Runtime Configuration',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md32',1,'']]],
  ['runtime_20configuration_20changes_69',['Runtime Configuration Changes',['../md_docs_2convention_2configuration__management.html#autotoc_md757',1,'']]],
  ['runtime_20control_70',['Runtime Control',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md35',1,'']]],
  ['runtime_20management_20ფუნქციები_71',['2. Runtime Management ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md815',1,'']]],
  ['runtime_20reconfiguration_72',['runtime reconfiguration',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1540',1,'3. Runtime Reconfiguration'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1396',1,'Runtime Reconfiguration']]],
  ['runtime_20state_20logging_73',['Runtime State Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md837',1,'']]],
  ['rx_5fdata_20size_5ft_20data_5flength_74',['esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md224',1,'']]]
];
