var searchData=
[
  ['ram_0',['RAM',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1749',1,'']]],
  ['ram_20ის_20გამოყენება_1',['RAM-ის გამოყენება',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1743',1,'']]],
  ['read_2',['read',['../structi2c__bus__api__t.html#a393ed034938fe2ff05bc86caf044605a',1,'i2c_bus_api_t']]],
  ['read_5fall_5fpins_3',['read_all_pins',['../structmcp23017__api__t.html#a6572ebe749b95f5c1bdd218ebbbdf412',1,'mcp23017_api_t']]],
  ['read_5ffile_4',['read_file',['../structstorage__api__t.html#af31e61ac9fa245b6a7bf4f541a3876ce',1,'storage_api_t']]],
  ['readme_20md_5',['[README.md]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md802',1,'']]],
  ['reboot_5fsystem_6',['reboot_system',['../structsystem__manager__api__t.html#a402ede4ddd5f00bdad179ec8e85d5e9e',1,'system_manager_api_t']]],
  ['reconfiguration_7',['reconfiguration',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md2005',1,'3. Runtime Reconfiguration'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1836',1,'Runtime Reconfiguration']]],
  ['record_20template_8',['არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)',['../md_docs_2design__decisions_2decision__record__template.html',1,'']]],
  ['recovery_20strategies_9',['Error Recovery Strategies',['../md_docs_2convention_2error__handling.html#autotoc_md1261',1,'']]],
  ['redraw_10',['Conditional redraw',['../md_docs_2performance_2performance__display.html#autotoc_md1707',1,'']]],
  ['ref_5fcount_11',['ref_count',['../structevent__data__wrapper__t.html#a1d75bdc3d17e5c455be5bdc2ad22574b',1,'event_data_wrapper_t']]],
  ['refactor_12',['[Major] Module System Automation &amp; Refactor',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md808',1,'']]],
  ['refactoring_13',['refactoring',['../md_docs_2changelog_2v7.html#autotoc_md986',1,'💥 არქიტექტურული ცვლილებები (Breaking Changes &amp; Refactoring)'],['../md_docs_2changelog_2v9.html#autotoc_md1031',1,'💥 არქიტექტურული ცვლილებები (Breaking Changes &amp; Refactoring)']]],
  ['refactoring_20improvements_14',['♻️ რეფაქტორინგი და გაუმჯობესებები (Refactoring &amp; Improvements)',['../md_docs_2changelog_2v5.html#autotoc_md924',1,'']]],
  ['reference_15',['reference',['../md_docs_2api__reference_2storage__api.html',1,'💾 Synapse Storage Manager API Reference'],['../md_docs_2api__reference_2communication__api.html',1,'📡 Synapse Communication Module API Reference'],['../md_docs_2api__reference_2provisioning__api.html',1,'📲 Synapse Provisioning Module API Reference'],['../md_docs_2api__reference_2relay__api.html',1,'🔌 Relay Actuator API Reference'],['../md_docs_2api__reference_2security__api.html',1,'🛡️ Security Status API Reference'],['../md_components_2modules_2utillities_2logger__module_2README.html#autotoc_md237',1,'API Reference'],['../md_docs_2api__reference_2actuators__api.html',1,'Synapse Actuators Module API Reference'],['../md_docs_2api__reference_2command__router__api.html',1,'Synapse Command Router API Reference'],['../md_docs_2api__reference_2configuration__api.html',1,'Synapse Configuration Manager API Reference'],['../md_docs_2api__reference_2core__api.html',1,'Synapse Core API Reference'],['../md_docs_2api__reference_2custom__api.html',1,'Synapse Custom API Reference'],['../md_docs_2api__reference_2device__identity__api.html',1,'Synapse Device Identity Service API Reference'],['../md_docs_2api__reference_2display__api.html',1,'Synapse Display Module API Reference'],['../md_docs_2api__reference_2drivers__api.html',1,'Synapse Drivers Module API Reference'],['../md_docs_2api__reference_2event__api.html',1,'Synapse Event Bus API Reference'],['../md_docs_2api__reference_2health__monitor__api.html',1,'Synapse Health Monitor Module API Reference'],['../md_docs_2api__reference_2local__ctrl__api.html',1,'Synapse Local Control Module API Reference'],['../md_docs_2api__reference_2module__api.html',1,'Synapse Module API Reference'],['../md_docs_2api__reference_2mqtt__api.html',1,'Synapse MQTT Manager Service API Reference'],['../md_docs_2api__reference_2ota__api.html',1,'Synapse OTA (Over-the-Air) Module API Reference'],['../md_docs_2api__reference_2promise__api.html',1,'Synapse Promise Manager API Reference'],['../md_docs_2api__reference_2resource__manager__api.html',1,'Synapse Resource Manager API Reference'],['../md_docs_2api__reference_2sensor__api.html',1,'Synapse Sensor Module API Reference'],['../md_docs_2api__reference_2system__api.html',1,'Synapse System Module API Reference'],['../md_docs_2api__reference_2task__pool__api.html',1,'Synapse Task Pool Manager API Reference'],['../md_docs_2api__reference_2time__sync__api.html',1,'Synapse Time Sync Module API Reference'],['../md_docs_2api__reference_2utility__api.html',1,'Synapse Utility Module API Reference'],['../md_docs_2api__reference_2utils__api.html',1,'Synapse Utils API Reference'],['../md_docs_2api__reference_2version__api.html',1,'Synapse Version Module API Reference'],['../md_docs_2api__reference_2wifi__api.html',1,'Synapse WiFi Manager Service API Reference']]],
  ['reference_20counting_16',['ივენთის მონაცემების მართვა (Reference Counting)',['../md_docs_2api__reference_2event__api.html#autotoc_md454',1,'']]],
  ['reference_20index_17',['reference index',['../md_docs_2api__reference_2api__index.html',1,'Synapse API Reference Index'],['../md_docs_2contributing_2contributing__index.html',1,'Synapse Contributing Reference Index'],['../md_docs_2convention_2convention__index.html',1,'Synapse Convention Reference Index']]],
  ['refresh_20interval_20ის_20ოპტიმიზაცია_18',['Refresh interval-ის ოპტიმიზაცია',['../md_docs_2performance_2performance__display.html#autotoc_md1706',1,'']]],
  ['register_19',['register',['../md_docs_2design__decisions_2core__components.html#autotoc_md1431',1,'3. Module Register'],['../md_docs_2structure_2core__components.html#autotoc_md1846',1,'3. Module Register']]],
  ['register_20api_20',['Module Register API',['../md_docs_2api__reference_2core__api.html#autotoc_md353',1,'']]],
  ['register_5fcommand_21',['register_command',['../structcmd__router__api__t.html#a577628a1e19c957eaac870d60b9ebdc7',1,'cmd_router_api_t']]],
  ['register_5fcommand_20const_20cmd_5ft_20command_20tt_22',['&lt;tt&gt;esp_err_t register_command(const cmd_t *command)&lt;/tt&gt;',['../md_docs_2api__reference_2command__router__api.html#autotoc_md300',1,'']]],
  ['register_5fcustom_5fcheck_23',['register_custom_check',['../structhealth__api__t.html#a2c81e551b68935b03450b76d0d09870c',1,'health_api_t']]],
  ['register_5fheartbeat_24',['register_heartbeat',['../structwatchdog__api__t.html#ac16b85ae36dedce6596731ba9d56f28c',1,'watchdog_api_t']]],
  ['registration_20logging_25',['2. Service Registration Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md1321',1,'']]],
  ['registration_20tt_20_5fcreate_20tt_20ფუნქციაში_26',['1. Service Registration (&lt;tt&gt;_create&lt;/tt&gt; ფუნქციაში)',['../md_docs_2convention_2communication__patterns.html#autotoc_md1214',1,'']]],
  ['registry_27',['Module Registry',['../md_docs_2convention_2variable__naming.html#autotoc_md1374',1,'']]],
  ['relay_20actuator_20api_20reference_28',['🔌 Relay Actuator API Reference',['../md_docs_2api__reference_2relay__api.html',1,'']]],
  ['relay_20module_20api_29',['Relay Module API',['../md_docs_2api__reference_2actuators__api.html#autotoc_md267',1,'']]],
  ['relay_5factuator_20tt_30',['🔌 მოდული: &lt;tt&gt;relay_actuator&lt;/tt&gt;',['../md_components_2modules_2actuators_2relay__actuator_2README.html',1,'']]],
  ['relay_5factuator_2ec_31',['relay_actuator.c',['../relay__actuator_8c.html',1,'']]],
  ['relay_5factuator_5fcreate_32',['relay_actuator_create',['../relay__actuator_8c.html#a57a9879a72789576f6d8d87dd4641088',1,'relay_actuator.c']]],
  ['relay_5fapi_5ft_33',['relay_api_t',['../structrelay__api__t.html',1,'']]],
  ['relay_5fapi_5ft_20tt_34',['4. 🔌 Service API (&lt;tt&gt;relay_api_t&lt;/tt&gt;)',['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md4',1,'']]],
  ['relay_5fdata_35',['static esp_err_t parse_relay_config(const cJSON *config, relay_private_data_t *relay_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md279',1,'']]],
  ['relay_5fget_5fstatus_20module_5ft_20module_36',['static module_status_t relay_get_status(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md282',1,'']]],
  ['relay_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_37',['static void relay_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md276',1,'']]],
  ['relay_5finterface_2eh_38',['relay_interface.h',['../relay__interface_8h.html',1,'']]],
  ['relay_5fmodule_5fcreate_20const_20cjson_20config_39',['module_t &lt;em&gt;relay_module_create(const cJSON *config);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md268',1,'']]],
  ['relay_5fmodule_5fdisable_20module_5ft_20module_40',['esp_err_t relay_module_disable(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md270',1,'']]],
  ['relay_5fmodule_5fenable_20module_5ft_20module_41',['esp_err_t relay_module_enable(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md269',1,'']]],
  ['relay_5fmodule_5fget_5fstate_20module_5ft_20module_42',['bool relay_module_get_state(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md273',1,'']]],
  ['relay_5fmodule_5fset_5fstate_20module_5ft_20module_20bool_20state_43',['esp_err_t relay_module_set_state(module_t *module, bool state);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md272',1,'']]],
  ['relay_5fmodule_5ftoggle_20module_5ft_20module_44',['esp_err_t relay_module_toggle(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md271',1,'']]],
  ['relay_5fprivate_5fdata_5ft_45',['relay_private_data_t',['../structrelay__private__data__t.html',1,'']]],
  ['relay_5fprivate_5fdata_5ft_20relay_5fdata_46',['static esp_err_t parse_relay_config(const cJSON *config, relay_private_data_t *relay_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md279',1,'']]],
  ['release_20checklist_47',['Release Checklist',['../md_docs_2security_2security__checklist.html#autotoc_md1775',1,'']]],
  ['release_5fcontrol_48',['release_control',['../structrgb__led__api__t.html#a51197765d41c0532713fa702fe463f88',1,'rgb_led_api_t']]],
  ['remove_5fdevice_49',['remove_device',['../structspi__bus__api__t.html#a3543e72a0988c094dbfd3d4c1dbe13fa',1,'spi_bus_api_t']]],
  ['render_5fcurrent_5fstate_50',['render_current_state',['../ui__manager_8h.html#a093af2fea1ff15543b2b9d7609a87e71',1,'render_current_state(ui_manager_private_data_t *private_data):&#160;ui_manager.c'],['../ui__manager_8c.html#a093af2fea1ff15543b2b9d7609a87e71',1,'render_current_state(ui_manager_private_data_t *private_data):&#160;ui_manager.c']]],
  ['render_5ffooter_5fbutton_51',['render_footer_button',['../ui__screens_8h.html#a96f4ec2d25f38fd55d514150af179086',1,'render_footer_button(ui_manager_private_data_t *private_data, const char *text, bool is_selected):&#160;ui_screens.c'],['../ui__screens_8c.html#a96f4ec2d25f38fd55d514150af179086',1,'render_footer_button(ui_manager_private_data_t *private_data, const char *text, bool is_selected):&#160;ui_screens.c']]],
  ['render_5fheader_52',['render_header',['../ui__screens_8c.html#a376f0da5f8fa958e09b7a5adfc084950',1,'render_header(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8h.html#a376f0da5f8fa958e09b7a5adfc084950',1,'render_header(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['render_5fhome_5fscreen_53',['render_home_screen',['../ui__screens_8h.html#aa073835a483ffe68580ffdec8bc36910',1,'render_home_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8c.html#aa073835a483ffe68580ffdec8bc36910',1,'render_home_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['render_5fmodule_5fcontrol_5fscreen_54',['render_module_control_screen',['../ui__screens_8h.html#a3660eb426382f4100fc635af4cbbbeff',1,'render_module_control_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8c.html#a3660eb426382f4100fc635af4cbbbeff',1,'render_module_control_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['render_5fsplash_5fscreen_55',['render_splash_screen',['../ui__screens_8c.html#a1d1f8173dcde1f8ca44070f3353a3457',1,'render_splash_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8h.html#a1d1f8173dcde1f8ca44070f3353a3457',1,'render_splash_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['report_56',['report',['../structself__test__private__data__t.html#a0d37551189770210afd3a97f7d9cc3aa',1,'self_test_private_data_t']]],
  ['report_5fbuffer_20size_5ft_20buffer_5fsize_57',['esp_err_t diagnostics_module_get_report(char *report_buffer, size_t buffer_size);',['../md_docs_2api__reference_2system__api.html#autotoc_md697',1,'']]],
  ['report_5fline_5fcount_58',['report_line_count',['../structself__test__private__data__t.html#aaef7d81c87d0caded1f92ac1e1bd26b9',1,'self_test_private_data_t']]],
  ['report_5fmutex_59',['report_mutex',['../structself__test__private__data__t.html#ab931d22b5587b17128e0f9f510e73a44',1,'self_test_private_data_t']]],
  ['reporting_60',['3. Core Dumps და Crash Reporting',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1935',1,'']]],
  ['request_61',['3. როგორ შევქმნა Pull Request?',['../md_docs_2contributing_2faq.html#autotoc_md1108',1,'']]],
  ['request_20ის_20მიმოხილვა_62',['4. Pull Request-ის მიმოხილვა',['../md_docs_2contributing_2contributing__guide.html#autotoc_md1084',1,'']]],
  ['request_20template_63',['Synapse Pull Request Template',['../md_docs_2contributing_2pull__request__template.html',1,'']]],
  ['reserved_64',['reserved',['../structalarms__manager__api__t.html#a50209ba0e325a0b6f9012b41389ee14e',1,'alarms_manager_api_t']]],
  ['reset_5fscreen_5foff_5ftimer_65',['reset_screen_off_timer',['../ui__manager_8c.html#af34942bb9de4ca5702cca0195deb934a',1,'reset_screen_off_timer(ui_manager_private_data_t *private_data):&#160;ui_manager.c'],['../ui__manager_8h.html#af34942bb9de4ca5702cca0195deb934a',1,'reset_screen_off_timer(ui_manager_private_data_t *private_data):&#160;ui_manager.c']]],
  ['resource_20allocation_20checking_66',['2. Resource Allocation Checking',['../md_docs_2convention_2error__handling.html#autotoc_md1251',1,'']]],
  ['resource_20cleanup_20functions_67',['2. Resource Cleanup Functions',['../md_docs_2convention_2error__handling.html#autotoc_md1257',1,'']]],
  ['resource_20management_68',['Cleanup and Resource Management',['../md_docs_2convention_2error__handling.html#autotoc_md1255',1,'']]],
  ['resource_20manager_20api_20reference_69',['Synapse Resource Manager API Reference',['../md_docs_2api__reference_2resource__manager__api.html',1,'']]],
  ['resource_20usage_20guide_70',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['resource_5fid_20const_20char_20owner_20tt_71',['resource_id const char owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md624',1,'&lt;tt&gt;esp_err_t synapse_resource_lock(synapse_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md626',1,'&lt;tt&gt;esp_err_t synapse_resource_release(synapse_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['resource_5fid_20tt_72',['resource_id tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md628',1,'&lt;tt&gt;bool synapse_resource_is_locked(synapse_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md630',1,'&lt;tt&gt;const char *synapse_resource_get_owner(synapse_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;']]],
  ['resource_5fmanager_20h_73',['[core/include/resource_manager.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md797',1,'']]],
  ['resource_5fmanager_2ec_74',['resource_manager.c',['../resource__manager_8c.html',1,'']]],
  ['resource_5fmanager_2eh_75',['resource_manager.h',['../resource__manager_8h.html',1,'']]],
  ['resource_5fpool_5ft_76',['resource_pool_t',['../structresource__pool__t.html',1,'']]],
  ['rest_20api_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20rest_20api_77',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['rest_20api_20integration_78',['4. REST API Integration',['../md_docs_2tutorials_2integration__example.html#autotoc_md2038',1,'']]],
  ['result_79',['result',['../structtest__report__line__t.html#a3ae7d1e5697b1014dd54c30b0d655fd6',1,'test_report_line_t']]],
  ['result_5fdata_20void_20free_5ffn_20void_20tt_80',['&lt;tt&gt;esp_err_t synapse_promise_resolve(promise_handle_t handle, void* result_data, void (*free_fn)(void*));&lt;/tt&gt;',['../md_docs_2api__reference_2promise__api.html#autotoc_md562',1,'']]],
  ['retry_20logic_81',['1. Retry Logic',['../md_docs_2convention_2error__handling.html#autotoc_md1262',1,'']]],
  ['review_20checklist_82',['Code Review Checklist',['../md_docs_2security_2security__checklist.html#autotoc_md1776',1,'']]],
  ['review_20guidelines_83',['Synapse Review Guidelines',['../md_docs_2contributing_2review__guidelines.html',1,'']]],
  ['rgb_5fled_5fapi_5ft_84',['rgb_led_api_t',['../structrgb__led__api__t.html',1,'']]],
  ['rgb_5fled_5fapi_5ft_20tt_85',['4. 🛠️ Service API (&lt;tt&gt;rgb_led_api_t&lt;/tt&gt;)',['../md_components_2modules_2utillities_2rgb__led__indicator_2README.html#autotoc_md247',1,'']]],
  ['rgb_5fled_5findicator_20tt_86',['💡 მოდული: &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utillities_2rgb__led__indicator_2README.html',1,'']]],
  ['rgb_5fled_5findicator_2ec_87',['rgb_led_indicator.c',['../rgb__led__indicator_8c.html',1,'']]],
  ['rgb_5fled_5findicator_2eh_88',['rgb_led_indicator.h',['../rgb__led__indicator_8h.html',1,'']]],
  ['rgb_5fled_5findicator_5fcreate_89',['rgb_led_indicator_create',['../rgb__led__indicator_8h.html#af7ab099c2a16ab7a894d97a3a01f3d31',1,'rgb_led_indicator_create(const cJSON *config):&#160;rgb_led_indicator.c'],['../rgb__led__indicator_8c.html#af7ab099c2a16ab7a894d97a3a01f3d31',1,'rgb_led_indicator_create(const cJSON *config):&#160;rgb_led_indicator.c']]],
  ['rgb_5fled_5finterface_2eh_90',['rgb_led_interface.h',['../rgb__led__interface_8h.html',1,'']]],
  ['rgb_5fled_5fprivate_5fdata_5ft_91',['rgb_led_private_data_t',['../structrgb__led__private__data__t.html',1,'']]],
  ['roboto_5fbold_5f24_2eh_92',['roboto_bold_24.h',['../roboto__bold__24_8h.html',1,'']]],
  ['roboto_5fbold_5f24_5fdigits_2eh_93',['roboto_bold_24_digits.h',['../roboto__bold__24__digits_8h.html',1,'']]],
  ['rollback_94',['8. განახლების ვალიდაცია და Rollback',['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md181',1,'']]],
  ['rotary_5fencoder_5finput_20tt_95',['🔘 მოდული: &lt;tt&gt;rotary_encoder_input&lt;/tt&gt;',['../md_components_2modules_2drivers_2rotary__encoder__input_2README.html',1,'']]],
  ['rotary_5fencoder_5finput_2ec_96',['rotary_encoder_input.c',['../rotary__encoder__input_8c.html',1,'']]],
  ['rotary_5fencoder_5finput_2eh_97',['rotary_encoder_input.h',['../rotary__encoder__input_8h.html',1,'']]],
  ['rotary_5fencoder_5finput_5fcreate_98',['rotary_encoder_input_create',['../rotary__encoder__input_8h.html#ab6525e0e429a20c6dfe66658870203f6',1,'rotary_encoder_input_create(const cJSON *config):&#160;rotary_encoder_input.c'],['../rotary__encoder__input_8c.html#ab6525e0e429a20c6dfe66658870203f6',1,'rotary_encoder_input_create(const cJSON *config):&#160;rotary_encoder_input.c']]],
  ['rotary_5fprivate_5fdata_5ft_99',['rotary_private_data_t',['../structrotary__private__data__t.html',1,'']]],
  ['router_20api_20reference_100',['Synapse Command Router API Reference',['../md_docs_2api__reference_2command__router__api.html',1,'']]],
  ['router_20pattern_101',['3. Command Router Pattern',['../md_docs_2convention_2communication__patterns.html#autotoc_md1203',1,'']]],
  ['router_20system_20shell_102',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utillities_2command__router_2README.html',1,'']]],
  ['runtime_20პრობლემები_103',['5. Runtime პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1960',1,'']]],
  ['runtime_20configuration_104',['Runtime Configuration',['../md_components_2modules_2utillities_2logger__module_2README.html#autotoc_md223',1,'']]],
  ['runtime_20control_105',['Runtime Control',['../md_components_2modules_2utillities_2logger__module_2README.html#autotoc_md226',1,'']]],
  ['runtime_20management_20ფუნქციები_106',['2. Runtime Management ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md1280',1,'']]],
  ['runtime_20reconfiguration_107',['runtime reconfiguration',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md2005',1,'3. Runtime Reconfiguration'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1836',1,'Runtime Reconfiguration']]],
  ['runtime_20state_20logging_108',['Runtime State Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md1326',1,'']]],
  ['rx_5fdata_20size_5ft_20data_5flength_109',['esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md439',1,'']]]
];
