var searchData=
[
  ['⚙️_20კონფიგურაცია_0',['⚙️ კონფიგურაცია',['../md_components_2modules_2system_2time__sync_2README.html#autotoc_md149',1,'2. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2ui__manager_2README.html#autotoc_md226',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md209',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2testing_2timer__test__module_2README.html#autotoc_md168',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2testing_2sensor__simulator_2README.html#autotoc_md162',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md154',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md121',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2system__timer_2README.html#autotoc_md219',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md97',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md88',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2security_2security__status__reporter_2README.html#autotoc_md70',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md60',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2displays_2ssd1306__driver_2README.html#autotoc_md41',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md33',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md22',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2communications_2mqtt__manager_2README.html#autotoc_md12',1,'3. ⚙️ კონფიგურაცია']]],
  ['⚙️_20კონფიგურაცია_20tt_20config_20json_20tt_1',['⚙️ კონფიგურაცია tt config json tt',['../md_components_2modules_2drivers_2i2c__bus_2README.html#autotoc_md53',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2button__input_2README.html#autotoc_md47',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md3',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)']]],
  ['⚙️_20კონფიგურაცია_20tt_20system_5fconfig_20json_20tt_2',['⚙️ კონფიგურაცია tt system_config json tt',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md107',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;system_config.json&lt;/tt&gt;)'],['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md78',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;system_config.json&lt;/tt&gt;)']]],
  ['⚙️_20მოდული_3a_20command_20router_20system_20shell_3',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utilities_2command__router_2README.html',1,'']]],
  ['⚙️_20როგორ_20მუშაობს_4',['⚙️ როგორ მუშაობს?',['../md_docs_2convention_2initialization__levels.html#autotoc_md1006',1,'']]],
  ['⚙️_20ძირითადი_20api_20ფუნქციები_5',['⚙️ ძირითადი API ფუნქციები',['../md_docs_2api__reference_2configuration__api.html#autotoc_md296',1,'']]],
  ['⚙️_20api_20სტრუქტურა_20tt_20cmd_5frouter_5fapi_5ft_20tt_6',['⚙️ API სტრუქტურა (&lt;tt&gt;cmd_router_api_t&lt;/tt&gt;)',['../md_docs_2api__reference_2command__router__api.html#autotoc_md263',1,'']]],
  ['⚙️_20api_20ს_20სტრუქტურა_20tt_20storage_5fapi_5ft_20tt_7',['⚙️ API-ს სტრუქტურა (&lt;tt&gt;storage_api_t&lt;/tt&gt;)',['../md_docs_2api__reference_2storage__api.html#autotoc_md622',1,'']]]
];
