var searchData=
[
  ['✨_20არქიტექტურული_20გაუმჯობესებები_20და_20dx_20architectural_20developer_20experience_20improvements_0',['✨ არქიტექტურული გაუმჯობესებები და DX (Architectural &amp; Developer Experience Improvements)',['../md_docs_2changelog_2v9.html#autotoc_md1002',1,'']]],
  ['✨_20არქიტექტურული_20გაუმჯობესებები_20architectural_20improvements_1',['✨ არქიტექტურული გაუმჯობესებები architectural improvements',['../md_docs_2changelog_2v9.html#autotoc_md1027',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md1018',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md1015',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v8.html#autotoc_md997',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v8.html#autotoc_md991',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v7.html#autotoc_md975',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)']]],
  ['✨_20ახალი_20ფუნქციები_20features_2',['✨ ახალი ფუნქციები features',['../md_docs_2changelog_2v5.html#autotoc_md889',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md912',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md893',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md898',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md903',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md908',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md917',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md920',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md923',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md928',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md932',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md884',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md880',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md871',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md876',1,'✨ ახალი ფუნქციები (Features)']]],
  ['✨_20ახალი_20ფუნქციონალი_3',['✨ ახალი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md942',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md956',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md953',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md949',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md946',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md940',1,'✨ ახალი ფუნქციონალი']]],
  ['✨_20გაუმჯობესებები_20improvements_4',['✨ გაუმჯობესებები improvements',['../md_docs_2changelog_2v5.html#autotoc_md872',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md1023',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md1007',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md877',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md885',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md904',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md899',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md881',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md894',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md914',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v7.html#autotoc_md981',1,'✨ გაუმჯობესებები (Improvements)']]],
  ['✨_20დამატებულია_5',['✨ დამატებულია',['../md_docs_2changelog_2v5.html#autotoc_md936',1,'']]],
  ['✨_20დამატებულია_20added_6',['✨ დამატებულია (Added)',['../md_docs_2changelog_2v5.html#autotoc_md867',1,'']]],
  ['✨_20დამატებული_7',['✨ დამატებული',['../md_docs_2changelog_2v6.html#autotoc_md961',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md970',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md965',1,'✨ დამატებული']]],
  ['✨_20დამატებული_20ფუნქციონალი_20added_8',['✨ დამატებული ფუნქციონალი added',['../md_docs_2changelog_2v5.html#autotoc_md839',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md834',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md822',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md828',1,'✨ დამატებული ფუნქციონალი (Added)']]],
  ['✨_20added_20დამატებული_20ფუნქციონალი_9',['✨ added დამატებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md858',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md853',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md848',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md843',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md863',1,'✨ Added (დამატებული ფუნქციონალი)']]]
];
