var searchData=
[
  ['of_20conduct_0',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['offs_1',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['on_20errors_2',['1. Proper Cleanup on Errors',['../md_docs_2convention_2error__handling.html#autotoc_md758',1,'']]],
  ['operation_20error_20handling_3',['5. Hardware Operation Error Handling',['../md_docs_2convention_2error__handling.html#autotoc_md756',1,'']]],
  ['operation_20logging_4',['4. Hardware Operation Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md801',1,'']]],
  ['operation_20timing_5',['1. Operation Timing',['../md_docs_2convention_2logging__standards.html#autotoc_md808',1,'']]],
  ['optimization_20guide_6',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['options_7',['Main Configuration Options',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md5',1,'']]],
  ['ota_8',['Flash-ში მონაცემების შენახვა (OTA)',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1080',1,'']]],
  ['ota_20განახლების_20სიგნირება_9',['ota განახლების სიგნირება',['../md_docs_2security_2security__best__practices.html#autotoc_md1304',1,'OTA განახლების სიგნირება'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1058',1,'OTA განახლების სიგნირება']]],
  ['ota_20და_20firmware_20security_10',['OTA და Firmware Security',['../md_docs_2security_2security__guidelines.html#autotoc_md1330',1,'']]],
  ['ota_20module_20api_11',['ota module api',['../md_docs_2api__reference_2system__api.html#autotoc_md406',1,'OTA Module API'],['../md_docs_2api__reference_2ota__api.html#autotoc_md286',1,'OTA Module API']]],
  ['ota_20over_20the_20air_20module_20api_20reference_12',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['ota_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_13',['static void ota_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2ota__api.html#autotoc_md293',1,'']]],
  ['ota_5fmodule_5fabort_20void_14',['esp_err_t ota_module_abort(void);',['../md_docs_2api__reference_2ota__api.html#autotoc_md290',1,'']]],
  ['ota_5fmodule_5fcreate_20const_20cjson_20config_15',['ota_module_create const cjson config',['../md_docs_2api__reference_2ota__api.html#autotoc_md287',1,'module_t *ota_module_create(const cJSON *config);'],['../md_docs_2api__reference_2system__api.html#autotoc_md407',1,'module_t *ota_module_create(const cJSON *config);']]],
  ['ota_5fmodule_5fget_5fstatus_20ota_5fstatus_5ft_20status_16',['ota_module_get_status ota_status_t status',['../md_docs_2api__reference_2ota__api.html#autotoc_md289',1,'esp_err_t ota_module_get_status(ota_status_t *status);'],['../md_docs_2api__reference_2system__api.html#autotoc_md409',1,'esp_err_t ota_module_get_status(ota_status_t *status);']]],
  ['ota_5fmodule_5fstart_5fupdate_20const_20char_20url_17',['ota_module_start_update const char url',['../md_docs_2api__reference_2ota__api.html#autotoc_md288',1,'esp_err_t ota_module_start_update(const char *url);'],['../md_docs_2api__reference_2system__api.html#autotoc_md408',1,'esp_err_t ota_module_start_update(const char *url);']]],
  ['ota_5fstatus_5ft_20status_18',['ota_status_t status',['../md_docs_2api__reference_2ota__api.html#autotoc_md289',1,'esp_err_t ota_module_get_status(ota_status_t *status);'],['../md_docs_2api__reference_2system__api.html#autotoc_md409',1,'esp_err_t ota_module_get_status(ota_status_t *status);']]],
  ['out_5fvalue_19',['out_value',['../md_docs_2api__reference_2configuration__api.html#autotoc_md97',1,'esp_err_t fmw_config_get_bool(const char *key, bool*out_value)'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md96',1,'esp_err_t fmw_config_get_int(const char *key, int*out_value)']]],
  ['output_20format_20',['Output Format',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md19',1,'']]],
  ['over_20the_20air_20module_20api_20reference_21',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['overflow_20და_20task_20watchdog_22',['1. Stack Overflow და Task Watchdog',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1460',1,'']]],
  ['overview_23',['overview',['../index.html',1,'პროექტის მიმოხილვა (Project Overview)'],['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md1',1,'Overview']]],
  ['owner_20tt_24',['owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md351',1,'&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md353',1,'&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['owner_5fnames_25',['owner_names',['../structresource__pool__t.html#aab904375ff53b6c6d69a4fb8678ba6e6',1,'resource_pool_t']]]
];
