var searchData=
[
  ['წაკითხვა_0',['წაკითხვა',['../md_docs_2api__reference_2configuration__api.html#autotoc_md109',1,'გლობალური პარამეტრის წაკითხვა'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md110',1,'მოდულის პარამეტრის წაკითხვა'],['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1087',1,'NVS-დან სტრიქონის წაკითხვა']]],
  ['წარმადობისა_20და_20რესურსების_20არქიტექტურული_20კომპრომისები_20performance_20trade_20offs_1',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['წარმადობისთვის_20performance_20best_20practices_2',['საუკეთესო პრაქტიკები წარმადობისთვის (Performance Best Practices)',['../md_docs_2performance_2performance__best__practices.html',1,'']]],
  ['წარმადობის_20სახელმძღვანელო_3',['Performance (წარმადობის სახელმძღვანელო)',['../md_docs_2performance_2performance__index.html',1,'']]],
  ['წარმადობის_20ტერმინები_20glossary_20—_20security_20performance_4',['უსაფრთხოების და წარმადობის ტერმინები (Glossary — Security &amp; Performance)',['../md_docs_2glossary_2glossary__security.html',1,'']]],
  ['წაშლილია_5',['წაშლილია',['../md_docs_2changelog_2CHANGELOG__2025-06-28.html#autotoc_md522',1,'']]],
  ['წერის_20წესები_6',['წერის წესები',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md562',1,'დეტალური აღწერის წერის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md560',1,'სათაურის წერის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md564',1,'Footer-ის წერის წესები']]],
  ['წესები_7',['წესები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md532',1,'ბრენჩის სახელდების წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md562',1,'დეტალური აღწერის წერის წესები'],['../md_docs_2convention_2communication__patterns.html',1,'კომუნიკაციის პატერნების წესები'],['../md_docs_2convention_2configuration__management.html',1,'კონფიგურაციის მართვის წესები'],['../md_docs_2convention_2module__structure.html',1,'მოდულის სტრუქტურის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md560',1,'სათაურის წერის წესები'],['../md_docs_2structure_2communication__patterns.html#autotoc_md1358',1,'სწორი გამოყენების წესები'],['../md_docs_2convention_2function__naming.html',1,'ფუნქციების დასახელების წესები'],['../md_docs_2convention_2variable__naming.html',1,'ცვლადების დასახელების წესები'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md689',1,'5. Doxygen ტეგების გამოყენების წესები'],['../contributing_docs.html#contrib_commit_sec',1,'Commit Message-ის წესები'],['../md_docs_2convention_2error__handling.html',1,'Error Handling-ის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md564',1,'Footer-ის წერის წესები']]],
  ['წესი_8',['წესი',['../md_docs_2glossary_2glossary__index.html#autotoc_md1115',1,'გამოყენების წესი'],['../md_docs_2integration_2integration__index.html#autotoc_md1138',1,'გამოყენების წესი'],['../md_docs_2performance_2performance__index.html#autotoc_md1224',1,'გამოყენების წესი'],['../md_docs_2security_2security__index.html#autotoc_md1338',1,'გამოყენების წესი']]],
  ['წვდომა_20კოდიდან_20dot_20notation_9',['4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1571',1,'']]],
  ['წვდომის_20მაგალითები_10',['კონფიგურაციის წვდომის მაგალითები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1369',1,'']]],
  ['წყაროები_11',['კონფიგურაციის წყაროები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1366',1,'']]]
];
