var searchData=
[
  ['✨_20ახალი_20ფუნქციები_20features_0',['✨ ახალი ფუნქციები features',['../md_docs_2changelog_2v5.html#autotoc_md832',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md859',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md854',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md864',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md849',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md845',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md868',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md840',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md836',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md873',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md876',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md827',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md879',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md884',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md888',1,'✨ ახალი ფუნქციები (Features)']]],
  ['✨_20ახალი_20ფუნქციონალი_1',['✨ ახალი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md896',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md898',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md902',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md905',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md909',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md912',1,'✨ ახალი ფუნქციონალი']]],
  ['✨_20გაუმჯობესებები_20improvements_2',['✨ გაუმჯობესებები improvements',['../md_docs_2changelog_2v5.html#autotoc_md850',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md870',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md860',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md855',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md841',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md837',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md833',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md828',1,'✨ გაუმჯობესებები (Improvements)']]],
  ['✨_20დამატებულია_3',['✨ დამატებულია',['../md_docs_2changelog_2v5.html#autotoc_md892',1,'']]],
  ['✨_20დამატებულია_20added_4',['✨ დამატებულია (Added)',['../md_docs_2changelog_2v5.html#autotoc_md823',1,'']]],
  ['✨_20დამატებული_20ფუნქციონალი_20added_5',['✨ დამატებული ფუნქციონალი added',['../md_docs_2changelog_2v5.html#autotoc_md778',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md795',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md790',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md784',1,'✨ დამატებული ფუნქციონალი (Added)']]],
  ['✨_20added_20დამატებული_20ფუნქციონალი_6',['✨ added დამატებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md819',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md814',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md809',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md804',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md799',1,'✨ Added (დამატებული ფუნქციონალი)']]]
];
