var searchData=
[
  ['იბილდება_0',['პრობლემა: მოდული არ იბილდება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1541',1,'']]],
  ['იბილდება_20ჩემი_20მოდული_1',['1. რატომ არ იბილდება ჩემი მოდული?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1575',1,'']]],
  ['იდენტიფიკატორი_2',['Custom Event-ის იდენტიფიკატორი',['../md_docs_2api__reference_2custom__api.html#autotoc_md205',1,'']]],
  ['ივენთების_20დამუშავება_3',['6. ივენთების დამუშავება',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md75',1,'']]],
  ['ივენთების_20დამუშავება_3a_4',['3. ივენთების დამუშავება:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md963',1,'']]],
  ['ივენთები_5',['ივენთები',['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md5',1,'გამოქვეყნებული ივენთები'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md6',1,'გამოწერილი ივენთები'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md32',1,'6. გამოქვეყნებული ივენთები'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md23',1,'6. გამოქვეყნებული ივენთები'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md15',1,'6. გამოქვეყნებული ივენთები']]],
  ['ივენთები_20events_6',['4. 📢 ივენთები (Events)',['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md4',1,'']]],
  ['ივენთის_20მონაცემების_20მართვა_20reference_20counting_7',['ივენთის მონაცემების მართვა (Reference Counting)',['../md_docs_2api__reference_2event__api.html#autotoc_md270',1,'']]],
  ['იზოლაცია_8',['ძირითადი პრინციპი: მაქსიმალური იზოლაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md747',1,'']]],
  ['იზოლაცია_20ყველაზე_20მნიშვნელოვანი_20შემოწმება_20_3a_20strong_9',['✅ &lt;strong&gt;მოდულების იზოლაცია (ყველაზე მნიშვნელოვანი შემოწმება):&lt;/strong&gt;',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md647',1,'']]],
  ['ით_20api_20არ_20იძებნება_10',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1550',1,'']]],
  ['იკითხება_11',['პრობლემა: შეცდომის კოდი არ იკითხება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1554',1,'']]],
  ['იმავე_20ტიპის_20რამდენიმე_20მოდულის_20დამატება_12',['2. შეიძლება თუ არა ერთი და იმავე ტიპის რამდენიმე მოდულის დამატება?',['../md_docs_2structure_2faq.html#autotoc_md1485',1,'']]],
  ['იმპლემენტაცია_13',['სწორი იმპლემენტაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md758',1,'']]],
  ['იმპლემენტაციის_20დეტალები_14',['7. ტექნიკური იმპლემენტაციის დეტალები',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md76',1,'']]],
  ['ინდექსი_15',['ინდექსი',['../md_docs_2integration_2integration__index.html',1,'Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)'],['../md_docs_2security_2security__index.html',1,'Security Index (უსაფრთხოების სახელმძღვანელოების ინდექსი)']]],
  ['ინიციალიზაცია_20lifecycle_20initialization_16',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['ინიციალიზაციის_20დონეების_20რეკომენდებული_20დიაპაზონები_17',['📊 ინიციალიზაციის დონეების რეკომენდებული დიაპაზონები',['../md_docs_2convention_2initialization__levels.html#autotoc_md856',1,'']]],
  ['ინიციალიზაციის_20დონეები_20initialization_20levels_18',['🚀 მოდულების ინიციალიზაციის დონეები (Initialization Levels)',['../md_docs_2convention_2initialization__levels.html',1,'']]],
  ['ინიციალიზაციის_20პრობლემის_20დიაგნოსტიკა_20და_20გამოსწორება_19',['CHANGELOG: led_blinker ინიციალიზაციის პრობლემის დიაგნოსტიკა და გამოსწორება',['../md_docs_2changelog_22025-06-26-led__blinker-nvs-debug.html',1,'']]],
  ['ინიციალიზდება_20',['პრობლემა: მოდული არ ინიციალიზდება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1545',1,'']]],
  ['ინიციალიზდება_20მოდული_21',['5. რატომ არ ინიციალიზდება მოდული?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1579',1,'']]],
  ['ინსტალაცია_22',['ESP-IDF-ის ინსტალაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md691',1,'']]],
  ['ინსტრუმენტები_23',['8. დამატებითი ინსტრუმენტები',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1572',1,'']]],
  ['ინტეგრაცია_24',['✅ ავტომატური ინტეგრაცია',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1339',1,'']]],
  ['ინტეგრაცია_20github_20actions_20თან_20ავტომატური_20შემოწმება_25',['4. ინტეგრაცია GitHub Actions-თან (ავტომატური შემოწმება)',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md650',1,'']]],
  ['ინტეგრაცია_3a_26',['✅ ავტომატური ინტეგრაცია:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md940',1,'']]],
  ['ინტეგრაციის_20მაგალითი_27',['ინტეგრაციის მაგალითი',['../tutorials_docs.html#tut_integration_sec',1,'']]],
  ['ინტეგრაციის_20მაგალითი_20integration_20example_28',['ინტეგრაციის მაგალითი (Integration Example)',['../md_docs_2tutorials_2integration__example.html',1,'']]],
  ['ინტეგრაციის_20საჭიროების_20განსაზღვრა_29',['1. ინტეგრაციის საჭიროების განსაზღვრა',['../md_docs_2tutorials_2integration__example.html#autotoc_md1616',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელოების_20ინდექსი_30',['Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)',['../md_docs_2integration_2integration__index.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელოები_31',['თემატური ინტეგრაციის სახელმძღვანელოები',['../md_docs_2integration_2integration__index.html#autotoc_md1210',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20cloud_32',['Cloud ინტეგრაციის სახელმძღვანელო (Integration — Cloud)',['../md_docs_2integration_2integration__cloud.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20mqtt_33',['MQTT ინტეგრაციის სახელმძღვანელო (Integration — MQTT)',['../md_docs_2integration_2integration__mqtt.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20rest_20api_34',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20websocket_35',['WebSocket ინტეგრაციის სახელმძღვანელო (Integration — WebSocket)',['../md_docs_2integration_2integration__websocket.html',1,'']]],
  ['ინტერპრეტაცია_36',['შედეგების ინტერპრეტაცია',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md649',1,'']]],
  ['ინფორმაცია_37',['ინფორმაცია',['../md_docs_2contributing_2issue__template.html#autotoc_md679',1,'გარემოს ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md681',1,'დამატებითი ინფორმაცია'],['../md_docs_2contributing_2pull__request__template.html#autotoc_md717',1,'დამატებითი ინფორმაცია'],['../md_docs_2security_2security__vulnerability__disclosure.html#autotoc_md1423',1,'საკონტაქტო ინფორმაცია'],['../md_docs_2contributing_2pull__request__template.html#autotoc_md709',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md669',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2faq.html#autotoc_md660',1,'7. სად ვიპოვო დოკუმენტაციის სტრუქტურის და სტანდარტების შესახებ ინფორმაცია?']]],
  ['ისთვის_38',['ისთვის',['../md_docs_2api__reference_2display__api.html#autotoc_md223',1,'Service API (Service Locator-ისთვის)'],['../md_docs_2api__reference_2module__api.html#autotoc_md330',1,'Service API (Service Locator-ისთვის)']]],
  ['ის_20აღწერისა_39',['მაგალითი Custom Event-ის აღწერისა',['../md_docs_2api__reference_2event__api.html#autotoc_md275',1,'']]],
  ['ის_20გამოყენება_40',['ის გამოყენება',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1324',1,'CPU-ის გამოყენება'],['../md_docs_2convention_2communication__patterns.html#autotoc_md767',1,'Event Bus-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1323',1,'Flash-ის გამოყენება'],['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md1078',1,'Public API-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1322',1,'RAM-ის გამოყენება'],['../md_docs_2convention_2communication__patterns.html#autotoc_md766',1,'Service Locator-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1325',1,'Stack-ის გამოყენება']]],
  ['ის_20იდენტიფიკატორი_41',['Custom Event-ის იდენტიფიკატორი',['../md_docs_2api__reference_2custom__api.html#autotoc_md205',1,'']]],
  ['ის_20ინსტალაცია_42',['ESP-IDF-ის ინსტალაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md691',1,'']]],
  ['ის_20კონფიგურაცია_43',['2. Debug Build-ის კონფიგურაცია',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1566',1,'']]],
  ['ის_20მაგალითი_44',['Event Handler-ის მაგალითი',['../md_docs_2api__reference_2event__api.html#autotoc_md272',1,'']]],
  ['ის_20მიმოხილვა_45',['4. Pull Request-ის მიმოხილვა',['../md_docs_2contributing_2contributing__guide.html#autotoc_md632',1,'']]],
  ['ის_20მონაცემების_20სტრუქტურა_46',['Custom Event-ის მონაცემების სტრუქტურა',['../md_docs_2api__reference_2custom__api.html#autotoc_md206',1,'']]],
  ['ის_20მონიშვნა_47',['Deprecated API-ის მონიშვნა',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md1098',1,'']]],
  ['ის_20ოპტიმიზაცია_48',['Refresh interval-ის ოპტიმიზაცია',['../md_docs_2performance_2performance__display.html#autotoc_md1285',1,'']]],
  ['ის_20როლი_49',['1. &lt;tt&gt;system_config.json&lt;/tt&gt;-ის როლი',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1639',1,'']]],
  ['ის_20სტანდარტები_50',['Logging-ის სტანდარტები',['../md_docs_2convention_2logging__standards.html',1,'']]],
  ['ის_20წერის_20წესები_51',['Footer-ის წერის წესები',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md620',1,'']]],
  ['ის_20წესები_52',['ის წესები',['../contributing_docs.html#contrib_commit_sec',1,'Commit Message-ის წესები'],['../md_docs_2convention_2error__handling.html',1,'Error Handling-ის წესები']]],
  ['იქმნება_3a_53',['1. რომ დარწმუნდეთ მოდული სწორად იქმნება:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md968',1,'']]],
  ['იძებნება_54',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1550',1,'']]],
  ['იწვევს_20პრობლემას_55',['6. როგორ გავიგო რომელი მოდული იწვევს პრობლემას?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1580',1,'']]],
  ['ი_20ჩემს_20სერვისს_56',['3. რატომ ვერ პოულობს Service Locator-ი ჩემს სერვისს?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1577',1,'']]]
];
