var searchData=
[
  ['💡_20ახალი_20ტესტის_20დამატების_20მაგალითი_0',['6. 💡 ახალი ტესტის დამატების მაგალითი',['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md34',1,'']]],
  ['💡_20გადაწყვეტა_3a_20promise_20პატერნი_1',['3. 💡 გადაწყვეტა: Promise პატერნი',['../md_docs_2convention_2promise__pattern.html#autotoc_md1352',1,'']]],
  ['💡_20გადაწყვეტა_3a_20tt_20task_20pool_20manager_20tt_2',['3. 💡 გადაწყვეტა: &lt;tt&gt;Task Pool Manager&lt;/tt&gt;',['../md_docs_2convention_2task__pool__pattern.html#autotoc_md1361',1,'']]],
  ['💡_20გამოყენება_20და_20უსაფრთხოების_20ჩართვა_3',['6. 💡 გამოყენება და უსაფრთხოების ჩართვა',['../md_components_2modules_2security_2security__status__reporter_2README.html#autotoc_md98',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_4',['💡 გამოყენების მაგალითი',['../md_docs_2api__reference_2task__pool__api.html#autotoc_md714',1,'💡 გამოყენების მაგალითი'],['../md_docs_2api__reference_2storage__api.html#autotoc_md675',1,'💡 გამოყენების მაგალითი'],['../md_docs_2api__reference_2promise__api.html#autotoc_md565',1,'💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2i2c__bus_2README.html#autotoc_md56',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2displays_2ssd1306__driver_2README.html#autotoc_md41',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2sn74hc595n__writer_2README.html#autotoc_md83',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2spi__bus_2README.html#autotoc_md90',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md125',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utillities_2system__timer_2README.html#autotoc_md256',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2testing_2sensor__simulator_2README.html#autotoc_md201',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2time__sync_2README.html#autotoc_md187',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2mcp23017__io__expander_2README.html#autotoc_md67',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utillities_2command__router_2README.html#autotoc_md214',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md194',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md180',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md172',1,'7. 💡 გამოყენების მაგალითი']]],
  ['💡_20გამოყენების_20მაგალითი_20და_20ტესტირება_5',['5. 💡 გამოყენების მაგალითი და ტესტირება',['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md108',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_20მოთხოვნა_20პასუხი_6',['8. 💡 გამოყენების მაგალითი (მოთხოვნა-პასუხი)',['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md161',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_20tt_20sensor_5faggregator_20tt_20თან_20ინტეგრაცია_7',['5. 💡 გამოყენების მაგალითი (&lt;tt&gt;sensor_aggregator&lt;/tt&gt;-თან ინტეგრაცია)',['../md_components_2modules_2sensors_2time__of__flight__sensor_2README.html#autotoc_md116',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_20tt_20ui_5fmanager_20tt_20თან_8',['6. 💡 გამოყენების მაგალითი (&lt;tt&gt;ui_manager&lt;/tt&gt;-თან)',['../md_components_2modules_2drivers_2rotary__encoder__input_2README.html#autotoc_md77',1,'']]],
  ['💡_20გამოყენების_20პატერნი_3a_20კონფლიქტისგან_20დაცული_20რეგისტრაცია_9',['💡 გამოყენების პატერნი: კონფლიქტისგან დაცული რეგისტრაცია',['../md_docs_2api__reference_2command__router__api.html#autotoc_md308',1,'']]],
  ['💡_20გამოყენების_20სცენარები_10',['6. 💡 გამოყენების სცენარები',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md135',1,'']]],
  ['💡_20მოდული_3a_20tt_20rgb_5fled_5findicator_20tt_11',['💡 მოდული: &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utillities_2rgb__led__indicator_2README.html',1,'']]],
  ['💡_20პრაქტიკული_20მაგალითი_3a_20tt_20wifi_5fmanager_20tt_20და_20tt_20command_5frouter_20tt_12',['💡 პრაქტიკული მაგალითი: &lt;tt&gt;wifi_manager&lt;/tt&gt; და &lt;tt&gt;command_router&lt;/tt&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1289',1,'']]],
  ['💡_20mqtt_20api_20ს_20გამოყენების_20მაგალითი_13',['💡 MQTT API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md318',1,'']]],
  ['💡_20strong_20დონე_204_3a_20აპლიკაციის_20ლოგიკა_20და_20პერიფერია_2060_2079_20strong_14',['💡 &lt;strong&gt;დონე 4: აპლიკაციის ლოგიკა და პერიფერია (60-79)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1298',1,'']]],
  ['💡_20wifi_20api_20ს_20გამოყენების_20მაგალითი_15',['💡 WiFi API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md314',1,'']]]
];
