var searchData=
[
  ['ram_0',['RAM',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1476',1,'']]],
  ['ram_20ის_20გამოყენება_1',['RAM-ის გამოყენება',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1470',1,'']]],
  ['read_2',['read',['../structi2c__bus__api__t.html#a831febe316b7c4570e2bcaf46b59d3c7',1,'i2c_bus_api_t']]],
  ['read_5ffile_3',['read_file',['../structstorage__api__t.html#af31e61ac9fa245b6a7bf4f541a3876ce',1,'storage_api_t']]],
  ['readme_20md_4',['[README.md]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md732',1,'']]],
  ['reboot_5fsystem_5',['reboot_system',['../structsystem__manager__api__t.html#a402ede4ddd5f00bdad179ec8e85d5e9e',1,'system_manager_api_t']]],
  ['reconfiguration_6',['reconfiguration',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1719',1,'3. Runtime Reconfiguration'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1576',1,'Runtime Reconfiguration']]],
  ['reconfigure_7',['reconfigure',['../structmodule__t.html#a68e5d4c7041e43135876d4f0b4e39ea7',1,'module_t']]],
  ['reconfigure_3a_8',['2. სისტემის reconfigure:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1104',1,'']]],
  ['record_20template_9',['არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)',['../md_docs_2design__decisions_2decision__record__template.html',1,'']]],
  ['recovery_20strategies_10',['Error Recovery Strategies',['../md_docs_2convention_2error__handling.html#autotoc_md980',1,'']]],
  ['redraw_11',['Conditional redraw',['../md_docs_2performance_2performance__display.html#autotoc_md1434',1,'']]],
  ['ref_5fcount_12',['ref_count',['../structevent__data__wrapper__t.html#a1d75bdc3d17e5c455be5bdc2ad22574b',1,'event_data_wrapper_t']]],
  ['refactor_13',['[Major] Module System Automation &amp; Refactor',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html#autotoc_md738',1,'']]],
  ['reference_14',['reference',['../md_docs_2api__reference_2storage__api.html',1,'💾 Synapse Storage Manager API Reference'],['../md_docs_2api__reference_2communication__api.html',1,'📡 Synapse Communication Module API Reference'],['../md_docs_2api__reference_2provisioning__api.html',1,'📲 Synapse Provisioning Module API Reference'],['../md_docs_2api__reference_2relay__api.html',1,'🔌 Relay Actuator API Reference'],['../md_docs_2api__reference_2security__api.html',1,'🛡️ Security Status API Reference'],['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md200',1,'API Reference'],['../md_docs_2api__reference_2actuators__api.html',1,'Synapse Actuators Module API Reference'],['../md_docs_2api__reference_2command__router__api.html',1,'Synapse Command Router API Reference'],['../md_docs_2api__reference_2configuration__api.html',1,'Synapse Configuration Manager API Reference'],['../md_docs_2api__reference_2core__api.html',1,'Synapse Core API Reference'],['../md_docs_2api__reference_2custom__api.html',1,'Synapse Custom API Reference'],['../md_docs_2api__reference_2device__identity__api.html',1,'Synapse Device Identity Service API Reference'],['../md_docs_2api__reference_2display__api.html',1,'Synapse Display Module API Reference'],['../md_docs_2api__reference_2drivers__api.html',1,'Synapse Drivers Module API Reference'],['../md_docs_2api__reference_2event__api.html',1,'Synapse Event Bus API Reference'],['../md_docs_2api__reference_2health__monitor__api.html',1,'Synapse Health Monitor Module API Reference'],['../md_docs_2api__reference_2local__ctrl__api.html',1,'Synapse Local Control Module API Reference'],['../md_docs_2api__reference_2module__api.html',1,'Synapse Module API Reference'],['../md_docs_2api__reference_2mqtt__api.html',1,'Synapse MQTT Manager Service API Reference'],['../md_docs_2api__reference_2ota__api.html',1,'Synapse OTA (Over-the-Air) Module API Reference'],['../md_docs_2api__reference_2resource__manager__api.html',1,'Synapse Resource Manager API Reference'],['../md_docs_2api__reference_2sensor__api.html',1,'Synapse Sensor Module API Reference'],['../md_docs_2api__reference_2system__api.html',1,'Synapse System Module API Reference'],['../md_docs_2api__reference_2time__sync__api.html',1,'Synapse Time Sync Module API Reference'],['../md_docs_2api__reference_2utility__api.html',1,'Synapse Utility Module API Reference'],['../md_docs_2api__reference_2version__api.html',1,'Synapse Version Module API Reference'],['../md_docs_2api__reference_2wifi__api.html',1,'Synapse WiFi Manager Service API Reference']]],
  ['reference_20counting_15',['ივენთის მონაცემების მართვა (Reference Counting)',['../md_docs_2api__reference_2event__api.html#autotoc_md419',1,'']]],
  ['reference_20index_16',['reference index',['../md_docs_2api__reference_2api__index.html',1,'Synapse API Reference Index'],['../md_docs_2contributing_2contributing__index.html',1,'Synapse Contributing Reference Index'],['../md_docs_2convention_2convention__index.html',1,'Synapse Convention Reference Index']]],
  ['refresh_20interval_20ის_20ოპტიმიზაცია_17',['Refresh interval-ის ოპტიმიზაცია',['../md_docs_2performance_2performance__display.html#autotoc_md1433',1,'']]],
  ['register_18',['register',['../md_docs_2structure_2core__components.html#autotoc_md1584',1,'3. Module Register'],['../md_docs_2design__decisions_2core__components.html#autotoc_md1167',1,'3. Module Register']]],
  ['register_20api_19',['Module Register API',['../md_docs_2api__reference_2core__api.html#autotoc_md318',1,'']]],
  ['register_5fcommand_20',['register_command',['../structcmd__router__api__t.html#a577628a1e19c957eaac870d60b9ebdc7',1,'cmd_router_api_t']]],
  ['register_5fcommand_20const_20cmd_5ft_20command_20tt_21',['&lt;tt&gt;esp_err_t register_command(const cmd_t *command)&lt;/tt&gt;',['../md_docs_2api__reference_2command__router__api.html#autotoc_md266',1,'']]],
  ['register_5fcustom_5fcheck_22',['register_custom_check',['../structhealth__api__t.html#a2c81e551b68935b03450b76d0d09870c',1,'health_api_t']]],
  ['register_5fheartbeat_23',['register_heartbeat',['../structwatchdog__api__t.html#ac16b85ae36dedce6596731ba9d56f28c',1,'watchdog_api_t']]],
  ['registration_20display_20module_24',['1. Service Registration (Display Module)',['../md_docs_2convention_2communication__patterns.html#autotoc_md933',1,'']]],
  ['registration_20logging_25',['2. Service Registration Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md1034',1,'']]],
  ['registry_26',['Module Registry',['../md_docs_2convention_2variable__naming.html#autotoc_md1068',1,'']]],
  ['relay_20actuator_20api_20reference_27',['🔌 Relay Actuator API Reference',['../md_docs_2api__reference_2relay__api.html',1,'']]],
  ['relay_20module_20api_28',['Relay Module API',['../md_docs_2api__reference_2actuators__api.html#autotoc_md233',1,'']]],
  ['relay_5factuator_20tt_29',['🔌 მოდული: &lt;tt&gt;relay_actuator&lt;/tt&gt;',['../md_components_2modules_2actuators_2relay__actuator_2README.html',1,'']]],
  ['relay_5factuator_2ec_30',['relay_actuator.c',['../relay__actuator_8c.html',1,'']]],
  ['relay_5factuator_5fcreate_31',['relay_actuator_create',['../relay__actuator_8c.html#a57a9879a72789576f6d8d87dd4641088',1,'relay_actuator.c']]],
  ['relay_5fapi_5ft_32',['relay_api_t',['../structrelay__api__t.html',1,'']]],
  ['relay_5fapi_5ft_20tt_33',['4. 🔌 Service API (&lt;tt&gt;relay_api_t&lt;/tt&gt;)',['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md4',1,'']]],
  ['relay_5fdata_34',['static esp_err_t parse_relay_config(const cJSON *config, relay_private_data_t *relay_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md245',1,'']]],
  ['relay_5fget_5fstatus_20module_5ft_20module_35',['static module_status_t relay_get_status(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md248',1,'']]],
  ['relay_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_36',['static void relay_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md242',1,'']]],
  ['relay_5finterface_2eh_37',['relay_interface.h',['../relay__interface_8h.html',1,'']]],
  ['relay_5fmodule_5fcreate_20const_20cjson_20config_38',['module_t &lt;em&gt;relay_module_create(const cJSON *config);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md234',1,'']]],
  ['relay_5fmodule_5fdisable_20module_5ft_20module_39',['esp_err_t relay_module_disable(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md236',1,'']]],
  ['relay_5fmodule_5fenable_20module_5ft_20module_40',['esp_err_t relay_module_enable(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md235',1,'']]],
  ['relay_5fmodule_5fget_5fstate_20module_5ft_20module_41',['bool relay_module_get_state(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md239',1,'']]],
  ['relay_5fmodule_5fset_5fstate_20module_5ft_20module_20bool_20state_42',['esp_err_t relay_module_set_state(module_t *module, bool state);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md238',1,'']]],
  ['relay_5fmodule_5ftoggle_20module_5ft_20module_43',['esp_err_t relay_module_toggle(module_t *module);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md237',1,'']]],
  ['relay_5fprivate_5fdata_5ft_44',['relay_private_data_t',['../structrelay__private__data__t.html',1,'']]],
  ['relay_5fprivate_5fdata_5ft_20relay_5fdata_45',['static esp_err_t parse_relay_config(const cJSON *config, relay_private_data_t *relay_data);',['../md_docs_2api__reference_2actuators__api.html#autotoc_md245',1,'']]],
  ['release_20checklist_46',['Release Checklist',['../md_docs_2security_2security__checklist.html#autotoc_md1515',1,'']]],
  ['release_5fcontrol_47',['release_control',['../structrgb__led__api__t.html#a51197765d41c0532713fa702fe463f88',1,'rgb_led_api_t']]],
  ['render_5fcurrent_5fstate_48',['render_current_state',['../ui__manager_8h.html#a093af2fea1ff15543b2b9d7609a87e71',1,'render_current_state(ui_manager_private_data_t *private_data):&#160;ui_manager.c'],['../ui__manager_8c.html#a093af2fea1ff15543b2b9d7609a87e71',1,'render_current_state(ui_manager_private_data_t *private_data):&#160;ui_manager.c']]],
  ['render_5ffooter_5fbutton_49',['render_footer_button',['../ui__screens_8h.html#a96f4ec2d25f38fd55d514150af179086',1,'render_footer_button(ui_manager_private_data_t *private_data, const char *text, bool is_selected):&#160;ui_screens.c'],['../ui__screens_8c.html#a96f4ec2d25f38fd55d514150af179086',1,'render_footer_button(ui_manager_private_data_t *private_data, const char *text, bool is_selected):&#160;ui_screens.c']]],
  ['render_5fheader_50',['render_header',['../ui__screens_8c.html#a376f0da5f8fa958e09b7a5adfc084950',1,'render_header(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8h.html#a376f0da5f8fa958e09b7a5adfc084950',1,'render_header(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['render_5fhome_5fscreen_51',['render_home_screen',['../ui__screens_8c.html#aa073835a483ffe68580ffdec8bc36910',1,'render_home_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8h.html#aa073835a483ffe68580ffdec8bc36910',1,'render_home_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['render_5fmodule_5fcontrol_5fscreen_52',['render_module_control_screen',['../ui__screens_8c.html#a3660eb426382f4100fc635af4cbbbeff',1,'render_module_control_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8h.html#a3660eb426382f4100fc635af4cbbbeff',1,'render_module_control_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['render_5fsplash_5fscreen_53',['render_splash_screen',['../ui__screens_8c.html#a1d1f8173dcde1f8ca44070f3353a3457',1,'render_splash_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c'],['../ui__screens_8h.html#a1d1f8173dcde1f8ca44070f3353a3457',1,'render_splash_screen(ui_manager_private_data_t *private_data):&#160;ui_screens.c']]],
  ['report_54',['report',['../structself__test__private__data__t.html#a0d37551189770210afd3a97f7d9cc3aa',1,'self_test_private_data_t']]],
  ['report_5fbuffer_20size_5ft_20buffer_5fsize_55',['esp_err_t diagnostics_module_get_report(char *report_buffer, size_t buffer_size);',['../md_docs_2api__reference_2system__api.html#autotoc_md649',1,'']]],
  ['report_5fline_5fcount_56',['report_line_count',['../structself__test__private__data__t.html#aaef7d81c87d0caded1f92ac1e1bd26b9',1,'self_test_private_data_t']]],
  ['report_5fmutex_57',['report_mutex',['../structself__test__private__data__t.html#ab931d22b5587b17128e0f9f510e73a44',1,'self_test_private_data_t']]],
  ['reporting_58',['3. Core Dumps და Crash Reporting',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1661',1,'']]],
  ['request_59',['3. როგორ შევქმნა Pull Request?',['../md_docs_2contributing_2faq.html#autotoc_md828',1,'']]],
  ['request_20ის_20მიმოხილვა_60',['4. Pull Request-ის მიმოხილვა',['../md_docs_2contributing_2contributing__guide.html#autotoc_md804',1,'']]],
  ['request_20template_61',['Synapse Pull Request Template',['../md_docs_2contributing_2pull__request__template.html',1,'']]],
  ['reserved_62',['reserved',['../structalarms__manager__api__t.html#a50209ba0e325a0b6f9012b41389ee14e',1,'alarms_manager_api_t']]],
  ['reset_5fscreen_5foff_5ftimer_63',['reset_screen_off_timer',['../ui__manager_8h.html#af34942bb9de4ca5702cca0195deb934a',1,'reset_screen_off_timer(ui_manager_private_data_t *private_data):&#160;ui_manager.c'],['../ui__manager_8c.html#af34942bb9de4ca5702cca0195deb934a',1,'reset_screen_off_timer(ui_manager_private_data_t *private_data):&#160;ui_manager.c']]],
  ['resource_20allocation_20checking_64',['2. Resource Allocation Checking',['../md_docs_2convention_2error__handling.html#autotoc_md970',1,'']]],
  ['resource_20cleanup_20functions_65',['2. Resource Cleanup Functions',['../md_docs_2convention_2error__handling.html#autotoc_md976',1,'']]],
  ['resource_20management_66',['Cleanup and Resource Management',['../md_docs_2convention_2error__handling.html#autotoc_md974',1,'']]],
  ['resource_20manager_20api_20reference_67',['Synapse Resource Manager API Reference',['../md_docs_2api__reference_2resource__manager__api.html',1,'']]],
  ['resource_20usage_20guide_68',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['resource_5fid_20const_20char_20owner_20tt_69',['resource_id const char owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md576',1,'&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md578',1,'&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['resource_5fid_20tt_70',['resource_id tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md580',1,'&lt;tt&gt;bool fmw_resource_is_locked(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md582',1,'&lt;tt&gt;const char *fmw_resource_get_owner(fmw_resource_type_t type, uint8_t resource_id)&lt;/tt&gt;']]],
  ['resource_5fmanager_20h_71',['[core/include/resource_manager.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md727',1,'']]],
  ['resource_5fmanager_2ec_72',['resource_manager.c',['../resource__manager_8c.html',1,'']]],
  ['resource_5fmanager_2eh_73',['resource_manager.h',['../resource__manager_8h.html',1,'']]],
  ['resource_5fpool_5ft_74',['resource_pool_t',['../structresource__pool__t.html',1,'']]],
  ['rest_20api_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20rest_20api_75',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['rest_20api_20integration_76',['4. REST API Integration',['../md_docs_2tutorials_2integration__example.html#autotoc_md1747',1,'']]],
  ['result_77',['result',['../structtest__report__line__t.html#a3ae7d1e5697b1014dd54c30b0d655fd6',1,'test_report_line_t']]],
  ['retry_20logic_78',['1. Retry Logic',['../md_docs_2convention_2error__handling.html#autotoc_md981',1,'']]],
  ['review_20checklist_79',['Code Review Checklist',['../md_docs_2security_2security__checklist.html#autotoc_md1516',1,'']]],
  ['review_20guidelines_80',['Synapse Review Guidelines',['../md_docs_2contributing_2review__guidelines.html',1,'']]],
  ['rgb_5fled_5fapi_5ft_81',['rgb_led_api_t',['../structrgb__led__api__t.html',1,'']]],
  ['rgb_5fled_5fapi_5ft_20tt_82',['4. 🛠️ Service API (&lt;tt&gt;rgb_led_api_t&lt;/tt&gt;)',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md210',1,'']]],
  ['rgb_5fled_5findicator_20tt_83',['💡 მოდული &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['rgb_5fled_5findicator_2ec_84',['rgb_led_indicator.c',['../rgb__led__indicator_8c.html',1,'']]],
  ['rgb_5fled_5findicator_2eh_85',['rgb_led_indicator.h',['../rgb__led__indicator_8h.html',1,'']]],
  ['rgb_5fled_5findicator_5fcreate_86',['rgb_led_indicator_create',['../rgb__led__indicator_8h.html#af7ab099c2a16ab7a894d97a3a01f3d31',1,'rgb_led_indicator_create(const cJSON *config):&#160;rgb_led_indicator.c'],['../rgb__led__indicator_8c.html#af7ab099c2a16ab7a894d97a3a01f3d31',1,'rgb_led_indicator_create(const cJSON *config):&#160;rgb_led_indicator.c']]],
  ['rgb_5fled_5finterface_2eh_87',['rgb_led_interface.h',['../rgb__led__interface_8h.html',1,'']]],
  ['rgb_5fled_5fprivate_5fdata_5ft_88',['rgb_led_private_data_t',['../structrgb__led__private__data__t.html',1,'']]],
  ['roboto_5fbold_5f24_2eh_89',['roboto_bold_24.h',['../roboto__bold__24_8h.html',1,'']]],
  ['roboto_5fbold_5f24_5fdigits_2eh_90',['roboto_bold_24_digits.h',['../roboto__bold__24__digits_8h.html',1,'']]],
  ['rollback_91',['8. განახლების ვალიდაცია და Rollback',['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md146',1,'']]],
  ['router_20api_20reference_92',['Synapse Command Router API Reference',['../md_docs_2api__reference_2command__router__api.html',1,'']]],
  ['router_20pattern_20ახალი_20სექცია_93',['3. Command Router Pattern (ახალი სექცია)',['../md_docs_2convention_2communication__patterns.html#autotoc_md923',1,'']]],
  ['router_20system_20shell_94',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utilities_2command__router_2README.html',1,'']]],
  ['runtime_20პრობლემები_95',['5. Runtime პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1686',1,'']]],
  ['runtime_20configuration_96',['Runtime Configuration',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md186',1,'']]],
  ['runtime_20control_97',['Runtime Control',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md189',1,'']]],
  ['runtime_20management_20ფუნქციები_98',['2. Runtime Management ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md999',1,'']]],
  ['runtime_20reconfiguration_99',['runtime reconfiguration',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1719',1,'3. Runtime Reconfiguration'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1576',1,'Runtime Reconfiguration']]],
  ['runtime_20state_20logging_100',['Runtime State Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md1039',1,'']]],
  ['rx_5fdata_20size_5ft_20data_5flength_101',['esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md404',1,'']]]
];
