var searchData=
[
  ['🔄_20პროექტის_20კლონირება_20submodule_20ებთან_20ერთად_0',['3. 🔄 პროექტის კლონირება Submodule-ებთან ერთად',['../md_docs_2contributing_2managing__modules.html#autotoc_md963',1,'']]],
  ['🔄_20სრული_20სამუშაო_20პროცესი_20workflow_1',['5. 🔄 სრული სამუშაო პროცესი (Workflow)',['../md_docs_2tools_2create__module.html#autotoc_md1747',1,'']]],
  ['🔄_20შეცვლილია_20changed_2',['🔄 შეცვლილია (Changed)',['../md_docs_2changelog_2v5.html#autotoc_md668',1,'']]],
  ['🔄_20შეცვლილი_3',['🔄 შეცვლილი',['../md_docs_2changelog_2v6.html#autotoc_md771',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md766',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md762',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v7.html#autotoc_md787',1,'🔄 შეცვლილი']]],
  ['🔄_20შეცვლილი_20და_20გაუმჯობესებული_20ფუნქციონალი_20changed_4',['🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი changed',['../md_docs_2changelog_2v5.html#autotoc_md640',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md635',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md629',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md626',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)']]],
  ['🔄_20შეცვლილი_20და_20გაუმჯობესებული_20ფუნქციონალი_20changed_20improved_5',['🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed &amp; Improved)',['../md_docs_2changelog_2v10.html#autotoc_md617',1,'']]],
  ['🔄_20შეცვლილი_20და_20გაუმჯობესებული_20changed_20improved_6',['🔄 შეცვლილი და გაუმჯობესებული changed improved',['../md_docs_2changelog_2v9.html#autotoc_md819',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v9.html#autotoc_md811',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v9.html#autotoc_md803',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v8.html#autotoc_md792',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v10.html#autotoc_md602',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v7.html#autotoc_md776',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v10.html#autotoc_md607',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v10.html#autotoc_md598',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)']]],
  ['🔄_20changed_20შეცვლილი_20და_20გაუმჯობესებული_20ფუნქციონალი_7',['🔄 changed შეცვლილი და გაუმჯობესებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md654',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md649',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md644',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)']]],
  ['🔄_20changed_20შეცვლილი_20ფუნქციონალი_8',['🔄 changed შეცვლილი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md664',1,'🔄 Changed (შეცვლილი ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md659',1,'🔄 Changed (შეცვლილი ფუნქციონალი)']]]
];
