var searchData=
[
  ['ფაილების_20სტრუქტურა_0',['ფაილების სტრუქტურა',['../structure_docs.html#struct_dir_sec',1,'საქაღალდეებისა და ფაილების სტრუქტურა'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md911',1,'საქაღალდეებისა და ფაილების სტრუქტურა']]],
  ['ფაილების_20სტრუქტურა_20directory_20structure_1',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['ფაილების_20შაბლონები_2',['3. Header და Source ფაილების შაბლონები',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1525',1,'']]],
  ['ფაილების_20შექმნა_3',['2. საქაღალდის და ფაილების შექმნა',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1524',1,'']]],
  ['ფაილები_4',['დამატებული და განახლებული ფაილები',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md489',1,'']]],
  ['ფაილები_205_20ფაილი_5',['✅ შექმნილი ფაილები (5 ფაილი)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1264',1,'']]],
  ['ფაილები_205_20ფაილი_20_3a_6',['✅ შექმნილი ფაილები (5 ფაილი):',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md865',1,'']]],
  ['ფაილის_20კონფიგურაცია_7',['sdkconfig ფაილის კონფიგურაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md639',1,'']]],
  ['ფაილის_20სათაურის_20header_20კომენტარი_8',['2. ფაილის სათაურის (Header) კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md681',1,'']]],
  ['ფაილის_20სტრუქტურა_9',['ფაილის სტრუქტურა',['../md_docs_2convention_2module__structure.html#autotoc_md827',1,'']]],
  ['ფაილი_10',['✅ შექმნილი ფაილები (5 ფაილი)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1264',1,'']]],
  ['ფაილი_20_3a_11',['✅ შექმნილი ფაილები (5 ფაილი):',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md865',1,'']]],
  ['ფაილი_20tt_20include_20module_5fname_20h_20tt_12',['1. Header ფაილი (&lt;tt&gt;include/{module_name}.h&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md828',1,'']]],
  ['ფაილი_20tt_20module_5fname_20c_20tt_13',['2. Source ფაილი (&lt;tt&gt;{module_name}.c&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md829',1,'']]],
  ['ფაქტობრივი_20შედეგი_14',['ფაქტობრივი შედეგი',['../md_docs_2contributing_2issue__template.html#autotoc_md621',1,'']]],
  ['ფენები_20და_20ძირითადი_20კომპონენტები_15',['არქიტექტურული ფენები და ძირითადი კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md908',1,'']]],
  ['ფლეში_16',['4. ბილდი და ფლეში',['../md_docs_2tutorials_2getting__started.html#autotoc_md1536',1,'']]],
  ['ფორმატი_17',['ფორმატი',['../md_docs_2convention_2logging__standards.html#autotoc_md797',1,'სტანდარტული ფორმატი'],['../md_docs_2convention_2configuration__management.html#autotoc_md717',1,'სტანდარტული ფორმატი']]],
  ['ფორმატი_20dot_20notation_18',['🔑 გასაღების ფორმატი (Dot-Notation)',['../md_docs_2api__reference_2configuration__api.html#autotoc_md100',1,'']]],
  ['ფრეიმვორქის_20გაფართოება_19',['ფრეიმვორქის გაფართოება',['../structure_docs.html#struct_extending_sec',1,'']]],
  ['ფრეიმვორქის_20გაფართოება_20და_20best_20practices_20extending_20the_20framework_20',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['ფუნქციების_20დასახელება_21',['ფუნქციების დასახელება',['../conventions_docs.html#conv_func_name_sec',1,'']]],
  ['ფუნქციების_20დასახელების_20წესები_22',['ფუნქციების დასახელების წესები',['../md_docs_2convention_2function__naming.html',1,'']]],
  ['ფუნქციები_23',['ფუნქციები',['../md_docs_2api__reference_2event__payloads__api.html#autotoc_md230',1,'მეხსიერების მართვის ფუნქციები'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md102',1,'⚙️ ძირითადი API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md789',1,'1. Module Lifecycle ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md790',1,'2. Runtime Management ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md791',1,'3. Event Handler ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md792',1,'4. Task ფუნქციები'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md356',1,'API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md781',1,'Framework API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md779',1,'Public API ფუნქციები'],['../md_docs_2convention_2function__naming.html#autotoc_md780',1,'Static/Private ფუნქციები']]],
  ['ფუნქციის_20დამატება_24',['3. ახალი API ან ფუნქციის დამატება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1554',1,'']]],
  ['ფუნქციის_20კომენტარი_25',['3. ფუნქციის კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md684',1,'']]],
  ['ფუნქციონალის_20დამატება_20module_20extension_20feature_20addition_26',['მოდულის გაფართოება ან ფუნქციონალის დამატება (Module Extension &amp; Feature Addition)',['../md_docs_2tutorials_2module__extension.html',1,'']]]
];
