var searchData=
[
  ['of_20conduct_0',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['offs_1',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['on_20errors_2',['1. Proper Cleanup on Errors',['../md_docs_2convention_2error__handling.html#autotoc_md1160',1,'']]],
  ['operation_20error_20handling_3',['5. Hardware Operation Error Handling',['../md_docs_2convention_2error__handling.html#autotoc_md1158',1,'']]],
  ['operation_20logging_4',['4. Hardware Operation Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md1221',1,'']]],
  ['operation_20timing_5',['1. Operation Timing',['../md_docs_2convention_2logging__standards.html#autotoc_md1228',1,'']]],
  ['optimization_20guide_6',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['options_7',['Main Configuration Options',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md221',1,'']]],
  ['ota_8',['Flash-ში მონაცემების შენახვა (OTA)',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1496',1,'']]],
  ['ota_20განახლების_20სიგნირება_9',['ota განახლების სიგნირება',['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1474',1,'OTA განახლების სიგნირება'],['../md_docs_2security_2security__best__practices.html#autotoc_md1690',1,'OTA განახლების სიგნირება']]],
  ['ota_20და_20firmware_20security_10',['OTA და Firmware Security',['../md_docs_2security_2security__guidelines.html#autotoc_md1716',1,'']]],
  ['ota_20module_20api_11',['ota module api',['../md_docs_2api__reference_2ota__api.html#autotoc_md540',1,'OTA Module API'],['../md_docs_2api__reference_2system__api.html#autotoc_md667',1,'OTA Module API']]],
  ['ota_20over_20the_20air_20module_20api_20reference_12',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['ota_20update_20manager_13',['მოდული: OTA Update Manager',['../md_components_2modules_2system_2ota__update__manager_2README.html',1,'']]],
  ['ota_5fapi_5ft_14',['ota_api_t',['../structota__api__t.html',1,'']]],
  ['ota_5fapi_5ft_20tt_15',['5. Service API (&lt;tt&gt;ota_api_t&lt;/tt&gt;)',['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md178',1,'']]],
  ['ota_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_16',['static void ota_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2ota__api.html#autotoc_md547',1,'']]],
  ['ota_5finterface_2eh_17',['ota_interface.h',['../ota__interface_8h.html',1,'']]],
  ['ota_5fmodule_5fabort_20void_18',['esp_err_t ota_module_abort(void);',['../md_docs_2api__reference_2ota__api.html#autotoc_md544',1,'']]],
  ['ota_5fmodule_5fcreate_20const_20cjson_20config_19',['ota_module_create const cjson config',['../md_docs_2api__reference_2ota__api.html#autotoc_md541',1,'module_t *ota_module_create(const cJSON *config);'],['../md_docs_2api__reference_2system__api.html#autotoc_md668',1,'module_t *ota_module_create(const cJSON *config);']]],
  ['ota_5fmodule_5fget_5fstatus_20ota_5fstatus_5ft_20status_20',['ota_module_get_status ota_status_t status',['../md_docs_2api__reference_2system__api.html#autotoc_md670',1,'esp_err_t ota_module_get_status(ota_status_t *status);'],['../md_docs_2api__reference_2ota__api.html#autotoc_md543',1,'esp_err_t ota_module_get_status(ota_status_t *status);']]],
  ['ota_5fmodule_5fstart_5fupdate_20const_20char_20url_21',['ota_module_start_update const char url',['../md_docs_2api__reference_2ota__api.html#autotoc_md542',1,'esp_err_t ota_module_start_update(const char *url);'],['../md_docs_2api__reference_2system__api.html#autotoc_md669',1,'esp_err_t ota_module_start_update(const char *url);']]],
  ['ota_5fstatus_5ft_20status_22',['ota_status_t status',['../md_docs_2api__reference_2system__api.html#autotoc_md670',1,'esp_err_t ota_module_get_status(ota_status_t *status);'],['../md_docs_2api__reference_2ota__api.html#autotoc_md543',1,'esp_err_t ota_module_get_status(ota_status_t *status);']]],
  ['ota_5fupdate_5fmanager_2ec_23',['ota_update_manager.c',['../ota__update__manager_8c.html',1,'']]],
  ['ota_5fupdate_5fmanager_2eh_24',['ota_update_manager.h',['../ota__update__manager_8h.html',1,'']]],
  ['ota_5fupdate_5fmanager_5fconfig_5ft_25',['ota_update_manager_config_t',['../structota__update__manager__config__t.html',1,'']]],
  ['ota_5fupdate_5fmanager_5fcreate_26',['ota_update_manager_create',['../ota__update__manager_8c.html#a792fc2704dda3f70481bb8073fcc1c4e',1,'ota_update_manager_create(const cJSON *config):&#160;ota_update_manager.c'],['../ota__update__manager_8h.html#a792fc2704dda3f70481bb8073fcc1c4e',1,'ota_update_manager_create(const cJSON *config):&#160;ota_update_manager.c']]],
  ['ota_5fupdate_5fmanager_5fprivate_5fdata_5ft_27',['ota_update_manager_private_data_t',['../structota__update__manager__private__data__t.html',1,'']]],
  ['out_5fvalue_20tt_28',['out_value tt',['../md_docs_2api__reference_2configuration__api.html#autotoc_md334',1,'&lt;tt&gt;esp_err_t fmw_config_get_bool(const char *key, bool *out_value)&lt;/tt&gt;'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md333',1,'&lt;tt&gt;esp_err_t fmw_config_get_int(const char *key, int *out_value)&lt;/tt&gt;']]],
  ['output_20format_29',['Output Format',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md235',1,'']]],
  ['over_20the_20air_20module_20api_20reference_30',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['overflow_20და_20task_20watchdog_31',['1. Stack Overflow და Task Watchdog',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1851',1,'']]],
  ['overview_32',['overview',['../index.html',1,'პროექტის მიმოხილვა (Project Overview)'],['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md217',1,'Overview']]],
  ['owner_20tt_33',['owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md611',1,'&lt;tt&gt;esp_err_t fmw_resource_lock(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md613',1,'&lt;tt&gt;esp_err_t fmw_resource_release(fmw_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['owner_5fnames_34',['owner_names',['../structresource__pool__t.html#aab904375ff53b6c6d69a4fb8678ba6e6',1,'resource_pool_t']]]
];
