var searchData=
[
  ['✨_20არქიტექტურული_20გაუმჯობესებები_20და_20dx_20architectural_20developer_20experience_20improvements_0',['✨ არქიტექტურული გაუმჯობესებები და DX (Architectural &amp; Developer Experience Improvements)',['../md_docs_2changelog_2v9.html#autotoc_md802',1,'']]],
  ['✨_20არქიტექტურული_20გაუმჯობესებები_20architectural_20improvements_1',['✨ არქიტექტურული გაუმჯობესებები architectural improvements',['../md_docs_2changelog_2v9.html#autotoc_md827',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md818',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md815',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v8.html#autotoc_md797',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v8.html#autotoc_md791',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)'],['../md_docs_2changelog_2v7.html#autotoc_md775',1,'✨ არქიტექტურული გაუმჯობესებები (Architectural Improvements)']]],
  ['✨_20ახალი_20ფუნქციები_20features_2',['✨ ახალი ფუნქციები features',['../md_docs_2changelog_2v5.html#autotoc_md684',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md717',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md732',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md689',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md693',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md728',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md698',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md723',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md703',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md720',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md708',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md712',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md680',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md676',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md671',1,'✨ ახალი ფუნქციები (Features)']]],
  ['✨_20ახალი_20ფუნქციონალი_3',['✨ ახალი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md740',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md742',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md746',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md749',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md753',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md756',1,'✨ ახალი ფუნქციონალი']]],
  ['✨_20გაუმჯობესებები_20improvements_4',['✨ გაუმჯობესებები improvements',['../md_docs_2changelog_2v7.html#autotoc_md781',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md807',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v9.html#autotoc_md823',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md704',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md714',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md699',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md694',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md685',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md681',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md677',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md672',1,'✨ გაუმჯობესებები (Improvements)']]],
  ['✨_20დამატებულია_5',['✨ დამატებულია',['../md_docs_2changelog_2v5.html#autotoc_md736',1,'']]],
  ['✨_20დამატებულია_20added_6',['✨ დამატებულია (Added)',['../md_docs_2changelog_2v5.html#autotoc_md667',1,'']]],
  ['✨_20დამატებული_7',['✨ დამატებული',['../md_docs_2changelog_2v6.html#autotoc_md770',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md761',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md765',1,'✨ დამატებული']]],
  ['✨_20დამატებული_20ფუნქციონალი_20და_20dx_20added_20features_20developer_20experience_8',['✨ დამატებული ფუნქციონალი და dx added features developer experience',['../md_docs_2changelog_2v10.html#autotoc_md606',1,'✨ დამატებული ფუნქციონალი და DX (Added Features &amp; Developer Experience)'],['../md_docs_2changelog_2v10.html#autotoc_md611',1,'✨ დამატებული ფუნქციონალი და DX (Added Features &amp; Developer Experience)'],['../md_docs_2changelog_2v10.html#autotoc_md601',1,'✨ დამატებული ფუნქციონალი და DX (Added Features &amp; Developer Experience)']]],
  ['✨_20დამატებული_20ფუნქციონალი_20added_9',['✨ დამატებული ფუნქციონალი added',['../md_docs_2changelog_2v5.html#autotoc_md639',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md634',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md628',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md622',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v10.html#autotoc_md616',1,'✨ დამატებული ფუნქციონალი (Added)']]],
  ['✨_20added_20დამატებული_20ფუნქციონალი_10',['✨ added დამატებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md658',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md653',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md648',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md643',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md663',1,'✨ Added (დამატებული ფუნქციონალი)']]]
];
