var searchData=
[
  ['კატეგორია_20მოდულებისთვის_0',['8. როგორ დავამატო ახალი კატეგორია მოდულებისთვის?',['../md_docs_2structure_2faq.html#autotoc_md1709',1,'']]],
  ['კატეგორიები_1',['2.2. კატეგორიები',['../md_docs_2convention_2module__structure.html#autotoc_md1161',1,'']]],
  ['კითხვა_2',['სენსორის კითხვა',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1501',1,'']]],
  ['კითხვა_20ამ_20faq_20ში_3',['9. როგორ დავამატო ახალი კითხვა ამ FAQ-ში?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1826',1,'']]],
  ['კითხვების_20ან_20პრობლემების_20შემთხვევაში_4',['10. ვის მივმართო დამატებითი კითხვების ან პრობლემების შემთხვევაში?',['../md_docs_2contributing_2faq.html#autotoc_md915',1,'']]],
  ['კითხვები_20faq_5',['კითხვები faq',['../md_docs_2contributing_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)'],['../md_docs_2structure_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)']]],
  ['კითხვები_20troubleshooting_20faq_6',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['კლონირება_7',['პროექტის კლონირება',['../md_docs_2contributing_2local__setup.html#autotoc_md945',1,'']]],
  ['კლონირება_20submodule_20ებთან_20ერთად_8',['3. 🔄 პროექტის კლონირება Submodule-ებთან ერთად',['../md_docs_2contributing_2managing__modules.html#autotoc_md963',1,'']]],
  ['კოდები_9',['შეცდომების კოდები',['../md_docs_2structure_2error__handling__and__logging.html#autotoc_md1688',1,'']]],
  ['კოდექსი_10',['კოდექსი',['../contributing_docs.html#contrib_coc_sec',1,'ქცევის კოდექსი'],['../md_docs_2contributing_2faq.html#autotoc_md914',1,'9. როგორ დავიცვა ქცევის კოდექსი?']]],
  ['კოდექსი_20code_20of_20conduct_11',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['კოდიდან_20dot_20notation_12',['4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1891',1,'']]],
  ['კოდის_20იმპლემენტაცია_13',['4. კოდის იმპლემენტაცია',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1846',1,'']]],
  ['კოდის_20ოპტიმიზაცია_14',['კოდის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1546',1,'']]],
  ['კოდის_20სტანდარტები_15',['2. კოდის სტანდარტები',['../md_docs_2contributing_2contributing__guide.html#autotoc_md882',1,'']]],
  ['კოდის_20სტრუქტურა_20tt_20_5fcreate_20tt_20ფუნქცია_16',['3.4. კოდის სტრუქტურა (&lt;tt&gt;_create&lt;/tt&gt; ფუნქცია)',['../md_docs_2convention_2module__structure.html#autotoc_md1166',1,'']]],
  ['კოდის_20ტერმინები_20glossary_20—_20api_20code_17',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['კოდი_20არ_20იკითხება_18',['პრობლემა: შეცდომის კოდი არ იკითხება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1785',1,'']]],
  ['კოდში_19',['ცვლილებები კოდში',['../md_docs_2changelog_22025-06-26-led__blinker-nvs-debug.html#autotoc_md559',1,'']]],
  ['კომენტარების_20სტანდარტი_20',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['კომენტარების_20სტანდარტი_20v1_200_21',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['კომენტარები_22',['4. სტრუქტურების და ტიპების კომენტარები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md1015',1,'']]],
  ['კომენტარი_23',['კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md1009',1,'2. ფაილის სათაურის (Header) კომენტარი'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md1012',1,'3. ფუნქციის კომენტარი']]],
  ['კომპოზიტური_20მოდულები_2080_20100_20strong_24',['🧩 &lt;strong&gt;დონე 5: მაღალი დონის კომპოზიტური მოდულები (80-100)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1120',1,'']]],
  ['კომპონენტები_25',['კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1214',1,'არქიტექტურული ფენები და ძირითადი კომპონენტები'],['../md_docs_2design__decisions_2core__components.html#autotoc_md1249',1,'ძირითადი კომპონენტები'],['../md_docs_2structure_2core__components.html#autotoc_md1664',1,'ძირითადი კომპონენტები'],['../index.html#autotoc_md1734',1,'ძირითადი კომპონენტები']]],
  ['კომპონენტები_20core_20components_26',['კომპონენტები core components',['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['კომპრომისები_20performance_20trade_20offs_27',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['კომუნიკაცია_28',['3. როგორ ხდება მოდულებს შორის კომუნიკაცია?',['../md_docs_2structure_2faq.html#autotoc_md1704',1,'']]],
  ['კომუნიკაცია_2040_2059_20strong_29',['📡 &lt;strong&gt;დონე 3: ქსელი, კონტროლი და კომუნიკაცია (40-59)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1116',1,'']]],
  ['კომუნიკაციის_20არქიტექტურული_20არჩევანი_20communication_20choices_30',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['კომუნიკაციის_20გაფართოება_31',['5. კომუნიკაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1876',1,'']]],
  ['კომუნიკაციის_20პატერნების_20წესები_20v2_200_32',['კომუნიკაციის პატერნების წესები (v2.0)',['../md_docs_2convention_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პატერნები_33',['კომუნიკაციის პატერნები',['../structure_docs.html#struct_comm_patterns_sec',1,'კომუნიკაციის პატერნები'],['../conventions_docs.html#conv_comm_sec',1,'კომუნიკაციის პატერნები'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1215',1,'მოდულებს შორის კომუნიკაციის პატერნები']]],
  ['კომუნიკაციის_20პატერნები_20communication_20patterns_34',['კომუნიკაციის პატერნები (Communication Patterns)',['../md_docs_2structure_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პრობლემები_35',['3. კომუნიკაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1779',1,'']]],
  ['კომუნიკაციის_20ტიპები_36',['კომუნიკაციის ტიპები',['../md_docs_2convention_2communication__patterns.html#autotoc_md1025',1,'']]],
  ['კონვენცია_37',['კონვენცია',['../md_docs_2convention_2configuration__management.html',1,'კონფიგურაციის მართვის კონვენცია'],['../md_docs_2convention_2logging__colors.html',1,'ლოგირების ფერთა სქემის კონვენცია'],['../md_docs_2convention_2module__structure.html',1,'მოდულის სტრუქტურის კონვენცია'],['../md_docs_2convention_2assertion__and__guards.html',1,'Assertions და Guard Clauses კონვენცია']]],
  ['კონვენცია_20მოდულის_20დეველოპერებისთვის_38',['4.1. კონვენცია მოდულის დეველოპერებისთვის',['../md_docs_2design__decisions_2dependency__injection.html#autotoc_md1279',1,'']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_39',['კონვენციების ავტომატური შემმოწმებელი',['../contributing_docs.html#contrib_linter_guide_sec',1,'']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_20tt_20check_5fconventions_20py_20tt_40',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['კონვენციები_41',['კონვენციები',['../md_docs_2convention_2function__naming.html#autotoc_md1098',1,'სპეციალური კონვენციები'],['../md_docs_2api__reference_2communication__api.html#autotoc_md95',1,'📜 Naming &amp; Structure კონვენციები'],['../md_docs_2convention_2variable__naming.html#autotoc_md1197',1,'4. კონვენციები']]],
  ['კონვენციები_20და_20სტანდარტები_42',['კონვენციები და სტანდარტები',['../conventions_docs.html',1,'']]],
  ['კონვენციებს_20უნდა_20დავიცვა_43',['2. რა სტანდარტებს და კონვენციებს უნდა დავიცვა?',['../md_docs_2contributing_2faq.html#autotoc_md907',1,'']]],
  ['კონტექსტი_44',['კონტექსტი',['../md_docs_2design__decisions_2communication__choices.html#autotoc_md1225',1,'კონტექსტი'],['../md_docs_2design__decisions_2decision__record__template.html#autotoc_md1267',1,'კონტექსტი'],['../md_docs_2design__decisions_2error__handling__decisions.html#autotoc_md1290',1,'კონტექსტი'],['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md1310',1,'კონტექსტი'],['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md1330',1,'კონტექსტი'],['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md1351',1,'კონტექსტი'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1372',1,'კონტექსტი'],['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1393',1,'კონტექსტი'],['../md_docs_2design__decisions_2dependency__injection.html#autotoc_md1275',1,'1. კონტექსტი']]],
  ['კონტექსტი_20სერვისის_20api_20ს_20გამოძახებისას_45',['პრობლემა: როგორ გადავცეთ კონტექსტი სერვისის API-ს გამოძახებისას?',['../md_docs_2troubleshooting_2dependency__injection__and__context.html',1,'']]],
  ['კონტრაქტი_46',['&lt;tt&gt;_create&lt;/tt&gt; ფუნქციის კონტრაქტი',['../md_docs_2structure_2module__architecture.html#autotoc_md1726',1,'']]],
  ['კონტრიბუცია_20synapse_20framework_20ში_47',['1. როგორ დავიწყო კონტრიბუცია Synapse Framework-ში?',['../md_docs_2contributing_2faq.html#autotoc_md906',1,'']]],
  ['კონტრიბუციის_20გზამკვლევი_48',['კონტრიბუციის გზამკვლევი',['../contributing_docs.html',1,'']]],
  ['კონტრიბუციის_20პროცესი_49',['კონტრიბუციის პროცესი',['../contributing_docs.html#contrib_guide_sec',1,'კონტრიბუციის პროცესი'],['../md_docs_2contributing_2contributing__guide.html#autotoc_md881',1,'1. კონტრიბუციის პროცესი']]],
  ['კონტრიბუციის_20სახელმძღვანელო_20contributing_20guide_50',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['კონტროლი_51',['კონტროლი',['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1383',1,'ლოგირების კონტროლი'],['../md_docs_2security_2security__best__practices.html#autotoc_md1586',1,'ლოგირების კონტროლი']]],
  ['კონტროლი_20და_20კომუნიკაცია_2040_2059_20strong_52',['📡 &lt;strong&gt;დონე 3: ქსელი, კონტროლი და კომუნიკაცია (40-59)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1116',1,'']]],
  ['კონფიგურაციაზე_20წვდომა_20სხვა_20მოდულებიდან_53',['5. 🌐 კონფიგურაციაზე წვდომა სხვა მოდულებიდან',['../md_docs_2convention_2configuration__management.html#autotoc_md1053',1,'']]],
  ['კონფიგურაცია_54',['კონფიგურაცია',['../md_docs_2troubleshooting_2dependency__injection__and__context.html#autotoc_md1814',1,'ეტაპი 3: &lt;tt&gt;config.json&lt;/tt&gt;-ის კონფიგურაცია'],['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1830',1,'1. მრავალმოდულიანი კონფიგურაცია'],['../md_docs_2tutorials_2integration__example.html#autotoc_md1863',1,'2. საჭირო მოდულების ჩართვა და კონფიგურაცია'],['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1800',1,'2. Debug Build-ის კონფიგურაცია'],['../md_docs_2tutorials_2create__first__module.html#autotoc_md1845',1,'3. კონფიგურაცია'],['../md_docs_2structure_2faq.html#autotoc_md1705',1,'4. როგორ მივიღო ან შევცვალო მოდულის კონფიგურაცია?'],['../md_docs_2contributing_2local__setup.html#autotoc_md947',1,'sdkconfig ფაილის კონფიგურაცია']]],
  ['კონფიგურაცია_20system_20configuration_55',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['კონფიგურაციისა_20და_20შენახვის_20ტერმინები_20glossary_20—_20configuration_20storage_56',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['კონფიგურაციის_20გაფართოება_57',['4. კონფიგურაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1875',1,'']]],
  ['კონფიგურაციის_20დამუშავების_20ეტაპები_58',['კონფიგურაციის დამუშავების ეტაპები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1654',1,'']]],
  ['კონფიგურაციის_20ვალიდაცია_20და_20default_20ები_59',['5. კონფიგურაციის ვალიდაცია და Default-ები',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1893',1,'']]],
  ['კონფიგურაციის_20მართვა_60',['კონფიგურაციის მართვა',['../conventions_docs.html#conv_config_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20კონვენცია_61',['კონფიგურაციის მართვის კონვენცია',['../md_docs_2convention_2configuration__management.html',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_62',['კონფიგურაციის მართვის პროცესი',['../structure_docs.html#struct_config_flow_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_20configuration_20flow_63',['კონფიგურაციის მართვის პროცესი (Configuration Flow)',['../md_docs_2structure_2configuration__flow.html',1,'']]],
  ['კონფიგურაციის_20ობიექტის_20აღწერა_64',['3. მოდულის კონფიგურაციის ობიექტის აღწერა',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1889',1,'']]],
  ['კონფიგურაციის_20ოპტიმიზაცია_65',['კონფიგურაციის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1548',1,'']]],
  ['კონფიგურაციის_20პარსინგის_20დამხმარე_20ფუნქციები_66',['2. კონფიგურაციის პარსინგის დამხმარე ფუნქციები',['../md_docs_2api__reference_2utils__api.html#autotoc_md524',1,'']]],
  ['კონფიგურაციის_20პარსინგის_20პატერნი_67',['4. 📝 კონფიგურაციის პარსინგის პატერნი',['../md_docs_2convention_2configuration__management.html#autotoc_md1050',1,'']]],
  ['კონფიგურაციის_20პრობლემები_68',['2. კონფიგურაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1775',1,'']]],
  ['კონფიგურაციის_20სტრუქტურა_69',['კონფიგურაციის სტრუქტურა',['../md_docs_2structure_2configuration__flow.html#autotoc_md1653',1,'კონფიგურაციის სტრუქტურა'],['../md_docs_2convention_2configuration__management.html#autotoc_md1049',1,'3. 🏗️ კონფიგურაციის სტრუქტურა']]],
  ['კონფიგურაციის_20ფაილების_20როლები_70',['1. კონფიგურაციის ფაილების როლები',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1885',1,'']]],
  ['კონფიგურაციის_20ფაილები_71',['3.2. კონფიგურაციის ფაილები',['../md_docs_2convention_2module__structure.html#autotoc_md1164',1,'']]],
  ['კონფიგურაციის_20შეცდომა_72',['8. როგორ დავადგინო კონფიგურაციის შეცდომა?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1825',1,'']]],
  ['კონფიგურაციის_20წვდომის_20მაგალითები_73',['კონფიგურაციის წვდომის მაგალითები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1655',1,'']]],
  ['კონფიგურაციის_20წყაროები_74',['კონფიგურაციის წყაროები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1652',1,'']]],
  ['კონფიგურაციის_20წყაროები_20და_20იერარქია_75',['2. 📂 კონფიგურაციის წყაროები და იერარქია',['../md_docs_2convention_2configuration__management.html#autotoc_md1048',1,'']]],
  ['კონფლიქტისგან_20დაცული_20რეგისტრაცია_76',['💡 გამოყენების პატერნი: კონფლიქტისგან დაცული რეგისტრაცია',['../md_docs_2api__reference_2command__router__api.html#autotoc_md80',1,'']]],
  ['კრახი_20tt_20loadprohibited_20tt_20ან_20tt_20assert_20failed_3a_20heap_5fcaps_5ffree_20tt_77',['პრობლემა: სისტემის კრახი &lt;tt&gt;LoadProhibited&lt;/tt&gt; ან &lt;tt&gt;assert failed: heap_caps_free&lt;/tt&gt;',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1792',1,'']]],
  ['კრახი_20tt_20stack_20overflow_20in_20task_20tmr_20svc_20tt_20შეცდომით_78',['პრობლემა: სისტემის კრახი &lt;tt&gt;Stack Overflow in task Tmr Svc&lt;/tt&gt; შეცდომით',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1791',1,'']]],
  ['კრიტერიუმები_79',['მიმოხილვის კრიტერიუმები',['../md_docs_2contributing_2review__guidelines.html#autotoc_md988',1,'']]]
];
