var searchData=
[
  ['ობიექტის_20აღწერა_0',['3. მოდულის კონფიგურაციის ობიექტის აღწერა',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1932',1,'']]],
  ['ობიექტის_20პარამეტრები_1',['ობიექტის პარამეტრები',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md131',1,'3.2. &lt;tt&gt;layers&lt;/tt&gt; ობიექტის პარამეტრები'],['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md94',1,'3.2. &lt;tt&gt;sensors_to_aggregate&lt;/tt&gt; ობიექტის პარამეტრები'],['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md132',1,'3.3. &lt;tt&gt;actions&lt;/tt&gt; ობიექტის პარამეტრები']]],
  ['ობიექტი_2',['ობიექტი',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md120',1,'3.1. განგაშის წესის პარამეტრები (&lt;tt&gt;alarms&lt;/tt&gt; ობიექტი)'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md121',1,'3.2. მოქმედებების პარამეტრები (&lt;tt&gt;actions&lt;/tt&gt; ობიექტი)']]],
  ['ოპერაციები_3',['ოპერაციები',['../md_docs_2api__reference_2storage__api.html#autotoc_md645',1,'🔑 Key-Value ოპერაციები'],['../md_docs_2api__reference_2storage__api.html#autotoc_md647',1,'🗂️ ფაილური ოპერაციები'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md112',1,'Key-Value ოპერაციები']]],
  ['ოპერაციები_20მხარდაჭერილია_20spiffs_20და_20sd_20card_20backend_20ებზე_4',['ფაილური ოპერაციები (მხარდაჭერილია SPIFFS და SD Card backend-ებზე)',['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md113',1,'']]],
  ['ოპტიმიზაცია_5',['ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1613',1,'კოდის ოპტიმიზაცია'],['../md_docs_2performance_2performance__optimization.html#autotoc_md1615',1,'კონფიგურაციის ოპტიმიზაცია'],['../md_docs_2performance_2performance__optimization.html#autotoc_md1617',1,'მოდულების ოპტიმიზაცია'],['../md_docs_2performance_2performance__display.html#autotoc_md1594',1,'Refresh interval-ის ოპტიმიზაცია']]],
  ['ოპტიმიზაცია_20და_20რესურსების_20მართვა_6',['6. ოპტიმიზაცია და რესურსების მართვა',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1883',1,'']]],
  ['ოპტიმიზაცია_20performance_20—_20display_20modules_7',['ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)',['../md_docs_2performance_2performance__display.html',1,'']]],
  ['ოპტიმიზაციის_20რეკომენდაციები_8',['ოპტიმიზაციის რეკომენდაციები',['../md_docs_2performance_2performance__display.html#autotoc_md1591',1,'']]],
  ['ოპტიმიზაციის_20სახელმძღვანელოები_20performance_20optimization_20guide_9',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['ოქროს_20წესი_10',['📜 ოქროს წესი',['../md_docs_2convention_2initialization__levels.html#autotoc_md1168',1,'']]]
];
