var searchData=
[
  ['latency_0',['MQTT publish latency',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1194',1,'']]],
  ['layout_1',['სტანდარტული მოდულის layout',['../md_docs_2convention_2module__structure.html#autotoc_md833',1,'']]],
  ['lazy_20initialization_2',['lazy initialization',['../md_docs_2performance_2performance__optimization.html#autotoc_md1246',1,'Lazy initialization'],['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md1054',1,'Lazy initialization']]],
  ['lcd_20display_20configuration_3',['3. LCD Display Configuration',['../md_docs_2convention_2configuration__management.html#autotoc_md730',1,'']]],
  ['leak_4',['leak',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1492',1,'პრობლემა: რესურსების გაჟონვა (memory leak)'],['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1464',1,'2. Heap Corruption და Memory Leak'],['../md_docs_2troubleshooting_2faq.html#autotoc_md1515',1,'7. როგორ გამოვასწორო რესურსების გაჟონვა (memory leak)?']]],
  ['led_5fblinker_20ინიციალიზაციის_20პრობლემის_20დიაგნოსტიკა_20და_20გამოსწორება_5',['CHANGELOG: led_blinker ინიციალიზაციის პრობლემის დიაგნოსტიკა და გამოსწორება',['../md_docs_2changelog_22025-06-26-led__blinker-nvs-debug.html',1,'']]],
  ['led_5fblinker_2ec_6',['led_blinker.c',['../led__blinker_8c.html',1,'']]],
  ['led_5fblinker_2eh_7',['led_blinker.h',['../led__blinker_8h.html',1,'']]],
  ['led_5fblinker_5fconfig_5ft_8',['led_blinker_config_t',['../structled__blinker__config__t.html',1,'']]],
  ['led_5fblinker_5fcreate_9',['led_blinker_create',['../led__blinker_8h.html#a58464148167e157567a7abd4cddeccea',1,'led_blinker_create(const cJSON *config):&#160;led_blinker.c'],['../led__blinker_8c.html#a58464148167e157567a7abd4cddeccea',1,'led_blinker_create(const cJSON *config):&#160;led_blinker.c']]],
  ['led_5fblinker_5fmodule_5ft_10',['led_blinker_module_t',['../structled__blinker__module__t.html',1,'']]],
  ['led_5fcommand_5ft_11',['led_command_t',['../structled__command__t.html',1,'']]],
  ['level_12',['level',['../md_docs_2convention_2logging__standards.html#autotoc_md808',1,'1. ESP_LOGE - Error Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md809',1,'2. ESP_LOGW - Warning Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md810',1,'3. ESP_LOGI - Info Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md811',1,'4. ESP_LOGD - Debug Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md812',1,'5. ESP_LOGV - Verbose Level']]],
  ['levels_13',['levels',['../md_docs_2convention_2error__handling.html#autotoc_md777',1,'1. Error Levels'],['../md_docs_2convention_2logging__standards.html#autotoc_md807',1,'Log Levels']]],
  ['lifecycle_14',['lifecycle',['../md_docs_2structure_2module__architecture.html#autotoc_md1445',1,'მოდულის სიცოცხლის ციკლი (Lifecycle)'],['../md_docs_2api__reference_2module__api.html#autotoc_md275',1,'Module Creation &amp; Lifecycle']]],
  ['lifecycle_20ფუნქციები_15',['1. Module Lifecycle ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md797',1,'']]],
  ['lifecycle_20initialization_16',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['lifecycle_20logging_17',['1. Module Lifecycle Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md814',1,'']]],
  ['line_18',['line',['../md_docs_2api__reference_2display__api.html#autotoc_md179',1,'esp_err_t ssd1306_api_write_text(const char *text, uint8_t line);'],['../md_docs_2api__reference_2module__api.html#autotoc_md286',1,'esp_err_t {module_name}_api_write_text(const char *text, uint8_t line);']]],
  ['list_19',['Deprecated List',['../deprecated.html',1,'']]],
  ['local_20control_20module_20api_20',['Local Control Module API',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md261',1,'']]],
  ['local_20control_20module_20api_20reference_21',['Synapse Local Control Module API Reference',['../md_docs_2api__reference_2local__ctrl__api.html',1,'']]],
  ['local_20setup_20guide_22',['Synapse Local Setup Guide',['../md_docs_2contributing_2local__setup.html',1,'']]],
  ['local_5fctrl_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_23',['static void local_ctrl_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md268',1,'']]],
  ['local_5fctrl_5fhandler_5ft_20handler_24',['esp_err_t local_ctrl_module_register_endpoint(const char *uri, http_method_t method, local_ctrl_handler_t handler);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md265',1,'']]],
  ['local_5fctrl_5fmodule_5fcreate_20const_20cjson_20config_25',['module_t *local_ctrl_module_create(const cJSON *config);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md262',1,'']]],
  ['local_5fctrl_5fmodule_5fregister_5fendpoint_20const_20char_20uri_20http_5fmethod_5ft_20method_20local_5fctrl_5fhandler_5ft_20handler_26',['esp_err_t local_ctrl_module_register_endpoint(const char *uri, http_method_t method, local_ctrl_handler_t handler);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md265',1,'']]],
  ['local_5fctrl_5fmodule_5fstart_20module_5ft_20module_27',['esp_err_t local_ctrl_module_start(module_t *module);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md263',1,'']]],
  ['local_5fctrl_5fmodule_5fstop_20module_5ft_20module_28',['esp_err_t local_ctrl_module_stop(module_t *module);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md264',1,'']]],
  ['locator_29',['locator',['../md_docs_2convention_2function__naming.html#autotoc_md791',1,'1. Service Locator'],['../md_docs_2structure_2core__components.html#autotoc_md1385',1,'1. Service Locator'],['../md_docs_2design__decisions_2core__components.html#autotoc_md951',1,'1. Service Locator'],['../md_docs_2convention_2communication__patterns.html#autotoc_md704',1,'Direct API Communication (Service Locator)'],['../md_docs_2structure_2communication__patterns.html#autotoc_md1369',1,'Service Locator'],['../md_docs_2design__decisions_2communication__choices.html#autotoc_md936',1,'Service Locator'],['../md_docs_2convention_2variable__naming.html#autotoc_md852',1,'Service Locator']]],
  ['locator_20ით_20api_20არ_20იძებნება_30',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1484',1,'']]],
  ['locator_20ისთვის_31',['locator ისთვის',['../md_docs_2api__reference_2display__api.html#autotoc_md175',1,'Service API (Service Locator-ისთვის)'],['../md_docs_2api__reference_2module__api.html#autotoc_md282',1,'Service API (Service Locator-ისთვის)']]],
  ['locator_20ის_20გამოყენება_32',['Service Locator-ის გამოყენება',['../md_docs_2convention_2communication__patterns.html#autotoc_md718',1,'']]],
  ['locator_20ი_20ჩემს_20სერვისს_33',['3. რატომ ვერ პოულობს Service Locator-ი ჩემს სერვისს?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1511',1,'']]],
  ['locator_20api_34',['Service Locator API',['../md_docs_2api__reference_2core__api.html#autotoc_md120',1,'']]],
  ['locator_20error_20handling_35',['3. Service Locator Error Handling',['../md_docs_2convention_2error__handling.html#autotoc_md770',1,'']]],
  ['locator_20pattern_36',['locator pattern',['../md_docs_2structure_2communication__patterns.html#autotoc_md1364',1,'1. Service Locator Pattern'],['../md_docs_2convention_2communication__patterns.html#autotoc_md701',1,'1. Service Locator Pattern']]],
  ['locator_20usage_37',['Service Locator Usage',['../md_docs_2convention_2communication__patterns.html#autotoc_md711',1,'']]],
  ['lock_5fbitmap_38',['lock_bitmap',['../structresource__pool__t.html#a69c076badb474d5b46959a1701935e8f',1,'resource_pool_t']]],
  ['log_20levels_39',['Log Levels',['../md_docs_2convention_2logging__standards.html#autotoc_md807',1,'']]],
  ['log_20message_20format_20standards_40',['Log Message Format Standards',['../md_docs_2convention_2logging__standards.html#autotoc_md826',1,'']]],
  ['logger_41',['logger',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md21',1,'Disable Logger'],['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md22',1,'Enable Logger']]],
  ['logger_20module_42',['logger module',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md17',1,'Disable Logger Module'],['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md16',1,'Enable Logger Module'],['../md_components_2modules_2utilities_2logger__module_2README.html',1,'Logger Module']]],
  ['logger_20module_20api_43',['Logger Module API',['../md_docs_2api__reference_2utility__api.html#autotoc_md465',1,'']]],
  ['logger_5fconsole_5foutput_5fenabled_44',['LOGGER_CONSOLE_OUTPUT_ENABLED',['../logger__module__config_8h.html#ac07384e32aa977e981ee16e260267e50',1,'logger_module_config.h']]],
  ['logger_5fdefault_5finstance_5fname_45',['LOGGER_DEFAULT_INSTANCE_NAME',['../logger__module__config_8h.html#a75d92458c36a0b39cdc223497ee9fc57',1,'logger_module_config.h']]],
  ['logger_5fevent_5fbuffer_5fsize_46',['LOGGER_EVENT_BUFFER_SIZE',['../logger__module__config_8h.html#a86c211625d4964b996fa89a04dcbcc44',1,'logger_module_config.h']]],
  ['logger_5fif_5fconsole_5foutput_47',['LOGGER_IF_CONSOLE_OUTPUT',['../logger__module__config_8h.html#ab48a8903d26363ce73662dbe50cc36fc',1,'logger_module_config.h']]],
  ['logger_5fif_5fenabled_48',['LOGGER_IF_ENABLED',['../logger__module__config_8h.html#ab55c2f1ca3d1d500997a31928ce9d40b',1,'logger_module_config.h']]],
  ['logger_5fif_5fruntime_5fcontrol_49',['LOGGER_IF_RUNTIME_CONTROL',['../logger__module__config_8h.html#a4ec4fb113c07e93e7f7da8870aede999',1,'logger_module_config.h']]],
  ['logger_5finstance_5fname_5fmax_5flen_50',['LOGGER_INSTANCE_NAME_MAX_LEN',['../logger__module__config_8h.html#a3d2b792852bc6dca45c3a24daeac84f1',1,'logger_module_config.h']]],
  ['logger_5fmax_5fevent_5fdata_5fsize_51',['LOGGER_MAX_EVENT_DATA_SIZE',['../logger__module__config_8h.html#a0203b63d11e3a6acb0f3eb289242d104',1,'logger_module_config.h']]],
  ['logger_5fmodule_2ec_52',['logger_module.c',['../logger__module_8c.html',1,'']]],
  ['logger_5fmodule_2eh_53',['logger_module.h',['../logger__module_8h.html',1,'']]],
  ['logger_5fmodule_5fconfig_2eh_54',['logger_module_config.h',['../logger__module__config_8h.html',1,'']]],
  ['logger_5fmodule_5fcreate_55',['logger_module_create',['../logger__module_8h.html#a43e3a3a59f4f51311e997fcd358871da',1,'logger_module_create(const cJSON *config):&#160;logger_module.c'],['../logger__module_8c.html#a43e3a3a59f4f51311e997fcd358871da',1,'logger_module_create(const cJSON *config):&#160;logger_module.c']]],
  ['logger_5fmodule_5fcreate_20const_20cjson_20config_56',['module_t *logger_module_create(const cJSON *config);',['../md_docs_2api__reference_2utility__api.html#autotoc_md466',1,'']]],
  ['logger_5fmodule_5fcreate_20const_20cjson_20config_20tt_57',['&lt;tt&gt;logger_module_create(const cJSON *config)&lt;/tt&gt;',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md31',1,'']]],
  ['logger_5fmodule_5fenabled_58',['LOGGER_MODULE_ENABLED',['../logger__module__config_8h.html#a1fad97e02379876ec92171a17a0a043c',1,'logger_module_config.h']]],
  ['logger_5fmodule_5flog_5ferror_20const_20char_20message_59',['esp_err_t logger_module_log_error(const char *message);',['../md_docs_2api__reference_2utility__api.html#autotoc_md469',1,'']]],
  ['logger_5fmodule_5flog_5finfo_20const_20char_20message_60',['esp_err_t logger_module_log_info(const char *message);',['../md_docs_2api__reference_2utility__api.html#autotoc_md467',1,'']]],
  ['logger_5fmodule_5flog_5fwarning_20const_20char_20message_61',['esp_err_t logger_module_log_warning(const char *message);',['../md_docs_2api__reference_2utility__api.html#autotoc_md468',1,'']]],
  ['logger_5fprivate_5fdata_5ft_62',['logger_private_data_t',['../structlogger__private__data__t.html',1,'']]],
  ['logger_5fruntime_5fcontrol_5fenabled_63',['LOGGER_RUNTIME_CONTROL_ENABLED',['../logger__module__config_8h.html#a61fc94d0902cdbb23ba3a87f0735d623',1,'logger_module_config.h']]],
  ['logging_64',['logging',['../md_docs_2structure_2error__handling__and__logging.html',1,'შეცდომების დამუშავება და ლოგირების სტანდარტები (Error Handling &amp; Logging)'],['../md_docs_2convention_2logging__standards.html#autotoc_md814',1,'1. Module Lifecycle Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md815',1,'2. Service Registration Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md816',1,'3. Configuration Parsing Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md817',1,'4. Hardware Operation Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md818',1,'5. Event Handling Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md819',1,'6. Error Context Logging'],['../md_docs_2design__decisions_2core__components.html#autotoc_md956',1,'6. Logging'],['../md_docs_2structure_2core__components.html#autotoc_md1390',1,'6. Logging'],['../md_docs_2security_2security__guidelines.html#autotoc_md1334',1,'Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md823',1,'Performance Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md820',1,'Runtime State Logging']]],
  ['logging_20ის_20სტანდარტები_65',['Logging-ის სტანდარტები',['../md_docs_2convention_2logging__standards.html',1,'']]],
  ['logging_20api_66',['Logging API',['../md_docs_2api__reference_2core__api.html#autotoc_md144',1,'']]],
  ['logging_20h_67',['[interfaces/include/logging.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md509',1,'']]],
  ['logging_20patterns_68',['Logging Patterns',['../md_docs_2convention_2logging__standards.html#autotoc_md813',1,'']]],
  ['logging_20standards_69',['Logging Standards',['../md_docs_2convention_2error__handling.html#autotoc_md776',1,'']]],
  ['logging_2eh_70',['logging.h',['../logging_8h.html',1,'']]],
  ['logic_71',['logic',['../md_docs_2convention_2error__handling.html#autotoc_md780',1,'1. Retry Logic'],['../md_docs_2convention_2configuration__management.html#autotoc_md739',1,'Fallback Logic']]]
];
