var searchData=
[
  ['of_20conduct_0',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['offs_1',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['offset_2',['offset',['../structmodule__dependency__t.html#a59c3ee80fc361f3a40271d7461c574f9',1,'module_dependency_t']]],
  ['old_5fstatus_3',['old_status',['../structsynapse__service__status__payload__t.html#a2de66c7d9d352c7a4cdbd394152f2702',1,'synapse_service_status_payload_t']]],
  ['on_20errors_4',['1. Proper Cleanup on Errors',['../md_docs_2convention_2error__handling.html#autotoc_md1279',1,'']]],
  ['operation_20error_20handling_5',['5. Hardware Operation Error Handling',['../md_docs_2convention_2error__handling.html#autotoc_md1277',1,'']]],
  ['operation_20logging_6',['4. Hardware Operation Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md1346',1,'']]],
  ['operation_20timing_7',['1. Operation Timing',['../md_docs_2convention_2logging__standards.html#autotoc_md1353',1,'']]],
  ['optimization_20guide_8',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['options_9',['Main Configuration Options',['../md_components_2modules_2utillities_2logger__module_2README.html#autotoc_md221',1,'']]],
  ['ota_10',['Flash-ში მონაცემების შენახვა (OTA)',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1606',1,'']]],
  ['ota_20განახლების_20სიგნირება_11',['ota განახლების სიგნირება',['../md_docs_2security_2security__best__practices.html#autotoc_md1787',1,'OTA განახლების სიგნირება'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1584',1,'OTA განახლების სიგნირება']]],
  ['ota_20და_20firmware_20security_12',['OTA და Firmware Security',['../md_docs_2security_2security__guidelines.html#autotoc_md1813',1,'']]],
  ['ota_20module_20api_13',['ota module api',['../md_docs_2api__reference_2system__api.html#autotoc_md689',1,'OTA Module API'],['../md_docs_2api__reference_2ota__api.html#autotoc_md549',1,'OTA Module API']]],
  ['ota_20over_20the_20air_20module_20api_20reference_14',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['ota_20update_20manager_15',['მოდული: OTA Update Manager',['../md_components_2modules_2system_2ota__update__manager_2README.html',1,'']]],
  ['ota_5fapi_5ft_16',['ota_api_t',['../structota__api__t.html',1,'']]],
  ['ota_5fapi_5ft_20tt_17',['5. Service API (&lt;tt&gt;ota_api_t&lt;/tt&gt;)',['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md178',1,'']]],
  ['ota_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_18',['static void ota_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2ota__api.html#autotoc_md556',1,'']]],
  ['ota_5finterface_2eh_19',['ota_interface.h',['../ota__interface_8h.html',1,'']]],
  ['ota_5fmodule_5fabort_20void_20',['esp_err_t ota_module_abort(void);',['../md_docs_2api__reference_2ota__api.html#autotoc_md553',1,'']]],
  ['ota_5fmodule_5fcreate_20const_20cjson_20config_21',['ota_module_create const cjson config',['../md_docs_2api__reference_2ota__api.html#autotoc_md550',1,'module_t *ota_module_create(const cJSON *config);'],['../md_docs_2api__reference_2system__api.html#autotoc_md690',1,'module_t *ota_module_create(const cJSON *config);']]],
  ['ota_5fmodule_5fget_5fstatus_20ota_5fstatus_5ft_20status_22',['ota_module_get_status ota_status_t status',['../md_docs_2api__reference_2system__api.html#autotoc_md692',1,'esp_err_t ota_module_get_status(ota_status_t *status);'],['../md_docs_2api__reference_2ota__api.html#autotoc_md552',1,'esp_err_t ota_module_get_status(ota_status_t *status);']]],
  ['ota_5fmodule_5fstart_5fupdate_20const_20char_20url_23',['ota_module_start_update const char url',['../md_docs_2api__reference_2system__api.html#autotoc_md691',1,'esp_err_t ota_module_start_update(const char *url);'],['../md_docs_2api__reference_2ota__api.html#autotoc_md551',1,'esp_err_t ota_module_start_update(const char *url);']]],
  ['ota_5fstatus_5ft_20status_24',['ota_status_t status',['../md_docs_2api__reference_2system__api.html#autotoc_md692',1,'esp_err_t ota_module_get_status(ota_status_t *status);'],['../md_docs_2api__reference_2ota__api.html#autotoc_md552',1,'esp_err_t ota_module_get_status(ota_status_t *status);']]],
  ['ota_5fupdate_5fmanager_2ec_25',['ota_update_manager.c',['../ota__update__manager_8c.html',1,'']]],
  ['ota_5fupdate_5fmanager_2eh_26',['ota_update_manager.h',['../ota__update__manager_8h.html',1,'']]],
  ['ota_5fupdate_5fmanager_5fconfig_5ft_27',['ota_update_manager_config_t',['../structota__update__manager__config__t.html',1,'']]],
  ['ota_5fupdate_5fmanager_5fcreate_28',['ota_update_manager_create',['../ota__update__manager_8c.html#a792fc2704dda3f70481bb8073fcc1c4e',1,'ota_update_manager_create(const cJSON *config):&#160;ota_update_manager.c'],['../ota__update__manager_8h.html#a792fc2704dda3f70481bb8073fcc1c4e',1,'ota_update_manager_create(const cJSON *config):&#160;ota_update_manager.c']]],
  ['ota_5fupdate_5fmanager_5fprivate_5fdata_5ft_29',['ota_update_manager_private_data_t',['../structota__update__manager__private__data__t.html',1,'']]],
  ['out_5fstatus_20tt_30',['&lt;tt&gt;esp_err_t synapse_service_get_status(const char *service_name, service_status_t *out_status);&lt;/tt&gt;',['../md_docs_2api__reference_2core__api.html#autotoc_md352',1,'']]],
  ['out_5fvalue_20tt_31',['out_value tt',['../md_docs_2api__reference_2utils__api.html#autotoc_md763',1,'&lt;tt&gt;bool synapse_config_get_bool_from_node(const char* tag, const cJSON *json_node, const char *key, bool *out_value);&lt;/tt&gt;'],['../md_docs_2api__reference_2utils__api.html#autotoc_md762',1,'&lt;tt&gt;bool synapse_config_get_int_from_node(const char* tag, const cJSON *json_node, const char *key, int *out_value);&lt;/tt&gt;'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md342',1,'&lt;tt&gt;esp_err_t synapse_config_get_bool(const char *key, bool *out_value)&lt;/tt&gt;'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md341',1,'&lt;tt&gt;esp_err_t synapse_config_get_int(const char *key, int *out_value)&lt;/tt&gt;']]],
  ['output_20format_32',['Output Format',['../md_components_2modules_2utillities_2logger__module_2README.html#autotoc_md235',1,'']]],
  ['over_20the_20air_20module_20api_20reference_33',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['overflow_20და_20task_20watchdog_34',['1. Stack Overflow და Task Watchdog',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1962',1,'']]],
  ['overflow_20in_20task_20tmr_20svc_20tt_20შეცდომით_35',['პრობლემა: სისტემის კრახი &lt;tt&gt;Stack Overflow in task Tmr Svc&lt;/tt&gt; შეცდომით',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1993',1,'']]],
  ['overview_36',['overview',['../index.html',1,'პროექტის მიმოხილვა (Project Overview)'],['../md_components_2modules_2utillities_2logger__module_2README.html#autotoc_md217',1,'Overview']]],
  ['owner_20tt_37',['owner tt',['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md633',1,'&lt;tt&gt;esp_err_t synapse_resource_lock(synapse_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;'],['../md_docs_2api__reference_2resource__manager__api.html#autotoc_md635',1,'&lt;tt&gt;esp_err_t synapse_resource_release(synapse_resource_type_t type, uint8_t resource_id, const char *owner)&lt;/tt&gt;']]],
  ['owner_5fnames_38',['owner_names',['../structresource__pool__t.html#aab904375ff53b6c6d69a4fb8678ba6e6',1,'resource_pool_t']]]
];
