var searchData=
[
  ['kconfig_20configuration_0',['Kconfig Configuration',['../md_components_2modules_2utillities_2logger__module_2README.html#autotoc_md220',1,'']]],
  ['key_20bool_20out_5fvalue_20tt_1',['key bool out_value tt',['../md_docs_2api__reference_2utils__api.html#autotoc_md753',1,'&lt;tt&gt;bool synapse_config_get_bool_from_node(const char* tag, const cJSON *json_node, const char *key, bool *out_value);&lt;/tt&gt;'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md333',1,'&lt;tt&gt;esp_err_t synapse_config_get_bool(const char *key, bool *out_value)&lt;/tt&gt;']]],
  ['key_20char_20buffer_20size_5ft_20buffer_5fsize_20tt_2',['&lt;tt&gt;esp_err_t synapse_config_get_string(const char *key, char *buffer, size_t buffer_size)&lt;/tt&gt;',['../md_docs_2api__reference_2configuration__api.html#autotoc_md331',1,'']]],
  ['key_20char_20dest_20size_5ft_20dest_5fsize_20tt_3',['&lt;tt&gt;bool synapse_config_get_string_from_node(const char* tag, const cJSON *json_node, const char *key, char *dest, size_t dest_size);&lt;/tt&gt;',['../md_docs_2api__reference_2utils__api.html#autotoc_md751',1,'']]],
  ['key_20int_20out_5fvalue_20tt_4',['key int out_value tt',['../md_docs_2api__reference_2utils__api.html#autotoc_md752',1,'&lt;tt&gt;bool synapse_config_get_int_from_node(const char* tag, const cJSON *json_node, const char *key, int *out_value);&lt;/tt&gt;'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md332',1,'&lt;tt&gt;esp_err_t synapse_config_get_int(const char *key, int *out_value)&lt;/tt&gt;']]],
  ['key_20value_20ოპერაციები_5',['key value ოპერაციები',['../md_docs_2api__reference_2storage__api.html#autotoc_md670',1,'🔑 Key-Value ოპერაციები'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md123',1,'Key-Value ოპერაციები']]]
];
