var searchData=
[
  ['ბაგია_0',['გამეორების ნაბიჯები (თუ ეს ბაგია)',['../md_docs_2contributing_2issue__template.html#autotoc_md816',1,'']]],
  ['ბენჩმარკების_20ჩატარების_20სახელმძღვანელო_20performance_20benchmarks_20guide_1',['ბენჩმარკების ჩატარების სახელმძღვანელო (Performance Benchmarks Guide)',['../md_docs_2performance_2performance__benchmarks.html',1,'']]],
  ['ბენჩმარკის_20ჩატარების_20ძირითადი_20ნაბიჯები_2',['ბენჩმარკის ჩატარების ძირითადი ნაბიჯები',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1401',1,'']]],
  ['ბილდიდან_3',['მოდულის გამორთვა ბილდიდან',['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md1263',1,'']]],
  ['ბილდის_20პრობლემები_4',['6. როგორ მოვაგვარო გარემოს ან ბილდის პრობლემები?',['../md_docs_2contributing_2faq.html#autotoc_md802',1,'']]],
  ['ბილდის_20შეცდომები_5',['1. ბილდის შეცდომები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1685',1,'']]],
  ['ბილდი_20და_20ფლეში_6',['4. ბილდი და ფლეში',['../md_docs_2tutorials_2getting__started.html#autotoc_md1755',1,'']]],
  ['ბრენჩები_7',['ძირითადი ბრენჩები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md729',1,'']]],
  ['ბრენჩინგის_20სტრატეგია_8',['ბრენჩინგის სტრატეგია',['../contributing_docs.html#contrib_branching_sec',1,'']]],
  ['ბრენჩის_20სახელდების_20წესები_9',['ბრენჩის სახელდების წესები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md731',1,'']]],
  ['ბრძანებები_10',['ბრძანებები',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md179',1,'ბრძანებები'],['../md_components_2modules_2utilities_2command__router_2README.html#autotoc_md152',1,'5. 🚀 ჩაშენებული ბრძანებები']]],
  ['ბრძანებები_20command_20line_20interface_11',['ბრძანებები command line interface',['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md4',1,'4. ⌨️ CLI ბრძანებები (Command Line Interface)'],['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md33',1,'4. ⌨️ CLI ბრძანებები (Command Line Interface)'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md187',1,'5. ⌨️ CLI ბრძანებები (Command Line Interface)'],['../md_components_2modules_2security_2security__status__reporter_2README.html#autotoc_md52',1,'5. ⌨️ CLI ბრძანებები (Command Line Interface)'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md26',1,'6. ⌨️ CLI ბრძანებები (Command Line Interface)'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md107',1,'7. ⌨️ CLI ბრძანებები (Command Line Interface)']]],
  ['ბრძანების_20გაგზავნა_12',['ბრძანების გაგზავნა',['../md_docs_2api__reference_2relay__api.html#autotoc_md534',1,'']]]
];
