var searchData=
[
  ['gdb_20და_20breakpoint_20ების_20გამოყენება_0',['3. GDB და Breakpoint-ების გამოყენება',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1640',1,'']]],
  ['generate_5fmqtt_5ftopics_1',['generate_mqtt_topics',['../namespacegenerate__mqtt__topics.html',1,'']]],
  ['generate_5ftopic_5fdefines_2',['generate_topic_defines',['../namespacegenerate__mqtt__topics.html#a155412cdaa45b16a0a5c3cfaf05f27c0',1,'generate_mqtt_topics']]],
  ['get_5fall_5fmodules_3',['get_all_modules',['../structsystem__manager__api__t.html#ab8bea01e2fe57fa651cf7a4b4185ff4a',1,'system_manager_api_t']]],
  ['get_5fbool_4',['get_bool',['../structstorage__api__t.html#a595d4fb163439815f05dbf38937bf3d8',1,'storage_api_t']]],
  ['get_5fdevice_5fid_5',['get_device_id',['../structdevice__identity__api__t.html#a6ce92f397b78dbb4ad6fc610966d1b64',1,'device_identity_api_t']]],
  ['get_5fdevice_5fid_20void_20tt_6',['&lt;tt&gt;const char* get_device_id(void);&lt;/tt&gt;',['../md_docs_2api__reference_2device__identity__api.html#autotoc_md269',1,'']]],
  ['get_5ffirmware_5fversion_7',['get_firmware_version',['../structdevice__identity__api__t.html#aa6ac323b1353ebb091c3407cc4cebf43',1,'device_identity_api_t']]],
  ['get_5ffirmware_5fversion_20void_20tt_8',['&lt;tt&gt;const char* get_firmware_version(void);&lt;/tt&gt;',['../md_docs_2api__reference_2device__identity__api.html#autotoc_md270',1,'']]],
  ['get_5fi32_9',['get_i32',['../structstorage__api__t.html#af6df514442f41d9eaf92fbeda1ee8390',1,'storage_api_t']]],
  ['get_5fstatus_10',['get_status',['../structmodule__t.html#ad91ac1dc0334cbe050b7d3babcf6c639',1,'module_t']]],
  ['get_5fstring_11',['get_string',['../structstorage__api__t.html#aa12449cfc6a8bd24760deedbe5419a7b',1,'storage_api_t']]],
  ['get_5fsystem_5fhealth_5freport_12',['get_system_health_report',['../structhealth__api__t.html#a50abcc64550890f281f6fcf4634fdf5b',1,'health_api_t']]],
  ['getting_20started_13',['სწრაფი სტარტი (Getting Started)',['../md_docs_2tutorials_2getting__started.html',1,'']]],
  ['github_20actions_20თან_20ავტომატური_20შემოწმება_14',['4. ინტეგრაცია GitHub Actions-თან (ავტომატური შემოწმება)',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md723',1,'']]],
  ['gitignore_15',['[.gitignore]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md634',1,'']]],
  ['global_20ცვლადები_16',['Global ცვლადები',['../md_docs_2convention_2variable__naming.html#autotoc_md996',1,'']]],
  ['glossary_20ტერმინები_17',['Glossary (ტერმინები)',['../md_docs_2glossary_2glossary__index.html',1,'']]],
  ['glossary_20—_20api_20code_18',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['glossary_20—_20architecture_19',['არქიტექტურული ტერმინები (Glossary — Architecture)',['../md_docs_2glossary_2glossary__architecture.html',1,'']]],
  ['glossary_20—_20configuration_20storage_20',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['glossary_20—_20security_20performance_21',['უსაფრთხოების და წარმადობის ტერმინები (Glossary — Security &amp; Performance)',['../md_docs_2glossary_2glossary__security.html',1,'']]],
  ['gpio_5fnum_22',['gpio_num',['../structled__blinker__config__t.html#ade55793ac3fbcd70b080e4a7cbbd90a0',1,'led_blinker_config_t']]],
  ['graceful_20degradation_23',['2. Graceful Degradation',['../md_docs_2convention_2error__handling.html#autotoc_md902',1,'']]],
  ['guide_24',['guide',['../md_docs_2performance_2performance__benchmarks.html',1,'ბენჩმარკების ჩატარების სახელმძღვანელო (Performance Benchmarks Guide)'],['../md_docs_2contributing_2contributing__guide.html',1,'კონტრიბუციის სახელმძღვანელო (Contributing Guide)'],['../md_docs_2performance_2performance__optimization.html',1,'ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)'],['../md_docs_2performance_2performance__resource__usage.html',1,'რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)'],['../md_docs_2contributing_2local__setup.html',1,'Synapse Local Setup Guide']]],
  ['guide_20დიბაგინგის_20სახელმძღვანელო_25',['Debugging Guide (დიბაგინგის სახელმძღვანელო)',['../md_docs_2troubleshooting_2debugging__guide.html',1,'']]],
  ['guidelines_26',['guidelines',['../md_docs_2security_2security__guidelines.html',1,'უსაფრთხოების სახელმძღვანელოები (Security Guidelines)'],['../md_docs_2contributing_2commit__message__guidelines.html',1,'Synapse Commit Message Guidelines'],['../md_docs_2contributing_2review__guidelines.html',1,'Synapse Review Guidelines']]]
];
