var searchData=
[
  ['✨_20ახალი_20ფუნქციები_20features_0',['✨ ახალი ფუნქციები features',['../md_docs_2changelog_2v5.html#autotoc_md897',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md885',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md882',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md877',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md873',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md868',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md863',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md858',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md854',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md849',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md845',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md841',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md893',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md836',1,'✨ ახალი ფუნქციები (Features)'],['../md_docs_2changelog_2v5.html#autotoc_md888',1,'✨ ახალი ფუნქციები (Features)']]],
  ['✨_20ახალი_20ფუნქციონალი_1',['✨ ახალი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md921',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md905',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md907',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md918',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md911',1,'✨ ახალი ფუნქციონალი'],['../md_docs_2changelog_2v5.html#autotoc_md914',1,'✨ ახალი ფუნქციონალი']]],
  ['✨_20გაუმჯობესებები_20improvements_2',['✨ გაუმჯობესებები improvements',['../md_docs_2changelog_2v5.html#autotoc_md842',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md879',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md869',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md864',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md859',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md850',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md846',1,'✨ გაუმჯობესებები (Improvements)'],['../md_docs_2changelog_2v5.html#autotoc_md837',1,'✨ გაუმჯობესებები (Improvements)']]],
  ['✨_20დამატებულია_3',['✨ დამატებულია',['../md_docs_2changelog_2v5.html#autotoc_md901',1,'']]],
  ['✨_20დამატებულია_20added_4',['✨ დამატებულია (Added)',['../md_docs_2changelog_2v5.html#autotoc_md832',1,'']]],
  ['✨_20დამატებული_5',['✨ დამატებული',['../md_docs_2changelog_2v6.html#autotoc_md926',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md930',1,'✨ დამატებული'],['../md_docs_2changelog_2v6.html#autotoc_md935',1,'✨ დამატებული']]],
  ['✨_20დამატებული_20ფუნქციონალი_20added_6',['✨ დამატებული ფუნქციონალი added',['../md_docs_2changelog_2v5.html#autotoc_md804',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md799',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md793',1,'✨ დამატებული ფუნქციონალი (Added)'],['../md_docs_2changelog_2v5.html#autotoc_md787',1,'✨ დამატებული ფუნქციონალი (Added)']]],
  ['✨_20added_20დამატებული_20ფუნქციონალი_7',['✨ added დამატებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md828',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md823',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md818',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md813',1,'✨ Added (დამატებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md808',1,'✨ Added (დამატებული ფუნქციონალი)']]]
];
