var searchData=
[
  ['ძირითადი_20არქიტექტურული_20პრინციპები_0',['ძირითადი არქიტექტურული პრინციპები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1054',1,'']]],
  ['ძირითადი_20ბრენჩები_1',['ძირითადი ბრენჩები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md659',1,'']]],
  ['ძირითადი_20დოკუმენტები_2',['ძირითადი დოკუმენტები',['../md_docs_2design__decisions_2design__decisions__index.html#autotoc_md1115',1,'']]],
  ['ძირითადი_20ინფორმაცია_3',['ძირითადი ინფორმაცია',['../md_docs_2contributing_2pull__request__template.html#autotoc_md782',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md742',1,'ძირითადი ინფორმაცია']]],
  ['ძირითადი_20კომპონენტები_4',['ძირითადი კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1055',1,'არქიტექტურული ფენები და ძირითადი კომპონენტები'],['../index.html#autotoc_md1595',1,'ძირითადი კომპონენტები'],['../md_docs_2structure_2core__components.html#autotoc_md1523',1,'ძირითადი კომპონენტები'],['../md_docs_2design__decisions_2core__components.html#autotoc_md1089',1,'ძირითადი კომპონენტები']]],
  ['ძირითადი_20ნაბიჯები_5',['ძირითადი ნაბიჯები',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1329',1,'ბენჩმარკის ჩატარების ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__websocket.html#autotoc_md1311',1,'ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__rest.html#autotoc_md1301',1,'ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__mqtt.html#autotoc_md1291',1,'ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__cloud.html#autotoc_md1273',1,'ძირითადი ნაბიჯები']]],
  ['ძირითადი_20პატერნები_6',['ძირითადი პატერნები',['../md_docs_2structure_2communication__patterns.html#autotoc_md1502',1,'']]],
  ['ძირითადი_20პრინციპები_7',['ძირითადი პრინციპები',['../md_docs_2convention_2function__naming.html#autotoc_md905',1,'ძირითადი პრინციპები'],['../md_docs_2convention_2variable__naming.html#autotoc_md987',1,'ძირითადი პრინციპები'],['../index.html#autotoc_md1594',1,'ძირითადი პრინციპები'],['../md_docs_2structure_2module__architecture.html#autotoc_md1581',1,'ძირითადი პრინციპები'],['../md_docs_2convention_2error__handling.html#autotoc_md882',1,'ძირითადი პრინციპები'],['../md_docs_2contributing_2code__of__conduct.html#autotoc_md673',1,'ძირითადი პრინციპები']]],
  ['ძირითადი_20პრინციპი_8',['ძირითადი პრინციპი',['../md_docs_2convention_2configuration__management.html#autotoc_md844',1,'']]],
  ['ძირითადი_20პრინციპი_3a_20მაქსიმალური_20იზოლაცია_9',['ძირითადი პრინციპი: მაქსიმალური იზოლაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md820',1,'']]],
  ['ძირითადი_20რეკომენდაციები_10',['ძირითადი რეკომენდაციები',['../md_docs_2security_2security__best__practices.html#autotoc_md1442',1,'ძირითადი რეკომენდაციები'],['../md_docs_2performance_2performance__best__practices.html#autotoc_md1343',1,'ძირითადი რეკომენდაციები']]],
  ['ძირითადი_20საქაღალდეების_20აღწერა_11',['ძირითადი საქაღალდეების აღწერა',['../md_docs_2structure_2directory__structure.html#autotoc_md1535',1,'']]],
  ['ძირითადი_20სახელმძღვანელოები_12',['ძირითადი სახელმძღვანელოები',['../md_docs_2contributing_2contributing__index.html#autotoc_md711',1,'']]],
  ['ძირითადი_20სინტაქსი_13',['1. ძირითადი სინტაქსი',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1414',1,'']]],
  ['ძირითადი_20სინტაქსი_3a_14',['1. ძირითადი სინტაქსი:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1015',1,'']]],
  ['ძირითადი_20სტრუქტურა_15',['ძირითადი სტრუქტურა',['../md_docs_2structure_2directory__structure.html#autotoc_md1534',1,'ძირითადი სტრუქტურა'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md687',1,'ძირითადი სტრუქტურა']]],
  ['ძირითადი_20ფუნქციები_16',['ძირითადი ფუნქციები',['../md_docs_2api__reference_2communication__api.html#autotoc_md197',1,'ძირითადი ფუნქციები'],['../md_docs_2api__reference_2communication__api.html#autotoc_md201',1,'ძირითადი ფუნქციები'],['../md_docs_2api__reference_2provisioning__api.html#autotoc_md440',1,'ძირითადი ფუნქციები'],['../md_docs_2api__reference_2communication__api.html#autotoc_md193',1,'ძირითადი ფუნქციები']]],
  ['ძირითადი_20ცვლილებები_17',['ძირითადი ცვლილებები',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md636',1,'']]],
  ['ძირითადი_20api_20ფუნქციები_18',['⚙️ ძირითადი API ფუნქციები',['../md_docs_2api__reference_2configuration__api.html#autotoc_md210',1,'']]]
];
