var searchData=
[
  ['name_0',['name',['../structmodule__t.html#afb5f2d3d957c8717f54cd8668e4cab5e',1,'module_t::name'],['../structservice__entry__t.html#a56a995a275a2f565f6677fc1ed136702',1,'service_entry_t::name']]],
  ['naming_1',['naming',['../md_docs_2convention_2logging__standards.html#autotoc_md967',1,'2. Parameter Naming'],['../md_docs_2convention_2variable__naming.html#autotoc_md1005',1,'Private Data Pointer Naming']]],
  ['naming_20და_20structure_20კონვენციების_20გამოყენება_2',['4. Naming და Structure კონვენციების გამოყენება',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1673',1,'']]],
  ['naming_20და_20structure_20სტანდარტები_3',['6. როგორ დავიცვა naming და structure სტანდარტები?',['../md_docs_2structure_2faq.html#autotoc_md1562',1,'']]],
  ['naming_20structure_4',['naming structure',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1318',1,'1. API Naming &amp; Structure'],['../md_docs_2api__reference_2ota__api.html#autotoc_md432',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2utility__api.html#autotoc_md582',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2time__sync__api.html#autotoc_md569',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2system__api.html#autotoc_md552',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2sensor__api.html#autotoc_md516',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2provisioning__api.html#autotoc_md471',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2version__api.html#autotoc_md595',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2wifi__api.html#autotoc_md605',1,'Naming &amp; Structure'],['../md_docs_2convention_2convention__index.html#autotoc_md878',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2actuators__api.html#autotoc_md166',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2mqtt__api.html#autotoc_md416',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2module__api.html#autotoc_md408',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md381',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2health__monitor__api.html#autotoc_md365',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2event__api.html#autotoc_md340',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md320',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2display__api.html#autotoc_md301',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2device__identity__api.html#autotoc_md272',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2custom__api.html#autotoc_md261',1,'Naming &amp; Structure']]],
  ['naming_20structure_20კონვენციები_5',['📜 Naming &amp; Structure კონვენციები',['../md_docs_2api__reference_2communication__api.html#autotoc_md203',1,'']]],
  ['network_20diagnostics_6',['6. Network Diagnostics',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1607',1,'']]],
  ['network_20parameters_7',['4. Network Parameters',['../md_docs_2convention_2configuration__management.html#autotoc_md872',1,'']]],
  ['next_8',['next',['../structevent__subscription__node__t.html#a21fc6eec18e9253a574a7bc1bd30db99',1,'event_subscription_node_t']]],
  ['nfc_20provisioning_20api_9',['NFC Provisioning API',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md465',1,'']]],
  ['nfc_5fprov_5fmodule_5fcreate_20const_20cjson_20config_10',['module_t *nfc_prov_module_create(const cJSON*config)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md466',1,'']]],
  ['nfc_5fprov_5fmodule_5fset_5fcredentials_20module_5ft_20module_20const_20char_20ssid_20const_20char_20password_11',['esp_err_t nfc_prov_module_set_credentials(module_t *module, const char*ssid, const char *password)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md469',1,'']]],
  ['nfc_5fprov_5fmodule_5fstart_20module_5ft_20module_12',['esp_err_t nfc_prov_module_start(module_t *module)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md467',1,'']]],
  ['nfc_5fprov_5fmodule_5fstop_20module_5ft_20module_13',['esp_err_t nfc_prov_module_stop(module_t *module)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md468',1,'']]],
  ['not_20found_14',['პრობლემა: include file not found',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1615',1,'']]],
  ['notation_15',['notation',['../md_docs_2api__reference_2configuration__api.html#autotoc_md208',1,'🔑 გასაღების ფორმატი (Dot-Notation)'],['../md_docs_2tutorials_2system__configuration.html#autotoc_md1718',1,'4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)']]],
  ['notes_16',['Development Notes',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md122',1,'']]],
  ['now_17',['3. Communication Integration (MQTT/WiFi/ESP-NOW)',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1320',1,'']]],
  ['now_20service_20api_18',['⚡ ESP-NOW Service API',['../md_docs_2api__reference_2communication__api.html#autotoc_md200',1,'']]],
  ['nvs_20დან_20სტრიქონის_20წაკითხვა_19',['NVS-დან სტრიქონის წაკითხვა',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1234',1,'']]],
  ['nvs_20ში_20სტრიქონის_20შენახვა_20',['NVS-ში სტრიქონის შენახვა',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1233',1,'']]]
];
