var searchData=
[
  ['წაკითხვა_0',['წაკითხვა',['../md_docs_2api__reference_2configuration__api.html#autotoc_md288',1,'გლობალური პარამეტრის წაკითხვა'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md289',1,'მოდულის პარამეტრის წაკითხვა'],['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1294',1,'NVS-დან სტრიქონის წაკითხვა']]],
  ['წარმადობისა_20და_20რესურსების_20არქიტექტურული_20კომპრომისები_20performance_20trade_20offs_1',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['წარმადობისთვის_20performance_20best_20practices_2',['საუკეთესო პრაქტიკები წარმადობისთვის (Performance Best Practices)',['../md_docs_2performance_2performance__best__practices.html',1,'']]],
  ['წარმადობის_20სახელმძღვანელო_3',['Performance (წარმადობის სახელმძღვანელო)',['../md_docs_2performance_2performance__index.html',1,'']]],
  ['წარმადობის_20ტერმინები_20glossary_20—_20security_20performance_4',['უსაფრთხოების და წარმადობის ტერმინები (Glossary — Security &amp; Performance)',['../md_docs_2glossary_2glossary__security.html',1,'']]],
  ['წაშლილია_5',['წაშლილია',['../md_docs_2changelog_2CHANGELOG__2025-06-28.html#autotoc_md735',1,'']]],
  ['წერის_20წესები_6',['წერის წესები',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md775',1,'დეტალური აღწერის წერის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md773',1,'სათაურის წერის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md777',1,'Footer-ის წერის წესები']]],
  ['წესები_7',['წესები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md745',1,'ბრენჩის სახელდების წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md775',1,'დეტალური აღწერის წერის წესები'],['../md_docs_2convention_2communication__patterns.html',1,'კომუნიკაციის პატერნების წესები'],['../md_docs_2convention_2configuration__management.html',1,'კონფიგურაციის მართვის წესები'],['../md_docs_2convention_2module__structure.html',1,'მოდულის სტრუქტურის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md773',1,'სათაურის წერის წესები'],['../md_docs_2structure_2communication__patterns.html#autotoc_md1548',1,'სწორი გამოყენების წესები'],['../md_docs_2convention_2function__naming.html',1,'ფუნქციების დასახელების წესები'],['../md_docs_2convention_2variable__naming.html',1,'ცვლადების დასახელების წესები'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md902',1,'5. Doxygen ტეგების გამოყენების წესები'],['../contributing_docs.html#contrib_commit_sec',1,'Commit Message-ის წესები'],['../md_docs_2convention_2error__handling.html',1,'Error Handling-ის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md777',1,'Footer-ის წერის წესები']]],
  ['წესის_20პარამეტრები_20tt_20alarms_20tt_20ობიექტი_8',['3.1. განგაშის წესის პარამეტრები (&lt;tt&gt;alarms&lt;/tt&gt; ობიექტი)',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md94',1,'']]],
  ['წესი_9',['წესი',['../md_docs_2security_2security__index.html#autotoc_md1528',1,'გამოყენების წესი'],['../md_docs_2performance_2performance__index.html#autotoc_md1431',1,'გამოყენების წესი'],['../md_docs_2integration_2integration__index.html#autotoc_md1345',1,'გამოყენების წესი'],['../md_docs_2glossary_2glossary__index.html#autotoc_md1322',1,'გამოყენების წესი'],['../md_docs_2convention_2initialization__levels.html#autotoc_md992',1,'📜 ოქროს წესი']]],
  ['წვდომა_20კოდიდან_20dot_20notation_10',['4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1758',1,'']]],
  ['წვდომის_20მაგალითები_11',['კონფიგურაციის წვდომის მაგალითები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1559',1,'']]],
  ['წვდომის_20პატერნები_12',['კონფიგურაციის წვდომის პატერნები',['../md_docs_2convention_2configuration__management.html#autotoc_md933',1,'']]],
  ['წინაპირობები_20და_20tt_20menuconfig_20tt_13',['წინაპირობები და tt menuconfig tt',['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md128',1,'2. წინაპირობები და &lt;tt&gt;menuconfig&lt;/tt&gt;'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md136',1,'2. წინაპირობები და &lt;tt&gt;menuconfig&lt;/tt&gt;'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md150',1,'7. ❗ წინაპირობები და &lt;tt&gt;menuconfig&lt;/tt&gt;']]],
  ['წყაროები_14',['წყაროები',['../md_docs_2convention_2configuration__management.html#autotoc_md932',1,'კონფიგურაციის სტრუქტურა და წყაროები'],['../md_docs_2structure_2configuration__flow.html#autotoc_md1556',1,'კონფიგურაციის წყაროები']]]
];
