var searchData=
[
  ['💡_20ახალი_20ტესტის_20დამატების_20მაგალითი_0',['6. 💡 ახალი ტესტის დამატების მაგალითი',['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md36',1,'']]],
  ['💡_20გამოყენება_20და_20უსაფრთხოების_20ჩართვა_1',['6. 💡 გამოყენება და უსაფრთხოების ჩართვა',['../md_components_2modules_2security_2security__status__reporter_2README.html#autotoc_md100',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_2',['💡 გამოყენების მაგალითი',['../md_docs_2api__reference_2storage__api.html#autotoc_md662',1,'💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2time__sync_2README.html#autotoc_md187',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2displays_2ssd1306__driver_2README.html#autotoc_md43',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2i2c__bus_2README.html#autotoc_md58',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2testing_2sensor__simulator_2README.html#autotoc_md201',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2sn74hc595n__writer_2README.html#autotoc_md85',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2spi__bus_2README.html#autotoc_md92',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2system__timer_2README.html#autotoc_md256',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md127',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md194',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2command__router_2README.html#autotoc_md214',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2drivers_2mcp23017__io__expander_2README.html#autotoc_md69',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md172',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md180',1,'7. 💡 გამოყენების მაგალითი']]],
  ['💡_20გამოყენების_20მაგალითი_20და_20ტესტირება_3',['5. 💡 გამოყენების მაგალითი და ტესტირება',['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md110',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_20მოთხოვნა_20პასუხი_4',['💡 გამოყენების მაგალითი მოთხოვნა პასუხი',['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md28',1,'7. 💡 გამოყენების მაგალითი (მოთხოვნა-პასუხი)'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md163',1,'8. 💡 გამოყენების მაგალითი (მოთხოვნა-პასუხი)']]],
  ['💡_20გამოყენების_20მაგალითი_20tt_20sensor_5faggregator_20tt_20თან_20ინტეგრაცია_5',['5. 💡 გამოყენების მაგალითი (&lt;tt&gt;sensor_aggregator&lt;/tt&gt;-თან ინტეგრაცია)',['../md_components_2modules_2sensors_2time__of__flight__sensor_2README.html#autotoc_md118',1,'']]],
  ['💡_20გამოყენების_20მაგალითი_20tt_20ui_5fmanager_20tt_20თან_6',['6. 💡 გამოყენების მაგალითი (&lt;tt&gt;ui_manager&lt;/tt&gt;-თან)',['../md_components_2modules_2drivers_2rotary__encoder__input_2README.html#autotoc_md79',1,'']]],
  ['💡_20გამოყენების_20პატერნი_3a_20კონფლიქტისგან_20დაცული_20რეგისტრაცია_7',['💡 გამოყენების პატერნი: კონფლიქტისგან დაცული რეგისტრაცია',['../md_docs_2api__reference_2command__router__api.html#autotoc_md309',1,'']]],
  ['💡_20გამოყენების_20სცენარები_8',['6. 💡 გამოყენების სცენარები',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md137',1,'']]],
  ['💡_20მოდული_3a_20tt_20rgb_5fled_5findicator_20tt_9',['💡 მოდული: &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['💡_20პრაქტიკული_20მაგალითი_3a_20tt_20wifi_5fmanager_20tt_20და_20tt_20command_5frouter_20tt_10',['💡 პრაქტიკული მაგალითი: &lt;tt&gt;wifi_manager&lt;/tt&gt; და &lt;tt&gt;command_router&lt;/tt&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1193',1,'']]],
  ['💡_20mqtt_20api_20ს_20გამოყენების_20მაგალითი_11',['💡 MQTT API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md319',1,'']]],
  ['💡_20strong_20დონე_204_3a_20აპლიკაციის_20ლოგიკა_20და_20პერიფერია_2060_2079_20strong_12',['💡 &lt;strong&gt;დონე 4: აპლიკაციის ლოგიკა და პერიფერია (60-79)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1202',1,'']]],
  ['💡_20wifi_20api_20ს_20გამოყენების_20მაგალითი_13',['💡 WiFi API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md315',1,'']]]
];
