var searchData=
[
  ['7_20დამატებითი_20რესურსები_0',['7. დამატებითი რესურსები',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1748',1,'']]],
  ['7_20დოკუმენტაციის_20განახლება_1',['7. დოკუმენტაციის განახლება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1777',1,'']]],
  ['7_20როგორ_20გამოვასწორო_20რესურსების_20გაჟონვა_20memory_20leak_2',['7. როგორ გამოვასწორო რესურსების გაჟონვა (memory leak)?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1726',1,'']]],
  ['7_20როგორ_20ხდება_20შეცდომების_20დამუშავება_20და_20ლოგირება_3',['7. როგორ ხდება შეცდომების დამუშავება და ლოგირება?',['../md_docs_2structure_2faq.html#autotoc_md1635',1,'']]],
  ['7_20სად_20ვიპოვო_20დოკუმენტაციის_20სტრუქტურის_20და_20სტანდარტების_20შესახებ_20ინფორმაცია_4',['7. სად ვიპოვო დოკუმენტაციის სტრუქტურის და სტანდარტების შესახებ ინფორმაცია?',['../md_docs_2contributing_2faq.html#autotoc_md803',1,'']]],
  ['7_20ტექნიკური_20იმპლემენტაციის_20დეტალები_5',['7. ტექნიკური იმპლემენტაციის დეტალები',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md189',1,'']]],
  ['7_20⌨️_20cli_20ბრძანებები_20command_20line_20interface_6',['7. ⌨️ CLI ბრძანებები (Command Line Interface)',['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md107',1,'']]],
  ['7_20❗_20მნიშვნელოვანი_20შენიშვნები_7',['7 ❗ მნიშვნელოვანი შენიშვნები',['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md7',1,'7. ❗ მნიშვნელოვანი შენიშვნები'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md83',1,'7. ❗ მნიშვნელოვანი შენიშვნები'],['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md36',1,'7. ❗ მნიშვნელოვანი შენიშვნები'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md46',1,'7. ❗ მნიშვნელოვანი შენიშვნები']]],
  ['7_20💡_20გამოყენების_20მაგალითი_8',['7 💡 გამოყენების მაგალითი',['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md117',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md125',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md134',1,'7. 💡 გამოყენების მაგალითი']]],
  ['7_20💡_20გამოყენების_20მაგალითი_20მოთხოვნა_20პასუხი_9',['7. 💡 გამოყენების მაგალითი (მოთხოვნა-პასუხი)',['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md27',1,'']]],
  ['7_20🤝_20ინტეგრაცია_20tt_20self_5ftest_5fmanager_20tt_20თან_10',['7. 🤝 ინტეგრაცია &lt;tt&gt;self_test_manager&lt;/tt&gt;-თან',['../md_components_2modules_2security_2security__status__reporter_2README.html#autotoc_md54',1,'']]],
  ['7_20🩺_20პრობლემების_20მოგვარება_20troubleshooting_11',['7. 🩺 პრობლემების მოგვარება (Troubleshooting)',['../md_components_2modules_2utilities_2command__router_2README.html#autotoc_md154',1,'']]],
  ['7_20assertion_20ები_20და_20error_20checking_12',['7. Assertion-ები და Error Checking',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1716',1,'']]],
  ['7_20best_20practices_13',['7. Best Practices',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1738',1,'']]],
  ['7_20performance_20metrics_14',['7. Performance Metrics',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1680',1,'']]],
  ['7_20testability_15',['7. Testability',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1396',1,'']]],
  ['7_20troubleshooting_16',['7. Troubleshooting',['../md_docs_2tutorials_2integration__example.html#autotoc_md1767',1,'']]],
  ['79_20strong_17',['💡 &lt;strong&gt;დონე 4: აპლიკაციის ლოგიკა და პერიფერია (60-79)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md1009',1,'']]]
];
