var searchData=
[
  ['წაკითხვა_0',['წაკითხვა',['../md_docs_2api__reference_2configuration__api.html#autotoc_md82',1,'გლობალური პარამეტრის წაკითხვა'],['../md_docs_2api__reference_2configuration__api.html#autotoc_md83',1,'მოდულის პარამეტრის წაკითხვა'],['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1367',1,'NVS-დან სტრიქონის წაკითხვა']]],
  ['წარმადობისა_20და_20რესურსების_20არქიტექტურული_20კომპრომისები_20performance_20trade_20offs_1',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['წარმადობისთვის_20performance_20best_20practices_2',['საუკეთესო პრაქტიკები წარმადობისთვის (Performance Best Practices)',['../md_docs_2performance_2performance__best__practices.html',1,'']]],
  ['წარმადობის_20სახელმძღვანელო_3',['Performance (წარმადობის სახელმძღვანელო)',['../md_docs_2performance_2performance__index.html',1,'']]],
  ['წარმადობის_20ტერმინები_20glossary_20—_20security_20performance_4',['უსაფრთხოების და წარმადობის ტერმინები (Glossary — Security &amp; Performance)',['../md_docs_2glossary_2glossary__security.html',1,'']]],
  ['წერის_20წესები_5',['წერის წესები',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md843',1,'დეტალური აღწერის წერის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md841',1,'სათაურის წერის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md845',1,'Footer-ის წერის წესები']]],
  ['წესები_6',['წესები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md813',1,'ბრენჩის სახელდების წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md843',1,'დეტალური აღწერის წერის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md841',1,'სათაურის წერის წესები'],['../md_docs_2structure_2communication__patterns.html#autotoc_md1608',1,'სწორი გამოყენების წესები'],['../md_docs_2convention_2function__naming.html',1,'ფუნქციების დასახელების წესები'],['../md_docs_2convention_2variable__naming.html',1,'ცვლადების დასახელების წესები'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md981',1,'5. Doxygen ტეგების გამოყენების წესები'],['../contributing_docs.html#contrib_commit_sec',1,'Commit Message-ის წესები'],['../md_docs_2convention_2error__handling.html',1,'Error Handling-ის წესები'],['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md845',1,'Footer-ის წერის წესები']]],
  ['წესები_20v2_200_7',['კომუნიკაციის პატერნების წესები (v2.0)',['../md_docs_2convention_2communication__patterns.html',1,'']]],
  ['წესი_8',['წესი',['../md_docs_2glossary_2glossary__index.html#autotoc_md1395',1,'გამოყენების წესი'],['../md_docs_2integration_2integration__index.html#autotoc_md1418',1,'გამოყენების წესი'],['../md_docs_2performance_2performance__index.html#autotoc_md1504',1,'გამოყენების წესი'],['../md_docs_2security_2security__index.html#autotoc_md1588',1,'გამოყენების წესი'],['../md_docs_2convention_2initialization__levels.html#autotoc_md1072',1,'📜 ოქროს წესი']]],
  ['წვდომა_20კოდიდან_20dot_20notation_9',['4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1855',1,'']]],
  ['წვდომა_20სხვა_20მოდულებიდან_10',['5. 🌐 კონფიგურაციაზე წვდომა სხვა მოდულებიდან',['../md_docs_2convention_2configuration__management.html#autotoc_md1017',1,'']]],
  ['წვდომა_3a_20facade_20pattern_20tt_20synapse_20h_20tt_11',['ფრეიმვორქის API-სთან წვდომა: Facade Pattern (&lt;tt&gt;synapse.h&lt;/tt&gt;)',['../md_docs_2design__decisions_2communication__choices.html#autotoc_md1207',1,'']]],
  ['წვდომის_20მაგალითები_12',['კონფიგურაციის წვდომის მაგალითები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1619',1,'']]],
  ['წყაროები_13',['კონფიგურაციის წყაროები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1616',1,'']]],
  ['წყაროები_20და_20იერარქია_14',['2. 📂 კონფიგურაციის წყაროები და იერარქია',['../md_docs_2convention_2configuration__management.html#autotoc_md1012',1,'']]]
];
