var searchData=
[
  ['ობიექტის_20აღწერა_0',['3. მოდულის კონფიგურაციის ობიექტის აღწერა',['../md_docs_2tutorials_2system__configuration.html#autotoc_md2019',1,'']]],
  ['ობიექტის_20პარამეტრები_1',['ობიექტის პარამეტრები',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md144',1,'3.2. &lt;tt&gt;layers&lt;/tt&gt; ობიექტის პარამეტრები'],['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md107',1,'3.2. &lt;tt&gt;sensors_to_aggregate&lt;/tt&gt; ობიექტის პარამეტრები'],['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md145',1,'3.3. &lt;tt&gt;actions&lt;/tt&gt; ობიექტის პარამეტრები']]],
  ['ობიექტი_2',['ობიექტი',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md133',1,'3.1. განგაშის წესის პარამეტრები (&lt;tt&gt;alarms&lt;/tt&gt; ობიექტი)'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md134',1,'3.2. მოქმედებების პარამეტრები (&lt;tt&gt;actions&lt;/tt&gt; ობიექტი)']]],
  ['ოპერაციების_20მართვის_20პატერნი_20promise_20pattern_3',['asynchronous ოპერაციების მართვის პატერნი (Promise Pattern)',['../md_docs_2convention_2promise__pattern.html',1,'']]],
  ['ოპერაციები_4',['ოპერაციები',['../md_docs_2api__reference_2storage__api.html#autotoc_md676',1,'🔑 Key-Value ოპერაციები'],['../md_docs_2api__reference_2storage__api.html#autotoc_md678',1,'🗂️ ფაილური ოპერაციები'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md125',1,'Key-Value ოპერაციები']]],
  ['ოპერაციები_20მხარდაჭერილია_20spiffs_20და_20sd_20card_20backend_20ებზე_5',['ფაილური ოპერაციები (მხარდაჭერილია SPIFFS და SD Card backend-ებზე)',['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md126',1,'']]],
  ['ოპტიმიზაცია_6',['ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1691',1,'კოდის ოპტიმიზაცია'],['../md_docs_2performance_2performance__optimization.html#autotoc_md1693',1,'კონფიგურაციის ოპტიმიზაცია'],['../md_docs_2performance_2performance__optimization.html#autotoc_md1695',1,'მოდულების ოპტიმიზაცია'],['../md_docs_2performance_2performance__display.html#autotoc_md1672',1,'Refresh interval-ის ოპტიმიზაცია']]],
  ['ოპტიმიზაცია_20და_20რესურსების_20მართვა_7',['6. ოპტიმიზაცია და რესურსების მართვა',['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1970',1,'']]],
  ['ოპტიმიზაცია_20performance_20—_20display_20modules_8',['ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)',['../md_docs_2performance_2performance__display.html',1,'']]],
  ['ოპტიმიზაციის_20რეკომენდაციები_9',['ოპტიმიზაციის რეკომენდაციები',['../md_docs_2performance_2performance__display.html#autotoc_md1669',1,'']]],
  ['ოპტიმიზაციის_20სახელმძღვანელოები_20performance_20optimization_20guide_10',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['ოქროს_20წესი_11',['📜 ოქროს წესი',['../md_docs_2convention_2initialization__levels.html#autotoc_md1227',1,'']]]
];
