var searchData=
[
  ['ძირითადი_20არქიტექტურული_20პრინციპები_0',['ძირითადი არქიტექტურული პრინციპები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1303',1,'']]],
  ['ძირითადი_20ბრენჩები_1',['ძირითადი ბრენჩები',['../md_docs_2contributing_2branching__strategy.html#autotoc_md932',1,'']]],
  ['ძირითადი_20დოკუმენტები_2',['ძირითადი დოკუმენტები',['../md_docs_2design__decisions_2design__decisions__index.html#autotoc_md1364',1,'']]],
  ['ძირითადი_20ინფორმაცია_3',['ძირითადი ინფორმაცია',['../md_docs_2contributing_2pull__request__template.html#autotoc_md1055',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md1015',1,'ძირითადი ინფორმაცია']]],
  ['ძირითადი_20კომპონენტები_4',['ძირითადი კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1304',1,'არქიტექტურული ფენები და ძირითადი კომპონენტები'],['../md_docs_2structure_2core__components.html#autotoc_md1755',1,'ძირითადი კომპონენტები'],['../index.html#autotoc_md1826',1,'ძირითადი კომპონენტები'],['../md_docs_2design__decisions_2core__components.html#autotoc_md1338',1,'ძირითადი კომპონენტები']]],
  ['ძირითადი_20კონფიგურაციის_20პარამეტრები_5',['3.1. ძირითადი კონფიგურაციის პარამეტრები',['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md106',1,'']]],
  ['ძირითადი_20ნაბიჯები_6',['ძირითადი ნაბიჯები',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1578',1,'ბენჩმარკის ჩატარების ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__websocket.html#autotoc_md1560',1,'ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__rest.html#autotoc_md1550',1,'ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__mqtt.html#autotoc_md1540',1,'ძირითადი ნაბიჯები'],['../md_docs_2integration_2integration__cloud.html#autotoc_md1522',1,'ძირითადი ნაბიჯები']]],
  ['ძირითადი_20პატერნები_7',['ძირითადი პატერნები',['../md_docs_2structure_2communication__patterns.html#autotoc_md1734',1,'']]],
  ['ძირითადი_20პატერნი_8',['სამი ძირითადი პატერნი',['../md_docs_2convention_2communication__patterns.html#autotoc_md1094',1,'']]],
  ['ძირითადი_20პრინციპები_9',['ძირითადი პრინციპები',['../md_docs_2convention_2error__handling.html#autotoc_md1136',1,'ძირითადი პრინციპები'],['../md_docs_2convention_2function__naming.html#autotoc_md1159',1,'ძირითადი პრინციპები'],['../md_docs_2convention_2variable__naming.html#autotoc_md1236',1,'ძირითადი პრინციპები'],['../index.html#autotoc_md1825',1,'ძირითადი პრინციპები'],['../md_docs_2structure_2module__architecture.html#autotoc_md1813',1,'ძირითადი პრინციპები'],['../md_docs_2contributing_2code__of__conduct.html#autotoc_md946',1,'ძირითადი პრინციპები']]],
  ['ძირითადი_20პრინციპი_10',['ძირითადი პრინციპი',['../md_docs_2convention_2configuration__management.html#autotoc_md1120',1,'']]],
  ['ძირითადი_20პრინციპი_3a_20მაქსიმალური_20იზოლაცია_11',['ძირითადი პრინციპი: მაქსიმალური იზოლაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md1093',1,'']]],
  ['ძირითადი_20რეკომენდაციები_12',['ძირითადი რეკომენდაციები',['../md_docs_2security_2security__best__practices.html#autotoc_md1674',1,'ძირითადი რეკომენდაციები'],['../md_docs_2performance_2performance__best__practices.html#autotoc_md1592',1,'ძირითადი რეკომენდაციები']]],
  ['ძირითადი_20საქაღალდეების_20აღწერა_13',['ძირითადი საქაღალდეების აღწერა',['../md_docs_2structure_2directory__structure.html#autotoc_md1767',1,'']]],
  ['ძირითადი_20სახელმძღვანელოები_14',['ძირითადი სახელმძღვანელოები',['../md_docs_2contributing_2contributing__index.html#autotoc_md984',1,'']]],
  ['ძირითადი_20სინტაქსი_3a_15',['1. ძირითადი სინტაქსი:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1264',1,'']]],
  ['ძირითადი_20სტრუქტურა_16',['ძირითადი სტრუქტურა',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md960',1,'ძირითადი სტრუქტურა'],['../md_docs_2structure_2directory__structure.html#autotoc_md1766',1,'ძირითადი სტრუქტურა']]],
  ['ძირითადი_20ფუნქციები_17',['ძირითადი ფუნქციები',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md557',1,'ძირითადი ფუნქციები'],['../md_docs_2api__reference_2communication__api.html#autotoc_md322',1,'ძირითადი ფუნქციები'],['../md_docs_2api__reference_2communication__api.html#autotoc_md318',1,'ძირითადი ფუნქციები'],['../md_docs_2api__reference_2communication__api.html#autotoc_md314',1,'ძირითადი ფუნქციები']]],
  ['ძირითადი_20ცვლილებები_18',['ძირითადი ცვლილებები',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md770',1,'']]],
  ['ძირითადი_20api_20ფუნქციები_19',['⚙️ ძირითადი API ფუნქციები',['../md_docs_2api__reference_2configuration__api.html#autotoc_md331',1,'']]]
];
