var searchData=
[
  ['📢_20გამოქვეყნებული_20ივენთები_0',['📢 გამოქვეყნებული ივენთები',['../md_components_2modules_2testing_2sensor__simulator_2README.html#autotoc_md165',1,'4. 📢 გამოქვეყნებული ივენთები'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md158',1,'5. 📢 გამოქვეყნებული ივენთები']]],
  ['📢_20გამოქვეყნებული_20ივენთი_1',['4. 📢 გამოქვეყნებული ივენთი',['../md_components_2modules_2drivers_2button__input_2README.html#autotoc_md48',1,'']]],
  ['📢_20დამუშავებული_20ივენთები_2',['6. 📢 დამუშავებული ივენთები',['../md_components_2modules_2utilities_2ui__manager_2README.html#autotoc_md231',1,'']]],
  ['📢_20ივენთების_20დამუშავება_3',['📢 ივენთების დამუშავება',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md101',1,'5. 📢 ივენთების დამუშავება'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md214',1,'6. 📢 ივენთების დამუშავება']]],
  ['📢_20ივენთების_20მოდელი_4',['📢 ივენთების მოდელი',['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md82',1,'4. 📢 ივენთების მოდელი'],['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md6',1,'6. 📢 ივენთების მოდელი']]],
  ['📢_20ივენთების_20უნივერსალური_20მოდელი_5',['5. 📢 ივენთების უნივერსალური მოდელი',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md113',1,'']]],
  ['📢_20ივენთები_20events_6',['📢 ივენთები events',['../md_docs_2api__reference_2relay__api.html#autotoc_md568',1,'3. 📢 ივენთები (Events)'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md23',1,'4. 📢 ივენთები (Events)'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md62',1,'5. 📢 ივენთები (Events)'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md123',1,'5. 📢 ივენთები (Events)']]]
];
