var searchData=
[
  ['🔄_20მოდული_3a_20tt_20mcp23017_5fio_5fexpander_20tt_0',['🔄 მოდული: &lt;tt&gt;mcp23017_io_expander&lt;/tt&gt;',['../md_components_2modules_2drivers_2mcp23017__io__expander_2README.html',1,'']]],
  ['🔄_20სრული_20სამუშაო_20პროცესი_20workflow_1',['5. 🔄 სრული სამუშაო პროცესი (Workflow)',['../md_docs_2tools_2create__module.html#autotoc_md1896',1,'']]],
  ['🔄_20შეცვლილია_20changed_2',['🔄 შეცვლილია (Changed)',['../md_docs_2changelog_2v5.html#autotoc_md867',1,'']]],
  ['🔄_20შეცვლილი_3',['🔄 შეცვლილი',['../md_docs_2changelog_2v7.html#autotoc_md986',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md970',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md965',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md961',1,'🔄 შეცვლილი']]],
  ['🔄_20შეცვლილი_20და_20გაუმჯობესებული_20ფუნქციონალი_20changed_4',['🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი changed',['../md_docs_2changelog_2v5.html#autotoc_md825',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md839',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md834',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md828',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)']]],
  ['🔄_20შეცვლილი_20და_20გაუმჯობესებული_20changed_20improved_5',['🔄 შეცვლილი და გაუმჯობესებული changed improved',['../md_docs_2changelog_2v7.html#autotoc_md975',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v8.html#autotoc_md991',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)']]],
  ['🔄_20changed_20შეცვლილი_20და_20გაუმჯობესებული_20ფუნქციონალი_6',['🔄 changed შეცვლილი და გაუმჯობესებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md853',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md848',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md843',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)']]],
  ['🔄_20changed_20შეცვლილი_20ფუნქციონალი_7',['🔄 changed შეცვლილი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md858',1,'🔄 Changed (შეცვლილი ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md863',1,'🔄 Changed (შეცვლილი ფუნქციონალი)']]]
];
