var searchData=
[
  ['tag_20ები_0',['კომპონენტების TAG-ები',['../group__ComponentTags.html',1,'']]],
  ['tag_20definition_1',['Component Tag Definition',['../md_docs_2convention_2logging__standards.html#autotoc_md705',1,'']]],
  ['tag_5fconfig_5fmanager_2',['TAG_CONFIG_MANAGER',['../group__ComponentTags.html#ga9669b4172743fc734b52e78216724ca8',1,'logging.h']]],
  ['tag_5fevent_5fbus_3',['TAG_EVENT_BUS',['../group__ComponentTags.html#ga2e71c0b8abd35311bf60bf1c7fba0000',1,'logging.h']]],
  ['tag_5fevent_5fwrapper_4',['TAG_EVENT_WRAPPER',['../group__ComponentTags.html#gae78ebf36d2c5c4fcdf532d123f0deca2',1,'logging.h']]],
  ['tag_5fmodule_5fregistry_5',['TAG_MODULE_REGISTRY',['../group__ComponentTags.html#ga7ba4af78f9d3ce3e798c1445b6538ae7',1,'logging.h']]],
  ['tag_5fresource_5fmanager_6',['TAG_RESOURCE_MANAGER',['../group__ComponentTags.html#gae477c01601c50e7e25d61e74861421bb',1,'logging.h']]],
  ['tag_5fservice_5flocator_7',['TAG_SERVICE_LOCATOR',['../group__ComponentTags.html#ga84a3cea10966e73c817b6b306c21177e',1,'logging.h']]],
  ['tag_5fsystem_5fmanager_8',['TAG_SYSTEM_MANAGER',['../group__ComponentTags.html#ga667619e8d88a4a489aaed8e8fbe5ceb0',1,'logging.h']]],
  ['task_20და_20stack_20usage_20მონიტორინგი_9',['4. Task და Stack Usage მონიტორინგი',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1327',1,'']]],
  ['task_20კონფიგურაცია_10',['Task კონფიგურაცია',['../group__TaskConfig.html',1,'']]],
  ['task_20ფუნქციები_11',['4. Task ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md701',1,'']]],
  ['task_20state_20changes_12',['2. Task State Changes',['../md_docs_2convention_2logging__standards.html#autotoc_md723',1,'']]],
  ['task_20watchdog_13',['1. Stack Overflow და Task Watchdog',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1288',1,'']]],
  ['telemetry_5fdata_5ft_14',['telemetry_data_t',['../structtelemetry__data__t.html',1,'']]],
  ['telemetry_5fevents_20h_15',['[interfaces/include/telemetry_events.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md429',1,'']]],
  ['telemetry_5fevents_2eh_16',['telemetry_events.h',['../telemetry__events_8h.html',1,'']]],
  ['temperature_20float_20humidity_17',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md317',1,'']]],
  ['template_18',['template',['../md_docs_2design__decisions_2decision__record__template.html',1,'არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)'],['../md_docs_2contributing_2issue__template.html',1,'Synapse Issue Template'],['../md_docs_2contributing_2pull__request__template.html',1,'Synapse Pull Request Template']]],
  ['testability_19',['7. Testability',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1040',1,'']]],
  ['text_20uint8_5ft_20line_20',['text uint8_t line',['../md_docs_2api__reference_2display__api.html#autotoc_md136',1,'esp_err_t ssd1306_api_write_text(const char *text, uint8_t line);'],['../md_docs_2api__reference_2module__api.html#autotoc_md233',1,'esp_err_t {module_name}_api_write_text(const char *text, uint8_t line);']]],
  ['the_20air_20module_20api_20reference_21',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['the_20framework_22',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['time_20sync_20module_20api_23',['Time Sync Module API',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md374',1,'']]],
  ['time_20sync_20module_20api_20reference_24',['Synapse Time Sync Module API Reference',['../md_docs_2api__reference_2time__sync__api.html',1,'']]],
  ['time_5fstr_20size_5ft_20size_25',['esp_err_t version_module_get_build_time(char *time_str, size_t size);',['../md_docs_2api__reference_2version__api.html#autotoc_md408',1,'']]],
  ['time_5fsync_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_26',['static void time_sync_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md382',1,'']]],
  ['time_5fsync_5fmodule_5fcreate_20const_20cjson_20config_27',['module_t *time_sync_module_create(const cJSON *config);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md375',1,'']]],
  ['time_5fsync_5fmodule_5fget_5ftime_20time_5ft_20current_5ftime_28',['esp_err_t time_sync_module_get_time(time_t *current_time);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md379',1,'']]],
  ['time_5fsync_5fmodule_5fset_5fserver_20module_5ft_20module_20const_20char_20server_5furl_29',['esp_err_t time_sync_module_set_server(module_t *module, const char *server_url);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md378',1,'']]],
  ['time_5fsync_5fmodule_5fstart_20module_5ft_20module_30',['esp_err_t time_sync_module_start(module_t *module);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md376',1,'']]],
  ['time_5fsync_5fmodule_5fstop_20module_5ft_20module_31',['esp_err_t time_sync_module_stop(module_t *module);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md377',1,'']]],
  ['time_5ft_20current_5ftime_32',['esp_err_t time_sync_module_get_time(time_t *current_time);',['../md_docs_2api__reference_2time__sync__api.html#autotoc_md379',1,'']]],
  ['timeout_20კონფიგურაცია_33',['Timeout კონფიგურაცია',['../group__TimeoutConfig.html',1,'']]],
  ['timeout_5fms_34',['esp_err_t watchdog_module_set_timeout(uint32_t timeout_ms);',['../md_docs_2api__reference_2system__api.html#autotoc_md360',1,'']]],
  ['timing_35',['1. Operation Timing',['../md_docs_2convention_2logging__standards.html#autotoc_md725',1,'']]],
  ['timing_20parameters_36',['2. Timing Parameters',['../md_docs_2convention_2configuration__management.html#autotoc_md650',1,'']]],
  ['tls_20ssl_37',['TLS/SSL',['../md_docs_2security_2security__guidelines.html#autotoc_md1154',1,'']]],
  ['tls_20ssl_20ჩართვა_20mqtt_20ში_38',['tls ssl ჩართვა mqtt ში',['../md_docs_2security_2security__best__practices.html#autotoc_md1131',1,'TLS/SSL ჩართვა MQTT-ში'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md928',1,'TLS/SSL ჩართვა MQTT-ში']]],
  ['topic_20const_20char_20message_39',['esp_err_t mqtt_module_publish(const char *topic, const char *message);',['../md_docs_2api__reference_2communication__api.html#autotoc_md36',1,'']]],
  ['topic_20mqtt_5fmessage_5fhandler_5ft_20handler_40',['esp_err_t mqtt_module_subscribe(const char *topic, mqtt_message_handler_t handler);',['../md_docs_2api__reference_2communication__api.html#autotoc_md37',1,'']]],
  ['trade_20offs_41',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['troubleshooting_42',['7. Troubleshooting',['../md_docs_2tutorials_2integration__example.html#autotoc_md1381',1,'']]],
  ['troubleshooting_20faq_43',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['tt_20check_5fconventions_20py_20tt_44',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['tt_20i2c_5fbus_5fmodule_20h_20tt_45',['2.2. მაგალითი (&lt;tt&gt;i2c_bus_module.h&lt;/tt&gt;)',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md592',1,'']]],
  ['tt_20include_20module_5fname_20h_20tt_46',['1. Header ფაილი (&lt;tt&gt;include/{module_name}.h&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md737',1,'']]],
  ['tt_20module_5fname_20c_20tt_47',['2. Source ფაილი (&lt;tt&gt;{module_name}.c&lt;/tt&gt;)',['../md_docs_2convention_2module__structure.html#autotoc_md738',1,'']]],
  ['tt_20service_5flocator_20h_20tt_48',['3.2. მაგალითი (&lt;tt&gt;service_locator.h&lt;/tt&gt;)',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md595',1,'']]],
  ['tx_5fdata_20uint8_5ft_20rx_5fdata_20size_5ft_20data_5flength_49',['esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md164',1,'']]],
  ['txt_50',['[core/CMakeLists.txt]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md416',1,'']]],
  ['txt_20სტრუქტურა_51',['CMakeLists.txt სტრუქტურა',['../md_docs_2convention_2module__structure.html#autotoc_md743',1,'']]],
  ['type_52',['type',['../structmodule__t.html#ab812e70c27fc43ab62caa5d281e7e907',1,'module_t']]]
];
