var searchData=
[
  ['💡_20გამოყენების_20მაგალითი_0',['💡 გამოყენების მაგალითი',['../md_docs_2api__reference_2command__router__api.html#autotoc_md154',1,'💡 გამოყენების მაგალითი'],['../md_docs_2api__reference_2storage__api.html#autotoc_md473',1,'💡 გამოყენების მაგალითი'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md27',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2system__timer_2README.html#autotoc_md110',1,'5. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md8',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md18',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2command__router_2README.html#autotoc_md66',1,'6. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md36',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md44',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md53',1,'7. 💡 გამოყენების მაგალითი'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md103',1,'8. 💡 გამოყენების მაგალითი']]],
  ['💡_20მოდული_20tt_20rgb_5fled_5findicator_20tt_1',['💡 მოდული &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['💡_20პრაქტიკული_20მაგალითი_3a_20tt_20wifi_5fmanager_20tt_20და_20tt_20command_5frouter_20tt_2',['💡 პრაქტიკული მაგალითი: &lt;tt&gt;wifi_manager&lt;/tt&gt; და &lt;tt&gt;command_router&lt;/tt&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md863',1,'']]],
  ['💡_20mqtt_20api_20ს_20გამოყენების_20მაგალითი_3',['💡 MQTT API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md164',1,'']]],
  ['💡_20strong_20დონე_204_3a_20აპლიკაციის_20ლოგიკა_20და_20პერიფერია_2060_2079_20strong_4',['💡 &lt;strong&gt;დონე 4: აპლიკაციის ლოგიკა და პერიფერია (60-79)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md872',1,'']]],
  ['💡_20wifi_20api_20ს_20გამოყენების_20მაგალითი_5',['💡 WiFi API-ს გამოყენების მაგალითი',['../md_docs_2api__reference_2communication__api.html#autotoc_md160',1,'']]]
];
