var searchData=
[
  ['job_20tt_20იმპლემენტაცია_0',['4.2. სამუშაო ფუნქციის (&lt;tt&gt;Job&lt;/tt&gt;) იმპლემენტაცია',['../md_docs_2convention_2task__pool__pattern.html#autotoc_md1319',1,'']]],
  ['job_5ffunction_20void_20user_5fcontext_20uint32_5ft_20interval_5fms_20bool_20is_5fperiodic_20tt_1',['&lt;tt&gt;synapse_job_handle_t synapse_task_pool_schedule_job(synapse_job_cb job_function, void* user_context, uint32_t interval_ms, bool is_periodic);&lt;/tt&gt;',['../md_docs_2api__reference_2task__pool__api.html#autotoc_md710',1,'']]],
  ['json_20tt_2',['json tt',['../md_components_2modules_2actuators_2relay__actuator_2README.html#autotoc_md3',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2button__input_2README.html#autotoc_md45',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2i2c__bus_2README.html#autotoc_md54',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2mcp23017__io__expander_2README.html#autotoc_md61',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2rotary__encoder__input_2README.html#autotoc_md71',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2sn74hc595n__writer_2README.html#autotoc_md81',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2drivers_2spi__bus_2README.html#autotoc_md88',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2sensors_2time__of__flight__sensor_2README.html#autotoc_md113',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2utillities_2rgb__led__indicator_2README.html#autotoc_md246',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;config.json&lt;/tt&gt;)'],['../md_components_2modules_2sensors_2sensor__aggregator_2README.html#autotoc_md103',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;system_config.json&lt;/tt&gt;)'],['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md140',1,'3. ⚙️ კონფიგურაცია (&lt;tt&gt;system_config.json&lt;/tt&gt;)']]],
  ['json_20tt_20ის_20კონფიგურაცია_3',['ეტაპი 3: &lt;tt&gt;config.json&lt;/tt&gt;-ის კონფიგურაცია',['../md_docs_2troubleshooting_2dependency__injection__and__context.html#autotoc_md1947',1,'']]],
  ['json_20tt_20ის_20სტრუქტურა_20და_20მაგალითები_4',['2. &lt;tt&gt;config.json&lt;/tt&gt;-ის სტრუქტურა და მაგალითები',['../md_docs_2tutorials_2system__configuration.html#autotoc_md2018',1,'']]],
  ['json_5fdata_5',['json_data',['../structsynapse__telemetry__payload__t.html#aa3a11b443b0813f021d34202f329d6a4',1,'synapse_telemetry_payload_t']]]
];
