var searchData=
[
  ['name_0',['name',['../structmodule__t.html#afb5f2d3d957c8717f54cd8668e4cab5e',1,'module_t::name'],['../structservice__entry__t.html#a56a995a275a2f565f6677fc1ed136702',1,'service_entry_t::name']]],
  ['naming_1',['naming',['../md_docs_2convention_2logging__standards.html#autotoc_md1013',1,'2. Parameter Naming'],['../md_docs_2convention_2variable__naming.html#autotoc_md1046',1,'Private Data Pointer Naming']]],
  ['naming_20და_20structure_20სტანდარტები_2',['6. როგორ დავიცვა naming და structure სტანდარტები?',['../md_docs_2structure_2faq.html#autotoc_md1586',1,'']]],
  ['naming_20structure_3',['naming structure',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1359',1,'1. API Naming &amp; Structure'],['../md_docs_2api__reference_2actuators__api.html#autotoc_md219',1,'Naming &amp; Structure'],['../md_docs_2convention_2convention__index.html#autotoc_md924',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2wifi__api.html#autotoc_md671',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2version__api.html#autotoc_md661',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2utility__api.html#autotoc_md648',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2time__sync__api.html#autotoc_md635',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2system__api.html#autotoc_md618',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2sensor__api.html#autotoc_md582',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2provisioning__api.html#autotoc_md520',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2ota__api.html#autotoc_md481',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2mqtt__api.html#autotoc_md465',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2module__api.html#autotoc_md457',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md434',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2health__monitor__api.html#autotoc_md418',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2event__api.html#autotoc_md393',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md373',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2display__api.html#autotoc_md354',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2device__identity__api.html#autotoc_md325',1,'Naming &amp; Structure'],['../md_docs_2api__reference_2custom__api.html#autotoc_md314',1,'Naming &amp; Structure']]],
  ['naming_20structure_20კონვენციები_4',['📜 Naming &amp; Structure კონვენციები',['../md_docs_2api__reference_2communication__api.html#autotoc_md256',1,'']]],
  ['network_20diagnostics_5',['6. Network Diagnostics',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1630',1,'']]],
  ['next_6',['next',['../structevent__subscription__node__t.html#a21fc6eec18e9253a574a7bc1bd30db99',1,'event_subscription_node_t']]],
  ['nfc_20provisioning_20api_7',['NFC Provisioning API',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md514',1,'']]],
  ['nfc_5fprov_5fmodule_5fcreate_20const_20cjson_20config_8',['module_t *nfc_prov_module_create(const cJSON*config)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md515',1,'']]],
  ['nfc_5fprov_5fmodule_5fset_5fcredentials_20module_5ft_20module_20const_20char_20ssid_20const_20char_20password_9',['esp_err_t nfc_prov_module_set_credentials(module_t *module, const char*ssid, const char *password)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md518',1,'']]],
  ['nfc_5fprov_5fmodule_5fstart_20module_5ft_20module_10',['esp_err_t nfc_prov_module_start(module_t *module)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md516',1,'']]],
  ['nfc_5fprov_5fmodule_5fstop_20module_5ft_20module_11',['esp_err_t nfc_prov_module_stop(module_t *module)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md517',1,'']]],
  ['not_20found_12',['პრობლემა: include file not found',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1638',1,'']]],
  ['notation_13',['notation',['../md_docs_2api__reference_2configuration__api.html#autotoc_md261',1,'🔑 გასაღების ფორმატი (Dot-Notation)'],['../md_docs_2tutorials_2system__configuration.html#autotoc_md1739',1,'4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)']]],
  ['notes_14',['Development Notes',['../md_components_2modules_2utilities_2logger__module_2README.html#autotoc_md175',1,'']]],
  ['now_15',['3. Communication Integration (MQTT/WiFi/ESP-NOW)',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1361',1,'']]],
  ['now_20service_20api_16',['⚡ ESP-NOW Service API',['../md_docs_2api__reference_2communication__api.html#autotoc_md253',1,'']]],
  ['nvs_20დან_20სტრიქონის_20წაკითხვა_17',['NVS-დან სტრიქონის წაკითხვა',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1275',1,'']]],
  ['nvs_20ში_20სტრიქონის_20შენახვა_18',['NVS-ში სტრიქონის შენახვა',['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1274',1,'']]]
];
