var searchData=
[
  ['⚙️_20კონფიგურაცია_0',['⚙️ კონფიგურაცია',['../md_components_2modules_2communications_2mqtt__manager_2README.html#autotoc_md3',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md14',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2diagnostics_2self__test__manager_2README.html#autotoc_md25',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md33',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md43',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md52',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md76',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2testing_2timer__test__module_2README.html#autotoc_md113',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md154',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2system__timer_2README.html#autotoc_md164',1,'3. ⚙️ კონფიგურაცია']]],
  ['⚙️_20კონფიგურაცია_20tt_20system_5fconfig_20json_20tt_1',['3. ⚙️ კონფიგურაცია (&lt;tt&gt;system_config.json&lt;/tt&gt;)',['../md_components_2modules_2system_2connectivity__watchdog_2README.html#autotoc_md62',1,'']]],
  ['⚙️_20მოდული_3a_20command_20router_20system_20shell_2',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utilities_2command__router_2README.html',1,'']]],
  ['⚙️_20როგორ_20მუშაობს_3',['⚙️ როგორ მუშაობს?',['../md_docs_2convention_2initialization__levels.html#autotoc_md948',1,'']]],
  ['⚙️_20ძირითადი_20api_20ფუნქციები_4',['⚙️ ძირითადი API ფუნქციები',['../md_docs_2api__reference_2configuration__api.html#autotoc_md232',1,'']]],
  ['⚙️_20api_20სტრუქტურა_20tt_20cmd_5frouter_5fapi_5ft_20tt_5',['⚙️ API სტრუქტურა (&lt;tt&gt;cmd_router_api_t&lt;/tt&gt;)',['../md_docs_2api__reference_2command__router__api.html#autotoc_md201',1,'']]],
  ['⚙️_20api_20ს_20სტრუქტურა_20tt_20storage_5fapi_5ft_20tt_6',['⚙️ API-ს სტრუქტურა (&lt;tt&gt;storage_api_t&lt;/tt&gt;)',['../md_docs_2api__reference_2storage__api.html#autotoc_md545',1,'']]]
];
