var searchData=
[
  ['კატეგორია_20მოდულებისთვის_0',['8. როგორ დავამატო ახალი კატეგორია მოდულებისთვის?',['../md_docs_2structure_2faq.html#autotoc_md1517',1,'']]],
  ['კატეგორიები_1',['კატეგორიები',['../md_docs_2convention_2module__structure.html#autotoc_md926',1,'კატეგორიები'],['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1373',1,'4. ხელმისაწვდომი კატეგორიები']]],
  ['კითხვა_2',['სენსორის კითხვა',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1285',1,'']]],
  ['კითხვა_20ამ_20faq_20ში_3',['9. როგორ დავამატო ახალი კითხვა ამ FAQ-ში?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1609',1,'']]],
  ['კითხვების_20ან_20პრობლემების_20შემთხვევაში_4',['10. ვის მივმართო დამატებითი კითხვების ან პრობლემების შემთხვევაში?',['../md_docs_2contributing_2faq.html#autotoc_md689',1,'']]],
  ['კითხვები_20faq_5',['კითხვები faq',['../md_docs_2structure_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)'],['../md_docs_2contributing_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)']]],
  ['კითხვები_20troubleshooting_20faq_6',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['კლონირება_7',['პროექტის კლონირება',['../md_docs_2contributing_2local__setup.html#autotoc_md719',1,'']]],
  ['კოდები_8',['შეცდომების კოდები',['../md_docs_2structure_2error__handling__and__logging.html#autotoc_md1496',1,'']]],
  ['კოდექსი_9',['კოდექსი',['../contributing_docs.html#contrib_coc_sec',1,'ქცევის კოდექსი'],['../md_docs_2contributing_2faq.html#autotoc_md688',1,'9. როგორ დავიცვა ქცევის კოდექსი?']]],
  ['კოდექსი_20code_20of_20conduct_10',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['კოდიდან_20dot_20notation_11',['4. პარამეტრებზე წვდომა კოდიდან (Dot-Notation)',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1671',1,'']]],
  ['კოდის_20ოპტიმიზაცია_12',['კოდის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1330',1,'']]],
  ['კოდის_20სტანდარტები_13',['2. კოდის სტანდარტები',['../md_docs_2contributing_2contributing__guide.html#autotoc_md656',1,'']]],
  ['კოდის_20ტერმინები_20glossary_20—_20api_20code_14',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['კოდის_20ხარისხი_3a_15',['3. კოდის ხარისხი:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1002',1,'']]],
  ['კოდი_20არ_20იკითხება_16',['პრობლემა: შეცდომის კოდი არ იკითხება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1580',1,'']]],
  ['კოდში_17',['ცვლილებები კოდში',['../md_docs_2changelog_22025-06-26-led__blinker-nvs-debug.html#autotoc_md567',1,'']]],
  ['კომენტარების_20სტანდარტი_18',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['კომენტარების_20სტანდარტი_20v1_200_19',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['კომენტარები_20',['4. სტრუქტურების და ტიპების კომენტარები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md769',1,'']]],
  ['კომენტარი_21',['კომენტარი',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md763',1,'2. ფაილის სათაურის (Header) კომენტარი'],['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md766',1,'3. ფუნქციის კომენტარი']]],
  ['კომპილაცია_20გამარტივებული_22',['1. 🧠 პირობითი კომპილაცია (გამარტივებული)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1375',1,'']]],
  ['კომპილაცია_20smart_20system_20_3a_23',['1. 🧠 კონდიციური კომპილაცია (SMART SYSTEM):',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md977',1,'']]],
  ['კომპოზიტური_20მოდულები_2080_20100_20strong_24',['🧩 &lt;strong&gt;დონე 5: მაღალი დონის კომპოზიტური მოდულები (80-100)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md892',1,'']]],
  ['კომპონენტები_25',['კომპონენტები',['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1008',1,'არქიტექტურული ფენები და ძირითადი კომპონენტები'],['../index.html#autotoc_md1548',1,'ძირითადი კომპონენტები'],['../md_docs_2structure_2core__components.html#autotoc_md1476',1,'ძირითადი კომპონენტები'],['../md_docs_2design__decisions_2core__components.html#autotoc_md1042',1,'ძირითადი კომპონენტები']]],
  ['კომპონენტები_20core_20components_26',['კომპონენტები core components',['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['კომპრომისები_20performance_20trade_20offs_27',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['კომუნიკაცია_28',['3. როგორ ხდება მოდულებს შორის კომუნიკაცია?',['../md_docs_2structure_2faq.html#autotoc_md1512',1,'']]],
  ['კომუნიკაცია_2040_2059_20strong_29',['📡 &lt;strong&gt;დონე 3: ქსელი, კონტროლი და კომუნიკაცია (40-59)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md888',1,'']]],
  ['კომუნიკაციის_20არქიტექტურული_20არჩევანი_20communication_20choices_30',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['კომუნიკაციის_20გაფართოება_31',['5. კომუნიკაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1656',1,'']]],
  ['კომუნიკაციის_20პატერნების_20წესები_32',['კომუნიკაციის პატერნების წესები',['../md_docs_2convention_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პატერნები_33',['კომუნიკაციის პატერნები',['../conventions_docs.html#conv_comm_sec',1,'კომუნიკაციის პატერნები'],['../structure_docs.html#struct_comm_patterns_sec',1,'კომუნიკაციის პატერნები'],['../md_docs_2design__decisions_2architecture__overview.html#autotoc_md1009',1,'მოდულებს შორის კომუნიკაციის პატერნები']]],
  ['კომუნიკაციის_20პატერნები_20communication_20patterns_34',['კომუნიკაციის პატერნები (Communication Patterns)',['../md_docs_2structure_2communication__patterns.html',1,'']]],
  ['კომუნიკაციის_20პატერნი_35',['ორი კომუნიკაციის პატერნი',['../md_docs_2convention_2communication__patterns.html#autotoc_md774',1,'']]],
  ['კომუნიკაციის_20პრობლემები_36',['3. კომუნიკაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1574',1,'']]],
  ['კომუნიკაციის_20ტიპები_37',['კომუნიკაციის ტიპები',['../md_docs_2convention_2communication__patterns.html#autotoc_md777',1,'']]],
  ['კონდიციური_20კომპილაცია_20smart_20system_20_3a_38',['1. 🧠 კონდიციური კომპილაცია (SMART SYSTEM):',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md977',1,'']]],
  ['კონვენცია_3a_39',['1. სახელების კონვენცია:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1000',1,'']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_40',['კონვენციების ავტომატური შემმოწმებელი',['../contributing_docs.html#contrib_linter_guide_sec',1,'']]],
  ['კონვენციების_20ავტომატური_20შემმოწმებელი_20tt_20check_5fconventions_20py_20tt_41',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['კონვენციების_20გამოყენება_42',['4. Naming და Structure კონვენციების გამოყენება',['../md_docs_2tutorials_2create__first__module.html#autotoc_md1626',1,'']]],
  ['კონვენციები_43',['კონვენციები',['../md_docs_2convention_2function__naming.html#autotoc_md870',1,'სპეციალური კონვენციები'],['../md_docs_2api__reference_2communication__api.html#autotoc_md187',1,'📜 Naming &amp; Structure კონვენციები'],['../md_docs_2convention_2variable__naming.html#autotoc_md948',1,'4. კონვენციები']]],
  ['კონვენციები_20და_20სტანდარტები_44',['კონვენციები და სტანდარტები',['../conventions_docs.html',1,'']]],
  ['კონვენციებს_20უნდა_20დავიცვა_45',['2. რა სტანდარტებს და კონვენციებს უნდა დავიცვა?',['../md_docs_2contributing_2faq.html#autotoc_md681',1,'']]],
  ['კონტექსტი_46',['კონტექსტი',['../md_docs_2design__decisions_2error__handling__decisions.html#autotoc_md1074',1,'კონტექსტი'],['../md_docs_2design__decisions_2storage__strategy.html#autotoc_md1177',1,'კონტექსტი'],['../md_docs_2design__decisions_2decision__record__template.html#autotoc_md1059',1,'კონტექსტი'],['../md_docs_2design__decisions_2communication__choices.html#autotoc_md1019',1,'კონტექსტი'],['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md1094',1,'კონტექსტი'],['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md1114',1,'კონტექსტი'],['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md1135',1,'კონტექსტი'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1156',1,'კონტექსტი']]],
  ['კონტრიბუცია_20synapse_20framework_20ში_47',['1. როგორ დავიწყო კონტრიბუცია Synapse Framework-ში?',['../md_docs_2contributing_2faq.html#autotoc_md680',1,'']]],
  ['კონტრიბუციის_20გზამკვლევი_48',['კონტრიბუციის გზამკვლევი',['../contributing_docs.html',1,'']]],
  ['კონტრიბუციის_20პროცესი_49',['კონტრიბუციის პროცესი',['../contributing_docs.html#contrib_guide_sec',1,'კონტრიბუციის პროცესი'],['../md_docs_2contributing_2contributing__guide.html#autotoc_md655',1,'1. კონტრიბუციის პროცესი']]],
  ['კონტრიბუციის_20სახელმძღვანელო_20contributing_20guide_50',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['კონტროლი_51',['კონტროლი',['../md_docs_2security_2security__best__practices.html#autotoc_md1400',1,'ლოგირების კონტროლი'],['../md_docs_2design__decisions_2security__considerations.html#autotoc_md1167',1,'ლოგირების კონტროლი']]],
  ['კონტროლი_20და_20კომუნიკაცია_2040_2059_20strong_52',['📡 &lt;strong&gt;დონე 3: ქსელი, კონტროლი და კომუნიკაცია (40-59)&lt;/strong&gt;',['../md_docs_2convention_2initialization__levels.html#autotoc_md888',1,'']]],
  ['კონფიგურაცია_53',['კონფიგურაცია',['../md_docs_2convention_2configuration__management.html#autotoc_md800',1,'მაგალითი სრული კონფიგურაცია'],['../md_docs_2tutorials_2advanced__usage.html#autotoc_md1613',1,'1. მრავალმოდულიანი კონფიგურაცია'],['../md_docs_2tutorials_2integration__example.html#autotoc_md1643',1,'2. საჭირო მოდულების ჩართვა და კონფიგურაცია'],['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1592',1,'2. Debug Build-ის კონფიგურაცია'],['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1382',1,'3. კონფიგურაცია'],['../md_components_2modules_2storage_2storage__manager_2README.html#autotoc_md23',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md32',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md13',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2system__timer_2README.html#autotoc_md126',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md116',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md42',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2testing_2timer__test__module_2README.html#autotoc_md75',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md3',1,'3. ⚙️ კონფიგურაცია'],['../md_components_2modules_2utilities_2command__router_2README.html#autotoc_md81',1,'3. 🛠️ კონფიგურაცია'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md59',1,'4. კონფიგურაცია'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md51',1,'4. კონფიგურაცია'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md68',1,'4. კონფიგურაცია'],['../md_docs_2structure_2faq.html#autotoc_md1513',1,'4. როგორ მივიღო ან შევცვალო მოდულის კონფიგურაცია?'],['../md_docs_2contributing_2local__setup.html#autotoc_md721',1,'sdkconfig ფაილის კონფიგურაცია']]],
  ['კონფიგურაცია_20მუშაობს_3a_54',['3. რომ დარწმუნდეთ კონფიგურაცია მუშაობს:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md996',1,'']]],
  ['კონფიგურაცია_20system_20configuration_55',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['კონფიგურაცია_3a_56',['3. კონფიგურაცია:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md983',1,'']]],
  ['კონფიგურაციისა_20და_20შენახვის_20ტერმინები_20glossary_20—_20configuration_20storage_57',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['კონფიგურაციის_20გაფართოება_58',['4. კონფიგურაციის გაფართოება',['../md_docs_2tutorials_2module__extension.html#autotoc_md1655',1,'']]],
  ['კონფიგურაციის_20გაფართოება_3a_59',['1. კონფიგურაციის გაფართოება:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md987',1,'']]],
  ['კონფიგურაციის_20დამუშავების_20ეტაპები_60',['კონფიგურაციის დამუშავების ეტაპები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1468',1,'']]],
  ['კონფიგურაციის_20ვალიდაცია_61',['5. კონფიგურაციის ვალიდაცია',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1673',1,'']]],
  ['კონფიგურაციის_20მართვა_62',['კონფიგურაციის მართვა',['../conventions_docs.html#conv_config_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_63',['კონფიგურაციის მართვის პროცესი',['../structure_docs.html#struct_config_flow_sec',1,'']]],
  ['კონფიგურაციის_20მართვის_20პროცესი_20configuration_20flow_64',['კონფიგურაციის მართვის პროცესი (Configuration Flow)',['../md_docs_2structure_2configuration__flow.html',1,'']]],
  ['კონფიგურაციის_20მართვის_20წესები_65',['კონფიგურაციის მართვის წესები',['../md_docs_2convention_2configuration__management.html',1,'']]],
  ['კონფიგურაციის_20ოპტიმიზაცია_66',['კონფიგურაციის ოპტიმიზაცია',['../md_docs_2performance_2performance__optimization.html#autotoc_md1332',1,'']]],
  ['კონფიგურაციის_20პარამეტრები_67',['🎛️ კონფიგურაციის პარამეტრები',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md985',1,'']]],
  ['კონფიგურაციის_20პრობლემები_68',['2. კონფიგურაციის პრობლემები',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1570',1,'']]],
  ['კონფიგურაციის_20სტრუქტურა_69',['კონფიგურაციის სტრუქტურა',['../md_docs_2structure_2configuration__flow.html#autotoc_md1467',1,'']]],
  ['კონფიგურაციის_20ტიპები_70',['კონფიგურაციის ტიპები',['../md_docs_2convention_2configuration__management.html#autotoc_md801',1,'']]],
  ['კონფიგურაციის_20შეცდომა_71',['8. როგორ დავადგინო კონფიგურაციის შეცდომა?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1608',1,'']]],
  ['კონფიგურაციის_20წვდომის_20მაგალითები_72',['კონფიგურაციის წვდომის მაგალითები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1469',1,'']]],
  ['კონფიგურაციის_20წყაროები_73',['კონფიგურაციის წყაროები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1466',1,'']]],
  ['კონფიგურაციის_20parsing_74',['კონფიგურაციის Parsing',['../md_docs_2convention_2configuration__management.html#autotoc_md808',1,'']]],
  ['კრიტერიუმები_75',['მიმოხილვის კრიტერიუმები',['../md_docs_2contributing_2review__guidelines.html#autotoc_md753',1,'']]],
  ['კრიტიკულად_20განახლებული_76',['3. 🔗 Base Module Interface (კრიტიკულად განახლებული)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1377',1,'']]]
];
