var searchData=
[
  ['იბილდება_0',['პრობლემა: მოდული არ იბილდება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1614',1,'']]],
  ['იბილდება_20ჩემი_20მოდული_1',['1. რატომ არ იბილდება ჩემი მოდული?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1648',1,'']]],
  ['იდენტიფიკატორი_2',['Custom Event-ის იდენტიფიკატორი',['../md_docs_2api__reference_2custom__api.html#autotoc_md257',1,'']]],
  ['ივენთების_20დამუშავება_3',['ივენთების დამუშავება',['../md_components_2modules_2system_2alarms__manager_2README.html#autotoc_md48',1,'5. 📢 ივენთების დამუშავება'],['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md135',1,'6. 📢 ივენთების დამუშავება']]],
  ['ივენთების_20დამუშავება_3a_4',['3. ივენთების დამუშავება:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1036',1,'']]],
  ['ივენთები_5',['ივენთები',['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md57',1,'გამოქვეყნებული ივენთები'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md28',1,'გამოქვეყნებული ივენთები'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md16',1,'გამოქვეყნებული ივენთები'],['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md17',1,'გამოწერილი ივენთები'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md58',1,'გამოწერილი ივენთები'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md29',1,'გამოწერილი ივენთები'],['../md_components_2modules_2system_2watchdog__manager_2README.html#autotoc_md86',1,'6. გამოქვეყნებული ივენთები'],['../md_components_2modules_2system_2ota__update__manager_2README.html#autotoc_md77',1,'6. გამოქვეყნებული ივენთები'],['../md_components_2modules_2system_2health__monitor_2README.html#autotoc_md69',1,'6. გამოქვეყნებული ივენთები']]],
  ['ივენთები_20events_6',['ივენთები events',['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md15',1,'4. 📢 ივენთები (Events)'],['../md_components_2modules_2provisioning_2ble__provisioning_2README.html#autotoc_md27',1,'5. 📢 ივენთები (Events)'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md56',1,'5. 📢 ივენთები (Events)']]],
  ['ივენთის_20მონაცემების_20მართვა_20reference_20counting_7',['ივენთის მონაცემების მართვა (Reference Counting)',['../md_docs_2api__reference_2event__api.html#autotoc_md333',1,'']]],
  ['იზოლაცია_8',['ძირითადი პრინციპი: მაქსიმალური იზოლაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md820',1,'']]],
  ['იზოლაცია_20ყველაზე_20მნიშვნელოვანი_20შემოწმება_20_3a_20strong_9',['✅ &lt;strong&gt;მოდულების იზოლაცია (ყველაზე მნიშვნელოვანი შემოწმება):&lt;/strong&gt;',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md720',1,'']]],
  ['ით_20api_20არ_20იძებნება_10',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1623',1,'']]],
  ['იკითხება_11',['პრობლემა: შეცდომის კოდი არ იკითხება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1627',1,'']]],
  ['იმავე_20ტიპის_20რამდენიმე_20მოდულის_20დამატება_12',['2. შეიძლება თუ არა ერთი და იმავე ტიპის რამდენიმე მოდულის დამატება?',['../md_docs_2structure_2faq.html#autotoc_md1558',1,'']]],
  ['იმპლემენტაცია_13',['სწორი იმპლემენტაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md831',1,'']]],
  ['იმპლემენტაციის_20დეტალები_14',['7. ტექნიკური იმპლემენტაციის დეტალები',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html#autotoc_md136',1,'']]],
  ['იმპლემენტაციის_20ლოგიკა_15',['5. 🧠 იმპლემენტაციის ლოგიკა',['../md_components_2modules_2communications_2mqtt__manager_2README.html#autotoc_md5',1,'']]],
  ['იმპლემენტირებულია_16',['🔵 BLE Provisioning Service API (იმპლემენტირებულია)',['../md_docs_2api__reference_2provisioning__api.html#autotoc_md439',1,'']]],
  ['ინდექსი_17',['ინდექსი',['../md_docs_2integration_2integration__index.html',1,'Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)'],['../md_docs_2security_2security__index.html',1,'Security Index (უსაფრთხოების სახელმძღვანელოების ინდექსი)']]],
  ['ინიციალიზაცია_20lifecycle_20initialization_18',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['ინიციალიზაციის_20დონეების_20რეკომენდებული_20დიაპაზონები_19',['📊 ინიციალიზაციის დონეების რეკომენდებული დიაპაზონები',['../md_docs_2convention_2initialization__levels.html#autotoc_md929',1,'']]],
  ['ინიციალიზაციის_20დონეები_20initialization_20levels_20',['🚀 მოდულების ინიციალიზაციის დონეები (Initialization Levels)',['../md_docs_2convention_2initialization__levels.html',1,'']]],
  ['ინიციალიზაციის_20პრობლემის_20დიაგნოსტიკა_20და_20გამოსწორება_21',['CHANGELOG: led_blinker ინიციალიზაციის პრობლემის დიაგნოსტიკა და გამოსწორება',['../md_docs_2changelog_22025-06-26-led__blinker-nvs-debug.html',1,'']]],
  ['ინიციალიზდება_22',['პრობლემა: მოდული არ ინიციალიზდება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1618',1,'']]],
  ['ინიციალიზდება_20მოდული_23',['5. რატომ არ ინიციალიზდება მოდული?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1652',1,'']]],
  ['ინსტალაცია_24',['ESP-IDF-ის ინსტალაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md764',1,'']]],
  ['ინსტრუმენტები_25',['8. დამატებითი ინსტრუმენტები',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1645',1,'']]],
  ['ინტეგრაცია_26',['✅ ავტომატური ინტეგრაცია',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1412',1,'']]],
  ['ინტეგრაცია_20github_20actions_20თან_20ავტომატური_20შემოწმება_27',['4. ინტეგრაცია GitHub Actions-თან (ავტომატური შემოწმება)',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md723',1,'']]],
  ['ინტეგრაცია_3a_28',['✅ ავტომატური ინტეგრაცია:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1013',1,'']]],
  ['ინტეგრაციის_20მაგალითი_29',['ინტეგრაციის მაგალითი',['../tutorials_docs.html#tut_integration_sec',1,'']]],
  ['ინტეგრაციის_20მაგალითი_20integration_20example_30',['ინტეგრაციის მაგალითი (Integration Example)',['../md_docs_2tutorials_2integration__example.html',1,'']]],
  ['ინტეგრაციის_20საჭიროების_20განსაზღვრა_31',['1. ინტეგრაციის საჭიროების განსაზღვრა',['../md_docs_2tutorials_2integration__example.html#autotoc_md1689',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელოების_20ინდექსი_32',['Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)',['../md_docs_2integration_2integration__index.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელოები_33',['თემატური ინტეგრაციის სახელმძღვანელოები',['../md_docs_2integration_2integration__index.html#autotoc_md1283',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20cloud_34',['Cloud ინტეგრაციის სახელმძღვანელო (Integration — Cloud)',['../md_docs_2integration_2integration__cloud.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20mqtt_35',['MQTT ინტეგრაციის სახელმძღვანელო (Integration — MQTT)',['../md_docs_2integration_2integration__mqtt.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20rest_20api_36',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20websocket_37',['WebSocket ინტეგრაციის სახელმძღვანელო (Integration — WebSocket)',['../md_docs_2integration_2integration__websocket.html',1,'']]],
  ['ინტერპრეტაცია_38',['შედეგების ინტერპრეტაცია',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md722',1,'']]],
  ['ინტერფეისი_39',['ინტერფეისი',['../md_components_2modules_2communications_2wifi__manager_2README.html#autotoc_md18',1,'5. 📡 MQTT ინტერფეისი'],['../md_components_2modules_2system_2device__identity__service_2README.html#autotoc_md59',1,'6. 📡 MQTT ინტერფეისი']]],
  ['ინფორმაცია_40',['ინფორმაცია',['../md_docs_2contributing_2issue__template.html#autotoc_md752',1,'გარემოს ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md754',1,'დამატებითი ინფორმაცია'],['../md_docs_2contributing_2pull__request__template.html#autotoc_md790',1,'დამატებითი ინფორმაცია'],['../md_docs_2security_2security__vulnerability__disclosure.html#autotoc_md1496',1,'საკონტაქტო ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md742',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2pull__request__template.html#autotoc_md782',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2faq.html#autotoc_md733',1,'7. სად ვიპოვო დოკუმენტაციის სტრუქტურის და სტანდარტების შესახებ ინფორმაცია?']]],
  ['ისთვის_41',['ისთვის',['../md_docs_2api__reference_2display__api.html#autotoc_md286',1,'Service API (Service Locator-ისთვის)'],['../md_docs_2api__reference_2module__api.html#autotoc_md393',1,'Service API (Service Locator-ისთვის)']]],
  ['ის_20აღწერისა_42',['მაგალითი Custom Event-ის აღწერისა',['../md_docs_2api__reference_2event__api.html#autotoc_md338',1,'']]],
  ['ის_20გამოყენება_43',['ის გამოყენება',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1397',1,'CPU-ის გამოყენება'],['../md_docs_2convention_2communication__patterns.html#autotoc_md840',1,'Event Bus-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1396',1,'Flash-ის გამოყენება'],['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md1151',1,'Public API-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1395',1,'RAM-ის გამოყენება'],['../md_docs_2convention_2communication__patterns.html#autotoc_md839',1,'Service Locator-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1398',1,'Stack-ის გამოყენება']]],
  ['ის_20იდენტიფიკატორი_44',['Custom Event-ის იდენტიფიკატორი',['../md_docs_2api__reference_2custom__api.html#autotoc_md257',1,'']]],
  ['ის_20ინსტალაცია_45',['ESP-IDF-ის ინსტალაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md764',1,'']]],
  ['ის_20კონფიგურაცია_46',['2. Debug Build-ის კონფიგურაცია',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1639',1,'']]],
  ['ის_20მაგალითი_47',['Event Handler-ის მაგალითი',['../md_docs_2api__reference_2event__api.html#autotoc_md335',1,'']]],
  ['ის_20მიმოხილვა_48',['4. Pull Request-ის მიმოხილვა',['../md_docs_2contributing_2contributing__guide.html#autotoc_md705',1,'']]],
  ['ის_20მონაცემების_20სტრუქტურა_49',['Custom Event-ის მონაცემების სტრუქტურა',['../md_docs_2api__reference_2custom__api.html#autotoc_md258',1,'']]],
  ['ის_20მონიშვნა_50',['Deprecated API-ის მონიშვნა',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md1171',1,'']]],
  ['ის_20ოპტიმიზაცია_51',['Refresh interval-ის ოპტიმიზაცია',['../md_docs_2performance_2performance__display.html#autotoc_md1358',1,'']]],
  ['ის_20როლი_52',['1. &lt;tt&gt;system_config.json&lt;/tt&gt;-ის როლი',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1712',1,'']]],
  ['ის_20სტანდარტები_53',['Logging-ის სტანდარტები',['../md_docs_2convention_2logging__standards.html',1,'']]],
  ['ის_20წერის_20წესები_54',['Footer-ის წერის წესები',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md693',1,'']]],
  ['ის_20წესები_55',['ის წესები',['../contributing_docs.html#contrib_commit_sec',1,'Commit Message-ის წესები'],['../md_docs_2convention_2error__handling.html',1,'Error Handling-ის წესები']]],
  ['ის_20callback_56',['5.3. &lt;tt&gt;mqtt_event_handler_cb&lt;/tt&gt; (ESP-IDF-ის callback)',['../md_components_2modules_2communications_2mqtt__manager_2README.html#autotoc_md8',1,'']]],
  ['იქმნება_3a_57',['1. რომ დარწმუნდეთ მოდული სწორად იქმნება:',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html#autotoc_md1041',1,'']]],
  ['იძებნება_58',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1623',1,'']]],
  ['იწვევს_20პრობლემას_59',['6. როგორ გავიგო რომელი მოდული იწვევს პრობლემას?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1653',1,'']]],
  ['ი_20ჩემს_20სერვისს_60',['3. რატომ ვერ პოულობს Service Locator-ი ჩემს სერვისს?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1650',1,'']]]
];
