var searchData=
[
  ['data_20pointer_20naming_0',['Private Data Pointer Naming',['../md_docs_2convention_2variable__naming.html#autotoc_md767',1,'']]],
  ['data_20size_5ft_20data_5flength_1',['data size_t data_length',['../md_docs_2api__reference_2communication__api.html#autotoc_md47',1,'esp_err_t espnow_module_send(const uint8_t *peer_mac, const uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md157',1,'esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md158',1,'esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);']]],
  ['data_20structure_2',['Private Data Structure',['../md_docs_2convention_2configuration__management.html#autotoc_md636',1,'']]],
  ['data_5flength_3',['data_length',['../md_docs_2api__reference_2communication__api.html#autotoc_md47',1,'esp_err_t espnow_module_send(const uint8_t *peer_mac, const uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md157',1,'esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md158',1,'esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md164',1,'esp_err_t spi_bus_transfer(spi_bus_handle_t *spi_bus_handle, const uint8_t *tx_data, uint8_t *rx_data, size_t data_length);']]],
  ['date_5fstr_20size_5ft_20size_4',['esp_err_t version_module_get_build_date(char *date_str, size_t size);',['../md_docs_2api__reference_2version__api.html#autotoc_md407',1,'']]],
  ['debug_20build_20ის_20კონფიგურაცია_5',['2. Debug Build-ის კონფიგურაცია',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1325',1,'']]],
  ['debug_20level_6',['4. ESP_LOGD - Debug Level',['../md_docs_2convention_2logging__standards.html#autotoc_md712',1,'']]],
  ['debugging_7',['6. Event და Service Debugging',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1329',1,'']]],
  ['debugging_20guide_20დიბაგინგის_20სახელმძღვანელო_8',['Debugging Guide (დიბაგინგის სახელმძღვანელო)',['../md_docs_2troubleshooting_2debugging__guide.html',1,'']]],
  ['decision_20record_20template_9',['არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)',['../md_docs_2design__decisions_2decision__record__template.html',1,'']]],
  ['decisions_10',['decisions',['../md_docs_2design__decisions_2error__handling__decisions.html',1,'შეცდომების დამუშავების არქიტექტურული გადაწყვეტილებები (Error Handling Decisions)'],['../md_docs_2design__decisions_2design__decisions__index.html',1,'Synapse Design Decisions']]],
  ['default_20მნიშვნელობები_11',['ვალიდაცია და Default მნიშვნელობები',['../md_docs_2structure_2configuration__flow.html#autotoc_md1203',1,'']]],
  ['default_20მნიშვნელობები_20არ_20მუშაობს_12',['პრობლემა: default მნიშვნელობები არ მუშაობს',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1305',1,'']]],
  ['default_20values_13',['Default Values',['../md_docs_2convention_2configuration__management.html#autotoc_md638',1,'']]],
  ['define_5fcomponent_5ftag_14',['define_component_tag',['../logging_8h.html#a7ece332eb67f0652fb4b9af20392c0f9',1,'DEFINE_COMPONENT_TAG:&#160;logging.h'],['../md_docs_2api__reference_2core__api.html#autotoc_md102',1,'DEFINE_COMPONENT_TAG']]],
  ['definition_15',['definition',['../md_docs_2convention_2logging__standards.html#autotoc_md705',1,'Component Tag Definition'],['../md_docs_2convention_2configuration__management.html#autotoc_md639',1,'Constants Definition']]],
  ['degradation_16',['2. Graceful Degradation',['../md_docs_2convention_2error__handling.html#autotoc_md682',1,'']]],
  ['deinit_17',['4. Deinit',['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1261',1,'']]],
  ['dependencies_18',['❌ პირდაპირი Dependencies',['../md_docs_2convention_2communication__patterns.html#autotoc_md608',1,'']]],
  ['dependencies_20მიხედვით_19',['Dependencies მიხედვით',['../md_docs_2convention_2module__structure.html#autotoc_md744',1,'']]],
  ['deprecated_20api_20ის_20მონიშვნა_20',['Deprecated API-ის მონიშვნა',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md887',1,'']]],
  ['deprecated_20list_21',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20checklist_22',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['design_20decisions_23',['Synapse Design Decisions',['../md_docs_2design__decisions_2design__decisions__index.html',1,'']]],
  ['device_5faddress_20const_20uint8_5ft_20data_20size_5ft_20data_5flength_24',['esp_err_t i2c_bus_write(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, const uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md158',1,'']]],
  ['device_5faddress_20uint8_5ft_20data_20size_5ft_20data_5flength_25',['esp_err_t i2c_bus_read(i2c_bus_handle_t *i2c_bus_handle, uint8_t device_address, uint8_t *data, size_t data_length);',['../md_docs_2api__reference_2drivers__api.html#autotoc_md157',1,'']]],
  ['dht22_26',['1. Event-Driven Module (მაგ., DHT22)',['../md_docs_2convention_2module__structure.html#autotoc_md740',1,'']]],
  ['dht22_5fdata_27',['static esp_err_t parse_dht22_config(const cJSON *config, dht22_private_data_t *dht22_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md320',1,'']]],
  ['dht22_5fdata_20float_20temperature_20float_20humidity_28',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md317',1,'']]],
  ['dht22_5fdeinit_20module_5ft_20module_29',['static esp_err_t dht22_deinit(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md313',1,'']]],
  ['dht22_5fdisable_20module_5ft_20module_30',['static esp_err_t dht22_disable(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md312',1,'']]],
  ['dht22_5fenable_20module_5ft_20module_31',['static esp_err_t dht22_enable(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md311',1,'']]],
  ['dht22_5fget_5fstatus_20module_5ft_20module_32',['static module_status_t dht22_get_status(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md323',1,'']]],
  ['dht22_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_33',['static void dht22_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md316',1,'']]],
  ['dht22_5finit_20module_5ft_20module_34',['static esp_err_t dht22_init(module_t *module);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md310',1,'']]],
  ['dht22_5fmodule_5fcreate_20const_20cjson_20config_35',['module_t &lt;em&gt;dht22_module_create(const cJSON *config);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md309',1,'']]],
  ['dht22_5fprivate_5fdata_5ft_20dht22_5fdata_36',['static esp_err_t parse_dht22_config(const cJSON *config, dht22_private_data_t *dht22_data);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md320',1,'']]],
  ['dht22_5fprivate_5fdata_5ft_20dht22_5fdata_20float_20temperature_20float_20humidity_37',['static esp_err_t publish_sensor_data(dht22_private_data_t *dht22_data, float temperature, float humidity);',['../md_docs_2api__reference_2sensor__api.html#autotoc_md317',1,'']]],
  ['diagnostics_38',['diagnostics',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1292',1,'5. Peripheral Diagnostics'],['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1293',1,'6. Network Diagnostics']]],
  ['diagnostics_20გაფართოებული_20დიაგნოსტიკა_39',['Advanced Diagnostics (გაფართოებული დიაგნოსტიკა)',['../md_docs_2troubleshooting_2advanced__diagnostics.html',1,'']]],
  ['diagnostics_20module_20api_40',['Diagnostics Module API',['../md_docs_2api__reference_2system__api.html#autotoc_md362',1,'']]],
  ['diagnostics_5fmodule_5fcreate_20const_20cjson_20config_41',['module_t *diagnostics_module_create(const cJSON *config);',['../md_docs_2api__reference_2system__api.html#autotoc_md363',1,'']]],
  ['diagnostics_5fmodule_5fget_5freport_20char_20report_5fbuffer_20size_5ft_20buffer_5fsize_42',['esp_err_t diagnostics_module_get_report(char *report_buffer, size_t buffer_size);',['../md_docs_2api__reference_2system__api.html#autotoc_md365',1,'']]],
  ['diagnostics_5fmodule_5frun_5ftests_20void_43',['esp_err_t diagnostics_module_run_tests(void);',['../md_docs_2api__reference_2system__api.html#autotoc_md364',1,'']]],
  ['diagram_44',['Architecture Diagram',['../md_docs_2convention_2communication__patterns.html#autotoc_md621',1,'']]],
  ['direct_20api_20communication_20service_20locator_45',['Direct API Communication (Service Locator)',['../md_docs_2convention_2communication__patterns.html#autotoc_md605',1,'']]],
  ['directory_20structure_46',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['disable_47',['disable',['../md_docs_2convention_2logging__standards.html#autotoc_md722',1,'1. Module Enable/Disable'],['../md_docs_2structure_2lifecycle__and__init.html#autotoc_md1260',1,'3. Enable/Disable'],['../structbase__module__interface__t.html#a1ce7eab1d06d0093ecf0cb9309eae050',1,'base_module_interface_t::disable']]],
  ['disable_20ზე_48',['პრობლემა: მოდული არ რეაგირებს enable/disable-ზე',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1316',1,'']]],
  ['disclosure_20policy_20უსაფრთხოების_20ხარვეზების_20აღმოჩენისა_20და_20შეტყობინების_20პროცედურა_49',['Vulnerability Disclosure Policy (უსაფრთხოების ხარვეზების აღმოჩენისა და შეტყობინების პროცედურა)',['../md_docs_2security_2security__vulnerability__disclosure.html',1,'']]],
  ['display_20configuration_50',['3. LCD Display Configuration',['../md_docs_2convention_2configuration__management.html#autotoc_md631',1,'']]],
  ['display_20configuration_20ssd1306_51',['2. Display Configuration (SSD1306)',['../md_docs_2convention_2configuration__management.html#autotoc_md630',1,'']]],
  ['display_20module_52',['1. Service Registration (Display Module)',['../md_docs_2convention_2communication__patterns.html#autotoc_md613',1,'']]],
  ['display_20module_20api_20reference_53',['Synapse Display Module API Reference',['../md_docs_2api__reference_2display__api.html',1,'']]],
  ['display_20modules_54',['display modules',['../md_docs_2performance_2performance__display.html',1,'ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)'],['../md_docs_2convention_2function__naming.html#autotoc_md694',1,'3. Display Modules'],['../md_docs_2convention_2variable__naming.html#autotoc_md756',1,'Display Modules']]],
  ['display_20parameters_55',['3. Display Parameters',['../md_docs_2convention_2configuration__management.html#autotoc_md651',1,'']]],
  ['documentation_56',['documentation',['../md_docs_2internal_2synapse__checklist.html#autotoc_md1038',1,'5. Documentation'],['../md_docs_2convention_2convention__index.html#autotoc_md657',1,'Coding &amp; Documentation']]],
  ['documentation_20module_20design_20checklist_57',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['doxygen_20კომენტარების_20სტანდარტი_58',['Doxygen კომენტარების სტანდარტი',['../conventions_docs.html#conv_doxygen_sec',1,'']]],
  ['doxygen_20კომენტარების_20სტანდარტი_20v1_200_59',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['doxygen_20ტეგების_20გამოყენების_20წესები_60',['5. Doxygen ტეგების გამოყენების წესები',['../md_docs_2convention_2coding__doxygen__standard.html#autotoc_md598',1,'']]],
  ['doxygen_5fmain_5fpages_61',['doxygen_main_pages',['../md_docs_2doxygen__main__pages.html',1,'']]],
  ['driven_20module_20მაგ_20dht22_62',['1. Event-Driven Module (მაგ., DHT22)',['../md_docs_2convention_2module__structure.html#autotoc_md740',1,'']]],
  ['driven_20module_20მაგ_20ssd1306_63',['2. Service-Driven Module (მაგ., SSD1306)',['../md_docs_2convention_2module__structure.html#autotoc_md741',1,'']]],
  ['driver_20api_64',['driver api',['../md_docs_2api__reference_2drivers__api.html#autotoc_md154',1,'I2C Bus Driver API'],['../md_docs_2api__reference_2drivers__api.html#autotoc_md161',1,'SPI Bus Driver API']]],
  ['driver_20module_20მაგ_20i2c_20bus_65',['3. Driver Module (მაგ., I2C Bus)',['../md_docs_2convention_2module__structure.html#autotoc_md742',1,'']]],
  ['drivers_20module_20api_20reference_66',['Synapse Drivers Module API Reference',['../md_docs_2api__reference_2drivers__api.html',1,'']]],
  ['dumps_20და_20crash_20reporting_67',['3. Core Dumps და Crash Reporting',['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1290',1,'']]]
];
