var searchData=
[
  ['🔄_20მოდული_3a_20tt_20mcp23017_5fio_5fexpander_20tt_0',['🔄 მოდული: &lt;tt&gt;mcp23017_io_expander&lt;/tt&gt;',['../md_components_2modules_2drivers_2mcp23017__io__expander_2README.html',1,'']]],
  ['🔄_20სრული_20სამუშაო_20პროცესი_20workflow_1',['5. 🔄 სრული სამუშაო პროცესი (Workflow)',['../md_docs_2tools_2create__module.html#autotoc_md1926',1,'']]],
  ['🔄_20შეცვლილია_20changed_2',['🔄 შეცვლილია (Changed)',['../md_docs_2changelog_2v5.html#autotoc_md868',1,'']]],
  ['🔄_20შეცვლილი_3',['🔄 შეცვლილი',['../md_docs_2changelog_2v7.html#autotoc_md987',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md971',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md966',1,'🔄 შეცვლილი'],['../md_docs_2changelog_2v6.html#autotoc_md962',1,'🔄 შეცვლილი']]],
  ['🔄_20შეცვლილი_20და_20გაუმჯობესებული_20ფუნქციონალი_20changed_4',['🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი changed',['../md_docs_2changelog_2v5.html#autotoc_md826',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md835',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md829',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)'],['../md_docs_2changelog_2v5.html#autotoc_md840',1,'🔄 შეცვლილი და გაუმჯობესებული ფუნქციონალი (Changed)']]],
  ['🔄_20შეცვლილი_20და_20გაუმჯობესებული_20changed_20improved_5',['🔄 შეცვლილი და გაუმჯობესებული changed improved',['../md_docs_2changelog_2v7.html#autotoc_md976',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v8.html#autotoc_md992',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v9.html#autotoc_md1003',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v9.html#autotoc_md1011',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)'],['../md_docs_2changelog_2v9.html#autotoc_md1019',1,'🔄 შეცვლილი და გაუმჯობესებული (Changed &amp; Improved)']]],
  ['🔄_20changed_20შეცვლილი_20და_20გაუმჯობესებული_20ფუნქციონალი_6',['🔄 changed შეცვლილი და გაუმჯობესებული ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md854',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md849',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md844',1,'🔄 Changed (შეცვლილი და გაუმჯობესებული ფუნქციონალი)']]],
  ['🔄_20changed_20შეცვლილი_20ფუნქციონალი_7',['🔄 changed შეცვლილი ფუნქციონალი',['../md_docs_2changelog_2v5.html#autotoc_md864',1,'🔄 Changed (შეცვლილი ფუნქციონალი)'],['../md_docs_2changelog_2v5.html#autotoc_md859',1,'🔄 Changed (შეცვლილი ფუნქციონალი)']]]
];
