var searchData=
[
  ['დამატება_20module_20extension_20feature_20addition_0',['მოდულის გაფართოება ან ფუნქციონალის დამატება (Module Extension &amp; Feature Addition)',['../md_docs_2tutorials_2module__extension.html',1,'']]],
  ['დამუშავება_20და_20ლოგირების_20სტანდარტები_20error_20handling_20logging_1',['შეცდომების დამუშავება და ლოგირების სტანდარტები (Error Handling &amp; Logging)',['../md_docs_2structure_2error__handling__and__logging.html',1,'']]],
  ['დამუშავების_20არქიტექტურული_20გადაწყვეტილებები_20error_20handling_20decisions_2',['შეცდომების დამუშავების არქიტექტურული გადაწყვეტილებები (Error Handling Decisions)',['../md_docs_2design__decisions_2error__handling__decisions.html',1,'']]],
  ['დასახელების_20წესები_3',['დასახელების წესები',['../md_docs_2convention_2function__naming.html',1,'ფუნქციების დასახელების წესები'],['../md_docs_2convention_2variable__naming.html',1,'ცვლადების დასახელების წესები']]],
  ['დასმული_20კითხვები_20faq_4',['დასმული კითხვები faq',['../md_docs_2contributing_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)'],['../md_docs_2structure_2faq.html',1,'ხშირად დასმული კითხვები (FAQ)']]],
  ['დასმული_20კითხვები_20troubleshooting_20faq_5',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['და_20გადაჭრის_20გზები_20common_20issues_20solutions_6',['გავრცელებული პრობლემები და გადაჭრის გზები (Common Issues &amp; Solutions)',['../md_docs_2troubleshooting_2common__issues.html',1,'']]],
  ['და_20თავსებადობის_20არქიტექტურული_20გადაწყვეტილებები_20migration_20compatibility_7',['მიგრაციისა და თავსებადობის არქიტექტურული გადაწყვეტილებები (Migration &amp; Compatibility)',['../md_docs_2design__decisions_2migration__and__compatibility.html',1,'']]],
  ['და_20ინიციალიზაცია_20lifecycle_20initialization_8',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['და_20კოდის_20ტერმინები_20glossary_20—_20api_20code_9',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['და_20ლოგირების_20სტანდარტები_20error_20handling_20logging_10',['შეცდომების დამუშავება და ლოგირების სტანდარტები (Error Handling &amp; Logging)',['../md_docs_2structure_2error__handling__and__logging.html',1,'']]],
  ['და_20მაგალითები_11',['სახელმძღვანელოები და მაგალითები',['../tutorials_docs.html',1,'']]],
  ['და_20მოდულარობის_20არქიტექტურული_20გადაწყვეტილებები_20extensibility_20modularity_12',['გაფართოებადობისა და მოდულარობის არქიტექტურული გადაწყვეტილებები (Extensibility &amp; Modularity)',['../md_docs_2design__decisions_2extensibility__and__modularity.html',1,'']]],
  ['და_20რესურსების_20არქიტექტურული_20კომპრომისები_20performance_20trade_20offs_13',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['და_20სტანდარტები_14',['კონვენციები და სტანდარტები',['../conventions_docs.html',1,'']]],
  ['და_20სტრუქტურა_15',['არქიტექტურა და სტრუქტურა',['../structure_docs.html',1,'']]],
  ['და_20ფაილების_20სტრუქტურა_20directory_20structure_16',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['და_20შენახვის_20ტერმინები_20glossary_20—_20configuration_20storage_17',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['და_20შეტყობინების_20პროცედურა_18',['Vulnerability Disclosure Policy (უსაფრთხოების ხარვეზების აღმოჩენისა და შეტყობინების პროცედურა)',['../md_docs_2security_2security__vulnerability__disclosure.html',1,'']]],
  ['და_20წარმადობის_20ტერმინები_20glossary_20—_20security_20performance_19',['უსაფრთხოების და წარმადობის ტერმინები (Glossary — Security &amp; Performance)',['../md_docs_2glossary_2glossary__security.html',1,'']]],
  ['და_20best_20practices_20extending_20the_20framework_20',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['დიაგნოსტიკა_21',['Advanced Diagnostics (გაფართოებული დიაგნოსტიკა)',['../md_docs_2troubleshooting_2advanced__diagnostics.html',1,'']]],
  ['დიბაგინგის_20სახელმძღვანელო_22',['Debugging Guide (დიბაგინგის სახელმძღვანელო)',['../md_docs_2troubleshooting_2debugging__guide.html',1,'']]]
];
