var searchData=
[
  ['გადავცეთ_20კონტექსტი_20სერვისის_20api_20ს_20გამოძახებისას_0',['პრობლემა: როგორ გადავცეთ კონტექსტი სერვისის API-ს გამოძახებისას?',['../md_docs_2troubleshooting_2dependency__injection__and__context.html',1,'']]],
  ['გადაწყვეტილება_3a_20დამოკიდებულებების_20ინექცია_20dependency_20injection_1',['არქიტექტურული გადაწყვეტილება: დამოკიდებულებების ინექცია (Dependency Injection)',['../md_docs_2design__decisions_2dependency__injection.html',1,'']]],
  ['გადაწყვეტილებები_20error_20handling_20decisions_2',['შეცდომების დამუშავების არქიტექტურული გადაწყვეტილებები (Error Handling Decisions)',['../md_docs_2design__decisions_2error__handling__decisions.html',1,'']]],
  ['გადაწყვეტილებები_20extensibility_20modularity_3',['გაფართოებადობისა და მოდულარობის არქიტექტურული გადაწყვეტილებები (Extensibility &amp; Modularity)',['../md_docs_2design__decisions_2extensibility__and__modularity.html',1,'']]],
  ['გადაწყვეტილებები_20migration_20compatibility_4',['მიგრაციისა და თავსებადობის არქიტექტურული გადაწყვეტილებები (Migration &amp; Compatibility)',['../md_docs_2design__decisions_2migration__and__compatibility.html',1,'']]],
  ['გადაწყვეტილებები_20security_20considerations_5',['უსაფრთხოების არქიტექტურული გადაწყვეტილებები (Security Considerations)',['../md_docs_2design__decisions_2security__considerations.html',1,'']]],
  ['გადაწყვეტილების_20ჩანაწერის_20შაბლონი_20decision_20record_20template_6',['არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)',['../md_docs_2design__decisions_2decision__record__template.html',1,'']]],
  ['გადაჭრის_20გზები_20common_20issues_20solutions_7',['გავრცელებული პრობლემები და გადაჭრის გზები (Common Issues &amp; Solutions)',['../md_docs_2troubleshooting_2common__issues.html',1,'']]],
  ['გავრცელებული_20პრობლემები_20და_20გადაჭრის_20გზები_20common_20issues_20solutions_8',['გავრცელებული პრობლემები და გადაჭრის გზები (Common Issues &amp; Solutions)',['../md_docs_2troubleshooting_2common__issues.html',1,'']]],
  ['გაკვეთილი_3a_20მზა_20მოდულის_20დამატება_20თქვენს_20synapse_20პროექტში_9',['გაკვეთილი: მზა მოდულის დამატება თქვენს Synapse პროექტში',['../md_docs_2tutorials_2adding__a__module.html',1,'']]],
  ['გამოსწორება_10',['CHANGELOG: led_blinker ინიციალიზაციის პრობლემის დიაგნოსტიკა და გამოსწორება',['../md_docs_2changelog_22025-06-26-led__blinker-nvs-debug.html',1,'']]],
  ['გამოყენება_11',['Advanced Usage (გაფართოებული გამოყენება)',['../md_docs_2tutorials_2advanced__usage.html',1,'']]],
  ['გამოყენების_20სახელმძღვანელო_20performance_20resource_20usage_20guide_12',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['გამოძახებისას_13',['პრობლემა: როგორ გადავცეთ კონტექსტი სერვისის API-ს გამოძახებისას?',['../md_docs_2troubleshooting_2dependency__injection__and__context.html',1,'']]],
  ['გაფართოებადობისა_20და_20მოდულარობის_20არქიტექტურული_20გადაწყვეტილებები_20extensibility_20modularity_14',['გაფართოებადობისა და მოდულარობის არქიტექტურული გადაწყვეტილებები (Extensibility &amp; Modularity)',['../md_docs_2design__decisions_2extensibility__and__modularity.html',1,'']]],
  ['გაფართოება_20ან_20ფუნქციონალის_20დამატება_20module_20extension_20feature_20addition_15',['მოდულის გაფართოება ან ფუნქციონალის დამატება (Module Extension &amp; Feature Addition)',['../md_docs_2tutorials_2module__extension.html',1,'']]],
  ['გაფართოება_20და_20best_20practices_20extending_20the_20framework_16',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['გაფართოებული_20გამოყენება_17',['Advanced Usage (გაფართოებული გამოყენება)',['../md_docs_2tutorials_2advanced__usage.html',1,'']]],
  ['გაფართოებული_20დიაგნოსტიკა_18',['Advanced Diagnostics (გაფართოებული დიაგნოსტიკა)',['../md_docs_2troubleshooting_2advanced__diagnostics.html',1,'']]],
  ['გენერატორი_20v3_201_19',['🚀 &lt;tt&gt;create_module.py&lt;/tt&gt;: Synapse მოდულის გენერატორი (v3.1)',['../md_docs_2tools_2create__module.html',1,'']]],
  ['გზამკვლევი_20',['კონტრიბუციის გზამკვლევი',['../contributing_docs.html',1,'']]],
  ['გზები_20common_20issues_20solutions_21',['გავრცელებული პრობლემები და გადაჭრის გზები (Common Issues &amp; Solutions)',['../md_docs_2troubleshooting_2common__issues.html',1,'']]]
];
