var searchData=
[
  ['საკუთარი_20მოდულის_20შექმნა_20create_20your_20first_20module_0',['პირველი საკუთარი მოდულის შექმნა (Create Your First Module)',['../md_docs_2tutorials_2create__first__module.html',1,'']]],
  ['საუკეთესო_20პრაქტიკები_20წარმადობისთვის_20performance_20best_20practices_1',['საუკეთესო პრაქტიკები წარმადობისთვის (Performance Best Practices)',['../md_docs_2performance_2performance__best__practices.html',1,'']]],
  ['საუკეთესო_20პრაქტიკები_20security_20best_20practices_2',['უსაფრთხოების საუკეთესო პრაქტიკები (Security Best Practices)',['../md_docs_2security_2security__best__practices.html',1,'']]],
  ['საქაღალდეებისა_20და_20ფაილების_20სტრუქტურა_20directory_20structure_3',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['სახელმძღვანელოების_20ინდექსი_4',['სახელმძღვანელოების ინდექსი',['../md_docs_2integration_2integration__index.html',1,'Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)'],['../md_docs_2security_2security__index.html',1,'Security Index (უსაფრთხოების სახელმძღვანელოების ინდექსი)']]],
  ['სახელმძღვანელოები_20და_20მაგალითები_5',['სახელმძღვანელოები და მაგალითები',['../tutorials_docs.html',1,'']]],
  ['სახელმძღვანელოები_20performance_20optimization_20guide_6',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['სახელმძღვანელოები_20security_20guidelines_7',['უსაფრთხოების სახელმძღვანელოები (Security Guidelines)',['../md_docs_2security_2security__guidelines.html',1,'']]],
  ['სახელმძღვანელო_8',['სახელმძღვანელო',['../md_docs_2troubleshooting_2debugging__guide.html',1,'Debugging Guide (დიბაგინგის სახელმძღვანელო)'],['../md_docs_2performance_2performance__index.html',1,'Performance (წარმადობის სახელმძღვანელო)']]],
  ['სახელმძღვანელო_20contributing_20guide_9',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20cloud_10',['Cloud ინტეგრაციის სახელმძღვანელო (Integration — Cloud)',['../md_docs_2integration_2integration__cloud.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20mqtt_11',['MQTT ინტეგრაციის სახელმძღვანელო (Integration — MQTT)',['../md_docs_2integration_2integration__mqtt.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20rest_20api_12',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['სახელმძღვანელო_20integration_20—_20websocket_13',['WebSocket ინტეგრაციის სახელმძღვანელო (Integration — WebSocket)',['../md_docs_2integration_2integration__websocket.html',1,'']]],
  ['სახელმძღვანელო_20performance_20benchmarks_20guide_14',['ბენჩმარკების ჩატარების სახელმძღვანელო (Performance Benchmarks Guide)',['../md_docs_2performance_2performance__benchmarks.html',1,'']]],
  ['სახელმძღვანელო_20performance_20resource_20usage_20guide_15',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['სა_20და_20კოდის_20ტერმინები_20glossary_20—_20api_20code_16',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['სერვისის_20api_20ს_20გამოძახებისას_17',['პრობლემა: როგორ გადავცეთ კონტექსტი სერვისის API-ს გამოძახებისას?',['../md_docs_2troubleshooting_2dependency__injection__and__context.html',1,'']]],
  ['სია_20security_20checklist_18',['უსაფრთხოების შემოწმების სია (Security Checklist)',['../md_docs_2security_2security__checklist.html',1,'']]],
  ['სისტემის_20კონფიგურაცია_20system_20configuration_19',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['სიცოცხლის_20ციკლი_20და_20ინიციალიზაცია_20lifecycle_20initialization_20',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['სტანდარტები_21',['სტანდარტები',['../conventions_docs.html',1,'კონვენციები და სტანდარტები'],['../md_docs_2convention_2logging__standards.html',1,'Logging-ის სტანდარტები']]],
  ['სტანდარტები_20error_20handling_20logging_22',['შეცდომების დამუშავება და ლოგირების სტანდარტები (Error Handling &amp; Logging)',['../md_docs_2structure_2error__handling__and__logging.html',1,'']]],
  ['სტანდარტი_20v1_200_23',['9. Doxygen კომენტარების სტანდარტი (v1.0)',['../md_docs_2convention_2coding__doxygen__standard.html',1,'']]],
  ['სტარტი_20getting_20started_24',['სწრაფი სტარტი (Getting Started)',['../md_docs_2tutorials_2getting__started.html',1,'']]],
  ['სტრუქტურა_25',['არქიტექტურა და სტრუქტურა',['../structure_docs.html',1,'']]],
  ['სტრუქტურა_20directory_20structure_26',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['სტრუქტურის_20კონვენცია_27',['მოდულის სტრუქტურის კონვენცია',['../md_docs_2convention_2module__structure.html',1,'']]],
  ['სწრაფი_20სტარტი_20getting_20started_28',['სწრაფი სტარტი (Getting Started)',['../md_docs_2tutorials_2getting__started.html',1,'']]],
  ['ს_20გამოძახებისას_29',['პრობლემა: როგორ გადავცეთ კონტექსტი სერვისის API-ს გამოძახებისას?',['../md_docs_2troubleshooting_2dependency__injection__and__context.html',1,'']]]
];
