var searchData=
[
  ['manager_20api_20reference_0',['manager api reference',['../md_docs_2api__reference_2storage__api.html',1,'💾 Synapse Storage Manager API Reference'],['../md_docs_2api__reference_2configuration__api.html',1,'Synapse Configuration Manager API Reference'],['../md_docs_2api__reference_2promise__api.html',1,'Synapse Promise Manager API Reference'],['../md_docs_2api__reference_2resource__manager__api.html',1,'Synapse Resource Manager API Reference'],['../md_docs_2api__reference_2task__pool__api.html',1,'Synapse Task Pool Manager API Reference']]],
  ['manager_20service_20api_20reference_1',['manager service api reference',['../md_docs_2api__reference_2mqtt__api.html',1,'Synapse MQTT Manager Service API Reference'],['../md_docs_2api__reference_2wifi__api.html',1,'Synapse WiFi Manager Service API Reference']]],
  ['message_20guidelines_2',['Synapse Commit Message Guidelines',['../md_docs_2contributing_2commit__message__guidelines.html',1,'']]],
  ['migration_20compatibility_3',['მიგრაციისა და თავსებადობის არქიტექტურული გადაწყვეტილებები (Migration &amp; Compatibility)',['../md_docs_2design__decisions_2migration__and__compatibility.html',1,'']]],
  ['modularity_4',['გაფართოებადობისა და მოდულარობის არქიტექტურული გადაწყვეტილებები (Extensibility &amp; Modularity)',['../md_docs_2design__decisions_2extensibility__and__modularity.html',1,'']]],
  ['module_20api_20reference_5',['module api reference',['../md_docs_2api__reference_2communication__api.html',1,'📡 Synapse Communication Module API Reference'],['../md_docs_2api__reference_2provisioning__api.html',1,'📲 Synapse Provisioning Module API Reference'],['../md_docs_2api__reference_2actuators__api.html',1,'Synapse Actuators Module API Reference'],['../md_docs_2api__reference_2display__api.html',1,'Synapse Display Module API Reference'],['../md_docs_2api__reference_2drivers__api.html',1,'Synapse Drivers Module API Reference'],['../md_docs_2api__reference_2health__monitor__api.html',1,'Synapse Health Monitor Module API Reference'],['../md_docs_2api__reference_2local__ctrl__api.html',1,'Synapse Local Control Module API Reference'],['../md_docs_2api__reference_2module__api.html',1,'Synapse Module API Reference'],['../md_docs_2api__reference_2ota__api.html',1,'Synapse OTA (Over-the-Air) Module API Reference'],['../md_docs_2api__reference_2sensor__api.html',1,'Synapse Sensor Module API Reference'],['../md_docs_2api__reference_2system__api.html',1,'Synapse System Module API Reference'],['../md_docs_2api__reference_2time__sync__api.html',1,'Synapse Time Sync Module API Reference'],['../md_docs_2api__reference_2utility__api.html',1,'Synapse Utility Module API Reference'],['../md_docs_2api__reference_2version__api.html',1,'Synapse Version Module API Reference']]],
  ['module_20architecture_6',['მოდულების არქიტექტურა (Module Architecture)',['../md_docs_2structure_2module__architecture.html',1,'']]],
  ['module_20design_20checklist_7',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['module_20extension_20feature_20addition_8',['მოდულის გაფართოება ან ფუნქციონალის დამატება (Module Extension &amp; Feature Addition)',['../md_docs_2tutorials_2module__extension.html',1,'']]],
  ['modules_9',['ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)',['../md_docs_2performance_2performance__display.html',1,'']]],
  ['monitor_20module_20api_20reference_10',['Synapse Health Monitor Module API Reference',['../md_docs_2api__reference_2health__monitor__api.html',1,'']]],
  ['mqtt_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20mqtt_11',['MQTT ინტეგრაციის სახელმძღვანელო (Integration — MQTT)',['../md_docs_2integration_2integration__mqtt.html',1,'']]],
  ['mqtt_20manager_20service_20api_20reference_12',['Synapse MQTT Manager Service API Reference',['../md_docs_2api__reference_2mqtt__api.html',1,'']]]
];
