var searchData=
[
  ['patterns_0',['კომუნიკაციის პატერნები (Communication Patterns)',['../md_docs_2structure_2communication__patterns.html',1,'']]],
  ['payloads_20event_5fpayloads_20h_1',['API რეფერენსი: Event Payloads (event_payloads.h)',['../md_docs_2api__reference_2event__payloads__api.html',1,'']]],
  ['performance_2',['უსაფრთხოების და წარმადობის ტერმინები (Glossary — Security &amp; Performance)',['../md_docs_2glossary_2glossary__security.html',1,'']]],
  ['performance_20წარმადობის_20სახელმძღვანელო_3',['Performance (წარმადობის სახელმძღვანელო)',['../md_docs_2performance_2performance__index.html',1,'']]],
  ['performance_20—_20display_20modules_4',['ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)',['../md_docs_2performance_2performance__display.html',1,'']]],
  ['performance_20benchmarks_20guide_5',['ბენჩმარკების ჩატარების სახელმძღვანელო (Performance Benchmarks Guide)',['../md_docs_2performance_2performance__benchmarks.html',1,'']]],
  ['performance_20best_20practices_6',['საუკეთესო პრაქტიკები წარმადობისთვის (Performance Best Practices)',['../md_docs_2performance_2performance__best__practices.html',1,'']]],
  ['performance_20optimization_20guide_7',['ოპტიმიზაციის სახელმძღვანელოები (Performance Optimization Guide)',['../md_docs_2performance_2performance__optimization.html',1,'']]],
  ['performance_20resource_20usage_20guide_8',['რესურსების გამოყენების სახელმძღვანელო (Performance Resource Usage Guide)',['../md_docs_2performance_2performance__resource__usage.html',1,'']]],
  ['performance_20trade_20offs_9',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['policy_20უსაფრთხოების_20ხარვეზების_20აღმოჩენისა_20და_20შეტყობინების_20პროცედურა_10',['Vulnerability Disclosure Policy (უსაფრთხოების ხარვეზების აღმოჩენისა და შეტყობინების პროცედურა)',['../md_docs_2security_2security__vulnerability__disclosure.html',1,'']]],
  ['practices_11',['practices',['../md_docs_2performance_2performance__best__practices.html',1,'საუკეთესო პრაქტიკები წარმადობისთვის (Performance Best Practices)'],['../md_docs_2security_2security__best__practices.html',1,'უსაფრთხოების საუკეთესო პრაქტიკები (Security Best Practices)']]],
  ['practices_20extending_20the_20framework_12',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['project_20overview_13',['პროექტის მიმოხილვა (Project Overview)',['../index.html',1,'']]],
  ['provisioning_20module_20api_20reference_14',['Synapse Provisioning Module API Reference',['../md_docs_2api__reference_2provisioning__api.html',1,'']]],
  ['pull_20request_20template_15',['Synapse Pull Request Template',['../md_docs_2contributing_2pull__request__template.html',1,'']]],
  ['py_20ახალი_20მოდულის_20ავტომატური_20გენერატორი_16',['py ახალი მოდულის ავტომატური გენერატორი',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html',1,'🚀 CREATE_MODULE.PY - ახალი მოდულის ავტომატური გენერატორი'],['../md_docs_2CREATE__MODULE__DOCUMENTATION.html',1,'🚀 CREATE_MODULE.PY - ახალი მოდულის ავტომატური გენერატორი']]],
  ['py_20tt_17',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]]
];
