var searchData=
[
  ['მაგალითები_0',['სახელმძღვანელოები და მაგალითები',['../tutorials_docs.html',1,'']]],
  ['მაგალითი_20integration_20example_1',['ინტეგრაციის მაგალითი (Integration Example)',['../md_docs_2tutorials_2integration__example.html',1,'']]],
  ['მართვის_20პროცესი_20configuration_20flow_2',['კონფიგურაციის მართვის პროცესი (Configuration Flow)',['../md_docs_2structure_2configuration__flow.html',1,'']]],
  ['მართვის_20წესები_3',['კონფიგურაციის მართვის წესები',['../md_docs_2convention_2configuration__management.html',1,'']]],
  ['მიგრაციისა_20და_20თავსებადობის_20არქიტექტურული_20გადაწყვეტილებები_20migration_20compatibility_4',['მიგრაციისა და თავსებადობის არქიტექტურული გადაწყვეტილებები (Migration &amp; Compatibility)',['../md_docs_2design__decisions_2migration__and__compatibility.html',1,'']]],
  ['მიმოხილვა_5',['Synapse ESP Framework — არქიტექტურის მიმოხილვა',['../md_docs_2design__decisions_2architecture__overview.html',1,'']]],
  ['მიმოხილვა_20project_20overview_6',['პროექტის მიმოხილვა (Project Overview)',['../index.html',1,'']]],
  ['მოდულარობის_20არქიტექტურული_20გადაწყვეტილებები_20extensibility_20modularity_7',['გაფართოებადობისა და მოდულარობის არქიტექტურული გადაწყვეტილებები (Extensibility &amp; Modularity)',['../md_docs_2design__decisions_2extensibility__and__modularity.html',1,'']]],
  ['მოდულების_20არქიტექტურა_20module_20architecture_8',['მოდულების არქიტექტურა (Module Architecture)',['../md_docs_2structure_2module__architecture.html',1,'']]],
  ['მოდულების_20ინიციალიზაციის_20დონეები_20initialization_20levels_9',['🚀 მოდულების ინიციალიზაციის დონეები (Initialization Levels)',['../md_docs_2convention_2initialization__levels.html',1,'']]],
  ['მოდულების_20ოპტიმიზაცია_20performance_20—_20display_20modules_10',['ეკრანის მოდულების ოპტიმიზაცია (Performance — Display Modules)',['../md_docs_2performance_2performance__display.html',1,'']]],
  ['მოდულის_20ავტომატური_20გენერატორი_11',['🚀 CREATE_MODULE.PY - ახალი მოდულის ავტომატური გენერატორი',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html',1,'']]],
  ['მოდულის_20გაფართოება_20ან_20ფუნქციონალის_20დამატება_20module_20extension_20feature_20addition_12',['მოდულის გაფართოება ან ფუნქციონალის დამატება (Module Extension &amp; Feature Addition)',['../md_docs_2tutorials_2module__extension.html',1,'']]],
  ['მოდულის_20გენერატორი_20v2_200_13',['🚀 create_module.py: Synapse მოდულის გენერატორი (v2.0)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html',1,'']]],
  ['მოდულის_20სიცოცხლის_20ციკლი_20და_20ინიციალიზაცია_20lifecycle_20initialization_14',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['მოდულის_20სტრუქტურის_20წესები_15',['მოდულის სტრუქტურის წესები',['../md_docs_2convention_2module__structure.html',1,'']]],
  ['მოდულის_20შექმნა_20create_20your_20first_20module_16',['პირველი საკუთარი მოდულის შექმნა (Create Your First Module)',['../md_docs_2tutorials_2create__first__module.html',1,'']]],
  ['მოდული_20tt_20rgb_5fled_5findicator_20tt_17',['💡 მოდული &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['მოდული_20tt_20wifi_5fmanager_20tt_18',['📶 მოდული &lt;tt&gt;wifi_manager&lt;/tt&gt;',['../md_components_2modules_2communications_2wifi__manager_2README.html',1,'']]],
  ['მოდული_3a_20command_20router_20system_20shell_19',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utilities_2command__router_2README.html',1,'']]],
  ['მოდული_3a_20health_20monitor_20',['მოდული: Health Monitor',['../md_components_2modules_2system_2health__monitor_2README.html',1,'']]],
  ['მოდული_3a_20ota_20update_20manager_21',['მოდული: OTA Update Manager',['../md_components_2modules_2system_2ota__update__manager_2README.html',1,'']]],
  ['მოდული_3a_20watchdog_20manager_22',['მოდული: Watchdog Manager',['../md_components_2modules_2system_2watchdog__manager_2README.html',1,'']]],
  ['მონაცემთა_20შენახვის_20არქიტექტურული_20არჩევანი_20storage_20strategy_23',['მონაცემთა შენახვის არქიტექტურული არჩევანი (Storage Strategy)',['../md_docs_2design__decisions_2storage__strategy.html',1,'']]]
];
