var searchData=
[
  ['template_0',['template',['../md_docs_2design__decisions_2decision__record__template.html',1,'არქიტექტურული გადაწყვეტილების ჩანაწერის შაბლონი (Decision Record Template)'],['../md_docs_2contributing_2issue__template.html',1,'Synapse Issue Template'],['../md_docs_2contributing_2pull__request__template.html',1,'Synapse Pull Request Template']]],
  ['the_20air_20module_20api_20reference_1',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['the_20framework_2',['ფრეიმვორქის გაფართოება და Best Practices (Extending the Framework)',['../md_docs_2structure_2extending__framework.html',1,'']]],
  ['time_20sync_20module_20api_20reference_3',['Synapse Time Sync Module API Reference',['../md_docs_2api__reference_2time__sync__api.html',1,'']]],
  ['timer_5ftest_20tt_4',['🧪 მოდული &lt;tt&gt;timer_test&lt;/tt&gt;',['../md_components_2modules_2testing_2timer__test__module_2README.html',1,'']]],
  ['trade_20offs_5',['წარმადობისა და რესურსების არქიტექტურული კომპრომისები (Performance Trade-offs)',['../md_docs_2design__decisions_2performance__tradeoffs.html',1,'']]],
  ['troubleshooting_20faq_6',['ხშირად დასმული კითხვები (Troubleshooting FAQ)',['../md_docs_2troubleshooting_2faq.html',1,'']]],
  ['tt_20ble_5fprovisioning_20tt_7',['📲 მოდული &lt;tt&gt;ble_provisioning&lt;/tt&gt;',['../md_components_2modules_2provisioning_2ble__provisioning_2README.html',1,'']]],
  ['tt_20check_5fconventions_20py_20tt_8',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['tt_20create_5fmodule_20py_20tt_20_3a_20synapse_20მოდულის_20გენერატორი_20v3_200_9',['🚀 &lt;tt&gt;create_module.py&lt;/tt&gt;: Synapse მოდულის გენერატორი (v3.0)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html',1,'']]],
  ['tt_20device_5fidentity_5fservice_20tt_10',['🆔 მოდული: &lt;tt&gt;device_identity_service&lt;/tt&gt;',['../md_components_2modules_2system_2device__identity__service_2README.html',1,'']]],
  ['tt_20mqtt_5fmanager_20tt_11',['☁️ მოდული: &lt;tt&gt;mqtt_manager&lt;/tt&gt;',['../md_components_2modules_2communications_2mqtt__manager_2README.html',1,'']]],
  ['tt_20relay_5factuator_20tt_12',['🔌 მოდული: &lt;tt&gt;relay_actuator&lt;/tt&gt;',['../md_components_2modules_2actuators_2relay__actuator_2README.html',1,'']]],
  ['tt_20rgb_5fled_5findicator_20tt_13',['💡 მოდული &lt;tt&gt;rgb_led_indicator&lt;/tt&gt;',['../md_components_2modules_2utilities_2rgb__led__indicator_2README.html',1,'']]],
  ['tt_20security_5fstatus_5freporter_20tt_14',['🛡️ მოდული: &lt;tt&gt;security_status_reporter&lt;/tt&gt;',['../md_components_2modules_2security_2security__status__reporter_2README.html',1,'']]],
  ['tt_20self_5ftest_5fmanager_20tt_15',['🩺 მოდული: &lt;tt&gt;self_test_manager&lt;/tt&gt;',['../md_components_2modules_2diagnostics_2self__test__manager_2README.html',1,'']]],
  ['tt_20sensor_5faggregator_20tt_16',['🌡️ მოდული: &lt;tt&gt;sensor_aggregator&lt;/tt&gt;',['../md_components_2modules_2sensors_2sensor__aggregator_2README.html',1,'']]],
  ['tt_20sensor_5fsimulator_20tt_17',['🧪 მოდული: &lt;tt&gt;sensor_simulator&lt;/tt&gt;',['../md_components_2modules_2testing_2sensor__simulator_2README.html',1,'']]],
  ['tt_20storage_5fmanager_20tt_18',['💾 მოდული &lt;tt&gt;storage_manager&lt;/tt&gt;',['../md_components_2modules_2storage_2storage__manager_2README.html',1,'']]],
  ['tt_20system_5ftimer_20tt_19',['⏱️ მოდული &lt;tt&gt;system_timer&lt;/tt&gt;',['../md_components_2modules_2utilities_2system__timer_2README.html',1,'']]],
  ['tt_20timer_5ftest_20tt_20',['🧪 მოდული &lt;tt&gt;timer_test&lt;/tt&gt;',['../md_components_2modules_2testing_2timer__test__module_2README.html',1,'']]],
  ['tt_20watchdog_5fmanager_20tt_21',['🐕 მოდული: &lt;tt&gt;watchdog_manager&lt;/tt&gt;',['../md_components_2modules_2system_2watchdog__manager_2README.html',1,'']]],
  ['tt_20wifi_5fmanager_20tt_22',['📶 მოდული &lt;tt&gt;wifi_manager&lt;/tt&gt;',['../md_components_2modules_2communications_2wifi__manager_2README.html',1,'']]]
];
