var searchData=
[
  ['changelog_0',['changelog',['../md_docs_2changelog_2v5.html',1,'ცვლილებების ისტორია (Changelog)'],['../md_docs_2changelog_2CHANGELOG__2025-06-28.html',1,'Changelog'],['../md_docs_2changelog_2v6.html',1,'CHANGELOG']]],
  ['changelog_202025_2006_2026_1',['CHANGELOG - 2025-06-26',['../md_docs_2changelog_2CHANGELOG__2025-06-26.html',1,'']]],
  ['changelog_3a_20led_5fblinker_20ინიციალიზაციის_20პრობლემის_20დიაგნოსტიკა_20და_20გამოსწორება_2',['CHANGELOG: led_blinker ინიციალიზაციის პრობლემის დიაგნოსტიკა და გამოსწორება',['../md_docs_2changelog_22025-06-26-led__blinker-nvs-debug.html',1,'']]],
  ['check_5fconventions_20py_20tt_3',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['checklist_4',['checklist',['../md_docs_2security_2security__checklist.html',1,'უსაფრთხოების შემოწმების სია (Security Checklist)'],['../md_docs_2internal_2synapse__checklist.html',1,'✅ Synapse Framework — Documentation &amp; Module Design Checklist']]],
  ['choices_5',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['cloud_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20cloud_6',['Cloud ინტეგრაციის სახელმძღვანელო (Integration — Cloud)',['../md_docs_2integration_2integration__cloud.html',1,'']]],
  ['code_7',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['code_20of_20conduct_8',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['command_20router_20api_20reference_9',['Synapse Command Router API Reference',['../md_docs_2api__reference_2command__router__api.html',1,'']]],
  ['command_20router_20system_20shell_10',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utilities_2command__router_2README.html',1,'']]],
  ['commit_20message_20guidelines_11',['Synapse Commit Message Guidelines',['../md_docs_2contributing_2commit__message__guidelines.html',1,'']]],
  ['common_20issues_20solutions_12',['გავრცელებული პრობლემები და გადაჭრის გზები (Common Issues &amp; Solutions)',['../md_docs_2troubleshooting_2common__issues.html',1,'']]],
  ['communication_20choices_13',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['communication_20module_20api_20reference_14',['📡 Synapse Communication Module API Reference',['../md_docs_2api__reference_2communication__api.html',1,'']]],
  ['communication_20patterns_15',['კომუნიკაციის პატერნები (Communication Patterns)',['../md_docs_2structure_2communication__patterns.html',1,'']]],
  ['compatibility_16',['მიგრაციისა და თავსებადობის არქიტექტურული გადაწყვეტილებები (Migration &amp; Compatibility)',['../md_docs_2design__decisions_2migration__and__compatibility.html',1,'']]],
  ['components_17',['components',['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['conduct_18',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['configuration_19',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['configuration_20flow_20',['კონფიგურაციის მართვის პროცესი (Configuration Flow)',['../md_docs_2structure_2configuration__flow.html',1,'']]],
  ['configuration_20manager_20api_20reference_21',['Synapse Configuration Manager API Reference',['../md_docs_2api__reference_2configuration__api.html',1,'']]],
  ['configuration_20storage_22',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['connectivity_20watchdog_23',['🛰️ მოდული: Connectivity Watchdog',['../md_components_2modules_2system_2connectivity__watchdog_2README.html',1,'']]],
  ['considerations_24',['უსაფრთხოების არქიტექტურული გადაწყვეტილებები (Security Considerations)',['../md_docs_2design__decisions_2security__considerations.html',1,'']]],
  ['contributing_20guide_25',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['contributing_20reference_20index_26',['Synapse Contributing Reference Index',['../md_docs_2contributing_2contributing__index.html',1,'']]],
  ['control_20module_20api_20reference_27',['Synapse Local Control Module API Reference',['../md_docs_2api__reference_2local__ctrl__api.html',1,'']]],
  ['convention_20reference_20index_28',['Synapse Convention Reference Index',['../md_docs_2convention_2convention__index.html',1,'']]],
  ['core_20კომპონენტები_20core_20components_29',['core კომპონენტები core components',['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['core_20api_20reference_30',['Synapse Core API Reference',['../md_docs_2api__reference_2core__api.html',1,'']]],
  ['create_20your_20first_20module_31',['პირველი საკუთარი მოდულის შექმნა (Create Your First Module)',['../md_docs_2tutorials_2create__first__module.html',1,'']]],
  ['create_5fmodule_20py_20ახალი_20მოდულის_20ავტომატური_20გენერატორი_32',['🚀 CREATE_MODULE.PY - ახალი მოდულის ავტომატური გენერატორი',['../md_docs_2CREATE__MODULE__DOCUMENTATION.html',1,'']]],
  ['create_5fmodule_20py_20tt_20_3a_20synapse_20მოდულის_20გენერატორი_20v3_200_33',['🚀 &lt;tt&gt;create_module.py&lt;/tt&gt;: Synapse მოდულის გენერატორი (v3.0)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html',1,'']]],
  ['custom_20api_20reference_34',['Synapse Custom API Reference',['../md_docs_2api__reference_2custom__api.html',1,'']]]
];
