var searchData=
[
  ['actuators_20module_20api_20reference_0',['Synapse Actuators Module API Reference',['../md_docs_2api__reference_2actuators__api.html',1,'']]],
  ['addition_1',['მოდულის გაფართოება ან ფუნქციონალის დამატება (Module Extension &amp; Feature Addition)',['../md_docs_2tutorials_2module__extension.html',1,'']]],
  ['advanced_20diagnostics_20გაფართოებული_20დიაგნოსტიკა_2',['Advanced Diagnostics (გაფართოებული დიაგნოსტიკა)',['../md_docs_2troubleshooting_2advanced__diagnostics.html',1,'']]],
  ['advanced_20usage_20გაფართოებული_20გამოყენება_3',['Advanced Usage (გაფართოებული გამოყენება)',['../md_docs_2tutorials_2advanced__usage.html',1,'']]],
  ['air_20module_20api_20reference_4',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['api_5',['api',['../md_docs_2glossary_2api.html',1,'']]],
  ['api_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20rest_20api_6',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['api_20რეფერენსი_3a_20event_20payloads_20event_5fpayloads_20h_7',['API რეფერენსი: Event Payloads (event_payloads.h)',['../md_docs_2api__reference_2event__payloads__api.html',1,'']]],
  ['api_20სა_20და_20კოდის_20ტერმინები_20glossary_20—_20api_20code_8',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['api_20reference_9',['api reference',['../md_docs_2api__reference_2actuators__api.html',1,'Synapse Actuators Module API Reference'],['../md_docs_2api__reference_2command__router__api.html',1,'Synapse Command Router API Reference'],['../md_docs_2api__reference_2communication__api.html',1,'Synapse Communication Module API Reference'],['../md_docs_2api__reference_2configuration__api.html',1,'Synapse Configuration Manager API Reference'],['../md_docs_2api__reference_2core__api.html',1,'Synapse Core API Reference'],['../md_docs_2api__reference_2custom__api.html',1,'Synapse Custom API Reference'],['../md_docs_2api__reference_2display__api.html',1,'Synapse Display Module API Reference'],['../md_docs_2api__reference_2drivers__api.html',1,'Synapse Drivers Module API Reference'],['../md_docs_2api__reference_2event__api.html',1,'Synapse Event Bus API Reference'],['../md_docs_2api__reference_2health__monitor__api.html',1,'Synapse Health Monitor Module API Reference'],['../md_docs_2api__reference_2local__ctrl__api.html',1,'Synapse Local Control Module API Reference'],['../md_docs_2api__reference_2module__api.html',1,'Synapse Module API Reference'],['../md_docs_2api__reference_2ota__api.html',1,'Synapse OTA (Over-the-Air) Module API Reference'],['../md_docs_2api__reference_2provisioning__api.html',1,'Synapse Provisioning Module API Reference'],['../md_docs_2api__reference_2resource__manager__api.html',1,'Synapse Resource Manager API Reference'],['../md_docs_2api__reference_2sensor__api.html',1,'Synapse Sensor Module API Reference'],['../md_docs_2api__reference_2storage__api.html',1,'Synapse Storage Module API Reference'],['../md_docs_2api__reference_2system__api.html',1,'Synapse System Module API Reference'],['../md_docs_2api__reference_2time__sync__api.html',1,'Synapse Time Sync Module API Reference'],['../md_docs_2api__reference_2utility__api.html',1,'Synapse Utility Module API Reference'],['../md_docs_2api__reference_2version__api.html',1,'Synapse Version Module API Reference']]],
  ['api_20reference_20index_10',['Synapse API Reference Index',['../md_docs_2api__reference_2api__index.html',1,'']]],
  ['architecture_11',['architecture',['../md_docs_2glossary_2glossary__architecture.html',1,'არქიტექტურული ტერმინები (Glossary — Architecture)'],['../md_docs_2structure_2module__architecture.html',1,'მოდულების არქიტექტურა (Module Architecture)']]]
];
