var searchData=
[
  ['security_20best_20practices_0',['უსაფრთხოების საუკეთესო პრაქტიკები (Security Best Practices)',['../md_docs_2security_2security__best__practices.html',1,'']]],
  ['security_20checklist_1',['უსაფრთხოების შემოწმების სია (Security Checklist)',['../md_docs_2security_2security__checklist.html',1,'']]],
  ['security_20considerations_2',['უსაფრთხოების არქიტექტურული გადაწყვეტილებები (Security Considerations)',['../md_docs_2design__decisions_2security__considerations.html',1,'']]],
  ['security_20guidelines_3',['უსაფრთხოების სახელმძღვანელოები (Security Guidelines)',['../md_docs_2security_2security__guidelines.html',1,'']]],
  ['security_20index_20უსაფრთხოების_20სახელმძღვანელოების_20ინდექსი_4',['Security Index (უსაფრთხოების სახელმძღვანელოების ინდექსი)',['../md_docs_2security_2security__index.html',1,'']]],
  ['security_20performance_5',['უსაფრთხოების და წარმადობის ტერმინები (Glossary — Security &amp; Performance)',['../md_docs_2glossary_2glossary__security.html',1,'']]],
  ['sensor_20module_20api_20reference_6',['Synapse Sensor Module API Reference',['../md_docs_2api__reference_2sensor__api.html',1,'']]],
  ['setup_20guide_7',['Synapse Local Setup Guide',['../md_docs_2contributing_2local__setup.html',1,'']]],
  ['shell_8',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utilities_2command__router_2README.html',1,'']]],
  ['solutions_9',['გავრცელებული პრობლემები და გადაჭრის გზები (Common Issues &amp; Solutions)',['../md_docs_2troubleshooting_2common__issues.html',1,'']]],
  ['started_10',['სწრაფი სტარტი (Getting Started)',['../md_docs_2tutorials_2getting__started.html',1,'']]],
  ['storage_11',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['storage_20module_20api_20reference_12',['Synapse Storage Module API Reference',['../md_docs_2api__reference_2storage__api.html',1,'']]],
  ['storage_20strategy_13',['მონაცემთა შენახვის არქიტექტურული არჩევანი (Storage Strategy)',['../md_docs_2design__decisions_2storage__strategy.html',1,'']]],
  ['strategy_14',['strategy',['../md_docs_2design__decisions_2storage__strategy.html',1,'მონაცემთა შენახვის არქიტექტურული არჩევანი (Storage Strategy)'],['../md_docs_2contributing_2branching__strategy.html',1,'Synapse Branching Strategy']]],
  ['structure_15',['საქაღალდეებისა და ფაილების სტრუქტურა (Directory Structure)',['../md_docs_2structure_2directory__structure.html',1,'']]],
  ['synapse_20მოდულის_20გენერატორი_20v2_200_16',['🚀 create_module.py: Synapse მოდულის გენერატორი (v2.0)',['../md_docs_2scripts_2CREATE__MODULE__DOCUMENTATION.html',1,'']]],
  ['synapse_20actuators_20module_20api_20reference_17',['Synapse Actuators Module API Reference',['../md_docs_2api__reference_2actuators__api.html',1,'']]],
  ['synapse_20api_20reference_20index_18',['Synapse API Reference Index',['../md_docs_2api__reference_2api__index.html',1,'']]],
  ['synapse_20branching_20strategy_19',['Synapse Branching Strategy',['../md_docs_2contributing_2branching__strategy.html',1,'']]],
  ['synapse_20command_20router_20api_20reference_20',['Synapse Command Router API Reference',['../md_docs_2api__reference_2command__router__api.html',1,'']]],
  ['synapse_20commit_20message_20guidelines_21',['Synapse Commit Message Guidelines',['../md_docs_2contributing_2commit__message__guidelines.html',1,'']]],
  ['synapse_20communication_20module_20api_20reference_22',['Synapse Communication Module API Reference',['../md_docs_2api__reference_2communication__api.html',1,'']]],
  ['synapse_20configuration_20manager_20api_20reference_23',['Synapse Configuration Manager API Reference',['../md_docs_2api__reference_2configuration__api.html',1,'']]],
  ['synapse_20contributing_20reference_20index_24',['Synapse Contributing Reference Index',['../md_docs_2contributing_2contributing__index.html',1,'']]],
  ['synapse_20convention_20reference_20index_25',['Synapse Convention Reference Index',['../md_docs_2convention_2convention__index.html',1,'']]],
  ['synapse_20core_20api_20reference_26',['Synapse Core API Reference',['../md_docs_2api__reference_2core__api.html',1,'']]],
  ['synapse_20custom_20api_20reference_27',['Synapse Custom API Reference',['../md_docs_2api__reference_2custom__api.html',1,'']]],
  ['synapse_20design_20decisions_28',['Synapse Design Decisions',['../md_docs_2design__decisions_2design__decisions__index.html',1,'']]],
  ['synapse_20display_20module_20api_20reference_29',['Synapse Display Module API Reference',['../md_docs_2api__reference_2display__api.html',1,'']]],
  ['synapse_20drivers_20module_20api_20reference_30',['Synapse Drivers Module API Reference',['../md_docs_2api__reference_2drivers__api.html',1,'']]],
  ['synapse_20esp_20framework_20—_20არქიტექტურის_20მიმოხილვა_31',['Synapse ESP Framework — არქიტექტურის მიმოხილვა',['../md_docs_2design__decisions_2architecture__overview.html',1,'']]],
  ['synapse_20event_20bus_20api_20reference_32',['Synapse Event Bus API Reference',['../md_docs_2api__reference_2event__api.html',1,'']]],
  ['synapse_20framework_20—_20documentation_20module_20design_20checklist_33',['✅ Synapse Framework — Documentation &amp; Module Design Checklist',['../md_docs_2internal_2synapse__checklist.html',1,'']]],
  ['synapse_20health_20monitor_20module_20api_20reference_34',['Synapse Health Monitor Module API Reference',['../md_docs_2api__reference_2health__monitor__api.html',1,'']]],
  ['synapse_20issue_20template_35',['Synapse Issue Template',['../md_docs_2contributing_2issue__template.html',1,'']]],
  ['synapse_20local_20control_20module_20api_20reference_36',['Synapse Local Control Module API Reference',['../md_docs_2api__reference_2local__ctrl__api.html',1,'']]],
  ['synapse_20local_20setup_20guide_37',['Synapse Local Setup Guide',['../md_docs_2contributing_2local__setup.html',1,'']]],
  ['synapse_20module_20api_20reference_38',['Synapse Module API Reference',['../md_docs_2api__reference_2module__api.html',1,'']]],
  ['synapse_20ota_20over_20the_20air_20module_20api_20reference_39',['Synapse OTA (Over-the-Air) Module API Reference',['../md_docs_2api__reference_2ota__api.html',1,'']]],
  ['synapse_20provisioning_20module_20api_20reference_40',['Synapse Provisioning Module API Reference',['../md_docs_2api__reference_2provisioning__api.html',1,'']]],
  ['synapse_20pull_20request_20template_41',['Synapse Pull Request Template',['../md_docs_2contributing_2pull__request__template.html',1,'']]],
  ['synapse_20resource_20manager_20api_20reference_42',['Synapse Resource Manager API Reference',['../md_docs_2api__reference_2resource__manager__api.html',1,'']]],
  ['synapse_20review_20guidelines_43',['Synapse Review Guidelines',['../md_docs_2contributing_2review__guidelines.html',1,'']]],
  ['synapse_20sensor_20module_20api_20reference_44',['Synapse Sensor Module API Reference',['../md_docs_2api__reference_2sensor__api.html',1,'']]],
  ['synapse_20storage_20module_20api_20reference_45',['Synapse Storage Module API Reference',['../md_docs_2api__reference_2storage__api.html',1,'']]],
  ['synapse_20system_20module_20api_20reference_46',['Synapse System Module API Reference',['../md_docs_2api__reference_2system__api.html',1,'']]],
  ['synapse_20time_20sync_20module_20api_20reference_47',['Synapse Time Sync Module API Reference',['../md_docs_2api__reference_2time__sync__api.html',1,'']]],
  ['synapse_20utility_20module_20api_20reference_48',['Synapse Utility Module API Reference',['../md_docs_2api__reference_2utility__api.html',1,'']]],
  ['synapse_20version_20module_20api_20reference_49',['Synapse Version Module API Reference',['../md_docs_2api__reference_2version__api.html',1,'']]],
  ['sync_20module_20api_20reference_50',['Synapse Time Sync Module API Reference',['../md_docs_2api__reference_2time__sync__api.html',1,'']]],
  ['system_20configuration_51',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['system_20module_20api_20reference_52',['Synapse System Module API Reference',['../md_docs_2api__reference_2system__api.html',1,'']]],
  ['system_20shell_53',['⚙️ მოდული: Command Router &amp; System Shell',['../md_components_2modules_2utilities_2command__router_2README.html',1,'']]]
];
