var searchData=
[
  ['check_5fconventions_20py_20tt_0',['კონვენციების ავტომატური შემმოწმებელი (&lt;tt&gt;check_conventions.py&lt;/tt&gt;)',['../md_docs_2contributing_2convention__linter__guide.html',1,'']]],
  ['checklist_1',['checklist',['../md_docs_2security_2security__checklist.html',1,'უსაფრთხოების შემოწმების სია (Security Checklist)'],['../md_docs_2internal_2synapse__checklist.html',1,'✅ Synapse Framework — Documentation &amp; Module Design Checklist']]],
  ['choices_2',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['cloud_20ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20cloud_3',['Cloud ინტეგრაციის სახელმძღვანელო (Integration — Cloud)',['../md_docs_2integration_2integration__cloud.html',1,'']]],
  ['code_4',['API-სა და კოდის ტერმინები (Glossary — API &amp; Code)',['../md_docs_2glossary_2glossary__api.html',1,'']]],
  ['code_20of_20conduct_5',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['commit_20message_20guidelines_6',['Synapse Commit Message Guidelines',['../md_docs_2contributing_2commit__message__guidelines.html',1,'']]],
  ['common_20issues_20solutions_7',['გავრცელებული პრობლემები და გადაჭრის გზები (Common Issues &amp; Solutions)',['../md_docs_2troubleshooting_2common__issues.html',1,'']]],
  ['communication_20choices_8',['კომუნიკაციის არქიტექტურული არჩევანი (Communication Choices)',['../md_docs_2design__decisions_2communication__choices.html',1,'']]],
  ['communication_20module_20api_20reference_9',['Synapse Communication Module API Reference',['../md_docs_2api__reference_2communication__api.html',1,'']]],
  ['communication_20patterns_10',['კომუნიკაციის პატერნები (Communication Patterns)',['../md_docs_2structure_2communication__patterns.html',1,'']]],
  ['compatibility_11',['მიგრაციისა და თავსებადობის არქიტექტურული გადაწყვეტილებები (Migration &amp; Compatibility)',['../md_docs_2design__decisions_2migration__and__compatibility.html',1,'']]],
  ['components_12',['components',['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['conduct_13',['ქცევის კოდექსი (Code of Conduct)',['../md_docs_2contributing_2code__of__conduct.html',1,'']]],
  ['configuration_14',['სისტემის კონფიგურაცია (System Configuration)',['../md_docs_2tutorials_2system__configuration.html',1,'']]],
  ['configuration_20flow_15',['კონფიგურაციის მართვის პროცესი (Configuration Flow)',['../md_docs_2structure_2configuration__flow.html',1,'']]],
  ['configuration_20manager_20api_20reference_16',['Synapse Configuration Manager API Reference',['../md_docs_2api__reference_2configuration__api.html',1,'']]],
  ['configuration_20storage_17',['კონფიგურაციისა და შენახვის ტერმინები (Glossary — Configuration &amp; Storage)',['../md_docs_2glossary_2glossary__config.html',1,'']]],
  ['considerations_18',['უსაფრთხოების არქიტექტურული გადაწყვეტილებები (Security Considerations)',['../md_docs_2design__decisions_2security__considerations.html',1,'']]],
  ['contributing_20guide_19',['კონტრიბუციის სახელმძღვანელო (Contributing Guide)',['../md_docs_2contributing_2contributing__guide.html',1,'']]],
  ['contributing_20reference_20index_20',['Synapse Contributing Reference Index',['../md_docs_2contributing_2contributing__index.html',1,'']]],
  ['control_20module_20api_20reference_21',['Synapse Local Control Module API Reference',['../md_docs_2api__reference_2local__ctrl__api.html',1,'']]],
  ['convention_20reference_20index_22',['Synapse Convention Reference Index',['../md_docs_2convention_2convention__index.html',1,'']]],
  ['core_20კომპონენტები_20core_20components_23',['core კომპონენტები core components',['../md_docs_2design__decisions_2core__components.html',1,'Core კომპონენტები (Core Components)'],['../md_docs_2structure_2core__components.html',1,'Core კომპონენტები (Core Components)']]],
  ['core_20api_20reference_24',['Synapse Core API Reference',['../md_docs_2api__reference_2core__api.html',1,'']]],
  ['create_20your_20first_20module_25',['პირველი საკუთარი მოდულის შექმნა (Create Your First Module)',['../md_docs_2tutorials_2create__first__module.html',1,'']]],
  ['custom_20api_20reference_26',['Synapse Custom API Reference',['../md_docs_2api__reference_2custom__api.html',1,'']]]
];
