var searchData=
[
  ['იბილდება_0',['პრობლემა: მოდული არ იბილდება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1300',1,'']]],
  ['იბილდება_20ჩემი_20მოდული_1',['1. რატომ არ იბილდება ჩემი მოდული?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1334',1,'']]],
  ['იდენტიფიკატორი_2',['Custom Event-ის იდენტიფიკატორი',['../md_docs_2api__reference_2custom__api.html#autotoc_md114',1,'']]],
  ['იზოლაცია_3',['ძირითადი პრინციპი: მაქსიმალური იზოლაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md600',1,'']]],
  ['იზოლაცია_20ყველაზე_20მნიშვნელოვანი_20შემოწმება_20_3a_20strong_4',['✅ &lt;strong&gt;მოდულების იზოლაცია (ყველაზე მნიშვნელოვანი შემოწმება):&lt;/strong&gt;',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md500',1,'']]],
  ['ით_20api_20არ_20იძებნება_5',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1309',1,'']]],
  ['იკითხება_6',['პრობლემა: შეცდომის კოდი არ იკითხება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1313',1,'']]],
  ['იმავე_20ტიპის_20რამდენიმე_20მოდულის_20დამატება_7',['2. შეიძლება თუ არა ერთი და იმავე ტიპის რამდენიმე მოდულის დამატება?',['../md_docs_2structure_2faq.html#autotoc_md1244',1,'']]],
  ['იმპლემენტაცია_8',['სწორი იმპლემენტაცია',['../md_docs_2convention_2communication__patterns.html#autotoc_md611',1,'']]],
  ['ინდექსი_9',['ინდექსი',['../md_docs_2integration_2integration__index.html',1,'Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)'],['../md_docs_2security_2security__index.html',1,'Security Index (უსაფრთხოების სახელმძღვანელოების ინდექსი)']]],
  ['ინიციალიზაცია_20lifecycle_20initialization_10',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['ინიციალიზდება_11',['პრობლემა: მოდული არ ინიციალიზდება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1304',1,'']]],
  ['ინიციალიზდება_20მოდული_12',['5. რატომ არ ინიციალიზდება მოდული?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1338',1,'']]],
  ['ინსტალაცია_13',['ESP-IDF-ის ინსტალაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md544',1,'']]],
  ['ინსტრუმენტები_14',['8. დამატებითი ინსტრუმენტები',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1331',1,'']]],
  ['ინტეგრაცია_20github_20actions_20თან_20ავტომატური_20შემოწმება_15',['4. ინტეგრაცია GitHub Actions-თან (ავტომატური შემოწმება)',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md503',1,'']]],
  ['ინტეგრაციის_20მაგალითი_16',['ინტეგრაციის მაგალითი',['../tutorials_docs.html#tut_integration_sec',1,'']]],
  ['ინტეგრაციის_20მაგალითი_20integration_20example_17',['ინტეგრაციის მაგალითი (Integration Example)',['../md_docs_2tutorials_2integration__example.html',1,'']]],
  ['ინტეგრაციის_20საჭიროების_20განსაზღვრა_18',['1. ინტეგრაციის საჭიროების განსაზღვრა',['../md_docs_2tutorials_2integration__example.html#autotoc_md1375',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელოების_20ინდექსი_19',['Integration Index (ინტეგრაციის სახელმძღვანელოების ინდექსი)',['../md_docs_2integration_2integration__index.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელოები_20',['თემატური ინტეგრაციის სახელმძღვანელოები',['../md_docs_2integration_2integration__index.html#autotoc_md999',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20cloud_21',['Cloud ინტეგრაციის სახელმძღვანელო (Integration — Cloud)',['../md_docs_2integration_2integration__cloud.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20mqtt_22',['MQTT ინტეგრაციის სახელმძღვანელო (Integration — MQTT)',['../md_docs_2integration_2integration__mqtt.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20rest_20api_23',['REST API ინტეგრაციის სახელმძღვანელო (Integration — REST API)',['../md_docs_2integration_2integration__rest.html',1,'']]],
  ['ინტეგრაციის_20სახელმძღვანელო_20integration_20—_20websocket_24',['WebSocket ინტეგრაციის სახელმძღვანელო (Integration — WebSocket)',['../md_docs_2integration_2integration__websocket.html',1,'']]],
  ['ინტერპრეტაცია_25',['შედეგების ინტერპრეტაცია',['../md_docs_2contributing_2convention__linter__guide.html#autotoc_md502',1,'']]],
  ['ინფორმაცია_26',['ინფორმაცია',['../md_docs_2contributing_2issue__template.html#autotoc_md532',1,'გარემოს ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md534',1,'დამატებითი ინფორმაცია'],['../md_docs_2contributing_2pull__request__template.html#autotoc_md570',1,'დამატებითი ინფორმაცია'],['../md_docs_2security_2security__vulnerability__disclosure.html#autotoc_md1182',1,'საკონტაქტო ინფორმაცია'],['../md_docs_2contributing_2pull__request__template.html#autotoc_md562',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2issue__template.html#autotoc_md522',1,'ძირითადი ინფორმაცია'],['../md_docs_2contributing_2faq.html#autotoc_md513',1,'7. სად ვიპოვო დოკუმენტაციის სტრუქტურის და სტანდარტების შესახებ ინფორმაცია?']]],
  ['ისთვის_27',['ისთვის',['../md_docs_2api__reference_2display__api.html#autotoc_md132',1,'Service API (Service Locator-ისთვის)'],['../md_docs_2api__reference_2module__api.html#autotoc_md229',1,'Service API (Service Locator-ისთვის)']]],
  ['ის_20აღწერისა_3a_28',['მაგალითი Custom Event-ის აღწერისა:',['../md_docs_2api__reference_2event__api.html#autotoc_md180',1,'']]],
  ['ის_20გამოყენება_29',['ის გამოყენება',['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1113',1,'CPU-ის გამოყენება'],['../md_docs_2convention_2communication__patterns.html#autotoc_md620',1,'Event Bus-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1112',1,'Flash-ის გამოყენება'],['../md_docs_2design__decisions_2extensibility__and__modularity.html#autotoc_md867',1,'Public API-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1111',1,'RAM-ის გამოყენება'],['../md_docs_2convention_2communication__patterns.html#autotoc_md619',1,'Service Locator-ის გამოყენება'],['../md_docs_2performance_2performance__resource__usage.html#autotoc_md1114',1,'Stack-ის გამოყენება']]],
  ['ის_20იდენტიფიკატორი_30',['Custom Event-ის იდენტიფიკატორი',['../md_docs_2api__reference_2custom__api.html#autotoc_md114',1,'']]],
  ['ის_20ინსტალაცია_31',['ESP-IDF-ის ინსტალაცია',['../md_docs_2contributing_2local__setup.html#autotoc_md544',1,'']]],
  ['ის_20კონფიგურაცია_32',['2. Debug Build-ის კონფიგურაცია',['../md_docs_2troubleshooting_2debugging__guide.html#autotoc_md1325',1,'']]],
  ['ის_20მაგალითი_33',['Event Handler-ის მაგალითი',['../md_docs_2api__reference_2event__api.html#autotoc_md182',1,'']]],
  ['ის_20მიმოხილვა_34',['4. Pull Request-ის მიმოხილვა',['../md_docs_2contributing_2contributing__guide.html#autotoc_md485',1,'']]],
  ['ის_20მონაცემების_20სტრუქტურა_35',['Custom Event-ის მონაცემების სტრუქტურა',['../md_docs_2api__reference_2custom__api.html#autotoc_md115',1,'']]],
  ['ის_20მონიშვნა_36',['Deprecated API-ის მონიშვნა',['../md_docs_2design__decisions_2migration__and__compatibility.html#autotoc_md887',1,'']]],
  ['ის_20ოპტიმიზაცია_37',['Refresh interval-ის ოპტიმიზაცია',['../md_docs_2performance_2performance__display.html#autotoc_md1074',1,'']]],
  ['ის_20როლი_38',['1. system_config.json-ის როლი',['../md_docs_2tutorials_2system__configuration.html#autotoc_md1397',1,'']]],
  ['ის_20სტანდარტები_39',['Logging-ის სტანდარტები',['../md_docs_2convention_2logging__standards.html',1,'']]],
  ['ის_20წერის_20წესები_40',['Footer-ის წერის წესები',['../md_docs_2contributing_2commit__message__guidelines.html#autotoc_md473',1,'']]],
  ['ის_20წესები_41',['ის წესები',['../contributing_docs.html#contrib_commit_sec',1,'Commit Message-ის წესები'],['../md_docs_2convention_2error__handling.html',1,'Error Handling-ის წესები']]],
  ['იძებნება_42',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1309',1,'']]],
  ['იწვევს_20პრობლემას_43',['6. როგორ გავიგო რომელი მოდული იწვევს პრობლემას?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1339',1,'']]],
  ['ი_20ჩემს_20სერვისს_44',['3. რატომ ვერ პოულობს Service Locator-ი ჩემს სერვისს?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1336',1,'']]]
];
