var searchData=
[
  ['latency_0',['MQTT publish latency',['../md_docs_2performance_2performance__benchmarks.html#autotoc_md1049',1,'']]],
  ['layout_1',['სტანდარტული მოდულის layout',['../md_docs_2convention_2module__structure.html#autotoc_md734',1,'']]],
  ['lazy_20initialization_2',['lazy initialization',['../md_docs_2performance_2performance__optimization.html#autotoc_md1101',1,'Lazy initialization'],['../md_docs_2design__decisions_2performance__tradeoffs.html#autotoc_md909',1,'Lazy initialization']]],
  ['lcd_20display_20configuration_3',['3. LCD Display Configuration',['../md_docs_2convention_2configuration__management.html#autotoc_md631',1,'']]],
  ['leak_4',['leak',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1317',1,'პრობლემა: რესურსების გაჟონვა (memory leak)'],['../md_docs_2troubleshooting_2advanced__diagnostics.html#autotoc_md1289',1,'2. Heap Corruption და Memory Leak'],['../md_docs_2troubleshooting_2faq.html#autotoc_md1340',1,'7. როგორ გამოვასწორო რესურსების გაჟონვა (memory leak)?']]],
  ['level_5',['level',['../md_docs_2convention_2logging__standards.html#autotoc_md709',1,'1. ESP_LOGE - Error Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md710',1,'2. ESP_LOGW - Warning Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md711',1,'3. ESP_LOGI - Info Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md712',1,'4. ESP_LOGD - Debug Level'],['../md_docs_2convention_2logging__standards.html#autotoc_md713',1,'5. ESP_LOGV - Verbose Level']]],
  ['levels_6',['levels',['../md_docs_2convention_2error__handling.html#autotoc_md678',1,'1. Error Levels'],['../md_docs_2convention_2logging__standards.html#autotoc_md708',1,'Log Levels']]],
  ['lifecycle_7',['lifecycle',['../md_docs_2structure_2module__architecture.html#autotoc_md1270',1,'მოდულის სიცოცხლის ციკლი (Lifecycle)'],['../md_docs_2api__reference_2module__api.html#autotoc_md222',1,'Module Creation &amp; Lifecycle']]],
  ['lifecycle_20ფუნქციები_8',['1. Module Lifecycle ფუნქციები',['../md_docs_2convention_2function__naming.html#autotoc_md698',1,'']]],
  ['lifecycle_20initialization_9',['მოდულის სიცოცხლის ციკლი და ინიციალიზაცია (Lifecycle &amp; Initialization)',['../md_docs_2structure_2lifecycle__and__init.html',1,'']]],
  ['lifecycle_20logging_10',['1. Module Lifecycle Logging',['../md_docs_2convention_2logging__standards.html#autotoc_md715',1,'']]],
  ['line_11',['line',['../md_docs_2api__reference_2display__api.html#autotoc_md136',1,'esp_err_t ssd1306_api_write_text(const char *text, uint8_t line);'],['../md_docs_2api__reference_2module__api.html#autotoc_md233',1,'esp_err_t {module_name}_api_write_text(const char *text, uint8_t line);']]],
  ['list_12',['Deprecated List',['../deprecated.html',1,'']]],
  ['local_20control_20module_20api_13',['Local Control Module API',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md208',1,'']]],
  ['local_20control_20module_20api_20reference_14',['Synapse Local Control Module API Reference',['../md_docs_2api__reference_2local__ctrl__api.html',1,'']]],
  ['local_20setup_20guide_15',['Synapse Local Setup Guide',['../md_docs_2contributing_2local__setup.html',1,'']]],
  ['local_5fctrl_5fhandle_5fevent_20module_5ft_20module_20int32_5ft_20event_5fid_20void_20event_5fdata_16',['static void local_ctrl_handle_event(module_t *module, int32_t event_id, void *event_data);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md215',1,'']]],
  ['local_5fctrl_5fhandler_5ft_20handler_17',['esp_err_t local_ctrl_module_register_endpoint(const char *uri, http_method_t method, local_ctrl_handler_t handler);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md212',1,'']]],
  ['local_5fctrl_5fmodule_5fcreate_20const_20cjson_20config_18',['module_t *local_ctrl_module_create(const cJSON *config);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md209',1,'']]],
  ['local_5fctrl_5fmodule_5fregister_5fendpoint_20const_20char_20uri_20http_5fmethod_5ft_20method_20local_5fctrl_5fhandler_5ft_20handler_19',['esp_err_t local_ctrl_module_register_endpoint(const char *uri, http_method_t method, local_ctrl_handler_t handler);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md212',1,'']]],
  ['local_5fctrl_5fmodule_5fstart_20module_5ft_20module_20',['esp_err_t local_ctrl_module_start(module_t *module);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md210',1,'']]],
  ['local_5fctrl_5fmodule_5fstop_20module_5ft_20module_21',['esp_err_t local_ctrl_module_stop(module_t *module);',['../md_docs_2api__reference_2local__ctrl__api.html#autotoc_md211',1,'']]],
  ['locator_22',['locator',['../md_docs_2structure_2core__components.html#autotoc_md1210',1,'1. Service Locator'],['../md_docs_2design__decisions_2core__components.html#autotoc_md806',1,'1. Service Locator'],['../md_docs_2convention_2function__naming.html#autotoc_md692',1,'1. Service Locator'],['../md_docs_2convention_2communication__patterns.html#autotoc_md605',1,'Direct API Communication (Service Locator)'],['../md_docs_2structure_2communication__patterns.html#autotoc_md1194',1,'Service Locator'],['../md_docs_2design__decisions_2communication__choices.html#autotoc_md794',1,'Service Locator'],['../md_docs_2convention_2variable__naming.html#autotoc_md753',1,'Service Locator']]],
  ['locator_20ით_20api_20არ_20იძებნება_23',['პრობლემა: Service Locator-ით API არ იძებნება',['../md_docs_2troubleshooting_2common__issues.html#autotoc_md1309',1,'']]],
  ['locator_20ისთვის_24',['locator ისთვის',['../md_docs_2api__reference_2display__api.html#autotoc_md132',1,'Service API (Service Locator-ისთვის)'],['../md_docs_2api__reference_2module__api.html#autotoc_md229',1,'Service API (Service Locator-ისთვის)']]],
  ['locator_20ის_20გამოყენება_25',['Service Locator-ის გამოყენება',['../md_docs_2convention_2communication__patterns.html#autotoc_md619',1,'']]],
  ['locator_20ი_20ჩემს_20სერვისს_26',['3. რატომ ვერ პოულობს Service Locator-ი ჩემს სერვისს?',['../md_docs_2troubleshooting_2faq.html#autotoc_md1336',1,'']]],
  ['locator_20კონფიგურაცია_27',['Service Locator კონფიგურაცია',['../group__ServiceLocatorConfig.html',1,'']]],
  ['locator_20api_28',['Service Locator API',['../md_docs_2api__reference_2core__api.html#autotoc_md80',1,'']]],
  ['locator_20error_20handling_29',['3. Service Locator Error Handling',['../md_docs_2convention_2error__handling.html#autotoc_md671',1,'']]],
  ['locator_20pattern_30',['locator pattern',['../md_docs_2convention_2communication__patterns.html#autotoc_md602',1,'1. Service Locator Pattern'],['../md_docs_2structure_2communication__patterns.html#autotoc_md1189',1,'1. Service Locator Pattern']]],
  ['locator_20usage_31',['Service Locator Usage',['../md_docs_2convention_2communication__patterns.html#autotoc_md612',1,'']]],
  ['log_20levels_32',['Log Levels',['../md_docs_2convention_2logging__standards.html#autotoc_md708',1,'']]],
  ['log_20message_20format_20standards_33',['Log Message Format Standards',['../md_docs_2convention_2logging__standards.html#autotoc_md727',1,'']]],
  ['logger_20module_20api_34',['Logger Module API',['../md_docs_2api__reference_2utility__api.html#autotoc_md391',1,'']]],
  ['logger_5fmodule_5fcreate_20const_20cjson_20config_35',['module_t *logger_module_create(const cJSON *config);',['../md_docs_2api__reference_2utility__api.html#autotoc_md392',1,'']]],
  ['logger_5fmodule_5flog_5ferror_20const_20char_20message_36',['esp_err_t logger_module_log_error(const char *message);',['../md_docs_2api__reference_2utility__api.html#autotoc_md395',1,'']]],
  ['logger_5fmodule_5flog_5finfo_20const_20char_20message_37',['esp_err_t logger_module_log_info(const char *message);',['../md_docs_2api__reference_2utility__api.html#autotoc_md393',1,'']]],
  ['logger_5fmodule_5flog_5fwarning_20const_20char_20message_38',['esp_err_t logger_module_log_warning(const char *message);',['../md_docs_2api__reference_2utility__api.html#autotoc_md394',1,'']]],
  ['logging_39',['logging',['../md_docs_2structure_2error__handling__and__logging.html',1,'შეცდომების დამუშავება და ლოგირების სტანდარტები (Error Handling &amp; Logging)'],['../md_docs_2convention_2logging__standards.html#autotoc_md715',1,'1. Module Lifecycle Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md716',1,'2. Service Registration Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md717',1,'3. Configuration Parsing Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md718',1,'4. Hardware Operation Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md719',1,'5. Event Handling Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md720',1,'6. Error Context Logging'],['../md_docs_2structure_2core__components.html#autotoc_md1215',1,'6. Logging'],['../md_docs_2design__decisions_2core__components.html#autotoc_md811',1,'6. Logging'],['../md_docs_2security_2security__guidelines.html#autotoc_md1159',1,'Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md724',1,'Performance Logging'],['../md_docs_2convention_2logging__standards.html#autotoc_md721',1,'Runtime State Logging']]],
  ['logging_20ის_20სტანდარტები_40',['Logging-ის სტანდარტები',['../md_docs_2convention_2logging__standards.html',1,'']]],
  ['logging_20api_41',['Logging API',['../md_docs_2api__reference_2core__api.html#autotoc_md101',1,'']]],
  ['logging_20h_42',['[interfaces/include/logging.h]',['../md_docs_2changelog_2CHANGELOG__2025-06-24.html#autotoc_md427',1,'']]],
  ['logging_20patterns_43',['Logging Patterns',['../md_docs_2convention_2logging__standards.html#autotoc_md714',1,'']]],
  ['logging_20standards_44',['Logging Standards',['../md_docs_2convention_2error__handling.html#autotoc_md677',1,'']]],
  ['logging_2eh_45',['logging.h',['../logging_8h.html',1,'']]],
  ['logic_46',['logic',['../md_docs_2convention_2error__handling.html#autotoc_md681',1,'1. Retry Logic'],['../md_docs_2convention_2configuration__management.html#autotoc_md640',1,'Fallback Logic']]]
];
